### ISSUE TITLE
导出的inference模型，使用官方demo代码报InvalidArgumentError

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/PaddleX#1012]
问题类型：模型部署
**问题描述**  
1、Paddlex训练好的best_model，通过paddlex的export命令导出inference模型；
2、inference官方示例代码，如下：
[Uploading infer.py…]()
3、执行预测，报如下错误：
I0803 11:28:04.524127  8127 analysis_config.cc:424] use_dlnne_:0
I0803 11:28:04.524165  8127 analysis_config.cc:424] use_dlnne_:0
I0803 11:28:04.524183  8127 analysis_config.cc:424] use_dlnne_:0
W0803 11:28:04.896790  8127 analysis_predictor.cc:674] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0803 11:28:04.896821  8127 analysis_config.cc:424] use_dlnne_:0
I0803 11:28:04.896828  8127 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0803 11:28:04.967655  8127 graph_pattern_detector.cc:91] ---  detected 43 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I0803 11:28:04.992759  8127 graph_pattern_detector.cc:91] ---  detected 14 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0803 11:28:05.003835  8127 graph_pattern_detector.cc:91] ---  detected 48 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0803 11:28:05.014961  8127 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0803 11:28:05.027935  8127 memory_optimize_pass.cc:199] Cluster name : im_shape  size: 8
I0803 11:28:05.027946  8127 memory_optimize_pass.cc:199] Cluster name : image  size: 12
I0803 11:28:05.027948  8127 memory_optimize_pass.cc:199] Cluster name : pool2d_7.tmp_0  size: 1920
I0803 11:28:05.027949  8127 memory_optimize_pass.cc:199] Cluster name : batch_norm_41.tmp_3  size: 1920
I0803 11:28:05.027951  8127 memory_optimize_pass.cc:199] Cluster name : elementwise_add_3  size: 96
I0803 11:28:05.027952  8127 memory_optimize_pass.cc:199] Cluster name : elementwise_add_7  size: 224
I0803 11:28:05.027953  8127 memory_optimize_pass.cc:199] Cluster name : hardswish_18.tmp_0  size: 1920
I0803 11:28:05.027954  8127 memory_optimize_pass.cc:199] Cluster name : depthwise_conv2d_19.tmp_0  size: 384
I0803 11:28:05.027956  8127 memory_optimize_pass.cc:199] Cluster name : batch_norm_8.tmp_5  size: 512
I0803 11:28:05.027957  8127 memory_optimize_pass.cc:199] Cluster name : scale_factor  size: 8
I0803 11:28:05.027958  8127 memory_optimize_pass.cc:199] Cluster name : batch_norm_41.tmp_1  size: 1920
--- Running analysis [ir_graph_to_program_pass]
I0803 11:28:05.071388  8127 analysis_predictor.cc:595] ======= optimize end =======
I0803 11:28:05.074640  8127 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I0803 11:28:05.074651  8127 naive_executor.cc:98] ---  skip [feed], feed -> image
I0803 11:28:05.074652  8127 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I0803 11:28:05.076894  8127 naive_executor.cc:98] ---  skip [hardswish_18.tmp_0], fetch -> fetch
I0803 11:28:05.076901  8127 naive_executor.cc:98] ---  skip [pool2d_7.tmp_0], fetch -> fetch
W0803 11:28:19.539906  8127 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0803 11:28:19.541182  8127 device_context.cc:422] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "/opt/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/rain/PycharmProjects/plane/infer.py", line 72, in <module>
    predictor.run()
ValueError: In user code:

    File "/home/rain/anaconda3/envs/paddlex2_env/bin/paddlex", line 8, in <module>
      sys.exit(main())
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/command.py", line 158, in main
      model._export_inference_model(args.save_dir, fixed_input_shape)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/cv/models/base.py", line 598, in _export_inference_model
      paddle.jit.save(static_net, osp.join(save_dir, 'model'))
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 718, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmppaj1s02z.py", line 26, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_1,
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/ppdet/modeling/architectures/yolo.py", line 104, in get_pred
      return self._forward()
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/ppdet/modeling/architectures/yolo.py", line 63, in _forward
      body_feats = self.backbone(self.inputs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/ppdet/modeling/backbones/mobilenet_v3.py", line 473, in forward
      x = self.conv1(inputs['image'])
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddlex/ppdet/modeling/backbones/mobilenet_v3.py", line 100, in forward
      x = self.conv(x)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 655, in forward
      out = F.conv._conv_nd(
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/nn/functional/conv.py", line 138, in _conv_nd
      helper.append_op(
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3226, in append_op
      op = Operator(
    File "/home/rain/anaconda3/envs/paddlex2_env/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Tensor in the conv2d_fusion Op's Input Variable Input(image) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1565)
python-BaseException      [operator < conv2d_fusion > error]

Process finished with exit code 1

**Comment by yuyangup** [comment]
infer.py的具体代码如下：
`import numpy as np
import argparse
import cv2

from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType
from img_preprocess import preprocess


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_dir",
        type=str,
        default="",
        help=
        "Model dir, If you load a non-combined model, specify the directory of the model."
    )
    parser.add_argument(
        "--model_file",
        type=str,
        default="",
        help="Model filename, Specify this when your model is a combined model."
    )
    parser.add_argument(
        "--params_file",
        type=str,
        default="",
        help=
        "Parameter filename, Specify this when your model is a combined model."
    )
    parser.add_argument("--img_path", type=str, default="", help="Input image path.")
    parser.add_argument("--threads",
                        type=int,
                        default=1,
                        help="Whether use gpu.")
    return parser.parse_args()


if __name__ == '__main__':
    # args = parse_args()
    # assert (args.model_dir != "") or \
    #        (args.model_file != "" and args.params_file != ""), \
    #     "Set model path error."
    # assert args.img_path != "", "Set img_path error."
    #
    # # Init config
    # if args.model_dir == "":
    #     config = Config(args.model_file, args.params_file)
    # else:
    #     config = Config(args.model_dir)
    config = Config('inference_model/ppyolotiny/model.pdmodel','inference_model/ppyolotiny/model.pdiparams')
    config.enable_use_gpu(500, 0)
    config.switch_ir_optim()
    config.enable_memory_optim()
    # config.enable_tensorrt_engine(workspace_size=1 << 30, precision_mode=PrecisionType.Float32, max_batch_size=1,
    #                               min_subgraph_size=5, use_static=False, use_calib_mode=False)

    # Create predictor
    predictor = create_predictor(config)

    # Set input
    img = cv2.imread('testplane/660.jpg')
    img = preprocess(img)
    input_names = predictor.get_input_names()
    input_tensor = predictor.get_input_handle(input_names[0])
    input_tensor.reshape(img.shape)
    input_tensor.copy_from_cpu(img.copy())

    # Run
    predictor.run()

    # Set output
    output_names = predictor.get_output_names()
    output_tensor = predictor.get_output_handle(output_names[0])
    output_data = output_tensor.copy_to_cpu()

    print("Predict class index: ", np.argmax(output_data))`

**Comment by heliqi** [comment]
paddlex和paddle 、paddle inference版本分别是多少？

**Comment by yuyangup** [comment]
paddlex 2.0.0rc3
paddle 2.1.0
paddle inference 2.1.0.post112

**Comment by yuyangup** [comment]
自己顶起来，大佬快来看看

**Comment by heliqi** [comment]
paddlex导出的模型是有个model.yml 的配置文件，需要先读取这个配置文件对输入进行预处理后，才能用paddle inference接收预处理后的数据

**Comment by FlyingQianMM** [comment]
使用python paddle inference推理预测可参考  https://aistudio.baidu.com/paddle/forum/topic/show/990126
