### ISSUE TITLE
不使用GUI训练是正常的，使用GUI报错

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#1015]
问题类型：PaddleX可视化客户端  

version-1.1.7

This log file path is D:\Paddle_Re\paddlex_gui_train\projects\P0013\T0015\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
2021-08-03 10:41:38,345-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!

Process Process-1:3:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\segmentation.py", line 171, in train
  File "site-packages\paddlex\cv\models\deeplabv3p.py", line 346, in train
  File "site-packages\paddlex\cv\models\base.py", line 241, in net_initialize
  File "site-packages\paddlex\cv\models\utils\pretrain_weights.py", line 216, in get_pretrain_weights
  File "site-packages\paddlex\utils\download.py", line 156, in download_and_decompress
  File "site-packages\paddlex\utils\download.py", line 137, in decompress
  File "tarfile.py", line 2002, in extractall
  File "tarfile.py", line 2044, in extract
  File "tarfile.py", line 2114, in _extract_member
  File "tarfile.py", line 2163, in makefile
  File "tarfile.py", line 249, in copyfileobj
tarfile.ReadError: unexpected end of data

请在这里描述您在使用GUI过程中的问题

**Comment by jiangjiajun** [comment]
这个看起来是预训练模型下载出了问题，可在工作空间目录下，清空pretrain目录下的文件，重新训练即可
