### ISSUE TITLE
The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1018]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本
2.0.0rc4

**问题描述**  

win10下训练，报CUDA的错

====================  

请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

win10下训练，报如下CUDA的错：
```
W0804 21:55:45.072443 12172 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.2
W0804 21:55:45.073442 12172 dynamic_loader.cc:238] Note: [Recommend] copy cudnn into CUDA installation directory. 
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website, 
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "C:/Users/xxx/Desktop/xxx/PaddleX/xxx/train.py", line 53, in <module>
    model = pdx.cls.MobileNetV3_large_ssld(num_classes=num_classes)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddlex\cv\models\classifier.py", line 663, in __init__
    model_name='MobileNetV3_large_x1_0', num_classes=num_classes)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddlex\cv\models\classifier.py", line 68, in __init__
    self.net = self.build_net(**params)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddlex\cv\models\classifier.py", line 73, in build_net
    class_dim=self.num_classes, **params)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddlex\ppcls\modeling\architectures\mobilenet_v3.py", line 353, in MobileNetV3_large_x1_0
    model = MobileNetV3(model_name="large", scale=1.0, **args)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddlex\ppcls\modeling\architectures\mobilenet_v3.py", line 109, in __init__
    name="conv1")
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddlex\ppcls\modeling\architectures\mobilenet_v3.py", line 201, in __init__
    bias_attr=False)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\nn\layer\conv.py", line 646, in __init__
    data_format=data_format)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 412, in create_parameter
    default_initializer)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\fluid\layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\fluid\framework.py", line 2858, in create_parameter
    initializer(param, self)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\fluid\initializer.py", line 366, in __call__
    stop_gradient=True)
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\fluid\framework.py", line 2888, in append_op
    kwargs.get("stop_gradient", False))
  File "C:\Users\xxx\Desktop\xxx\venv\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release2\paddle\fluid\platform\dynload\dynamic_loader.cc:265)
  [operator < gaussian_random > error]
```
我的CUDA版本是：11.2，cudnn是：cudnn-11.2-windows-x64-v8.1.1.33。
按照提醒的建议添加了环境变量，依然报错。
有点奇怪的是cudnn文件下根本没有`cudnn64_7.dll`，有相近的`cudnn64_8.dll`，为什么要报`cudnn64_7.dll`的错呢？

谢谢

**Comment by geoexploring** [comment]
环境都配置好后，重启就可以解决了。
