### ISSUE TITLE
paddlex 采用 API模式训练时，没有报错却退出训练

### ISSUE THREAD

**Issue by lishuai903** [PaddlePaddle/PaddleX#1025]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本 ：2.0.0rc4
paddlepaddle版本：paddlepaddle-gpu==2.1.2

**问题描述**  
**api模式训练模型（无论是分类，检测和分割），在训练完成一个epoch后，就会退出，也不报错，不知道提示的这些信心有没有什么影响。gui可以正常训练**
PS I:\PaddleXProject\PaddleX\tutorials\train\image_classification>  & 'C:\Users\BadGuy\AppData\Local\Programs\Python\Python36\python.exe' 'c:\Users\BadGuy\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher' '55870' '--' 'i:\PaddleXProject\PaddleX\tutorials\train\image_classification\mobilenetv3_small.py'
C:\Users\BadGuy\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\distributed\parallel.py:120: UserWarning: Currently not
a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
2021-08-08 14:38:51 [INFO]      Decompressing ./vegetables_cls.tar.gz...
2021-08-08 14:38:54 [INFO]      Starting to read file list from dataset...
2021-08-08 14:38:54 [INFO]      840 samples in file vegetables_cls/train_list.txt
2021-08-08 14:38:54 [INFO]      Starting to read file list from dataset...
2021-08-08 14:38:54 [INFO]      240 samples in file vegetables_cls/val_list.txt
W0808 14:38:54.762717 20804 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 11.2
W0808 14:38:54.830319 20804 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-08-08 14:38:57 [INFO]      Loading pretrained model from output/mobilenetv3_small\pretrain\MobileNetV3_small_x1_0_pretrained.pdparams
2021-08-08 14:38:58 [WARNING]   [SKIP] Shape of pretrained params out.weight doesn't match.(Pretrained: [1280, 1000], Actual: [1280, 6])
2021-08-08 14:38:58 [WARNING]   [SKIP] Shape of pretrained params out.bias doesn't match.(Pretrained: [1000], Actual: [6])
2021-08-08 14:38:58 [INFO]      There are 212/214 variables loaded into MobileNetV3_small_x1_0.
2021-08-08 14:39:00 [INFO]      [TRAIN] Epoch=1/10, Step=10/26, loss=0.822392, acc1=0.875000, acc5=1.000000, lr=0.010000, time_each_step=0.26s, eta=0:1:6
2021-08-08 14:39:02 [INFO]      [TRAIN] Epoch=1/10, Step=20/26, loss=0.141440, acc1=0.937500, acc5=1.000000, lr=0.010000, time_each_step=0.15s, eta=0:0:36
PS I:\PaddleXProject\PaddleX\tutorials\train\image_classification>

**尝试CUDA10.2 和CUDA11.2，均出现上述问题。**
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by yzl19940819** [comment]
您好，请问咱们这边使用的是什么系统进行训练的呢？

**Comment by lishuai903** [comment]
> 您好，请问咱们这边使用的是什么系统进行训练的呢？

win10

**Comment by lishuai903** [comment]
> 您好，请问咱们这边使用的是什么系统进行训练的呢？

win10系统 1080ti显卡

**Comment by zhwesky2010** [comment]
@lishuai903 您好，请问有详细复现步骤或文档吗，我在我们Windows上试下

**Comment by lishuai903** [comment]
> @lishuai903 您好，请问有详细复现步骤或文档吗，我在我们Windows上试下
**@zhouwei25 @yzl19940819 您好，以下是我的操作步骤，希望问题能够得到解决，谢谢。**

- **一.问题描述**

1. 环境配置
系统：win10
显卡：1080ti 
paddlepaddle-gpu：2.1.2 
paddlex：2.0.0rc4  
cuda：10.2和11.2(当前是已经换成了11.2的版本，所以以下会以这个版本进行描述，问题是一样的)
python：3.6.8

- **二. 安装cuda和cudnn**

cuda试过了两个版本
cuda10.2
![1](https://user-images.githubusercontent.com/25630473/128667725-2e182988-46aa-44f3-8c7d-df31fb0fd896.png)
cuda11.2
![2](https://user-images.githubusercontent.com/25630473/128667763-bbcb9a2b-93e6-4752-9e28-f8ee2775618a.png)

1.下载以上两个文件
2.按照精简方式安装cuda
3.cuda安装完成后，把解压后的cudnn放到cuda的安装路径；
![3](https://user-images.githubusercontent.com/25630473/128667782-e224a610-28d8-4bca-bab9-124de686ad7f.png)


- **三. 安装paddlepaddle**	

1.安装
参考文档：开始使用_飞桨-源于产业实践的开源深度学习平台 (paddlepaddle.org.cn)
cuda11.2
python -m pip install paddlepaddle-gpu==2.1.2.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
![4](https://user-images.githubusercontent.com/25630473/128667828-620dfe98-7028-4f5c-bdac-5fdc8735397f.png)

2.测试
![5](https://user-images.githubusercontent.com/25630473/128667841-b64395a5-af76-4d42-8bff-bd01ad5bd145.png)

版本：
![6](https://user-images.githubusercontent.com/25630473/128667850-31010a17-0db7-44f1-8de0-4dfc0ba529a7.png)

- **四. 安装paddlex API**

1.安装
参考文档：PaddleX/install.md at develop · PaddlePaddle/PaddleX (github.com)
pip install paddlex==2.0.0rc4 -i https://mirror.baidu.com/pypi/simple
![7](https://user-images.githubusercontent.com/25630473/128667889-619c0103-23cc-4de0-8084-245c190afab0.png)

2.测试及版本
![8](https://user-images.githubusercontent.com/25630473/128667902-bdcba1a9-4717-4402-9348-9f8fc7f29216.png)

上图红框是否有影响？

- **五：训练**

1. 下载paddlex代码
git clone https://github.com/PaddlePaddle/PaddleX.git
2.分类训练
运行PaddleX\tutorials\train\image_classification的mobilenetv3_small.py
mobilenetv3_small.py
![9](https://user-images.githubusercontent.com/25630473/128667948-e093deee-58ae-4274-a122-474251489471.png)

3.检测训练
运行I:\PaddleXProject\PaddleX\examples\meter_reader下的train_detection.py
![10](https://user-images.githubusercontent.com/25630473/128667956-d3d355d3-61ee-4957-a60b-357aad0128bc.png)

4.分割训练同样出现上述问题。
5. 调小batchsize还是同样的问题。
6.用paddlex的GUI版本为：2.0.0rc1,可以正常使用。
![11](https://user-images.githubusercontent.com/25630473/128667990-3a12bce7-a547-4245-9526-7e87e61e2810.png)

训练如下图:
![12](https://user-images.githubusercontent.com/25630473/128667996-f634d2d1-29ae-4b1a-97c1-6b5b21e12766.png)

- **六、结论**

训练的时候只训练完一个epoch后就自动停止训练退出了（分类，检测，分割都一样），也没看见什么报错，不知道提示信息有没有相关错误。cuda10.2和11.2都试过了，GUI的可以正常训练，API训练会遇到这种问题。用API预测没有问题。

**Comment by zhwesky2010** [comment]
@lishuai903 您好，目前在我们Windows机器上尝试了一下

分类可以训练完成
![infoflow 2021-08-09 16-38-38](https://user-images.githubusercontent.com/52485244/128692143-803651a3-b929-4670-a1be-52629cb9accb.png)

检测也可以训练完成
![infoflow 2021-08-09 16-59-54](https://user-images.githubusercontent.com/52485244/128692157-5f94bb29-da5d-46b1-9b0a-42416e2cfa11.png)

可能是机器环境问题，试试重启一下机器还会在第一个epoch退出吗

**Comment by lishuai903** [comment]
@zhouwei25 您好，在此之前也试过重启。仍然会存在这种问题，GUI可以正常训练，所以就很奇怪。上述图片内的一些警告信息是否会有影响？

**Comment by zhwesky2010** [comment]
> @zhouwei25 您好，在此之前也试过重启。仍然会存在这种问题，GUI可以正常训练，所以就很奇怪。上述图片内的一些警告信息是否会有影响？

警告信息是shape不匹配，这个如果报错会有明确的信息打出的，这种突然挂了的，一般是内存 操作系统方面的

**Comment by lishuai903** [comment]
是的，一般突然挂了的可能就是内存爆了的原因，但是GUI训练没有问题，而且API的我也把batchsize调整到1，还是同样问题。所以就很纳闷了。

**Comment by FlyingQianMM** [comment]
GUI2.0rc2内置的paddle是2.1.1版本，可以试下安装paddlepaddle_gpu==2.1.1能不能正常运行。

另外，之前使用paddlex有遇到过这种情况么？

**Comment by zhwesky2010** [comment]
@lishuai903 
我们之前也遇到过paddleDectection在某些机器上不明原因挂掉的，可以试试是不是同一个问题
```
git clone https://github.com/PaddlePaddle/PaddleDetection

cd  PaddleDetection

pip install paddledet==2.1.0 -i https://mirror.baidu.com/pypi/simple

python ppdet/modeling/tests/test_architectures.py

python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml  -o use_gpu=true
```

**Comment by lishuai903** [comment]
> @lishuai903
> 我们之前也遇到过paddleDectection在某些机器上不明原因挂掉的，可以试试是不是同一个问题
> 
> ```
> git clone https://github.com/PaddlePaddle/PaddleDetection
> 
> cd  PaddleDetection
> 
> pip install paddledet==2.1.0 -i https://mirror.baidu.com/pypi/simple
> 
> python ppdet/modeling/tests/test_architectures.py
> 
> python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml  -o use_gpu=true
> ```

**这个训练没有问题**

PS I:\PaddleDetection> python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml  -o use_gpu=true
[08/09 22:45:36] ppdet.utils.download WARNING: Config annotation dataset/roadsign_voc\train.txt is not a file, dataset config is not valid
[08/09 22:45:36] ppdet.utils.download INFO: Dataset I:\PaddleDetection\dataset\roadsign_voc is not valid for reason above, try searching C:\Users\BadGuy/.cache/paddle/dataset or downloading dataset...
[08/09 22:45:36] ppdet.utils.download INFO: Found C:\Users\BadGuy/.cache/paddle/dataset\roadsign_voc\annotations
[08/09 22:45:36] ppdet.utils.download INFO: Found C:\Users\BadGuy/.cache/paddle/dataset\roadsign_voc\images
W0809 22:45:36.994424 10820 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0809 22:45:37.003821 10820 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.0.weight not used, shape [255, 1024, 1, 1] unmatched with [27, 1024, 1, 1] in model.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.0.bias not used, shape [255] unmatched with [27] in model.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.1.weight not used, shape [255, 512, 1, 1] unmatched with [27, 512, 1, 1] in model.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.1.bias not used, shape [255] unmatched with [27] in model.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.2.weight not used, shape [255, 256, 1, 1] unmatched with [27, 256, 1, 1] in model.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.2.bias not used, shape [255] unmatched with [27] in model.
[08/09 22:45:41] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\BadGuy/.cache/paddle/weights\yolov3_mobilenet_v1_270e_coco.pdparams
[08/09 22:45:41] ppdet.engine INFO: Epoch: [0] [ 0/87] learning_rate: 0.000033 loss_xy: 3.909322 loss_wh: 3.300014 loss_obj: 17249.468750 loss_cls: 4.095658 loss: 17260.773438 eta: 0:28:39 batch_cost: 0.4940 data_cost: 0.0005 ips: 16.1941 images/s
[08/09 22:45:50] ppdet.engine INFO: Epoch: [0] [20/87] learning_rate: 0.000047 loss_xy: 3.503009 loss_wh: 2.627209 loss_obj: 26.881359 loss_cls: 3.592066 loss: 36.304073 eta: 0:23:32 batch_cost: 0.4039 data_cost: 0.1780 ips: 19.8048 images/s
[08/09 22:46:01] ppdet.engine INFO: Epoch: [0] [40/87] learning_rate: 0.000060 loss_xy: 3.464864 loss_wh: 2.113954 loss_obj: 20.616684 loss_cls: 3.429104 loss: 30.092033 eta: 0:27:37 batch_cost: 0.5593 data_cost: 0.3003 ips: 14.3032 images/s
[08/09 22:46:11] ppdet.engine INFO: Epoch: [0] [60/87] learning_rate: 0.000073 loss_xy: 3.071153 loss_wh: 1.622754 loss_obj: 10.422483 loss_cls: 2.725348 loss: 17.804844 eta: 0:28:26 batch_cost: 0.5341 data_cost: 0.2998 ips: 14.9785 images/s
[08/09 22:46:22] ppdet.engine INFO: Epoch: [0] [80/87] learning_rate: 0.000087 loss_xy: 3.511780 loss_wh: 1.680867 loss_obj: 8.079425 loss_cls: 3.072501 loss: 16.166416 eta: 0:28:17 batch_cost: 0.5003 data_cost: 0.2761 ips: 15.9892 images/s
[08/09 22:46:25] ppdet.utils.checkpoint INFO: Save checkpoint: output\yolov3_mobilenet_v1_roadsign
[08/09 22:46:25] ppdet.engine INFO: Epoch: [1] [ 0/87] learning_rate: 0.000091 loss_xy: 3.457119 loss_wh: 1.584953 loss_obj: 7.782506 loss_cls: 3.053960 loss: 15.424970 eta: 0:27:49 batch_cost: 0.4698 data_cost: 0.2598 ips: 17.0275 images/s
[08/09 22:46:35] ppdet.engine INFO: Epoch: [1] [20/87] learning_rate: 0.000100 loss_xy: 3.229367 loss_wh: 1.267389 loss_obj: 6.425802 loss_cls: 2.698676 loss: 14.231686 eta: 0:27:29 batch_cost: 0.4749 data_cost: 0.2650 ips: 16.8474 images/s
[08/09 22:46:45] ppdet.engine INFO: Epoch: [1] [40/87] learning_rate: 0.000100 loss_xy: 3.613449 loss_wh: 1.385784 loss_obj: 6.730758 loss_cls: 2.728001 loss: 14.208764 eta: 0:27:15 batch_cost: 0.4825 data_cost: 0.2720 ips: 16.5806 images/s
[08/09 22:46:54] ppdet.engine INFO: Epoch: [1] [60/87] learning_rate: 0.000100 loss_xy: 3.077477 loss_wh: 1.195504 loss_obj: 5.611897 loss_cls: 2.369928 loss: 12.516779 eta: 0:27:02 batch_cost: 0.4788 data_cost: 0.2783 ips: 16.7088 images/s
[08/09 22:47:04] ppdet.engine INFO: Epoch: [1] [80/87] learning_rate: 0.000100 loss_xy: 3.193162 loss_wh: 1.049135 loss_obj: 5.239515 loss_cls: 2.519114 loss: 11.755295 eta: 0:26:57 batch_cost: 0.4990 data_cost: 0.2762 ips: 16.0336 images/s
[08/09 22:47:08] ppdet.utils.checkpoint INFO: Save checkpoint: output\yolov3_mobilenet_v1_roadsign
[08/09 22:47:09] ppdet.engine INFO: Epoch: [2] [ 0/87] learning_rate: 0.000100 loss_xy: 3.252958 loss_wh: 1.061992 loss_obj: 5.353124 loss_cls: 2.420962 loss: 11.902792 eta: 0:26:50 batch_cost: 0.4784 data_cost: 0.2641 ips: 16.7227 images/s
[08/09 22:47:19] ppdet.engine INFO: Epoch: [2] [20/87] learning_rate: 0.000100 loss_xy: 3.401884 loss_wh: 1.098959 loss_obj: 5.533315 loss_cls: 2.380068 loss: 12.286291 eta: 0:26:48 batch_cost: 0.5116 data_cost: 0.2915 ips: 15.6379 images/s
[08/09 22:47:29] ppdet.engine INFO: Epoch: [2] [40/87] learning_rate: 0.000100 loss_xy: 3.212712 loss_wh: 1.122733 loss_obj: 5.351942 loss_cls: 2.429179 loss: 11.936543 eta: 0:26:46 batch_cost: 0.5142 data_cost: 0.3009 ips: 15.5573 images/s

**Comment by lishuai903** [comment]
> GUI2.0rc2内置的paddle是2.1.1版本，可以试下安装paddlepaddle_gpu==2.1.1能不能正常运行。
> 
> 另外，之前使用paddlex有遇到过这种情况么？

**换成2.1.1有同样的问题。
之前只是用GUI训练，所以也没发现。**

**Comment by zhwesky2010** [comment]
> GUI2.0rc2内置的paddle是2.1.1版本，可以试下安装paddlepaddle_gpu==2.1.1能不能正常运行。
> 
> 另外，之前使用paddlex有遇到过这种情况么？

我试了2.1.1和2.1.2下的CUDA10.2/11.2均没问题，以前是报过paddleDectection在最后一个batch挂了

**Comment by lishuai903** [comment]
> > GUI2.0rc2内置的paddle是2.1.1版本，可以试下安装paddlepaddle_gpu==2.1.1能不能正常运行。
> > 另外，之前使用paddlex有遇到过这种情况么？
> 
> 我试了2.1.1和2.1.2下的CUDA10.2/11.2均没问题，以前是报过paddleDectection在最后一个batch挂了

打断点看是第一个epoch的最后一次执行代码for step, data in enumerate(self.train_data_loader()):然后就进入了另一个线程里的wait，再等一会就退出了。

**Comment by lishuai903** [comment]
@zhouwei25 @FlyingQianMM @yzl19940819 感谢各位大佬的回复。
感谢@libingbingdev提供的方法，问题已经得到解决，方法是：
卸载原有的scipy,安装1.3.1版本
`pip uninstall scipy`
`pip install scipy==1.3.1`

**Comment by sannnyu** [comment]
> @zhouwei25 @FlyingQianMM @yzl19940819 感谢各位大佬的回复。
> 感谢@libingbingdev提供的方法，问题已经得到解决，方法是：
> 卸载原有的scipy,安装1.3.1版本
> `pip uninstall scipy`
> `pip install scipy==1.3.1`

我也遇到了这样的情况

Python3.9 scipy 1.7.1开始报错，然后按照楼主方法安装不上scipy 1.3.1（可能是python版本原因）然后在conda里用python3.7成功安装scipy 1.3.1后，仍然报相同错误。

> (sapaddlex) C:\Users\SANG-HP\PaddleX-develop\dygraph\tutorials\train\object_detection>ppyolov2.py
C:\Python39\lib\site-packages\paddle\distributed\parallel.py:119: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
2021-08-15 15:12:46 [INFO]      Decompressing ./insect_det.tar.gz...
2021-08-15 15:12:46 [INFO]      Starting to read file list from dataset...
2021-08-15 15:12:47 [INFO]      169 samples in file insect_det/train_list.txt
creating index...
index created!
2021-08-15 15:12:47 [INFO]      Starting to read file list from dataset...
2021-08-15 15:12:47 [INFO]      24 samples in file insect_det/val_list.txt
creating index...
index created!
W0815 15:12:47.232858 19692 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.2
W0815 15:12:47.271859 19692 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-08-15 15:12:53 [INFO]      Loading pretrained model from output/ppyolov2_r50vd_dcn\pretrain\ppyolov2_r50vd_dcn_365e_coco.pdparams
2021-08-15 15:12:55 [WARNING]   [SKIP] Shape of pretrained params yolo_head.yolo_output.0.weight doesn't match.(Pretrained: [258, 1024, 1, 1], Actual: [36, 1024, 1, 1])
2021-08-15 15:12:55 [WARNING]   [SKIP] Shape of pretrained params yolo_head.yolo_output.0.bias doesn't match.(Pretrained: [258], Actual: [36])
2021-08-15 15:12:55 [WARNING]   [SKIP] Shape of pretrained params yolo_head.yolo_output.1.weight doesn't match.(Pretrained: [258, 512, 1, 1], Actual: [36, 512, 1, 1])
2021-08-15 15:12:55 [WARNING]   [SKIP] Shape of pretrained params yolo_head.yolo_output.1.bias doesn't match.(Pretrained: [258], Actual: [36])
2021-08-15 15:12:55 [WARNING]   [SKIP] Shape of pretrained params yolo_head.yolo_output.2.weight doesn't match.(Pretrained: [258, 256, 1, 1], Actual: [36, 256, 1, 1])
2021-08-15 15:12:55 [WARNING]   [SKIP] Shape of pretrained params yolo_head.yolo_output.2.bias doesn't match.(Pretrained: [258], Actual: [36])
2021-08-15 15:12:55 [INFO]      There are 526/532 variables loaded into PPYOLOv2.
C:\Python39\lib\site-packages\paddle\nn\layer\norm.py:640: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
C:\Python39\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py:237: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.float32, the right dtype will convert to paddle.int64
  warnings.warn(
C:\Python39\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py:237: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\SANG-HP\PaddleX-develop\dygraph\tutorials\train\object_detection\ppyolov2.py", line 51, in <module>
    model.train(
  File "C:\Python39\lib\site-packages\paddlex\cv\models\detector.py", line 275, in train
    self.train_loop(
  File "C:\Python39\lib\site-packages\paddlex\cv\models\base.py", line 335, in train_loop
    outputs = self.run(self.net, data, mode='train')
  File "C:\Python39\lib\site-packages\paddlex\cv\models\detector.py", line 100, in run
    net_out = net(inputs)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Python39\lib\site-packages\paddlex\ppdet\modeling\architectures\meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "C:\Python39\lib\site-packages\paddlex\ppdet\modeling\architectures\yolo.py", line 101, in get_loss
    return self._forward()
  File "C:\Python39\lib\site-packages\paddlex\ppdet\modeling\architectures\yolo.py", line 64, in _forward
    neck_feats = self.neck(body_feats, self.for_mot)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Python39\lib\site-packages\paddlex\ppdet\modeling\necks\yolo_fpn.py", line 998, in forward
    route, tip = self.fpn_blocks[i](block)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Python39\lib\site-packages\paddlex\ppdet\modeling\necks\yolo_fpn.py", line 418, in forward
    conv_left = self.conv_module(conv_left)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\container.py", line 98, in forward
    input = layer(input)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Python39\lib\site-packages\paddlex\ppdet\modeling\backbones\darknet.py", line 77, in forward
    out = self.conv(inputs)
  File "C:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Python39\lib\site-packages\paddle\nn\layer\conv.py", line 655, in forward
    out = F.conv._conv_nd(
  File "C:\Python39\lib\site-packages\paddle\nn\functional\conv.py", line 114, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

> Out of memory error on GPU 0. Cannot allocate 81.000244MB memory on GPU 0, 6.000000GB memory has been allocated and available memory is only 0.000000B.

> Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 > (at C:\home\workspace\Paddle_release4\paddle\fluid\memory\allocation\cuda_allocator.cc:79)
. (at C:\home\workspace\Paddle_release4\paddle\fluid\imperative\tracer.cc:192)

@yzl19940819

**Comment by lishuai903** [comment]
@sannnyu `Out of memory error on GPU 0. Cannot allocate 81.000244MB memory on GPU 0, 6.000000GB memory has been allocated and available memory is only 0.000000B.
`
报错信息显示显卡的内存不够了，把batchsize调小，或者图片的尺寸调小。
