### ISSUE TITLE
You should do this according to your CUDA installation directory and CUDNN version

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1050]
问题类型：模型训练  

**版本**  
WIN11
Python 3.8.11
paddlepaddle-gpu                  2.1.1
paddleslim                        2.1.0
paddlex                           2.0.0rc4

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

cudnn-11.2-windows-x64-v8.1.1.33

**问题描述**  

====================  
python faster_rcnn_r50_fpn.py
```

D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\parallel.py:119: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
2021-08-18 09:34:06 [INFO]      Decompressing ./insect_det.tar.gz...
2021-08-18 09:34:14 [INFO]      Starting to read file list from dataset...
2021-08-18 09:34:14 [INFO]      169 samples in file insect_det/train_list.txt
creating index...
index created!
2021-08-18 09:34:14 [INFO]      Starting to read file list from dataset...
2021-08-18 09:34:14 [INFO]      24 samples in file insect_det/val_list.txt
creating index...
index created!
W0818 09:34:14.796905  2812 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0818 09:34:14.812496  2812 dynamic_loader.cc:238] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "faster_rcnn_r50_fpn.py", line 43, in <module>
    model = pdx.det.FasterRCNN(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddlex-2.0.0rc4-py3.8.egg\paddlex\cv\models\detector.py", line 796, in __init__
    backbone = self._get_backbone(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddlex-2.0.0rc4-py3.8.egg\paddlex\cv\models\detector.py", line 96, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddlex-2.0.0rc4-py3.8.egg\paddlex\ppdet\modeling\backbones\resnet.py", line 518, in __init__
    ConvNormLayer(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddlex-2.0.0rc4-py3.8.egg\paddlex\ppdet\modeling\backbones\resnet.py", line 61, in __init__
    self.conv = nn.Conv2D(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\nn\layer\conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\nn\layer\conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\fluid\dygraph\layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\fluid\layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\fluid\framework.py", line 2858, in create_parameter
    initializer(param, self)
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\fluid\initializer.py", line 355, in __call__
    op = block.append_op(
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\fluid\framework.py", line 2884, in append_op
    _dygraph_tracer().trace_op(type,
  File "D:\anaconda3\envs\PaddleX\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release3\paddle\fluid\platform\dynload\dynamic_loader.cc:265)
  [operator < gaussian_random > error]
```

**Comment by heliqi** [comment]
如报错所提示， 检查下你的cuda版本、cudnn版本 跟你安装的 paddlepaddle 是否一致。
不同cuda版本， 安装的指令是不一样的， 具体请看 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by thgpddl** [comment]
> 

我安装的cpu版的paddle，为什么也会报这个错？
