### ISSUE TITLE
self._handle = _dlopen(self._name, mode)

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1057]
问题类型：其它  

win11 版本

**PaddleX版本**  
anaconda
python 3.6
paddlepaddle-gpu                  2.1.2.post112
paddleslim                        2.1.0
paddlex                           2.0.0rc4

**问题描述**  

========================

D:\anaconda3\envs\PaddleX36\lib\site-packages\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    from CamOperation_class import *
  File "D:\IntSoft\CamOperation_class.py", line 27, in <module>
    import paddlex as pdx
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\cv\models\__init__.py", line 15, in <module>
    from .segmenter import *
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\cv\models\segmenter.py", line 24, in <module>
    from paddlex.cv.transforms import arrange_transforms
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\cv\transforms\__init__.py", line 15, in <module>
    from .operators import *
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\cv\transforms\operators.py", line 27, in <module>
    from .functions import normalize, horizontal_flip, permute, vertical_flip, center_crop, is_poly, \
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\paddlex\cv\transforms\functions.py", line 18, in <module>
    import shapely.ops
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\shapely\ops.py", line 13, in <module>
    from shapely.prepared import prep
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\shapely\prepared.py", line 5, in <module>
    from shapely.geos import lgeos
  File "D:\anaconda3\envs\PaddleX36\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\anaconda3\envs\PaddleX36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by xxhdxh** [comment]
去搜一下这个dll 下载放到它的目录里就行了
