### ISSUE TITLE
windows下shapely报错：lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll')) OSError: [WinError 126] 找不到指定的模块

### ISSUE THREAD

**Issue by zzy444626905** [PaddlePaddle/PaddleX#1064]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本

**问题描述**  

(paddlex) C:\Users\zzy\Desktop\paddle\tutorials\train\object_detection>python ppyolov2.py
E:\anaconda3\envs\paddlex\lib\site-packages\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
Traceback (most recent call last):
  File "ppyolov2.py", line 1, in <module>
    import paddlex as pdx
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\cv\models\__init__.py", line 15, in <module>
    from .segmenter import *
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\cv\models\segmenter.py", line 24, in <module>
    from paddlex.cv.transforms import arrange_transforms
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\cv\transforms\__init__.py", line 15, in <module>
    from .operators import *
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\cv\transforms\operators.py", line 27, in <module>
    from .functions import normalize, horizontal_flip, permute, vertical_flip, center_crop, is_poly, \
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\cv\transforms\functions.py", line 18, in <module>
    import shapely.ops
  File "E:\anaconda3\envs\paddlex\lib\site-packages\shapely\ops.py", line 13, in <module>
    from shapely.prepared import prep
  File "E:\anaconda3\envs\paddlex\lib\site-packages\shapely\prepared.py", line 5, in <module>
    from shapely.geos import lgeos
  File "E:\anaconda3\envs\paddlex\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "E:\anaconda3\envs\paddlex\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by FlyingQianMM** [comment]
1. 用管理权权限启动终端
2. 进入该conda环境后，pip show shapely看是否是1.7.1版本，卸载shapely后重新安装shapely
 
issue #1057

**Comment by FlyingQianMM** [comment]
windows上，在conda环境内通过pip install shapely后会出现该问题，具体可以看shapely issue https://github.com/Toblerity/Shapely/issues/1032

解决办法：
1. 卸载pip安装的shapely
```
pip uninstall shapely
```
2. 然后用conda安装
```
 conda install shapely==1.7.1
```

**Comment by monkeycc** [comment]
我也遇到了这个问题   只要升级到paddleX2.0 就会报这个错
