### ISSUE TITLE
Fast RCNN：Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by wxh453751461** [PaddlePaddle/PaddleX#1069]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本 ：1.3.11

**问题描述**  
网上查的解决方案为：更换numpy到1.20.0+，但是paddlex支持1.19.3
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
Traceback (most recent call last):
  File "C:/Users/beansprots/Desktop/paddlex/train.py", line 35, in <module>
    shuffle=True)
  File "D:\Anaconda3\envs\my_paddlex\lib\site-packages\paddlex\cv\datasets\voc.py", line 62, in __init__
    from pycocotools.coco import COCO
  File "D:\Anaconda3\envs\my_paddlex\lib\site-packages\pycocotools\coco.py", line 56, in <module>
    from . import mask as maskUtils
  File "D:\Anaconda3\envs\my_paddlex\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by FlyingQianMM** [comment]
> paddlex支持1.19.3

paddlex没有限制只能使用numpy==1.19.3，你可以将numpy进行升级，另外使用的python版本是多少呢

**Comment by wxh453751461** [comment]
更新了numpy版本 ，解决了
