### ISSUE TITLE
在AI studio脚本任务里import paddlex失败

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1094]
问题类型：其它  

**PaddleX版本**  
您使用的PaddleX版本
paddlex==2.0.0rc4
**问题描述**  
在AI studio 脚本任务里import paddlex失败

========================

请在这里描述您的问题：

AI studio的脚本任务环境里没有paddlex，所以运行依赖paddlex相关的任务时需要安装paddlex，安装paddlex倒是成功了，只是在运行`python train.py`时出现如下问题：
```
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    import paddlex as pdx
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/__init__.py", line 20, in <module>
    from . import cv
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/cv/__init__.py", line 15, in <module>
    from . import models
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/cv/models/__init__.py", line 16, in <module>
    from .classifier import *
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/cv/models/classifier.py", line 30, in <module>
    from paddlex.ppcls.modeling import architectures
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/ppcls/__init__.py", line 19, in <module>
    from .data import *
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/ppcls/data/__init__.py", line 15, in <module>
    from .reader import Reader
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/ppcls/data/reader.py", line 25, in <module>
    from paddlex.ppcls.utils import logger
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/ppcls/utils/__init__.py", line 18, in <module>
    from . import metrics
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlex/ppcls/utils/metrics.py", line 19, in <module>
    from sklearn.metrics import hamming_loss
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__init__.py", line 79, in <module>
    from . import __check_build  # noqa: F401
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 41, in raise_build_error
    %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
ImportError: dlopen: cannot load any more object with static TLS
```
在本地运行`python train.py`是没有问题的。请问该如何解决呢？

谢谢

**Comment by FlyingQianMM** [comment]
看起来像是scikit-learn的问题
```
pip install scikit-learn -U
```
更新下scikit-learn看下能不能解决这个问题

**Comment by geoexploring** [comment]
@FlyingQianMM ，确实是scikit-learn的问题，按安装`pip install scikit-learn -U`后仍然报上面的错，还是scikit-learn的问题。
算了，脚本任务太难用了，放弃。
谢谢
