### ISSUE TITLE
openvino部署出错RuntimeError: Unknown model format!

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleX#1112]
使用pyinstaller 打包paddlepaddle导出的openvino模型出现下面的错误，可能是什么原因
```
[E:] [BSL] found 0 ioexpander device
CPU
GNA
Loading network files:
        G:\seg\openvino_pyinstaller\seg\cho_openvino_model\paddle2onnx_model.xml
        G:\seg\openvino_pyinstaller\seg\cho_openvino_model\paddle2onnx_model.bin
Traceback (most recent call last):
  File "extact_edge.py", line 591, in <module>
  File "extact_edge.py", line 132, in __init__
  File "extact_edge.py", line 145, in create_predictor
  File "ie_api.pyx", line 324, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 346, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Unknown model format! Cannot find reader for model format: xml and read the model: G:\seg\openvino_pyinstaller\seg\cho_openvino_model\paddle2onnx_model.xml. Please check that reader library exists in your PATH.
[37764] Failed to execute script 'extact_edge' due to unhandled exception!
```

**Comment by FlyingQianMM** [comment]
如果不打包可以正常运行的话，看下是否跟这个提示信息有关：
```
RuntimeError: Unknown model format! Cannot find reader for model format: xml and read the model: G:\seg\openvino_pyinstaller\seg\cho_openvino_model\paddle2onnx_model.xml. Please check that reader library exists in your PATH.

```

**Comment by fanweiya** [comment]
解决方案：
推荐使用[QPT库](https://github.com/QPT-Family/QPT)进行打包，不推荐pyinstaller打包openvino
