### ISSUE TITLE
module 'paddlex' has no attribute 'ppdet'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1115]
问题类型：其它  

**PaddleX版本**  

Python 3.6

paddle2onnx         0.7
paddlehub           2.1.0
paddlenlp           2.0.5
paddlepaddle-gpu    2.1.2.post112
paddleslim          2.1.1
paddlex             2.0.0

**问题描述**  

========================

```

python main.py
E:\anaconda3\envs\XXXX\lib\site-packages\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    from CamOperation_class import *
  File "F:\xxxx\CamOperation_class.py", line 27, in <module>
    import paddlex as pdx
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\cv\models\__init__.py", line 17, in <module>
    from .detector import *
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\cv\models\detector.py", line 25, in <module>
    import paddlex.ppdet as ppdet
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\ppdet\engine\__init__.py", line 15, in <module>
    from . import trainer
  File "E:\anaconda3\envs\XXXX\lib\site-packages\paddlex\ppdet\engine\trainer.py", line 40, in <module>
    import paddlex.ppdet.utils.stats as stats
AttributeError: module 'paddlex' has no attribute 'ppdet'
```

-------------------------------

在python3.8 不会报这个错误
python3.6 会

**Comment by will-jl944** [comment]
感谢反馈，该问题已经进行修复。pr合入后可以参考[安装教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85)使用修复后的版本。

**Comment by huanhuan-xiao** [comment]
你好，我的python3.6也遇到AttributeError: module 'paddlex' has no attribute  @'ppdet'这样的问题，但是参考[安装教程]的链接失效了，麻烦能提供一下解决办法吗？

> 感谢反馈，该问题已经进行修复。pr合入后可以参考[安装教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85)使用修复后的版本。

**Comment by huanhuan-xiao** [comment]
我已经解决了，将trainer.py 中的
import paddlex.ppdet.utils.stats as stats
修改为
from paddlex.ppdet.utils import stats
并将tracker.py中的import paddlex.ppdet.utils.stats as stats注释掉
> 你好，我的python3.6也遇到AttributeError: module 'paddlex' has no attribute @'ppdet'这样的问题，但是参考[安装教程]的链接失效了，麻烦能提供一下解决办法吗？
> 
> > 感谢反馈，该问题已经进行修复。pr合入后可以参考[安装教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85)使用修复后的版本。
