### ISSUE TITLE
paddlex运行问题

### ISSUE THREAD

**Issue by adan2017** [PaddlePaddle/PaddleX#1153]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
PaddleX 版本 1.2.8    Paddle可视化客户端版本 1.1.7  飞桨版本：1.8.4   CUDA版本：10  CUDNN版本：7.6.5
**问题描述**  
运行 paddleX进行图像分割，模型无法训练，日志如下
===================================  
This log file path is C:\Users\P72\paddlex_workspace\projects\P0004\T0008\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
Process Process-1:17:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\segmentation.py", line 129, in train
  File "paddlexui\pms\model_tasks\train\segmentation.py", line 72, in build_datasets
  File "site-packages\paddlex\cv\datasets\seg_dataset.py", line 70, in __init__
Exception: A space is defined as the separator, but it exists in image or label name JPEGImages\weed (272).jpg Annotations\weed (272).png

**Comment by will-jl944** [comment]
> JPEGImages\weed (272).jpg

路径不要包含空格。
