### ISSUE TITLE
module 'paddlex' has no attribute 'ppdet'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1170]
问题类型：其它  

**PaddleX版本**  
WIN11

paddlepaddle-gpu                  2.1.3.post112
paddleslim                        2.1.1
paddlex                           2.0.0
Python 3.6.13 |Anaconda

**问题描述**  

========================
```

python ccmain.py

E:\anaconda3\envs\PaddlX36\lib\site-packages\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
Traceback (most recent call last):
  File "dianbiao_main.py", line 44, in <module>
    from CamOperation_dianbiao import *
  File "F:\AI\00__OK\CamOperation_dianbiao.py", line 27, in <module>
    import paddlex as pdx
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\cv\models\__init__.py", line 17, in <module>
    from .detector import *
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\cv\models\detector.py", line 25, in <module>
    import paddlex.ppdet as ppdet
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\ppdet\engine\__init__.py", line 15, in <module>
    from . import trainer
  File "E:\anaconda3\envs\PaddlX36\lib\site-packages\paddlex\ppdet\engine\trainer.py", line 40, in <module>
    import paddlex.ppdet.utils.stats as stats
AttributeError: module 'paddlex' has no attribute 'ppdet'
```

**Comment by FlyingQianMM** [comment]
已知问题，已修复。先把python3.6升级到python3.7吧
