### ISSUE TITLE
小度熊实例分割报错：numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1212]
## 复现

官方实例分割演示文件
python mask_rcnn_r50_fpn.py

官方 小度熊分拣数据集

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddlepaddle-gpu                  2.1.3.post112
paddlex                           2.0.0

numpy                             1.21.2

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
win11

3. 请问您使用的Python版本是？
anaconda Python 3.8.12

5. 请问您使用的CUDA/cuDNN的版本号是？
cudn 11.2
cuDNN v8.1.1

————————————————————
```
python mask_rcnn_r50_fpn.py

E:\anaconda3\envs\python38\lib\site-packages\paddle\distributed\parallel.py:119: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
2021-10-21 11:20:11 [INFO]      Downloading xiaoduxiong_ins_det.tar.gz from https://bj.bcebos.com/paddlex/datasets/xiaoduxiong_ins_det.tar.gz
100%|████████████████████████████████████████████████████████████████████████████| 3982/3982 [00:00<00:00, 4819.60KB/s]
2021-10-21 11:20:12 [INFO]      Decompressing ./xiaoduxiong_ins_det.tar.gz...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-10-21 11:20:12 [INFO]      Starting to read file list from dataset...
2021-10-21 11:20:12 [INFO]      14 samples in file xiaoduxiong_ins_det/train.json, including 14 positive samples and 0 negative samples.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-10-21 11:20:12 [INFO]      Starting to read file list from dataset...
2021-10-21 11:20:12 [INFO]      4 samples in file xiaoduxiong_ins_det/val.json, including 4 positive samples and 0 negative samples.
W1021 11:20:12.944486  9976 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W1021 11:20:12.957521  9976 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-10-21 11:20:14 [INFO]      Downloading mask_rcnn_r50_fpn_2x_coco.pdparams from https://paddledet.bj.bcebos.com/models/mask_rcnn_r50_fpn_2x_coco.pdparams
100%|████████████████████████████████████████████████████████████████████████| 261958/261958 [00:32<00:00, 7991.20KB/s]
2021-10-21 11:20:47 [INFO]      Loading pretrained model from output/mask_rcnn_r50_fpn\pretrain\mask_rcnn_r50_fpn_2x_coco.pdparams
2021-10-21 11:20:49 [WARNING]   [SKIP] Shape of pretrained params bbox_head.bbox_score.weight doesn't match.(Pretrained: [1024, 81], Actual: [1024, 2])
2021-10-21 11:20:49 [WARNING]   [SKIP] Shape of pretrained params bbox_head.bbox_score.bias doesn't match.(Pretrained: [81], Actual: [2])
2021-10-21 11:20:49 [WARNING]   [SKIP] Shape of pretrained params bbox_head.bbox_delta.weight doesn't match.(Pretrained: [1024, 320], Actual: [1024, 4])
2021-10-21 11:20:49 [WARNING]   [SKIP] Shape of pretrained params bbox_head.bbox_delta.bias doesn't match.(Pretrained: [320], Actual: [4])
2021-10-21 11:20:49 [WARNING]   [SKIP] Shape of pretrained params mask_head.mask_fcn_logits.weight doesn't match.(Pretrained: [80, 256, 1, 1], Actual: [1, 256, 1, 1])
2021-10-21 11:20:49 [WARNING]   [SKIP] Shape of pretrained params mask_head.mask_fcn_logits.bias doesn't match.(Pretrained: [80], Actual: [1])
2021-10-21 11:20:49 [INFO]      There are 301/307 variables loaded into MaskRCNN.
E:\anaconda3\envs\python38\lib\site-packages\paddlex\ppdet\modeling\proposal_generator\target.py:286: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return mask_util.decode(rle).astype(np.bool)
########################
#########
2021-10-21 11:20:53 [INFO]      base [TRAIN] Epoch=1/12, Step=10/14, loss_mask=0.547831, loss_rpn_cls=0.017113, loss_rpn_reg=0.039392, loss_bbox_cls=0.368648, loss_bbox_reg=0.637914, loss=1.610899, lr=0.001125, time_each_step=0.4s, eta=0:1:4
2021-10-21 11:20:54 [INFO]      [TRAIN] Epoch 1 finished, loss_mask=3.8378925, loss_rpn_cls=0.054269005, loss_rpn_reg=0.04423508, loss_bbox_cls=0.4465019, loss_bbox_reg=0.48798132, loss=4.870879 .
2021-10-21 11:20:54 [INFO]      Start to evaluate(total_samples=4, total_steps=4)...
2021-10-21 11:20:56 [INFO]      Start evaluate...
creating index...
index created!
Traceback (most recent call last):
  File "mask_rcnn_r50_fpn.py", line 44, in <module>
    model.train(
  File "E:\anaconda3\envs\python38\lib\site-packages\paddlex\cv\models\detector.py", line 280, in train
    self.train_loop(
  File "E:\anaconda3\envs\python38\lib\site-packages\paddlex\cv\models\base.py", line 460, in train_loop
    eval_result = self.evaluate(
  File "E:\anaconda3\envs\python38\lib\site-packages\paddlex\cv\models\detector.py", line 458, in evaluate
    eval_metric.accumulate()
  File "E:\anaconda3\envs\python38\lib\site-packages\paddlex\cv\models\utils\det_metrics\metrics.py", line 192, in accumulate
    bbox_stats = cocoapi_eval(
  File "E:\anaconda3\envs\python38\lib\site-packages\paddlex\cv\models\utils\det_metrics\coco_utils.py", line 94, in cocoapi_eval
    coco_eval = COCOeval(coco_gt, coco_dt, style)
  File "E:\anaconda3\envs\python38\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "E:\anaconda3\envs\python38\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "E:\anaconda3\envs\python38\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 5, in linspace
  File "E:\anaconda3\envs\python38\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
__________________________
```
# 定义训练和验证时的transforms
# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/transforms/transforms.md
train_transforms = T.Compose([
    T.RandomResizeByShort(
        short_sizes=[640, 672, 704, 736, 768, 800],
        max_size=1333,
        interp='CUBIC'), T.RandomHorizontalFlip(), T.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transforms = T.Compose([
    T.ResizeByShort(
        short_size=800, max_size=1333, interp='CUBIC'), T.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 定义训练和验证所用的数据集
# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/datasets.md
train_dataset = pdx.datasets.CocoDetection(
    data_dir='xiaoduxiong_ins_det/JPEGImages',
    ann_file='xiaoduxiong_ins_det/train.json',
    transforms=train_transforms,
    shuffle=True)
eval_dataset = pdx.datasets.CocoDetection(
    data_dir='xiaoduxiong_ins_det/JPEGImages',
    ann_file='xiaoduxiong_ins_det/val.json',
    transforms=eval_transforms)

# 初始化模型，并进行训练
# 可使用VisualDL查看训练指标，参考https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/visualdl.md
num_classes = len(train_dataset.labels)
model = pdx.det.MaskRCNN(
    num_classes=num_classes, backbone='ResNet50', with_fpn=True)

# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/instance_segmentation.md
# 各参数介绍与调整说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/parameters.md
model.train(
    num_epochs=12,
    train_dataset=train_dataset,
    train_batch_size=1,
    eval_dataset=eval_dataset,
    pretrain_weights='COCO',
    learning_rate=0.00125,
    lr_decay_epochs=[8, 11],
    warmup_steps=10,
    warmup_start_lr=0.0,
    save_dir='output/mask_rcnn_r50_fpn',
    use_vdl=True)

```

**Comment by monkeycc** [comment]
numpy\core\function_base.py

num = operator.index(num)
改为
num = operator.index(int(num))

可以正常跑

paddlex是否更新一下 传递参数的时候 直接转换为int
但是这样又不知道 是否有什么影响

**Comment by will-jl944** [comment]
报错是numpy和pycocotools版本不兼容导致的，你在使用的numpy和pycocotools版本分别是多少？

**Comment by monkeycc** [comment]
paddlepaddle-gpu                  2.1.3.post112
paddlex                           2.0.0
pycocotools                       2.0
numpy                             1.21.2

@will-jl944

**Comment by FlyingQianMM** [comment]
降低numpy版本可解决该问题
