### ISSUE TITLE
local variable 'downsample_ratios' referenced before assignment

### ISSUE THREAD

**Issue by sunxwfirst** [PaddlePaddle/PaddleX#1213]
PaddlePaddle: 2.1.3
PaddleX:  2.0.0
Python: 3.8
操作系统：win
CUDA:  11.2
cuDNN:  8.1.1
模型类型: ppyolov2
问题： 在调用 pdx.deploy.Predictor 时出现以下错误。

C:\exe\anaconda3\envs\paddle_env\lib\site-packages\paddle\distributed\parallel.py:119: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File "C:\exe\anaconda3\envs\paddle_env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\exe\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\unique_name.py", line 226, in guard
    yield
  File "C:\exe\anaconda3\envs\paddle_env\lib\site-packages\paddlex\cv\models\load_model.py", line 85, in load_model
    model = getattr(paddlex.cv.models, model_info['Model'])(
  File "C:\exe\anaconda3\envs\paddle_env\lib\site-packages\paddlex\cv\models\detector.py", line 1504, in __init__
    self.downsample_ratios = downsample_ratios
UnboundLocalError: local variable 'downsample_ratios' referenced before assignment

**Comment by FlyingQianMM** [comment]
该已知问题已经修复，使用develop可正常运行，develop安装方式见文档 https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85
