### ISSUE TITLE
目标检测使用add_negative_samples添加背景图片后，模型训练报错

### ISSUE THREAD

**Issue by libingbingdev** [PaddlePaddle/PaddleX#1264]
**## 问题描述**
目标检测任务，使用add_negative_samples方法添加背景图片后，模型训练报错；不使用add_negative_samples添加背景图片，可以正常训练

**## 环境**
Aistudio至尊版GPU， PaddlePaddle==2.2.0，PaddleX==2.0.0，Python==3.7

**## 运行代码**
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from paddlex import transforms
import paddlex as pdx
import paddle
import cv2

train_transforms = transforms.Compose([
    transforms.RandomDistort(),
    transforms.RandomHorizontalFlip(),
    transforms.ResizeByShort(short_size=1024, max_size=2048),
    transforms.Normalize(),
])
eval_transforms = transforms.Compose([
    transforms.ResizeByShort(short_size=1024, max_size=2048),
    transforms.Normalize(),
])

train_dataset = pdx.datasets.VOCDetection(
    data_dir='Datasets',
    file_list='Datasets/train_list.txt',
    label_list='Datasets/labels.txt',
    transforms=train_transforms,
    shuffle=True)
eval_dataset = pdx.datasets.VOCDetection(
    data_dir='Datasets',
    file_list='Datasets/val_list.txt',
    label_list='Datasets/labels.txt',
    transforms=eval_transforms)
_输出日志：
2021-11-22 13:57:41 [INFO]	Starting to read file list from dataset...
2021-11-22 13:57:44 [INFO]	2038 samples in file Datasets/train_list.txt, including 2038 positive samples and 0 negative samples.
creating index...
index created!
2021-11-22 13:57:44 [INFO]	Starting to read file list from dataset...
2021-11-22 13:57:45 [INFO]	509 samples in file Datasets/val_list.txt, including 509 positive samples and 0 negative samples.
creating index...
index created!_

**train_dataset.add_negative_samples(image_dir='Background')**
_输出日志：
2021-11-22 14:00:28 [INFO]	1356 negative samples added. Dataset contains 2038 positive samples and 1356 negative samples._

num_classes = len(train_dataset.labels) + 1

model = pdx.load_model('output/faster_rcnn_r50_vd_dcn/best_model')
_输出日志：
W1122 14:01:33.939844   224 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W1122 14:01:33.944779   224 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2021-11-22 14:01:36 [INFO]	Model[FasterRCNN] loaded._

model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=4,
    eval_dataset=eval_dataset,
    save_interval_epochs=1,
    metric='VOC',
    learning_rate=0.01,
    lr_decay_epochs=[213, 240],
    warmup_steps=500,
    save_dir='output/faster_rcnn_r50_vd_dcn',
    use_vdl=True,
    early_stop=True)
_输出日志：
2021-11-22 14:01:43 [INFO]	Loading pretrained model from full_output/faster_rcnn_r50_vd_dcn/pretrain/ResNet50_vd_ssld_v2_pretrained.pdparams
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3a.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3a.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3b.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3b.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3c.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3c.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3d.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res3.res3d.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4a.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4a.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4b.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4b.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4c.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4c.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4d.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4d.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4e.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4e.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4f.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res4.res4f.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res5.res5a.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res5.res5a.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res5.res5b.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res5.res5b.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res5.res5c.branch2b.conv_offset.weight is not in pretrained model
2021-11-22 14:01:43 [WARNING]	backbone.res5.res5c.branch2b.conv_offset.bias is not in pretrained model
2021-11-22 14:01:43 [WARNING]	neck.fpn_inner_res2_sum_lateral.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res2_sum_lateral.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res2_sum.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res2_sum.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res3_sum_lateral.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res3_sum_lateral.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res3_sum.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res3_sum.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res4_sum_lateral.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res4_sum_lateral.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res4_sum.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res4_sum.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res5_sum.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_inner_res5_sum.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res5_sum.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	neck.fpn_res5_sum.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	rpn_head.rpn_feat.rpn_conv.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	rpn_head.rpn_feat.rpn_conv.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	rpn_head.rpn_rois_score.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	rpn_head.rpn_rois_score.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	rpn_head.rpn_rois_delta.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	rpn_head.rpn_rois_delta.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.head.fc6.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.head.fc6.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.head.fc7.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.head.fc7.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.bbox_score.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.bbox_score.bias is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.bbox_delta.weight is not in pretrained model
2021-11-22 14:01:44 [WARNING]	bbox_head.bbox_delta.bias is not in pretrained model
2021-11-22 14:01:44 [INFO]	There are 275/331 variables loaded into FasterRCNN.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 355, in _worker_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 345, in _worker_loop
    for b in batch
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 345, in <listcomp>
    for b in batch
RuntimeError: (Unavailable) Memory map failed when create shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:81)

Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 355, in _worker_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 345, in _worker_loop
    for b in batch
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 345, in <listcomp>
    for b in batch
RuntimeError: (Unavailable) Memory map failed when create shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:81)

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 583, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 599, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 2 workers exit unexpectedly, pids: 771, 772

---------------------------------------------------------------------------SystemError Traceback (most recent call last)/tmp/ipykernel_224/2069708313.py in <module> 11 save_dir='full_output/faster_rcnn_r50_vd_dcn', 12 use_vdl=True, ---> 13 early_stop=True) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/detector.py in train(self, num_epochs, train_dataset, train_batch_size, eval_dataset, optimizer, save_interval_epochs, log_interval_steps, save_dir, pretrain_weights, learning_rate, warmup_steps, warmup_start_lr, lr_decay_epochs, lr_decay_gamma, metric, use_ema, early_stop, early_stop_patience, use_vdl, resume_checkpoint) 289 early_stop=early_stop, 290 early_stop_patience=early_stop_patience, --> 291 use_vdl=use_vdl) 292 293 def quant_aware_train(self, /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py in train_loop(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, ema, early_stop, early_stop_patience, use_vdl) 327 step_time_tic = time.time() 328 --> 329 for step, data in enumerate(self.train_data_loader()): 330 if nranks > 1: 331 outputs = self.run(ddp_net, data, mode='train') /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self) 695 696 if in_dygraph_mode(): --> 697 data = self._reader.read_next_var_list() 698 data = _restore_batch(data, self._structure_infos.pop(0)) 699 else: SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)_

**Comment by FlyingQianMM** [comment]
卸载已安装的PaddleX，安装PaddleX develop可解决该问题。[PaddleX develop安装文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/quick_start_API.md#paddlex-develop%E5%AE%89%E8%A3%85)

**Comment by libingbingdev** [comment]
此方法对Aistudio不适用，无法在线安装develop版本的paddlex

**Comment by will-jl944** [comment]
aistudio提供了终端，在里面操作即可。

**Comment by Aierbx** [comment]
> aistudio提供了终端，在里面操作即可。

你好，我也遇到了这个问题，请问具体再aistudio里面应该如何操作呢？谢谢

**Comment by will-jl944** [comment]
PaddleX 2.1修复了该问题，pip安装2.1版本即可。
