### ISSUE TITLE
转换onnx的问题AttributeError: 'YOLOv3' object has no attribute 'test_prog'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1265]
paddle2onnx                       0.4
paddlepaddle                      2.2.0
paddleslim                        2.1.1
paddlex                           2.0.0
```

paddlex --export_inference --model_dir=/path/to/paddle_model --save_dir=./inference_model --fixed_input_shape=[608,608]

python converter.py --model_dir /path/to/inference_model --save_dir /path/to/openvino_model --fixed_input_shape [608,608]


```
```

C:\Python37\lib\site-packages\paddle\distributed\parallel.py:136: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
C:\Python37\lib\site-packages\paddle\fluid\backward.py:1697: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return list(x) if isinstance(x, collections.Sequence) else [x]
2021-11-23 22:08:25 [INFO]      Model[YOLOv3] loaded.
Traceback (most recent call last):
  File "converter.py", line 127, in <module>
    main()
  File "converter.py", line 111, in main
    prog = model.test_prog
AttributeError: 'YOLOv3' object has no attribute 'test_prog'
```

**Comment by FlyingQianMM** [comment]
抱歉，converter.py目前仅适用于PaddleX 1.3.11。

PaddleX 2.0模型转换到onnx格式，目前需要您参考converter.py使用Paddle2ONNX进行转换。

**Comment by monkeycc** [comment]
```
  File "e:\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "e:\anaconda3\lib\site-packages\paddle2onnx\command.py", line 136, in main
    program2onnx(
  File "e:\anaconda3\lib\site-packages\paddle2onnx\command.py", line 99, in program2onnx
    [program, feed_var_names, fetch_vars] = fluid.io.load_inference_model(
  File "e:\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "e:\anaconda3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\paddle\fluid\framework.py", line 236, in __impl__
    return func(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\paddle\fluid\io.py", line 1526, in load_inference_model
    with open(model_filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\paddlex_workspace\\P0002-T0036_ONNXX\\inference_model\\inference_model\\__model__'

```

PaddleX 2.0模型转换到onnx格式
也不行

是一定要用converter.py来更改，才能转换为ONNX吗
@FlyingQianMM

**Comment by FlyingQianMM** [comment]
converter.py目前仅适用于PaddleX 1.3.11。converter.py暂未适配2.0模型。
