### ISSUE TITLE
Android 端，demo 可以运行。替换模型和yml之后报错。yml是否也需要转化呢？

### ISSUE THREAD

**Issue by SJJ-dot** [PaddlePaddle/PaddleX#1270]
```
2021-11-26 10:04:44.672 2731-2731/com.baidu.paddlex.lite.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddlex.lite.demo, PID: 2731
    java.lang.RuntimeException: Unable to resume activity {com.baidu.paddlex.lite.demo/com.baidu.paddlex.lite.demo.MainActivity}: Can't construct a java object for tag:yaml.org,2002:python/tuple; exception=Class not found: python/tuple
     in 'reader', line 6, column 18:
            target_size: !!python/tuple
                         ^
    
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4430)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: Can't construct a java object for tag:yaml.org,2002:python/tuple; exception=Class not found: python/tuple
     in 'reader', line 6, column 18:
            target_size: !!python/tuple
                         ^
    
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:349)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:376)
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:185)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:357)
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:532)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:376)
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:185)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:357)
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:532)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:277)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:248)
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:513)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:376)
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:185)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:357)
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:532)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:436)
        at com.baidu.paddlex.config.ConfigParser.init(ConfigParser.java:51)
        at com.baidu.paddlex.lite.demo.MainActivity.onResume(MainActivity.java:410)
2021-11-26 10:04:44.673 2731-2731/com.baidu.paddlex.lite.demo E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:7614)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4412)
        	... 11 more
     Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: python/tuple
        at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:664)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:334)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:344)
        	... 40 more
2021-11-26 10:04:44.718 2731-2731/? I/Process: Sending signal. PID: 2731 SIG: 9

```

**Comment by FlyingQianMM** [comment]
抱歉，PaddleX 2.0暂未适配Paddle Lite部署。
