### ISSUE TITLE
裁剪模型demo在Windows平台运行失败。paddlex 1.3

### ISSUE THREAD

**Issue by SJJ-dot** [PaddlePaddle/PaddleX#1276]
```
(paddlex1) PS D:\GitHub\PaddleX\tutorials\slim\prune\image_classification> python mobilenetv2_train.py
2021-12-01 16:43:34 [INFO]      Downloading vegetables_cls.tar.gz from https://bj.bcebos.com/paddlex/datasets/vegetables_cls.tar.gz
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26032/26032 [00:08<00:00, 2932.00KB/s]
2021-12-01 16:43:44 [INFO]      Decompressing ./vegetables_cls.tar.gz...
2021-12-01 16:43:54 [INFO]      Starting to read file list from dataset...
2021-12-01 16:43:54 [INFO]      840 samples in file vegetables_cls/train_list.txt
2021-12-01 16:43:54 [INFO]      Starting to read file list from dataset...
2021-12-01 16:43:54 [INFO]      240 samples in file vegetables_cls/val_list.txt
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=8 # for example, set CPU_NUM as number of physical CPU core which is 8.

!!! The default number of CPU_NUM=1.
2021-12-01 16:43:58 [INFO]      Connecting PaddleHub server to get pretrain weights...
Download https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV2_pretrained.tar
[##################################################] 100.00%
Decompress C:\Users\DoWang\.paddlehub\tmp\tmp0ihg_9um\MobileNetV2_pretrained.tar
[##################################################] 100.00%
2021-12-01 16:44:07 [INFO]      Load pretrain weights from output/mobilenetv2\pretrain\MobileNetV2_x1.0.
Traceback (most recent call last):
  File "mobilenetv2_train.py", line 41, in <module>
    use_vdl=True)
  File "E:\Anaconda3\envs\paddlex1\lib\site-packages\paddlex\cv\models\classifier.py", line 195, in train
    resume_checkpoint=resume_checkpoint)
  File "E:\Anaconda3\envs\paddlex1\lib\site-packages\paddlex\cv\models\base.py", line 264, in net_initialize
    self.exe, self.train_prog, pretrain_weights, fuse_bn)
  File "E:\Anaconda3\envs\paddlex1\lib\site-packages\paddlex\utils\utils.py", line 259, in load_pretrain_weights
    weights_dir))
Exception: File output/mobilenetv2\pretrain\MobileNetV2_x1.0 is not a paddle parameter file
```

**Comment by will-jl944** [comment]
使用的是具体哪一个demo？麻烦贴一下代码。

PaddleX具体版本是多少呢？静态图版本的PaddleX请使用1.3.11。 `pip install paddlex==1.3.11`
