### ISSUE TITLE
数据校验失败

### ISSUE THREAD

**Issue by fanfan321** [PaddlePaddle/PaddleX#1311]
实例分割数据集，labelme标注，用labelme2coco转为coco数据集，导入时校验失败，'1.jpg'是数据集图片名称，报错信息看不懂

数据校验失败！

Traceback (most recent call last):
  File "paddlexui\pms\dataset\operate.py", line 42, in _check_and_copy
  File "paddlexui\pms\dataset\ins_seg_dataset.py", line 101, in check_dataset
  File "paddlexui\pms\dataset\utils.py", line 239, in get_npy_from_coco_json
KeyError: '1.jpg'

PaddleX 1.1.6
win10
Python 3.6.12

**Comment by FlyingQianMM** [comment]
数据格式转换参考[PaddleX 数据格式转换](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data/convert.md)
