### ISSUE TITLE
gui训练报错!_src.empty() in function 'cv::cvtColor'Hint: Expected killed_ != true, but received killed_:1

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1313]
PaddleX 2.0 GUI
gui训练报错
!_src.empty() in function 'cv::cvtColor'Hint: Expected killed_ != true, but received killed_:1

我看报错信息
cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
以为是单通道 灰色

但是仔细查看图片 
是RGB格式的图片

```
This log file path is G:\AI_workspace33\projects\P0003\T0003\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\PaddleX200\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
D:\PaddleX200\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
2021-12-16 11:00:26 WARNING: DataLoader reader thread raised an exception.
Process Process-1:3:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "D:\PaddleX200\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop
    six.reraise(*sys.exc_info())
  File "site-packages\six.py", line 719, in reraise
  File "D:\PaddleX200\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "D:\PaddleX200\paddle\fluid\dataloader\fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "D:\PaddleX200\paddle\fluid\dataloader\fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "D:\PaddleX200\paddlex\cv\datasets\voc.py", line 322, in __getitem__
    sample = self.transforms(sample)
  File "D:\PaddleX200\paddlex\cv\transforms\operators.py", line 119, in __call__
    sample = self.decode_image(sample)
  File "D:\PaddleX200\paddlex\cv\transforms\operators.py", line 82, in __call__
    sample = self.apply(sample)
  File "D:\PaddleX200\paddlex\cv\transforms\operators.py", line 189, in apply
    sample['image'] = self.apply_im(sample['image'])
  File "D:\PaddleX200\paddlex\cv\transforms\operators.py", line 164, in apply_im
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 226, in train
  File "D:\PaddleX200\paddlex\cv\models\detector.py", line 291, in train
    use_vdl=use_vdl)
  File "D:\PaddleX200\paddlex\cv\models\base.py", line 329, in train_loop
    for step, data in enumerate(self.train_data_loader()):
  File "D:\PaddleX200\paddle\fluid\dataloader\dataloader_iter.py", line 197, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release2\paddle/fluid/operators/reader/blocking_queue.h:166)


```

**Comment by FlyingQianMM** [comment]
看起来是图片的问题。起个python任务，遍历下image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)看下是哪张图片的问题把

**Comment by mrcangye** [comment]
请问查出了这个图片有问题后，这个图片需要如何处理才会在后面的程序中不被报错？

**Comment by monkeycc** [comment]
@mrcangye  要删除才可以  手动操作

**Comment by mrcangye** [comment]
> 
@monkeycc 已经解决了，是数据集中的部分图片的问题，使用画图软件重新另存为原来格式就可以了。csdn上一群坑，全是说图片路径有问题。感谢！
