### ISSUE TITLE
PaddleX API 裁剪报错：ValueError: Given pretrained weights best_model/model.pdparams/model.pdparams is undefined.

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleX#1345]
## 描述
PaddleX API训练deeplabv3+完成后，裁剪时报错：
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "pms/model_tasks/tasks.py", line 73, in _call_paddlex_train
  File "pms/model_tasks/train/segmentation.py", line 169, in train
  File "/home/ubantu/Demo/PaddleX/paddlex/cv/models/base.py", line 82, in net_initialize
    backbone_name=backbone_name)
  File "/home/ubantu/Demo/PaddleX/paddlex/utils/checkpoint.py", line 374, in get_pretrain_weights
    flag))
ValueError: Given pretrained weights /home/ubantu/paddlex_workspace/projects/P0006/T0014/output/best_model/model.pdparams/model.pdparams is undefined.

## 问题
经过检查model.pdparams文件的实际地址是 best_model/model.pdparams，而报错是因为程序在best_model/model.pdparams/model.pdparams目录中寻找。请问是paddlex程序错了吗？如何改正错误？
## 环境
paddleX2.0.0，ubantu， python3.6

**Comment by FlyingQianMM** [comment]
> PaddleX API训练deeplabv3+完成后，裁剪时报错：

这是用PaddleX API完成的训练，然后用PaddleX API做剪裁么？

```
File "multiprocessing/process.py", line 297, in _bootstrap
File "multiprocessing/process.py", line 99, in run
File "pms/model_tasks/tasks.py", line 73, in _call_paddlex_train
File "pms/model_tasks/train/segmentation.py", line 169, in train
File "/home/ubantu/Demo/PaddleX/paddlex/cv/models/base.py", line 82, in net_initialize
backbone_name=backbone_name)
File "/home/ubantu/Demo/PaddleX/paddlex/utils/checkpoint.py", line 374, in get_pretrain_weights
flag))
ValueError: Given pretrained weights /home/ubantu/paddlex_workspace/projects/P0006/T0014/output/best_model/model.pdparams/model.pdparams is undefined.
```
这段日志看起来是PaddleX GUI的日志呀？

**Comment by ff12343** [comment]
> > PaddleX API训练deeplabv3+完成后，裁剪时报错：
> 
> 这是用PaddleX API完成的训练，然后用PaddleX API做剪裁么？
> 
> ```
> File "multiprocessing/process.py", line 297, in _bootstrap
> File "multiprocessing/process.py", line 99, in run
> File "pms/model_tasks/tasks.py", line 73, in _call_paddlex_train
> File "pms/model_tasks/train/segmentation.py", line 169, in train
> File "/home/ubantu/Demo/PaddleX/paddlex/cv/models/base.py", line 82, in net_initialize
> backbone_name=backbone_name)
> File "/home/ubantu/Demo/PaddleX/paddlex/utils/checkpoint.py", line 374, in get_pretrain_weights
> flag))
> ValueError: Given pretrained weights /home/ubantu/paddlex_workspace/projects/P0006/T0014/output/best_model/model.pdparams/model.pdparams is undefined.
> ```
> 
> 这段日志看起来是PaddleX GUI的日志呀？

是GUI，在GUI上做训练，再在GUI上裁剪

**Comment by FlyingQianMM** [comment]
抱歉，分割任务的剪裁任务传预训练模型的GUI代码有点问题，我们在下个版本会修复。分类和检测任务的剪裁可以正常运行。

如果您目前要用GUI完成该模型的剪裁，最快的解决办法是：剪裁时手动修改预训练模型的路径。将文件`model.pdparams`移动至文件夹`model.pdparams`下：
例如：
![image](https://user-images.githubusercontent.com/22235422/149061557-ffbc4209-3cb3-4db1-aa48-e945832cac55.png)


另外，不用GUI也可以用API模式完成该模型的剪裁，参考FAQ Q5: https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md/#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98

API剪裁参考：https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/slim/prune
