### ISSUE TITLE
Paddle 2.1.0 GUI,cv2.error: OpenCV(4.1.2)  error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1346]
Paddle 2.1.0 GUI

```
This log file path is H:\AI_workspace21\projects\P0005\T0018\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
H:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "H:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "H:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\datasets\voc.py", line 324, in __getitem__
    sample = self.transforms(sample)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 119, in __call__
    sample = self.decode_image(sample)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 82, in __call__
    sample = self.apply(sample)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 189, in apply
    sample['image'] = self.apply_im(sample['image'])
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 164, in apply_im
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

```

```

This log file path is H:\AI_workspace21\projects\P0005\T0018\out.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
2022-01-08 11:34:17 [INFO]	Starting to read file list from dataset...
2022-01-08 11:34:17 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:17 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:18 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:18 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:18 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:18 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:18 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:18 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:19 [INFO]	2272 samples in file H:\AI_workspace21\datasets\D0004\train_list.txt, including 2272 positive samples and 0 negative samples.
creating index...
index created!
2022-01-08 11:34:19 [INFO]	Starting to read file list from dataset...
2022-01-08 11:34:19 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:19 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:19 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:19 [WARNING]	Bounding box for object 3 does not satisfy x1 <= x2 and y1 <= y2, so this object is skipped
2022-01-08 11:34:20 [INFO]	649 samples in file H:\AI_workspace21\datasets\D0004\val_list.txt, including 649 positive samples and 0 negative samples.
creating index...
index created!
2022-01-08 11:34:22 [INFO]	Loading pretrained model from H:\AI_workspace21\pretrain\FasterRCNN_ResNet50_vd_fpn_COCO\faster_rcnn_r50_vd_fpn_2x_coco.pdparams
2022-01-08 11:34:22 [WARNING]	[SKIP] Shape of pretrained params bbox_head.bbox_score.weight doesn't match.(Pretrained: [1024, 81], Actual: [1024, 13])
2022-01-08 11:34:22 [WARNING]	[SKIP] Shape of pretrained params bbox_head.bbox_score.bias doesn't match.(Pretrained: [81], Actual: [13])
2022-01-08 11:34:22 [WARNING]	[SKIP] Shape of pretrained params bbox_head.bbox_delta.weight doesn't match.(Pretrained: [1024, 320], Actual: [1024, 48])
2022-01-08 11:34:22 [WARNING]	[SKIP] Shape of pretrained params bbox_head.bbox_delta.bias doesn't match.(Pretrained: [320], Actual: [48])
2022-01-08 11:34:23 [INFO]	There are 301/305 variables loaded into FasterRCNN.
```

**Comment by FlyingQianMM** [comment]
这个问题与您上次提的issue https://github.com/PaddlePaddle/PaddleX/issues/1313 类似，请参考之前的方法解决。

与另一个用户提的issue https://github.com/PaddlePaddle/PaddleX/issues/1336 也类似，该用户已经提供了解决办法，请参考
