### ISSUE TITLE
category_id': self.clsid2catid[int(l)]

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1359]
```
This log file path is H:\AI_workspace21\projects\P0013\T0044\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
H:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:4:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 263, in train
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 1378, in train
    early_stop_patience, use_vdl, resume_checkpoint)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 334, in train
    use_vdl=use_vdl)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\base.py", line 397, in train_loop
    return_details=True)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 500, in evaluate
    eval_metric.update(data, outputs)
  File "H:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\utils\det_metrics\metrics.py", line 130, in update
    'category_id': self.clsid2catid[int(l)],
KeyError: -1

```

看上去应该是哪个标注文件没有category_id
但是又不知道哪个文件有问题

**Comment by FlyingQianMM** [comment]
这是跑哪个模型？什么数据集格式？eval的间隔设置的多少？

**Comment by monkeycc** [comment]
目标检测 YOLO 和 RCNN  50VD
都会报错

也不知道哪里出现的问题 或者哪个文件有问题

**Comment by FlyingQianMM** [comment]
用我们提供的样例数据集会出现这个错误吗？看下可视化数据集的时候，可以正确的可视化目标和类别定义吗？
