### ISSUE TITLE
模型训练过程中报Invalid poly type错误，终止训练

### ISSUE THREAD

**Issue by liutinglong** [PaddlePaddle/PaddleX#1365]
2022-01-19 09:16:47 WARNING: DataLoader reader thread raised an exception.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop
    six.reraise(*sys.exc_info())
  File "site-packages\six.py", line 719, in reraise
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddle\fluid\dataloader\fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddle\fluid\dataloader\fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\datasets\voc.py", line 322, in __getitem__
    sample = self.transforms(sample)
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\transforms\operators.py", line 127, in __call__
    sample = op(sample)
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\transforms\operators.py", line 82, in __call__
    sample = self.apply(sample)
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\transforms\operators.py", line 500, in apply
    im_w)
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\transforms\operators.py", line 481, in apply_segm
    if is_poly(segm):
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\transforms\functions.py", line 70, in is_poly
    "Invalid poly type: {}".format(type(poly))
AssertionError: Invalid poly type: <class 'NoneType'>

Process Process-1:7:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 226, in train
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\models\detector.py", line 291, in train
    use_vdl=use_vdl)
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddlex\cv\models\base.py", line 329, in train_loop
    for step, data in enumerate(self.train_data_loader()):
  File "F:\paddle\PaddleX2.0.0_windows10\PaddleX\paddle\fluid\dataloader\dataloader_iter.py", line 197, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release2\paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by will-jl944** [comment]
标签图像（mask）没有读取成功，返回了None导致的，检查一下标签图像文件。

**Comment by liutinglong** [comment]
> 标签图像（mask）没有读取成功，返回了None导致的，检查一下标签图像文件。

如果注解中不设置标签图像（即"segmentation": []），使用category_id值来区分标注类型，还可以使用paddleX进行训练吗？
是不是paddleX中实例分割一定要人标注图像？

**Comment by will-jl944** [comment]
实例分割是进行像素级别的分类的，即需要标注中含有每一个像素所属的实例以及类别信息。

可否描述一下你的具体使用场景？

**Comment by liutinglong** [comment]
> 实例分割是进行像素级别的分类的，即需要标注中含有每一个像素所属的实例以及类别信息。
> 
> 可否描述一下你的具体使用场景？

做铝片表面缺陷检测的，有训练的图片和注解数据，但注解中是这样的
{"segmentation": [], "iscrowd": 0, "area": 9570, "image_id": 303, "bbox": [268, 236, 110, 87], "category_id": 3, "id": 808}, {"segmentation": [], "iscrowd": 0, "area": 16884, "image_id": 304, "bbox": [179, 150, 268, 63], "category_id": 2, "id": 809}

**Comment by will-jl944** [comment]
看到你的标注信息中只有缺陷的bounding box，如果不需要分割出缺陷的具体形状，只需要将有缺陷的位置用矩形框出来，使用目标检测模型即可。

**Comment by liutinglong** [comment]
> 看到你的标注信息中只有缺陷的bounding box，如果不需要分割出缺陷的具体形状，只需要将有缺陷的位置用矩形框出来，使用目标检测模型即可。

因为我这个缺陷一共分为四类，包括划痕，褶皱等，这个类别还是要区分的。这样的话只用目标检测就满足不了了。这种需求是不是就要重新标注图像了？

**Comment by will-jl944** [comment]
目标检测是区分类别的，结果会包含目标的位置（bounding box）以及类别。只不过无法给出缺陷的轮廓。

**Comment by liutinglong** [comment]
> 

谢谢，明白了
