### ISSUE TITLE
FasterRCNN输入图像格式和大小有要求吗？

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleX#1368]
环境：PaddlePaddle2.2、PaddleX2.1、Python3.7,Win10
利用FasterRCNN训练好的模型导出到hub,请问题对输入图像格式和大小有特别要求吗？

参考：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/hub_serving_deploy.md
如下 命令

```
paddlex --export_inference --model_dir=./output/FasterRCNN/best_model --save_dir=./FasterRCNN
hub convert --model_dir ./FasterRCNN/inference_model --module_name fr_fr --module_version 0.1 --output_dir  ./hubmodel
hub serving start -m fr_fr
```

大小一样的图像，发现有些图像hub serving 不识别，有些能正常识别？对输入图像格式和大小有特别要求吗？

**Comment by abanger** [comment]
补充下，直接在命令行测试如下出错信息

```
(nlp) D:\foguang>hub run fr_fr --input_path "D:\datasets\jiu01.jpg"
[2022-01-22 17:42:27,788] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
2022-01-22 17:42:27 [INFO]      Model[FasterRCNN] loaded.
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[37m---    fused 0 scale with matmule[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[37m---    fused 0 batch norm with relu activatione[0m
Traceback (most recent call last):
  File "d:\anaconda3\envs\nlp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\nlp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\anaconda3\envs\nlp\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlehub\commands\utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlehub\commands\run.py", line 56, in execute
    result = module._run_func(argv[1:])
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlehub\module\module.py", line 52, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\abanger\.paddlehub\modules\fr_fr\module.py", line 141, in run_cmd
    use_gpu=args.use_gpu)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlehub\compat\paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "C:\Users\abanger\.paddlehub\modules\fr_fr\module.py", line 83, in predict
    out = self.model.batch_predict(batch_data, **kwargs)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlex\deploy.py", line 268, in batch_predict
    return self.predict(img_file=image_list, **params)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlex\deploy.py", line 256, in predict
    images=images, topk=topk, transforms=transforms)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlex\deploy.py", line 219, in _run
    transforms=transforms)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlex\deploy.py", line 178, in postprocess
    preds = self._model._postprocess(net_outputs)
  File "d:\anaconda3\envs\nlp\lib\site-packages\paddlex\cv\models\detector.py", line 577, in _postprocess
    category = self.labels[int(num_id)]
IndexError: list index out of range
```

**Comment by FlyingQianMM** [comment]
> 大小一样的图像，发现有些图像hub serving 不识别，有些能正常识别？对输入图像格式和大小有特别要求吗？

对于识别不正确的图片，使用hub serving的预测结果，跟[直接加载预测](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/prediction.md)的结果是一致的吗？这里需要排除是模型本身预测不出的问题。

> (nlp) D:\foguang>hub run fr_fr --input_path "D:\datasets\jiu01.jpg"

我们目前没有提供`hub run`的使用示例，这个是您自己写的吗？

**Comment by abanger** [comment]
> > 大小一样的图像，发现有些图像hub serving 不识别，有些能正常识别？对输入图像格式和大小有特别要求吗？
> 
> 对于识别不正确的图片，使用hub serving的预测结果，跟[直接加载预测](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/prediction.md)的结果是一致的吗？这里需要排除是模型本身预测不出的问题。
> 
> > (nlp) D:\foguang>hub run fr_fr --input_path "D:\datasets\jiu01.jpg"
> 
> 我们目前没有提供`hub run`的使用示例，这个是您自己写的吗？

是自己写的，用paddlex建模，然后导入，hub转换。
发现图像变小有问题可以处理，但还是有问题无法处理。

**Comment by FlyingQianMM** [comment]
有试过使用paddlex提供的hub serving跑faster rcnn吗？faster rcnn不要求输入相同大小的图片，预处理环节会对输入图片做处理。

**Comment by abanger** [comment]
> 有试过使用paddlex提供的hub serving跑faster rcnn吗？faster rcnn不要求输入相同大小的图片，预处理环节会对输入图片做处理。

没测试“过使用paddlex提供的hub serving跑faster rcnn”，好像是新版本paddlex已不再提供hub服务？
请参考：“注意：使用此方式部署，需确保自己Python环境中PaddleHub的版本高于2.1.1” https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/hub_serving_deploy.md

**Comment by wobenxiaoyaoKurt** [comment]
我也有这个问题，只有FasterRCNN出这个问题
