### ISSUE TITLE
 paddleX今天是更新了吗？怎么昨天用还好好的，今天训练的时候进行eval评估就报错list out of index

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleX#1375]
## Checklist:
 paddleX今天是更新了吗？怎么昨天用还好好的，今天训练可以顺利进行，但是评估就报错index out of range
2022-01-26 01:27:46 [INFO]	Start to evaluate(total_samples=7, total_steps=7)...
Traceback (most recent call last):
  File "/content/drive/My Drive/helmet.py", line 67, in <module>
    use_vdl=True)  # 其用visuadl进行可视化训练记录
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 334, in train
    use_vdl=use_vdl)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/base.py", line 397, in train_loop
    return_details=True)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 500, in evaluate
    eval_metric.update(data, outputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/utils/det_metrics/metrics.py", line 120, in update
    difficult)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/ppdet/metrics/map_utils.py", line 233, in update
    self.class_score_poss[int(l)].append([s, 0.0])
IndexError: list index out of range

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？
自己的数据集
4. 请提供您出现的报错信息及相关log
2022-01-26 02:24:56 [INFO]	Starting to read file list from dataset...
2022-01-26 02:24:56 [INFO]	67 samples in file /content/drive/My Drive/PaddleDetection/dataset/voc/aistudio/train.txt, including 67 positive samples and 0 negative samples.
creating index...
index created!
2022-01-26 02:24:56 [INFO]	Starting to read file list from dataset...
2022-01-26 02:24:56 [INFO]	7 samples in file /content/drive/My Drive/PaddleDetection/dataset/voc/aistudio/val.txt, including 7 positive samples and 0 negative samples.
creating index...
index created!
2022-01-26 02:24:56 [WARNING]	Extremely small objects found. 1 of 93 labels are < 3 pixels in width or height
2022-01-26 02:24:56 [INFO]	Running kmeans for 9 anchors on 93 points...
Evolving anchors with Genetic Algorithm: fitness = 0.8396: 100% 1000/1000 [00:00<00:00, 6147.64it/s]
W0126 02:24:57.201138  1905 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 11.2, Runtime API Version: 10.1
W0126 02:24:57.206293  1905 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2022-01-26 02:24:58 [INFO]	Loading pretrained model from /content/drive/My Drive/PaddleDetection/output/model/pretrain/ppyolov2_r50vd_dcn_365e_coco.pdparams
2022-01-26 02:25:00 [WARNING]	[SKIP] Shape of pretrained params yolo_head.yolo_output.0.weight doesn't match.(Pretrained: [258, 1024, 1, 1], Actual: [27, 1024, 1, 1])
2022-01-26 02:25:00 [WARNING]	[SKIP] Shape of pretrained params yolo_head.yolo_output.0.bias doesn't match.(Pretrained: [258], Actual: [27])
2022-01-26 02:25:00 [WARNING]	[SKIP] Shape of pretrained params yolo_head.yolo_output.1.weight doesn't match.(Pretrained: [258, 512, 1, 1], Actual: [27, 512, 1, 1])
2022-01-26 02:25:00 [WARNING]	[SKIP] Shape of pretrained params yolo_head.yolo_output.1.bias doesn't match.(Pretrained: [258], Actual: [27])
2022-01-26 02:25:00 [WARNING]	[SKIP] Shape of pretrained params yolo_head.yolo_output.2.weight doesn't match.(Pretrained: [258, 256, 1, 1], Actual: [27, 256, 1, 1])
2022-01-26 02:25:00 [WARNING]	[SKIP] Shape of pretrained params yolo_head.yolo_output.2.bias doesn't match.(Pretrained: [258], Actual: [27])
2022-01-26 02:25:01 [INFO]	There are 526/532 variables loaded into PPYOLOv2.
2022-01-26 02:25:22 [INFO]	[TRAIN] Epoch 1 finished, loss_xy=1.3774147, loss_wh=2.3434458, loss_iou=5.1360044, loss_iou_aware=0.99732435, loss_obj=2757.1619, loss_cls=2.974835, loss=2769.991 .
2022-01-26 02:25:31 [INFO]	[TRAIN] Epoch=2/140, Step=2/8, loss_xy=1.814429, loss_wh=3.005027, loss_iou=6.297285, loss_iou_aware=1.176846, loss_obj=26.484335, loss_cls=3.317153, loss=42.095078, lr=0.000375, time_each_step=2.99s, eta=0:55:27
2022-01-26 02:25:44 [INFO]	[TRAIN] Epoch 2 finished, loss_xy=1.3971032, loss_wh=2.1557689, loss_iou=4.908485, loss_iou_aware=0.95476866, loss_obj=30.094877, loss_cls=2.8074496, loss=42.31845 .
2022-01-26 02:25:55 [INFO]	[TRAIN] Epoch=3/140, Step=4/8, loss_xy=1.495654, loss_wh=2.518140, loss_iou=5.853574, loss_iou_aware=1.037014, loss_obj=161.016693, loss_cls=3.168362, loss=175.089447, lr=0.000417, time_each_step=2.44s, eta=0:44:41
2022-01-26 02:26:07 [INFO]	[TRAIN] Epoch 3 finished, loss_xy=1.3442965, loss_wh=2.0091841, loss_iou=4.664646, loss_iou_aware=0.9392559, loss_obj=84.420425, loss_cls=2.6283557, loss=96.006165 .
2022-01-26 02:26:23 [INFO]	[TRAIN] Epoch=4/140, Step=6/8, loss_xy=1.406957, loss_wh=3.132844, loss_iou=4.711718, loss_iou_aware=0.859970, loss_obj=139.765625, loss_cls=2.439022, loss=152.316132, lr=0.000417, time_each_step=2.74s, eta=0:49:48
2022-01-26 02:26:29 [INFO]	[TRAIN] Epoch 4 finished, loss_xy=1.337368, loss_wh=2.3126767, loss_iou=4.5890493, loss_iou_aware=0.9085607, loss_obj=114.613464, loss_cls=2.5921834, loss=126.3533 .
2022-01-26 02:26:50 [INFO]	[TRAIN] Epoch=5/140, Step=8/8, loss_xy=1.594677, loss_wh=1.797401, loss_iou=5.125020, loss_iou_aware=1.101684, loss_obj=45.125916, loss_cls=3.006984, loss=57.751682, lr=0.000417, time_each_step=2.71s, eta=0:48:54
2022-01-26 02:26:50 [INFO]	[TRAIN] Epoch 5 finished, loss_xy=1.4352353, loss_wh=1.8309175, loss_iou=4.703064, loss_iou_aware=0.9594985, loss_obj=70.11356, loss_cls=2.6558304, loss=81.698105 .
2022-01-26 02:27:10 [INFO]	[TRAIN] Epoch 6 finished, loss_xy=1.307365, loss_wh=1.3192959, loss_iou=3.94635, loss_iou_aware=0.90343827, loss_obj=87.76163, loss_cls=2.4944928, loss=97.732574 .
2022-01-26 02:27:15 [INFO]	[TRAIN] Epoch=7/140, Step=2/8, loss_xy=1.509941, loss_wh=1.292396, loss_iou=4.283676, loss_iou_aware=1.019843, loss_obj=60.642189, loss_cls=2.990107, loss=71.738152, lr=0.000417, time_each_step=2.51s, eta=0:44:44
2022-01-26 02:27:28 [INFO]	[TRAIN] Epoch 7 finished, loss_xy=1.3695579, loss_wh=1.2484587, loss_iou=4.132871, loss_iou_aware=0.98400337, loss_obj=68.15987, loss_cls=2.7197134, loss=78.61447 .
2022-01-26 02:27:39 [INFO]	[TRAIN] Epoch=8/140, Step=4/8, loss_xy=1.002333, loss_wh=1.401259, loss_iou=3.807108, loss_iou_aware=0.881202, loss_obj=136.637253, loss_cls=2.332008, loss=146.061157, lr=0.000417, time_each_step=2.38s, eta=0:42:0
2022-01-26 02:27:46 [INFO]	[TRAIN] Epoch 8 finished, loss_xy=1.3567114, loss_wh=1.499833, loss_iou=4.50159, loss_iou_aware=0.976557, loss_obj=69.00421, loss_cls=2.5782442, loss=79.917145 .
2022-01-26 02:28:03 [INFO]	[TRAIN] Epoch=9/140, Step=6/8, loss_xy=1.422222, loss_wh=1.844999, loss_iou=4.924816, loss_iou_aware=0.954908, loss_obj=103.513596, loss_cls=2.433341, loss=115.093880, lr=0.000417, time_each_step=2.36s, eta=0:41:23
2022-01-26 02:28:08 [INFO]	[TRAIN] Epoch 9 finished, loss_xy=1.3653908, loss_wh=1.4585679, loss_iou=4.486429, loss_iou_aware=0.9638342, loss_obj=80.913635, loss_cls=2.4688668, loss=91.65672 .
2022-01-26 02:28:27 [INFO]	[TRAIN] Epoch=10/140, Step=8/8, loss_xy=1.432256, loss_wh=1.358292, loss_iou=4.073690, loss_iou_aware=0.904353, loss_obj=71.431664, loss_cls=2.289468, loss=81.489723, lr=0.000417, time_each_step=2.47s, eta=0:42:53
2022-01-26 02:28:27 [INFO]	[TRAIN] Epoch 10 finished, loss_xy=1.4260328, loss_wh=1.3822846, loss_iou=4.371355, loss_iou_aware=0.938861, loss_obj=63.21096, loss_cls=2.4229374, loss=73.75243 .
2022-01-26 02:28:27 [WARNING]	Detector only supports single card evaluation with batch_size=1 during evaluation, so batch_size is forcibly set to 1.
2022-01-26 02:28:27 [INFO]	Start to evaluate(total_samples=7, total_steps=7)...
Traceback (most recent call last):
  File "/content/drive/My Drive/helmet.py", line 67, in <module>
    use_vdl=False)  # 其用visuadl进行可视化训练记录
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 334, in train
    use_vdl=use_vdl)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/base.py", line 397, in train_loop
    return_details=True)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 500, in evaluate
    eval_metric.update(data, outputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/utils/det_metrics/metrics.py", line 120, in update
    difficult)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/ppdet/metrics/map_utils.py", line 233, in update
    self.class_score_poss[int(l)].append([s, 0.0])
IndexError: list index out of range
## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
都是最新版本  paddleX 2.1  paddlepaddle-gpu 2.2
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
linux 基于google colab
3. 请问您使用的Python版本是？
3.7
5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by lailuboy** [comment]
错误看来可能是有类别不在label.txt中，检查数据中是不是有多的类
