### ISSUE TITLE
安装paddlex测试视盘分割报错。

### ISSUE THREAD

**Issue by GanWang** [PaddlePaddle/PaddleX#1402]
测试参数中没用选用GPU但是baol爆了下属的错误
This log file path is D:\paddlex\projects\P0006\T0006\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\paddlex\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py:312: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
D:\paddlex\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 58, in _call_paddlex_train
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\__init__.py", line 17, in <module>
    from .detector import *
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 24, in <module>
    import paddlex.ppdet as ppdet
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\data\__init__.py", line 16, in <module>
    from . import transform
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\data\transform\__init__.py", line 15, in <module>
    from . import operators
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\data\transform\operators.py", line 44, in <module>
    from paddlex.ppdet.modeling import bbox_utils
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\__init__.py", line 22, in <module>
    from . import proposal_generator
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\__init__.py", line 1, in <module>
    from . import rpn_head
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\rpn_head.py", line 55, in <module>
    class RPNHead(nn.Layer):
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\rpn_head.py", line 71, in RPNHead
    anchor_generator=AnchorGenerator().__dict__,
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 57, in __init__
    self.cell_anchors = self._calculate_anchors(len(strides))
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 84, in _calculate_anchors
    for s, a in zip(sizes, aspect_ratios)
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 84, in <listcomp>
    for s, a in zip(sizes, aspect_ratios)
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 76, in generate_cell_anchors
    return paddle.to_tensor(anchors, dtype='float32')
  File "<decorator-gen-134>", line 2, in to_tensor
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "D:\paddlex\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py", line 172, in to_tensor
    stop_gradient=stop_gradient)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at ..\paddle\fluid\platform\gpu_info.cc:108)

**Comment by GanWang** [comment]
测试的是视盘检测项目，参数配置中没有选用GPU，paddlex的设置中版本2.1.0，CUDA版本是0.0，CUDNN版本是8.1.0显卡驱动版本是N/A

**Comment by FlyingQianMM** [comment]
在本地有GPU的情况下，即便选择CPU进行训练，但由于CUDA和显卡驱动安装不正确，也会引起该问题。

要么正确安装CUDA>=11.0, cuDNN>=8.0；要么就使用PaddleX API模式用CPU完成训练，但是训练时间会比较长。

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～
