### ISSUE TITLE
cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by hurui79** [PaddlePaddle/PaddleX#1417]
## 描述问题
训练时报错

This log file path is D:\paddlex_workspace\projects\P0006\T0030\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\Download\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 224, in train
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 1129, in __init__
    dcn_v2_stages=dcn_v2_stages)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 101, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\resnet.py", line 528, in __init__
    lr=1.0))
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\resnet.py", line 69, in __init__
    bias_attr=False)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 366, in __call__
    stop_gradient=True)
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "D:\Download\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
![image](https://user-images.githubusercontent.com/16483840/157820030-109bd1db-ff63-4361-9053-fcc1560ae154.png)

2. 请提供您使用的GUI版本号
2.1.0
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
windows10
4. 请问您使用的CUDA/cuDNN的版本号是？
cuda11.1 cudnn8.11

**Comment by hurui79** [comment]
![image](https://user-images.githubusercontent.com/16483840/157820222-42a439da-bf75-4978-9bc3-2309cc72ac08.png)
pip list  部分截图
![image](https://user-images.githubusercontent.com/16483840/157820351-8b2cdb11-7695-4cb2-9833-c760ea9a81e4.png)
run_check截图

补充说明官方数据集也同样报错

**Comment by hurui79** [comment]
![image](https://user-images.githubusercontent.com/16483840/157820916-123a3d0a-bb8f-4830-a443-e2ae94f759de.png)
训练的参数如上

**Comment by FlyingQianMM** [comment]
看cuda和cudnn的版本也是符合要求的，您要不先试下PaddleX API模式能不能正常运行: https://github.com/PaddlePaddle/PaddleX

![image](https://user-images.githubusercontent.com/22235422/159617333-cf46a5f3-7082-42fa-a6c2-a506f7596408.png)

**Comment by hurui79** [comment]
> 看cuda和cudnn的版本也是符合要求的，您要不先试下PaddleX API模式能不能正常运行: https://github.com/PaddlePaddle/PaddleX
> 
> ![image](https://user-images.githubusercontent.com/22235422/159617333-cf46a5f3-7082-42fa-a6c2-a506f7596408.png)

。。。有别的方法么，使用paddlex不就是看上他的gui界面简单哈用么，，，，

**Comment by lailuboy** [comment]
您用的是什么样的显卡，看错误是cuda版本不兼容

**Comment by hurui79** [comment]
> 您用的是什么样的显卡，看错误是cuda版本不兼容

![image](https://user-images.githubusercontent.com/16483840/165214398-6975dace-a5ed-425a-8b82-62dae261bab1.png)
@lailuboy
