### ISSUE TITLE
表计读数的例子，再导入meter_deg数据集时，出现这样的错误

### ISSUE THREAD

**Issue by xylovejq** [PaddlePaddle/PaddleX#1424]
## Checklist:
表计读数的例子，再导入meter_deg数据集时，出现这样的错误，我看了数据集里面只有一个json文件
![2](https://user-images.githubusercontent.com/101781837/158729668-b9ce5df8-992b-4c2c-99bb-5f81884372ec.jpg)
![image](https://user-images.githubusercontent.com/101781837/158729749-ba3d0cb6-f825-4d8b-9a69-9fa1c1ee32b5.png)

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2]数据校验失败！

Traceback (most recent call last):
  File "paddlexui\pms\dataset\det_dataset.py", line 58, in check_dataset
  File "xml\etree\ElementTree.py", line 1197, in parse
  File "xml\etree\ElementTree.py", line 587, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\paddlex_test_deg\\meter_det\\Annotations\\20190822_1.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paddlexui\pms\dataset\operate.py", line 42, in _check_and_copy
  File "paddlexui\pms\dataset\det_dataset.py", line 60, in check_dataset
Exception: 文件20190822_1.xml不是一个良构的xml文件

2. GUI版本2.1.0

3. 操作系统  win10

4. CUDA 10.2   cudnn 7.6.5.32

**Comment by xylovejq** [comment]
已经解决，需要把Annotations内的.json文件转换为.xml文件

**Comment by FlyingQianMM** [comment]
问题解决了，先关闭issue了哈
