### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1446]
`paddlex --data_conversion --source labelme --to MSCOCO  --pics H:\JPEGImages  --annotations H:\Annotations  --save_dir H:\dataset_coco`

```
D:\anaconda3\envs\paddleeX\lib\site-packages\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddleeX\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\paddleeX\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\paddleeX\Scripts\paddlex.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\paddlex\command.py", line 187, in main
    args.annotations, args.save_dir)
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\paddlex\tools\convert.py", line 45, in dataset_conversion
    labelme2coco(pics, anns, save_dir)
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 81, in convert
    self.parse_json(new_image_dir, json_dir)
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 175, in parse_json
    object_id, label_to_num))
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 117, in generate_polygon_anns_field
    map(float, self.get_bbox(height, width, points)))
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 133, in get_bbox
    left_top_r = np.min(rows)
  File "<__array_function__ internals>", line 6, in amin
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\numpy\core\fromnumeric.py", line 2880, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "D:\anaconda3\envs\paddleeX\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

labelme 可以正常打开数据集
labelme 的 labelme2coco.py 可以正常转换

**Comment by FlyingQianMM** [comment]
代码在这一行报错了：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/tools/dataset_conversion/x2coco.py#L117

报错原因是这个标注文件中的points字段的值为空，请检查下标注文件吧。
