### ISSUE TITLE
训练时，预训练模型参数加载完成后报错

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleX#1448]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题

我想尝试相同模型不同学习率的效果，所以我在训练中通过生成不同学习率传入模型训练的函数中训练，但是加载完预训练模型的参数后，程序报错，训练中断

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
- 是

3. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
- 训练脚本代码：
```python
import paddlex as pdx
from data import VOC
import numpy as np
# 加载数据集
voc=VOC("SpoonChopsticks/VOC2017",
        "SpoonChopsticks/VOC2017/train_list.txt",
        "SpoonChopsticks/VOC2017/val_list.txt",
        "SpoonChopsticks/VOC2017/labels.txt")
train_dataset,test_dataset=voc.getDataset()

# 获取类别数
num_class=len(train_dataset.labels)

# 获取模型
# 模型选择 https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/detection.md

def start_train(lr):
    model = pdx.det.PicoDet(num_classes=num_class, backbone="ESNet_l")
    model.train(
        num_epochs=2,
        train_dataset=train_dataset,
        train_batch_size=1,     # mini batch
        eval_dataset=test_dataset,
        pretrain_weights='COCO',
        learning_rate=lr,
        warmup_steps=15,
        warmup_start_lr=0,
        save_interval_epochs=1,
        use_ema=True,   # EMA滑动平均 https://www.cnblogs.com/wuliytTaotao/p/9479958.html
        save_dir='output/picodet_esnet_l_{}'.format(lr),
        use_vdl=True)


for n in range(3):
    r=np.random.rand()*(-4)
    lr=10**r
    start_train(lr)
```

数据集脚本代码（数据集应该没有问题，当我单纯使用model.train训练模型时，模型能够正常训练）：
```python
from paddlex import transforms as T
import paddlex
import os


class VOC:
    def __init__(self, data_dir, train_file_list, test_file_list, label_list):
        father_path=os.getcwd()
        self.data_dir = os.path.join(father_path,data_dir)
        self.train_file_list = os.path.join(father_path,train_file_list)
        self.test_file_list = os.path.join(father_path,test_file_list)
        self.label_list = os.path.join(father_path,label_list)

        self.train_transforms = T.Compose([
            T.RandomCrop(), T.RandomHorizontalFlip(), T.RandomDistort(),
            T.BatchRandomResize(
                target_sizes=[576, 608, 640, 672, 704], interp='RANDOM'),
                T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

        self.test_transforms = T.Compose([
            T.Resize(
                target_size=640, interp='CUBIC'),
                T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

    def getDataset(self):
        train_dataset = paddlex.datasets.VOCDetection(self.data_dir,
                                                      self.train_file_list,
                                                      self.label_list,
                                                      transforms=self.train_transforms,
                                                      num_workers='auto',
                                                      shuffle=True)
        test_dataset = paddlex.datasets.VOCDetection(self.data_dir,
                                                     self.test_file_list,
                                                     self.label_list,
                                                     transforms=self.test_transforms,
                                                     num_workers='auto',
                                                     shuffle=True)
        return train_dataset,test_dataset

```
4. 您使用的数据集是？
- VOC2017格式的自定义数据集

6. 请提供您出现的报错信息及相关log
```
C:\Users\ishyj\miniconda3\envs\pp\python.exe D:/WorkSpace/PaddleX-GUI/train.py
2022-04-07 09:13:20 [INFO]	Starting to read file list from dataset...
W0407 09:13:20.776988  9340 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2
2022-04-07 09:13:20 [INFO]	16 samples in file D:\WorkSpace\PaddleX-GUI\SpoonChopsticks/VOC2017/train_list.txt, including 16 positive samples and 0 negative samples.
creating index...
index created!
2022-04-07 09:13:20 [INFO]	Starting to read file list from dataset...
2022-04-07 09:13:20 [INFO]	4 samples in file D:\WorkSpace\PaddleX-GUI\SpoonChopsticks/VOC2017/val_list.txt, including 4 positive samples and 0 negative samples.
creating index...
index created!
W0407 09:13:20.791946  9340 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2022-04-07 09:13:22 [INFO]	Downloading picodet_l_640_coco.pdparams from https://paddledet.bj.bcebos.com/models/picodet_l_640_coco.pdparams
100%|██████████| 13118/13118 [00:13<00:00, 990.44KB/s]
2022-04-07 09:13:36 [INFO]	Loading pretrained model from output/picodet_esnet_l_0.004268200028090002\pretrain\picodet_l_640_coco.pdparams
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls0.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls0.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls1.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls1.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls2.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls2.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls3.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:13:36 [WARNING]	[SKIP] Shape of pretrained params head.head_cls3.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:13:36 [INFO]	There are 652/660 variables loaded into PicoDet.
2022-04-07 09:13:42 [INFO]	[TRAIN] Epoch=1/2, Step=10/16, loss_vfl=1.164518, loss_bbox=0.084303, loss_dfl=0.047330, loss=1.296151, lr=0.002561, time_each_step=0.5s, eta=0:0:13
2022-04-07 09:13:44 [INFO]	[TRAIN] Epoch 1 finished, loss_vfl=1.4120021, loss_bbox=0.30861744, loss_dfl=0.17033862, loss=1.890958 .
2022-04-07 09:13:44 [INFO]	Start to evaluate(total_samples=4, total_steps=4)...
2022-04-07 09:13:45 [INFO]	Accumulating evaluatation results...
2022-04-07 09:13:45 [INFO]	[EVAL] Finished, Epoch=1, bbox_map=32.575758 .
2022-04-07 09:13:45 [INFO]	Model saved in output/picodet_esnet_l_0.004268200028090002\best_model.
2022-04-07 09:13:45 [INFO]	Current evaluated best model on eval_dataset is epoch_1, bbox_map=32.57575757575758
2022-04-07 09:13:45 [INFO]	Model saved in output/picodet_esnet_l_0.004268200028090002\epoch_1.
2022-04-07 09:13:47 [INFO]	[TRAIN] Epoch=2/2, Step=4/16, loss_vfl=0.580096, loss_bbox=0.836319, loss_dfl=0.441161, loss=1.857577, lr=0.003711, time_each_step=0.44s, eta=0:0:5
2022-04-07 09:13:51 [INFO]	[TRAIN] Epoch=2/2, Step=14/16, loss_vfl=0.159180, loss_bbox=0.721760, loss_dfl=0.222973, loss=1.103913, lr=0.000320, time_each_step=0.38s, eta=0:0:0
2022-04-07 09:13:52 [INFO]	[TRAIN] Epoch 2 finished, loss_vfl=1.002348, loss_bbox=0.7877873, loss_dfl=0.47441328, loss=2.2645485 .
2022-04-07 09:13:52 [INFO]	Start to evaluate(total_samples=4, total_steps=4)...
2022-04-07 09:13:52 [INFO]	Accumulating evaluatation results...
2022-04-07 09:13:52 [INFO]	[EVAL] Finished, Epoch=2, bbox_map=83.333333 .
2022-04-07 09:13:52 [INFO]	Model saved in output/picodet_esnet_l_0.004268200028090002\best_model.
2022-04-07 09:13:52 [INFO]	Current evaluated best model on eval_dataset is epoch_2, bbox_map=83.33333333333334
2022-04-07 09:13:53 [INFO]	Model saved in output/picodet_esnet_l_0.004268200028090002\epoch_2.
2022-04-07 09:13:53 [INFO]	Downloading picodet_l_640_coco.pdparams from https://paddledet.bj.bcebos.com/models/picodet_l_640_coco.pdparams
100%|██████████| 13118/13118 [00:12<00:00, 1034.17KB/s]
2022-04-07 09:14:06 [INFO]	Loading pretrained model from output/picodet_esnet_l_0.30558667138438567\pretrain\picodet_l_640_coco.pdparams
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.main_conv.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.main_conv.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.main_conv.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.main_conv.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.main_conv.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.short_conv.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.short_conv.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.short_conv.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.short_conv.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.short_conv.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.final_conv.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.final_conv.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.final_conv.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.final_conv.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.final_conv.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv1.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv1.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv1.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv1.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv1.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.dwconv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn1.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn1.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn1._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn1._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.pwconv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn2.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn2.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn2._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.top_down_blocks.2.blocks.0.conv2.bn2._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.dwconv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn1.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn1.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn1._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn1._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.pwconv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn2.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn2.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn2._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.downsamples.2.bn2._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.main_conv.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.main_conv.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.main_conv.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.main_conv.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.main_conv.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.short_conv.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.short_conv.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.short_conv.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.short_conv.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.short_conv.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.final_conv.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.final_conv.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.final_conv.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.final_conv.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.final_conv.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv1.conv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv1.bn.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv1.bn.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv1.bn._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv1.bn._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.dwconv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn1.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn1.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn1._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn1._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.pwconv.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn2.weight is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn2.bias is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn2._mean is not in pretrained model
2022-04-07 09:14:06 [WARNING]	neck.bottom_up_blocks.2.blocks.0.conv2.bn2._variance is not in pretrained model
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls0.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls0.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls1.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls1.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls2.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls2.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls3.weight doesn't match.(Pretrained: [112, 160, 1, 1], Actual: [34, 160, 1, 1])
2022-04-07 09:14:06 [WARNING]	[SKIP] Shape of pretrained params head.head_cls3.bias doesn't match.(Pretrained: [112], Actual: [34])
2022-04-07 09:14:06 [INFO]	There are 652/730 variables loaded into PicoDet.
Traceback (most recent call last):
  File "D:/WorkSpace/PaddleX-GUI/train.py", line 37, in <module>
    start_train(lr)
  File "D:/WorkSpace/PaddleX-GUI/train.py", line 31, in start_train
    use_vdl=True)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\cv\models\detector.py", line 910, in train
    resume_checkpoint=resume_checkpoint)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\cv\models\detector.py", line 334, in train
    use_vdl=use_vdl)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\cv\models\base.py", line 337, in train_loop
    outputs = self.run(self.net, data, mode='train')
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\cv\models\detector.py", line 105, in run
    net_out = net(inputs)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\ppdet\modeling\architectures\picodet.py", line 78, in get_loss
    head_outs, _ = self._forward()
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\ppdet\modeling\architectures\picodet.py", line 64, in _forward
    fpn_feats = self.neck(body_feats)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\ishyj\miniconda3\envs\pp\lib\site-packages\paddlex\ppdet\modeling\necks\csp_pan.py", line 321, in forward
    assert len(inputs) == len(self.in_channels)
AssertionError

Process finished with exit code 1

```

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
```
paddlepaddle-gpu                  2.2.0
paddlex                           2.1.0
```

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
- Windows 10

5. 请问您使用的Python版本是？
- python 3.6.13（Anconda）

8. 请问您使用的CUDA/cuDNN的版本号是？
```python
paddle.version.cuda()
'10.2'
paddle.version.cudnn_version
'7.6.5'
```

**Comment by thgpddl** [comment]
顶

**Comment by FlyingQianMM** [comment]
我这里跑[picodet tutorial](https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/object_detection/picodet.py)是可以正常跑的。

看你的日志里面，在模型训练完之后又重新加载了预训练模型导致报错，检查下是否是自行修改引入的错误。
![image](https://user-images.githubusercontent.com/22235422/166855302-64e97d95-e25d-40e1-a888-1b997dc915f7.png)

**Comment by thgpddl** [comment]
> 我这里跑[picodet tutorial](https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/object_detection/picodet.py)是可以正常跑的。
> 
> 看你的日志里面，在模型训练完之后又重新加载了预训练模型导致报错，检查下是否是自行修改引入的错误。 ![image](https://user-images.githubusercontent.com/22235422/166855302-64e97d95-e25d-40e1-a888-1b997dc915f7.png)

没有修改，我只是在官方demo外层套了for循环，没有改任何代码。而且for循环里第一次能正常训练，第二次就出现上文的报错

**Comment by thgpddl** [comment]
我认为可能是模型实例化存在某些bug，在循环里多次实例化模型类并训练就会出现这个bug

**Comment by FlyingQianMM** [comment]
为什么要循环多次实例化模型？？
