### ISSUE TITLE
裁减分析失败

### ISSUE THREAD

**Issue by jo-dean** [PaddlePaddle/PaddleX#1452]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 描述问题
**裁减分析失败了 ppyolo mobilenetv3-small 模型**
![image](https://user-images.githubusercontent.com/38728358/162682926-7a85ac72-4aa7-4f3d-886d-d24d4c363718.png)

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
2. _/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/loss.py:1281: DeprecationWarning: invalid escape sequence \s
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/pooling.py:740: DeprecationWarning: invalid escape sequence \_
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/layer/pooling.py:1187: DeprecationWarning: invalid escape sequence \_
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/incubate/nn/functional/fused_transformer.py:111: DeprecationWarning: invalid escape sequence \_
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/incubate/nn/functional/fused_transformer.py:339: DeprecationWarning: invalid escape sequence \_
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/vision/ops.py:952: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (len(x.shape) == 4,
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/signal.py:307: DeprecationWarning: invalid escape sequence \o
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/signal.py:472: DeprecationWarning: invalid escape sequence \s
  """
/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
2022-04-11 09:40:56,487-WARNING: Leaves ['t_481', 't_468', 't_442', 't_422', 't_420', 't_410', 't_409', 't_408', 't_448', 't_383', 't_377', 't_370', 't_446', 't_352', 't_345', 't_344', 't_339', 't_338', 't_334', 't_331', 't_313', 't_309', 't_300', 't_9', 'fetch_1', 't_220', 't_202', 't_277', 't_177', 't_378', 't_118', 't_282', 't_169', 't_140', 't_228', 't_8', 't_44', 't_33', 't_170', 't_246', 't_3', 't_124', 't_14', 't_114', 't_40', 't_112', 't_276', 't_474', 't_1', 't_100', 't_7', 't_222', 't_120', 'fetch_0', 't_176', 't_307', 't_93', 't_268', 't_39', 't_254', 't_46', 't_195', 't_340', 't_165', 't_51', 't_346', 't_303', 't_94', 't_139', 't_217', 't_166', 't_62', 't_379', 't_144', 't_2', 't_38', 't_13', 't_203', 't_27', 't_28', 't_247', 't_29', 't_401', 't_34', 't_241', 't_45', 't_49', 't_50', 't_55', 't_56', 't_57', 't_61', 't_63', 't_126', 't_67', 't_68', 't_69', 't_215', 't_73', 't_74', 't_75', 't_87', 't_88', 't_146', 't_308', 't_98', 't_99', 't_113', 't_119', 't_404', 't_89', 't_138', 't_145', 't_227', 't_150', 't_201', 't_151', 't_152', 't_478', 't_164', 't_171', 't_175', 't_32', 't_92', 't_189', 't_190', 't_191', 't_196', 't_197', 't_15', 't_216', 't_221', 't_226', 't_278', 't_240', 't_267', 't_242', 't_248', 't_252', 't_253', 't_125', 't_266', 't_373'] will be skipped when parsing graph.
2022-04-11 09:40:59,711-WARNING: ('Unsupported operator named slice',)
2022-04-11 09:40:59,711-WARNING: ('Unsupported operator named concat',)
2022-04-11 09:40:59,711-INFO: Found 26 collections.
2022-04-11 09:40:59,720-INFO: Load status from /home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/projects/P0005/T0006/prune/model.sensi.data
2022-04-11 09:41:21,717-INFO: Pruning variable [conv2d_3.w_0] and its relatives ['conv2d_3.w_0', 'conv2d_3.b_0', 'conv2d_4.w_0']
Process Process-1:5:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "pms/model_tasks/tasks.py", line 114, in _call_paddle_prune
  File "pms/model_tasks/prune/detection.py", line 35, in prune
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/base.py", line 474, in analyze_sensitivity
    sen_file=sen_file)
  File "paddleslim/dygraph/prune/filter_pruner.py", line 129, in sensitive
  File "paddleslim/dygraph/prune/filter_pruner.py", line 267, in _cal_sensitive
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/slim/prune.py", line 22, in _pruner_eval_fn
    metric = model.evaluate(eval_dataset, batch_size=batch_size)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/detector.py", line 499, in evaluate
    outputs = self.run(self.net, data, 'eval')
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/detector.py", line 105, in run
    net_out = net(inputs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/architectures/meta_arch.py", line 71, in forward
    outs.append(self.get_pred())
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/architectures/yolo.py", line 124, in get_pred
    return self._forward()
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/architectures/yolo.py", line 79, in _forward
    body_feats = self.backbone(self.inputs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/backbones/mobilenet_v3.py", line 463, in forward
    x = block(x)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/backbones/mobilenet_v3.py", line 178, in forward
    x = self.mid_se(x)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/backbones/mobilenet_v3.py", line 216, in forward
    outputs = self.conv1(outputs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/layer/conv.py", line 677, in forward
    use_cudnn=self._use_cudnn)
  File "/home/wanfu3060/paddle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) the size of filter at axis 0 should be greater than 0
  [Hint: Expected filter_dims[0] > 0, but received filter_dims[0]:0 <= 0:0.] (at /paddle/paddle/fluid/operators/conv_op.cc:133)
  [operator < conv2d > error]_

3. 请提供您使用的GUI版本号 2.1.0

4. 请提供您使用的操作系统信息，Linux

5. 请问您使用的CUDA/cuDNN的版本号是？cuda 11.2 cudnn 8.1

**Comment by FlyingQianMM** [comment]
抱歉，PPYOLO_MobileNetV3只能剪裁部分层，GUI里面没有限制剪裁的的层，所以出现该错误。如您需要完成该模型剪裁，可先至[PaddleDetection剪裁教程](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/slim/prune/ppyolo_mbv3_large_prune_fpgm.yml) 。
