### ISSUE TITLE
Traceback (most recent call last):   File "paddlexui\pms\core.py", line 1773, in execute   File "paddlexui\pms\core.py", line 371, in get_dataset_status AssertionError: 数据集ID'D0005'不存在.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1456]
PaddleX可视化客户端使用问题

```
Traceback (most recent call last):
  File "paddlexui\pms\core.py", line 1773, in execute
  File "paddlexui\pms\core.py", line 371, in get_dataset_status
AssertionError: 数据集ID'D0005'不存在.
```
GUI界面 数据集显示 D0005 未导入
应该要怎么解决
一直提示错误 想导入也不行

我尝试了修改paddleX GUI的.pb文件
删除D0005 
结果 所有的项目都不见了
撤销操作重新保存也一样

**Comment by FlyingQianMM** [comment]
```
数据集ID'D0005'不存在.
```
是否之前有删除操作？可以给工作目录换个路径，确保当前的训练可以正常进行。
