### ISSUE TITLE
paddlex百度熊分类运行失败，选择不使用GPU后还是报GPU的错误

### ISSUE THREAD

**Issue by iwanglei1** [PaddlePaddle/PaddleX#1462]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 描述问题
训练参数中不使用gpu还是报cuda错误
## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
This log file path is C:\Users\13105\paddlex_workspace\projects\P0001\T0010\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:5:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 224, in train
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 1951, in __init__
    dcn_v2_stages=dcn_v2_stages)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 101, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\resnet.py", line 528, in __init__
    lr=1.0))
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\resnet.py", line 69, in __init__
    bias_attr=False)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 366, in __call__
    stop_gradient=True)
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "C:\Users\13105\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)

3. 请提供您使用的GUI版本号 2.1.0
4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS windows10家庭版21h2

5. 请问您使用的CUDA/cuDNN的版本号是？CPU训练

**Comment by FlyingQianMM** [comment]
本地有GPU的情况下，PaddleX GUI 2.0要求CUDA >= 11.0，cuDNN>=8.0，如果不满足，启动CPU训练也会有问题。
