### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by kungkook** [PaddlePaddle/PaddleX#1469]
环境:win11 cuda11.2 显卡3060ti
paddlepadlle-gpu==2.2.2
paddleslim==2.2.1
paddlex==2.1.0
运行examples/robot_grap/code/train.py
报错:
Traceback (most recent call last):
  File "E:/PaddleX/examples/robot_grab/code/train.py", line 1, in <module>
    import paddlex as pdx
  File "E:\PaddleX\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "E:\PaddleX\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "E:\PaddleX\paddlex\cv\models\__init__.py", line 17, in <module>
    from .detector import *
  File "E:\PaddleX\paddlex\cv\models\detector.py", line 24, in <module>
    import paddlex.ppdet as ppdet
  File "E:\PaddleX\paddlex\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "E:\PaddleX\paddlex\ppdet\data\__init__.py", line 15, in <module>
    from . import source
  File "E:\PaddleX\paddlex\ppdet\data\source\__init__.py", line 19, in <module>
    from . import keypoint_coco
  File "E:\PaddleX\paddlex\ppdet\data\source\keypoint_coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "D:\Ananconda3\envs\pdd\lib\site-packages\pycocotools\coco.py", line 56, in <module>
    from . import mask as maskUtils
  File "D:\Ananconda3\envs\pdd\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by FlyingQianMM** [comment]
see issue https://github.com/PaddlePaddle/PaddleX/issues/1247
