### ISSUE TITLE
2.1.0 添加负样本训练报错

### ISSUE THREAD

**Issue by SJJ-dot** [PaddlePaddle/PaddleX#1486]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    model.train(
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 280, in train
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    self.train_loop(
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 329, in train_loop
    batch = self._get_data()
      File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data
for step, data in enumerate(self.train_data_loader()):
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    batch.reraise()    
data = self._reader.read_next_var_list()  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise

SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
    
raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/datasets/voc.py", line 319, in __getitem__
    sample = self.mixup_op(sample=[
  File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/transforms/operators.py", line 1073, in __call__
    gt_bbox = np.concatenate((gt_bbox1, gt_bbox2), axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Comment by SJJ-dot** [comment]
```
import paddlex as pdx
from paddlex import transforms as T
# paddlex --split_dataset --format VOC --dataset_dir dataset --val_value 0.01 --test_value 0.01
# 定义训练和验证时的transforms
# API说明：https://github.com/PaddlePaddle/PaddleX/blob/release/2.0-rc/paddlex/cv/transforms/operators.py
train_transforms = T.Compose([
     T.MixupImage(mixup_epoch=250),
     T.RandomDistort(),
     T.RandomExpand(im_padding_value=[123.675, 116.28, 103.53]),
     T.RandomCrop(),
     T.RandomHorizontalFlip(),
     T.BatchRandomResize(target_sizes=[320, 352, 384, 416, 448, 480, 512, 544, 576, 608],interp='RANDOM'),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transforms = T.Compose([
     T.Resize(608, interp='CUBIC'),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 定义训练和验证所用的数据集
# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/datasets/coco.py#L26
train_dataset = pdx.datasets.VOCDetection(
    allow_empty =True,
    data_dir='dataset',
    file_list='dataset/train_list.txt',
    label_list='dataset/labels.txt',
    transforms=train_transforms,
    shuffle=True)

eval_dataset = pdx.datasets.VOCDetection(
    allow_empty =True,
    data_dir='dataset',
    file_list='dataset/val_list.txt',
    label_list='dataset/labels.txt',
    transforms=eval_transforms,
    shuffle=False)

```

**Comment by FlyingQianMM** [comment]
> File "/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/transforms/operators.py", line 1073, in call
gt_bbox = np.concatenate((gt_bbox1, gt_bbox2), axis=0)
File "<array_function internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

这里显示在Mixup这个transform里面，gt_bbox1是2维的，gt_bbox2是1维的。代码中解析VOC数据集出来的gt_bbox都是2维的：https://github.com/PaddlePaddle/PaddleX/blob/release/2.1/paddlex/cv/datasets/voc.py#L166，所以定位下是否是数据集标注的问题：

1、在/opt/miniconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/transforms/operators.py第1073行后打印下gt_bbox1, gt_bbox2，看下报错时这俩变量的shape分别是怎么样的
2、卸载PaddleX 2.1.0，使用PaddleX develop版本
3、如果以上步骤还未定位出问题，提供下完整的训练代码和最小复现数据集，我们一起来看下。

**Comment by SJJ-dot** [comment]
@FlyingQianMM 这个是版本的问题……那个版本是2.0.0 没发现
