### ISSUE TITLE
求助：PaddleX可视化客户端启动训练后报错

### ISSUE THREAD

**Issue by hyleallead** [PaddlePaddle/PaddleX#1518]
## 描述问题
    使用PaddleX可视化客户端启动训练后出错。

## 复现
1. 请提供您出现的报错信息及相关log
错误日志如下：
This log file path is /home/hyle/paddlex_workspace/projects/P0002/T0003/err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/loss.py:1281: DeprecationWarning: invalid escape sequence \s
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/pooling.py:740: DeprecationWarning: invalid escape sequence \_
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/layer/pooling.py:1187: DeprecationWarning: invalid escape sequence \_
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/incubate/nn/functional/fused_transformer.py:111: DeprecationWarning: invalid escape sequence \_
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/incubate/nn/functional/fused_transformer.py:339: DeprecationWarning: invalid escape sequence \_
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/vision/ops.py:952: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (len(x.shape) == 4,
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/signal.py:307: DeprecationWarning: invalid escape sequence \o
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/signal.py:472: DeprecationWarning: invalid escape sequence \s
  """
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/framework.py:312: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "pms/model_tasks/tasks.py", line 58, in _call_paddlex_train
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/__init__.py", line 20, in <module>
    from . import cv
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/__init__.py", line 15, in <module>
    from . import models
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/__init__.py", line 17, in <module>
    from .detector import *
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/detector.py", line 24, in <module>
    import paddlex.ppdet as ppdet
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/data/transform/operators.py", line 44, in <module>
    from paddlex.ppdet.modeling import bbox_utils
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/__init__.py", line 22, in <module>
    from . import proposal_generator
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/__init__.py", line 1, in <module>
    from . import rpn_head
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/rpn_head.py", line 55, in <module>
    class RPNHead(nn.Layer):
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/rpn_head.py", line 71, in RPNHead
    anchor_generator=AnchorGenerator().__dict__,
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/anchor_generator.py", line 57, in __init__
    self.cell_anchors = self._calculate_anchors(len(strides))
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/anchor_generator.py", line 84, in _calculate_anchors
    for s, a in zip(sizes, aspect_ratios)
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/anchor_generator.py", line 84, in <listcomp>
    for s, a in zip(sizes, aspect_ratios)
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppdet/modeling/proposal_generator/anchor_generator.py", line 76, in generate_cell_anchors
    return paddle.to_tensor(anchors, dtype='float32')
  File "<decorator-gen-134>", line 2, in to_tensor
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/hyle/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/tensor/creation.py", line 172, in to_tensor
    stop_gradient=stop_gradient)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:108)

2. 请提供您使用的GUI版本号
PaddleX_GUI_2.1.0_ubuntu_amd64

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
操作系统为Ubuntu18.04.6(kernal: 5.4.0-84-generic)，GCC (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0，GLIBC(Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27。

5. 请问您使用的CUDA/cuDNN的版本号是？
本机使用两块 GTX1060 5GB显卡。
nvidia-smi:
Thu Jun  2 17:35:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:01:00.0  On |                  N/A |
| 48%   46C    P8     9W / 120W |    468MiB /  5055MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  On   | 00000000:02:00.0 Off |                  N/A |
| 46%   35C    P8     4W / 120W |      2MiB /  5059MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1155      G   /usr/lib/xorg/Xorg                            38MiB |
|    0      1268      G   /usr/bin/gnome-shell                          48MiB |
|    0      1600      G   /usr/lib/xorg/Xorg                           258MiB |
|    0      1746      G   /usr/bin/gnome-shell                         116MiB |
|    0      3272      G   /usr/lib/firefox/firefox                       1MiB |
+-----------------------------------------------------------------------------+

./mnistCUDNN 
Executing: mnistCUDNN
cudnnGetVersion() : 8401 , CUDNN_VERSION from cudnn.h : 8401 (8.4.1)
Host compiler version : GCC 7.5.0

There are 2 CUDA capable devices on your machine :
device 0 : sms 10  Capabilities 6.1, SmClock 1759.0 Mhz, MemSize (Mb) 5055, MemClock 4004.0 Mhz, Ecc=0, boardGroupID=0
device 1 : sms 10  Capabilities 6.1, SmClock 1759.0 Mhz, MemSize (Mb) 5059, MemClock 4004.0 Mhz, Ecc=0, boardGroupID=1
......
Test passed!

以上信息，寻求帮助，谢谢！

**Comment by lailuboy** [comment]
看一下可视化客户端的设置中显示的显卡和驱动信息是否正常

**Comment by jack00000** [comment]
同问
