### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by zxc14751475** [PaddlePaddle/PaddleX#1524]
这个怎么解决？
This log file path is D:\paddleworkspace\projects\P0001\T0022\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 58, in _call_paddlex_train
ValueError: source code string cannot contain null bytes

**Comment by lailuboy** [comment]
看下PaddleX程序安装路径，不要在空格和中文路径
