### ISSUE TITLE
训练开启时候报错

### ISSUE THREAD

**Issue by FIR2022start** [PaddlePaddle/PaddleX#1528]
问题日志如下：

This log file path is D:\program files\PaddleX_GUI_2.1.0_win10\projects\P0016\T0050\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\program files\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:6:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\segmentation.py", line 132, in train
  File "paddlexui\pms\model_tasks\train\segmentation.py", line 64, in build_datasets
  File "D:\program files\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\datasets\seg_dataset.py", line 64, in __init__
    " file_list[{}] has a space in the image or label path.".format(line, file_list))
Exception: A space is defined as the delimiter to separate the image and label path, so the space cannot be in the image or label path, but the line[JPEGImages\1007 (2).jpg Annotations\1007 (2).png
] of  file_list[D:\program files\PaddleX_GUI_2.1.0_win10\datasets\D0015\train_list.txt] has a space in the image or label path.

GUI 版本：2.1.0
Windows系统
CUDA/CUDNN: 11.2/8.1.0

**Comment by simonchf** [comment]
我的paddlex也是这样，报    if data.dtype == np.object:  
基本上一训练就出错的，
似乎使用cpu不报错。

**Comment by lailuboy** [comment]
has a space in the image or label path. 训练的样本文件名中不能有空格或者中文

**Comment by lailuboy** [comment]
> 我的paddlex也是这样，报 if data.dtype == np.object: 基本上一训练就出错的， 似乎使用cpu不报错。

请把完整错误信息发一下

**Comment by FIR2022start** [comment]
非常感谢各位的解答！我检查了一下之前的数据集，应该是存在空格的原因。
