### ISSUE TITLE
zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1547]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX数据准备文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#2-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)

## 描述问题

这个标注数据 
labelme重新打开
看上去没有问题
但是不知道是哪里导致的报错

对于数据 这种报错
有什么方法 忽略有问题的文件吗
或者删除有问题的文件

比如 rows []
怎么样才能忽略这个文件
或者直接删除文件

```

image[file_name] 123456789.jpg
rows [  0   0   0 ... 332 332 333]
np.min(rows) 0

rows [170 171 171 ... 295 295 296]
np.min(rows) 170

rows [ 81  82  82 ... 209 209 210]
np.min(rows) 81

rows []
Traceback (most recent call last):
  File "D:\anaconda3\envs\PaddleX38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\PaddleX38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\PaddleX38\Scripts\paddlex.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\paddlex\command.py", line 186, in main
    pdx.tools.convert.dataset_conversion(args.source, args.to, args.pics,
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\paddlex\tools\convert.py", line 45, in dataset_conversion
    labelme2coco(pics, anns, save_dir)
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 81, in convert
    self.parse_json(new_image_dir, json_dir)
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 177, in parse_json
    self.generate_polygon_anns_field(
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 119, in generate_polygon_anns_field
    map(float, self.get_bbox(height, width, points)))
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\paddlex\tools\dataset_conversion\x2coco.py", line 136, in get_bbox
    print("np.min(rows)",np.min(rows))
  File "<__array_function__ internals>", line 180, in amin
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\numpy\core\fromnumeric.py", line 2916, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "D:\anaconda3\envs\PaddleX38\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

## 复现

1. 您使用的命令是？

```
paddlex --data_conversion --source labelme --to MSCOCO \
        --pics D:\MyDataset\JPEGImages \
        --annotations D:\MyDataset\Annotations \
        --save_dir D:\dataset_coco
```

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号
paddlepaddle-gpu        2.3.0.post112
paddleslim              2.2.1
paddlex                 2.1.0
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows11
4. 请问您使用的Python版本是
python3.8

**Comment by lailuboy** [comment]
是多边形标注的吗，请发一下上面有问题的图片123456789.jpg和标注。
