### ISSUE TITLE
  if data.dtype == np.object:

### ISSUE THREAD

**Issue by simonchf** [PaddlePaddle/PaddleX#1561]
paddleX 训练模型，一开始 就报错，  if data.dtype == np.object:

**Comment by lailuboy** [comment]
请贴一下完整错误信息

**Comment by oQuQu** [comment]
F:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 224, in train
  File "F:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 972, in __init__
    backbone = self._get_backbone('DarkNet', norm_type=norm_type)
  File "F:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 101, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "F:\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\darknet.py", line 279, in __init__
    data_format=data_format)
  File "F:\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\darknet.py", line 66, in __init__
    bias_attr=False)
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 366, in __call__
    stop_gradient=True)
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "F:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)

**Comment by lailuboy** [comment]
你是什么样的显卡，错误看起来是cuda版本不匹配。cudaErrorNoKernelImageForDevice
