### ISSUE TITLE
MaskRCNN:AttributeError: 'MAOutputScaleLayer' object has no attribute 'get_pred'

### ISSUE THREAD

**Issue by mediocre-Lin** [PaddlePaddle/PaddleX#1567]
## 描述问题
使用paddlex中的在线量化时报错

Traceback (most recent call last):
  File "e:/LKS/PaddleX-develop/PaddleX-develop/tutorials/slim/quantize/instance_segmentation/mask_rcnn_qat.py", line 32, in <module>
    model.quant_aware_train(
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\cv\models\detector.py", line 387, in quant_aware_train
    self.train(
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\cv\models\detector.py", line 2221, in train
    super(MaskRCNN, self).train(
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\cv\models\detector.py", line 323, in train
    self.train_loop(
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\cv\models\base.py", line 394, in train_loop
    eval_result = self.evaluate(
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\cv\models\detector.py", line 499, in evaluate
    outputs = self.run(self.net, data, 'eval')
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\cv\models\detector.py", line 105, in run
    net_out = net(inputs)
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\ppdet\modeling\architectures\meta_arch.py", line 71, in forward
    outs.append(self.get_pred())
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\ppdet\modeling\architectures\mask_rcnn.py", line 134, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddlex\ppdet\modeling\architectures\mask_rcnn.py", line 115, in _forward
    bbox_pred = self.bbox_post_process.get_pred(bbox, bbox_num,
  File "D:\Anaconda3\envs\camera\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1123, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'MAOutputScaleLayer' object has no attribute 'get_pred'

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddlepaddle-gpu 2.3.1
paddlex 2.1.0
paddleslim 2.3.1

**Comment by xuhi1996** [comment]
我也碰到了这个问题，请问你解决了吗？
