### ISSUE TITLE
裁剪分析失败

### ISSUE THREAD

**Issue by gm8811** [PaddlePaddle/PaddleX#1571]
![image](https://user-images.githubusercontent.com/6847837/184107172-786579e6-d3dd-46a9-afbe-5dff2e3bbeb9.png)

2022-08-11 17:15:01,127-INFO: pruned param: conv2d_11.w_0; 0.8; loss=0.2421245990957282
2022-08-11 17:15:01,128-INFO: Save status into C:\paddlex_workspace\projects\P0020\T0054\prune\model.sensi.data
2022-08-11 17:15:01,134-INFO: Pruning variable [conv2d_11.w_0] and its relatives ['conv2d_11.w_0', 'conv2d_11.b_0', 'sync_batch_norm_11.w_0', 'sync_batch_norm_11.b_0', 'sync_batch_norm_11.w_1', 'sync_batch_norm_11.w_2', 'conv2d_12.w_0', 'conv2d_16.w_0', 'conv2d_16.b_0', 'sync_batch_norm_16.w_0', 'sync_batch_norm_16.b_0', 'sync_batch_norm_16.w_1', 'sync_batch_norm_16.w_2', 'conv2d_17.w_0', 'conv2d_54.w_0']
2022-08-11 17:15:01,141-INFO: change groups from 16 to 2 for conv2d_16.w_0.
2022-08-11 17:15:16,284-INFO: pruned param: conv2d_11.w_0; 0.9; loss=0.24199546543630818
2022-08-11 17:15:16,286-INFO: Save status into C:\paddlex_workspace\projects\P0020\T0054\prune\model.sensi.data
2022-08-11 17:15:16,291-INFO: Pruning variable [conv2d_12.w_0] and its relatives ['conv2d_12.w_0', 'conv2d_12.b_0', 'sync_batch_norm_12.w_0', 'sync_batch_norm_12.b_0', 'sync_batch_norm_12.w_1', 'sync_batch_norm_12.w_2', 'conv2d_13.w_0', 'conv2d_13.b_0', 'sync_batch_norm_13.w_0', 'sync_batch_norm_13.b_0', 'sync_batch_norm_13.w_1', 'sync_batch_norm_13.w_2', 'conv2d_14.w_0', 'conv2d_14.b_0', 'sync_batch_norm_14.w_0', 'sync_batch_norm_14.b_0', 'sync_batch_norm_14.w_1', 'sync_batch_norm_14.w_2', 'conv2d_15.w_0']
Process Process-1:34:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 114, in _call_paddle_prune
  File "paddlexui\pms\model_tasks\prune\segmentation.py", line 21, in prune
  File "F:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\base.py", line 474, in analyze_sensitivity
    sen_file=sen_file)
  File "site-packages\paddleslim\dygraph\prune\filter_pruner.py", line 129, in sensitive
  File "site-packages\paddleslim\dygraph\prune\filter_pruner.py", line 266, in _cal_sensitive
  File "site-packages\paddleslim\dygraph\prune\filter_pruner.py", line 348, in prune_var
AssertionError: The length of current_mask must be equal to the size of dimension to be pruned on. But get: len(current_mask): 16; var_shape: (96,); axis: 0; var name: conv2d_13.b_0; len(mask): 16

**Comment by zhaoyj96** [comment]
您好，我出现了和您一样的问题，请问您是怎么解决这个问题的，感谢
