### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1577]
PPLCNet_ssld

CPU预测
model = pdx.deploy.Predictor("F:/inference_model/",use_gpu=False)
GPU也会报错

图片正常 能正常打开
多张图片 都不行

报错

------------------ Inference Time Info ----------------------
total_time(ms): 0.0, img_num: 1, batch_size: 1
Traceback (most recent call last):
  File "f:/AI.py", line 44, in <module>
    result = model.predict(img)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\deploy.py", line 260, in predict
    self.timer.info(average=True)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\utils\utils.py", line 199, in info
    average_latency * 1000, 1 / average_latency))
ZeroDivisionError: float division by zero

**Comment by monkeycc** [comment]
# self.timer.repeats = repeats
        # self.timer.img_num = len(images)
        # self.timer.info(average=False)

注释显示时间后 正常

**Comment by RayneYael** [comment]
这到底是什么bug，我的bleu分数计算总是出现ZeroDivisionError，找不到原因
