### ISSUE TITLE
PaddleX可视化客户端   导出模型失败

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1579]
PaddleX v2.0.0
PaddleX可视化客户端   导出模型提示失败 又不知道什么导致 
模型看上去也正常 可以预测

**Comment by monkeycc** [comment]
PicoDet 目标检测模型

手动导出
```

2022-08-22 14:50:28 [INFO]      Model[PicoDet] loaded.

2022-08-22 14:50:28 [WARNING]   [Important!!!] When exporting inference model for PicoDet, if fixed_input_shape is not set, it will be forcibly set to [None, 3, 620, 620]. Please ensure image shape after transforms is [3, 620, 620], if not, fixed_input_shape should be specified manually.

Traceback (most recent call last):
  File "D:\Anaconda3\envs\PaddleX38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\PaddleX38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\PaddleX38\Scripts\paddlex.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\command.py", line 158, in main
    model._export_inference_model(args.save_dir, fixed_input_shape)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\cv\models\base.py", line 606, in _export_inference_model
    paddle.jit.save(static_net, osp.join(save_dir, 'model'))
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\jit.py", line 629, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\jit.py", line 856, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\ppdet\modeling\architectures\meta_arch.py", line 71, in forward
        outs.append(self.get_pred())
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\ppdet\modeling\architectures\picodet.py", line 89, in get_pred
        bbox_pred, bbox_num = self._forward()
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\ppdet\modeling\architectures\picodet.py", line 64, in _forward
        fpn_feats = self.neck(body_feats)
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddlex\ppdet\modeling\necks\csp_pan.py", line 333, in forward
        inner_out = self.top_down_blocks[len(self.in_channels) - 1 - idx](
            paddle.concat([upsample_feat, feat_low], 1))
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        inner_outs.insert(0, inner_out)

    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\tensor\manipulation.py", line 331, in concat
        return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\layers\tensor.py", line 392, in concat
        helper.append_op(
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\layer_helper.py", line 44, in append_op
        return self.main_program.current_block().append_op(*args, **kwargs)
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
        op = Operator(
    File "D:\Anaconda3\envs\PaddleX38\lib\site-packages\paddle\fluid\framework.py", line 2764, in __init__
        self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [-1, 128, 40, 40], input[1]'s shape = [-1, 128, 39, 39].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:40 != inputs_dims[i][j]:39.] (at ..\paddle/phi/kernels/funcs/concat_funcs.h:83)
  [operator < concat > error]
```

**Comment by monkeycc** [comment]
检测模型中YOLO/PPYOLO系列请保存w与h一致，且为32的倍数大小；指定--fixed_input_shape时，RCNN类的w和h需为32的倍数大小。

知道了 要等比
