### ISSUE TITLE
复现教程 工业指针型表计读数https://aistudio.baidu.com/aistudio/projectdetail/4487340 ，语义分割训练时报错

### ISSUE THREAD

**Issue by ulen2000** [PaddlePaddle/PaddleX#1586]
复现教程 工业指针型表计读数https://aistudio.baidu.com/aistudio/projectdetail/4487340 ，语义分割训练时报错

没有更改任何代码，使用教程提供的数据及，报错显示：
Traceback (most recent call last):
  File "train_segmentation.py", line 49, in <module>
    model.train(
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddlex/cv/models/segmenter.py", line 292, in train
    self.train_loop(
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 337, in train_loop
    outputs = self.run(self.net, data, mode='train')
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddlex/cv/models/segmenter.py", line 146, in run
    loss_list = metrics.loss_computation(
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddlex/cv/models/utils/seg_metrics.py", line 24, in loss_computation
    loss_list.append(losses['coef'][i] * loss_i(logits, labels))
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddlex/paddleseg/models/losses/mixed_loss.py", line 56, in forward
    output = loss(logits, labels)
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddlex/paddleseg/models/losses/cross_entropy_loss.py", line 66, in forward
    loss = F.cross_entropy(
  File "/home/ulen/anaconda3/envs/env1/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1719, in cross_entropy
    raise ValueError("Target {} is out of lower bound.".format(
ValueError: Target 140212227276800 is out of lower bound.

环境安装没有问题，已经成功复现目标检测训练的部分

**Comment by FlyingQianMM** [comment]
分割模型训练在另一个Issue https://github.com/PaddlePaddle/PaddleX/issues/1587 已经可以正常运行，故先关闭issue。
