### ISSUE TITLE
paddleX小度熊训练时出现错误，请问下原因是内存不足还是？

### ISSUE THREAD

**Issue by M202176319** [PaddlePaddle/PaddleX#1659]
This log file path is E:\python related\new python study\paddlex workspace\projects\P0004\T0008\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:7:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 263, in train
  File "E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 2226, in train
    early_stop_patience, use_vdl, resume_checkpoint)
  File "E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 334, in train
    use_vdl=use_vdl)
  File "E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\base.py", line 339, in train_loop
    loss.backward()
  File "<decorator-gen-128>", line 2, in backward
  File "E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "E:\python related\new python study\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
OSError: (External) ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 53.450684MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:79)
 (at ..\paddle\fluid\imperative\basic_engine.cc:571)

**Comment by M202176319** [comment]
GPU0显示未被占用
