### ISSUE TITLE
GUI训练失败

### ISSUE THREAD

**Issue by czzzy** [PaddlePaddle/PaddleX#1673]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 142, in train
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 976, in train
    resume_checkpoint=resume_checkpoint)
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 336, in train
    use_vdl=use_vdl)
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\base.py", line 337, in train_loop
    outputs = self.run(self.net, data, mode='train')
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 137, in run
    loss = self.loss_func(net_out, inputs[1])['CELoss']
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\loss\celoss.py", line 54, in forward
    label = F.softmax(label, axis=-1)
  File "E:\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\nn\functional\activation.py", line 895, in softmax
    return _C_ops.softmax(outs_cast, 'axis', axis, 'use_cudnn', use_cudnn)
RuntimeError: (NotFound) Operator softmax does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[CUDNN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at ..\paddle\fluid\imperative\prepared_operator.cc:159)
  [operator < softmax > error]
## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境
![image](https://user-images.githubusercontent.com/27075974/224683854-01181718-c9a1-4ed7-b51b-89f58658a638.png)

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by lailuboy** [comment]
请问是NV 40系列显卡是吗？40系列GUI目前还没有支持，您可以执行nvidia-smi结果发一下看看

**Comment by czzzy** [comment]
![image](https://user-images.githubusercontent.com/27075974/224691051-2b77712a-f8aa-455d-a177-6870e42c07a8.png)

**Comment by czzzy** [comment]
gtx titan x的显卡
