### ISSUE TITLE
安装paddlex2.1.0训练不了

### ISSUE THREAD

**Issue by liuzhan12311** [PaddlePaddle/PaddleX#1677]
This log file path is D:\paddlexproject\projects\P0006\T0009\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 118, in train
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 888, in __init__
    model_name=model_name, num_classes=num_classes, **params)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 70, in __init__
    self.net = self.build_net(**params)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 75, in build_net
    **params)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 352, in PPLCNet_x1_0
    model = PPLCNet(scale=1.0, **kwargs)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 183, in __init__
    stride=2)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 93, in __init__
    bias_attr=False)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 719, in __call__
    stop_gradient=True)
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "C:\paddlex\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at ..\paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]

**Comment by liuzhan12311** [comment]
用的自带的的例程样本蔬菜分类，win11系统，cudn11.6和cudnn8.4，4060笔记本显卡

**Comment by 16605613297** [comment]
解决了吗

**Comment by liuzhan12311** [comment]
没解决






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 晚上11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleX] 安装paddlex2.1.0训练不了 (Issue #1677)






解决了吗

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
