### ISSUE TITLE
训练异常终止

### ISSUE THREAD

**Issue by zealot9527** [PaddlePaddle/PaddleX#1680]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
  File "D:\Program Files\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 719, in __call__
    stop_gradient=True)
  File "D:\Program Files\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "D:\Program Files\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)
2. 请提供您使用的GUI版本号
  2.1.0
4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
 windows11  显卡750Ti   cuda11.5   cudnn8.3

6. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by lailuboy** [comment]
尝试降低一下Cuda版本，11.2

**Comment by fenlier1** [comment]
Process Process-1:14:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 58, in _call_paddlex_train
  File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\__init__.py", line 20, in <module>
    from . import cv
  File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\cv\__init__.py", line 15, in <module>
    from . import models
  File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\__init__.py", line 17, in <module>
    from .detector import *
  File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 316
    'ESNet_' in train self.backbone_name))
                         ^
SyntaxError: invalid syntax

**Comment by fenlier1** [comment]
1.请提供您出现的报错信息及相关log
Process Process-1:14:
Traceback (most recent call last):
File "multiprocessing\process.py", line 297, in bootstrap
File "multiprocessing\process.py", line 99, in run
File "paddlexui\pms\model_tasks\tasks.py", line 58, in call_paddlex_train
File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex_init.py", line 20, in
from . import cv
File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\cv_init.py", line 15, in
from . import models
File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\cv\models_init_.py", line 17, in
from .detector import *
File "D:\paddleX\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 316
'ESNet_' in train self.backbone_name))
^
SyntaxError: invalid syntax
2.请提供您使用的GUI版本号
2.1.0
3.请提供您使用的操作系统信息
Windows10 显卡1660ti
4.请问您使用的CUDA/cuDNN的版本号是？
CUDA11.2 CUDNN8.1.0
