### ISSUE TITLE
PaddleX可视化客户端使用问题:numpy.core._exceptions._ArrayMemoryError: Unable to allocate 15.0 MiB for an array with shape (1280, 1024, 3) and data type float32

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1690]
```
This log file path is C:\Users\vipuser\paddlex_workspace\projects\P0001\T0006\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\datasets\voc.py", line 324, in __getitem__
    sample = self.transforms(sample)
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 127, in __call__
    sample = op(sample)
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 82, in __call__
    sample = self.apply(sample)
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 1209, in apply
    sample['image'] = func(sample['image'])
  File "C:\Users\vipuser\Downloads\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 1176, in apply_saturation
    gray = image * np.array([[[0.299, 0.587, 0.114]]], dtype=np.float32)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 15.0 MiB for an array with shape (1280, 1024, 3) and data type float32
```

**Comment by lailuboy** [comment]
看看环境硬件信息，错误是显存不足
