### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by bocchi-chan2003** [PaddlePaddle/PaddleX#1694]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？

3. 您使用的**模型**和**数据集**是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

4. 请问您使用的CUDA/cuDNN的版本号是？
我的paddlepaddle版本号是2.2.1,paddlex版本号为2.1.0，python版本为3.7.12
源码为
from paddlex.cls import transforms
import matplotlib.pyplot as plt
import paddlex
import cv2
import warnings

warnings.filterwarnings('ignore')

train_transforms = transforms.Compose([
    transforms.RandomCrop(crop_size=224),
    transforms.Normalize()
])

model = paddlex.deploy.Predictor('P0001-T0008_export_model/inference_model/inference_model')
im = cv2.imread('test.jpg')
result = model.predict(im, topk=1)
print("Predict Result:", result)

plt.imshow(im)
plt.show()
报错信息为Traceback (most recent call last):
  File "e:/pacimen/pacman-with-paddlepaddle-gesture-control-main/tools/test.py", line 14, in <module>
    model = paddlex.deploy.Predictor('P0001-T0008_export_model/inference_model/inference_model')
  File "E:\anaconda3\envs\mediapipe\lib\site-packages\paddlex\deploy.py", line 82, in __init__
    self.info['Transforms'], to_rgb)
  File "E:\anaconda3\envs\mediapipe\lib\site-packages\paddlex\cv\transforms\__init__.py", line 36, in build_transforms
    transforms.append(getattr(T, op_name)(**op_attr))
TypeError: __init__() got an unexpected keyword argument 'interp'
cuda版本为11.6

**Comment by bocchi-chan2003** [comment]
求大佬指点

**Comment by bocchi-chan2003** [comment]
我的模型是用paddlexGUI导出的模型
