### ISSUE TITLE
目标检测模型,CPU推理,遇到未知错误

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1695]
paddlepaddle       2.4.2
paddleslim         2.2.1
paddlex            2.1.0

CPU推理报错
不管什么目标模型都是一样

```

Exception in thread AI_Start_Thread_1_1:
Traceback (most recent call last):
  File "D:\baidu\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\baidu\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "baidu_2023_x.py", line 1698, in open_device_OK
    aiok(image,deploy_model_1,window)
  File "baidu_2023_x.py", line 1466, in aiok
    results_1 = deploy_model_1.predict(image)
  File "D:\baidu\Python\lib\site-packages\paddlex\cv\models\detector.py", line 540, in predict
    outputs = self.run(self.net, batch_samples, 'test')
  File "D:\baidu\Python\lib\site-packages\paddlex\cv\models\detector.py", line 105, in run
    net_out = net(inputs)
  File "D:\baidu\Python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\baidu\Python\lib\site-packages\paddlex\ppdet\modeling\architectures\meta_arch.py", line 71, in forward
    outs.append(self.get_pred())
  File "D:\baidu\Python\lib\site-packages\paddlex\ppdet\modeling\architectures\picodet.py", line 89, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "D:\baidu\Python\lib\site-packages\paddlex\ppdet\modeling\architectures\picodet.py", line 72, in _forward
    scale_factor)
  File "D:\baidu\Python\lib\site-packages\paddlex\ppdet\modeling\heads\gfl_head.py", line 486, in post_process
    bbox_pred, bbox_num, _ = self.nms(bboxes, score)
  File "D:\baidu\Python\lib\site-packages\paddlex\ppdet\modeling\layers.py", line 476, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "D:\baidu\Python\lib\site-packages\paddlex\ppdet\modeling\ops.py", line 985, in multiclass_nms
    bboxes, scores, rois_num, *attrs)
ValueError: (InvalidArgument) multiclass_nms3(): argument 'BBoxes' (position 0) must be Tensor, but got Tensor (at ..\pa
ddle\fluid\pybind\op_function_common.cc:818)
```

**Comment by monkeycc** [comment]
paddle 安装 2.3
