### ISSUE TITLE
通过web demo用demo提供的数据集进行restful接口测试时，在训练环节的验证步骤报错

### ISSUE THREAD

**Issue by BingerOne** [PaddlePaddle/PaddleX#1700]
## 描述问题
报错代码为PaddleX develop最新版，通过web demo用demo提供的数据集进行restful接口测试时，在训练中进行验证的时候报错。

## 复现

1. 报错log

```
This log file path is E:\AI\paddlepaddle\paddlex_restful_workspace\projects\P0008\T0020\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
E:\AI\paddlepaddle\PaddleX\paddlex\paddleseg\models\losses\decoupledsegnet_relax_boundary_loss.py:19: DeprecationWarning: Please use `shift` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.
  from scipy.ndimage.interpolation import shift
E:\AI\paddlepaddle\PaddleX\paddlex\paddleseg\transforms\functional.py:18: DeprecationWarning: Please use `distance_transform_edt` from the `scipy.ndimage` namespace, the `scipy.ndimage.morphology` namespace is deprecated.
  from scipy.ndimage.morphology import distance_transform_edt
2023-06-08 23:20:21,428-WARNING: type object 'QuantizationTransformPass' has no attribute '_supported_quantizable_op_type'
2023-06-08 23:20:21,429-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.4 or develop version
E:\AI\PythonEnv\paddlex\lib\site-packages\scikit_learn-0.23.2-py3.8-win-amd64.egg\sklearn\utils\multiclass.py:13: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
Process Process-3:
Traceback (most recent call last):
  File "E:\AI\.pyenv\pyenv-win\versions\3.8.10\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "E:\AI\.pyenv\pyenv-win\versions\3.8.10\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AI\paddlepaddle\PaddleX\paddlex_restful\restful\project\operate.py", line 85, in _call_paddlex_train
    train(task_path, dataset_path, params['train'])
  File "E:\AI\paddlepaddle\PaddleX\paddlex_restful\restful\project\train\detection.py", line 252, in train
    model.train(
  File "E:\AI\paddlepaddle\PaddleX\paddlex\cv\models\detector.py", line 323, in train
    self.train_loop(
  File "E:\AI\paddlepaddle\PaddleX\paddlex\cv\models\base.py", line 397, in train_loop
    eval_result = self.evaluate(
  File "E:\AI\paddlepaddle\PaddleX\paddlex\cv\models\detector.py", line 499, in evaluate
    outputs = self.run(self.net, data, 'eval')
  File "E:\AI\paddlepaddle\PaddleX\paddlex\cv\models\detector.py", line 105, in run
    net_out = net(inputs)
  File "E:\AI\PythonEnv\paddlex\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\AI\paddlepaddle\PaddleX\paddlex\ppdet\modeling\architectures\meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "E:\AI\paddlepaddle\PaddleX\paddlex\ppdet\modeling\architectures\yolo.py", line 128, in get_pred
    return self._forward()
  File "E:\AI\paddlepaddle\PaddleX\paddlex\ppdet\modeling\architectures\yolo.py", line 113, in _forward
    bbox, bbox_num = self.post_process(
  File "E:\AI\paddlepaddle\PaddleX\paddlex\ppdet\modeling\post_process.py", line 70, in __call__
    bbox_pred, bbox_num, _ = self.nms(bboxes, score, self.num_classes)
  File "E:\AI\paddlepaddle\PaddleX\paddlex\ppdet\modeling\layers.py", line 520, in __call__
    return ops.matrix_nms(
  File "E:\AI\paddlepaddle\PaddleX\paddlex\ppdet\modeling\ops.py", line 852, in matrix_nms
    out, index, rois_num = _C_ops.matrix_nms(bboxes, scores, *attrs)
ValueError: (InvalidArgument) matrix_nms(): argument (position 3) must be double, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:211)
```

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows 10 专业版  21H2  19044.1865

3. 请问您使用的CUDA/cuDNN的版本号是？
```
(PaddleX) D:\Projects\AI\PaddlePaddle\PaddleX>nvidia-smi
Thu Jun  8 23:49:40 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.61                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti    WDDM | 00000000:01:00.0 Off |                  N/A |
| 35%   41C    P8                8W / 120W|   3153MiB /  6144MiB |      8%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

|    0   N/A  N/A     33876    C+G   ...4309\office6\promecefpluginhost.exe    N/A      |
|    0   N/A  N/A     36112    C+G   ...t.LockApp_cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     38328    C+G   C:\Windows\System32\mstsc.exe             N/A      |
|    0   N/A  N/A     38344    C+G   ...\PyCharm 2022.1.4\bin\pycharm64.exe    N/A      |
|    0   N/A  N/A     38368    C+G   ...1.0_x64__8wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A     38688    C+G   ...oft\Edge Dev\Application\msedge.exe    N/A      |
+---------------------------------------------------------------------------------------+
```

**Comment by lailuboy** [comment]
PaddlePaddle的版本安装2.3.1再试看是否OK

**Comment by BingerOne** [comment]
OK了，感谢
