### ISSUE TITLE
换了4060显卡了，paddlex赶紧更新一下吧，全线用不了都

### ISSUE THREAD

**Issue by LeeGeong** [PaddlePaddle/PaddleX#1715]
## 描述问题
笔记本联想拯救者Y9000P ， 显卡4060，显存8G， 系统win11。使用PaddleXGUI版本，小度熊分拣训练初始参数训练。报错。
以下为PaddleXGUI内置参数：
PaddleX版本 2.1.0 ， 飞桨版本 2.2.1， CUDA版本 11.2 ， CUDNN版本 8.1.0 ， 显卡驱动版本 528.66
## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）

This log file path is D:\paddlex_workspace\projects\P0001\T0012\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
E:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 224, in train
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 1951, in __init__
    dcn_v2_stages=dcn_v2_stages)
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 101, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\resnet.py", line 528, in __init__
    lr=1.0))
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\resnet.py", line 69, in __init__
    bias_attr=False)
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 366, in __call__
    stop_gradient=True)
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at ..\paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]

3. 请提供您使用的GUI版本号
2.1.0
4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows11
5. 请问您使用的CUDA/cuDNN的版本号是？
CUDA版本11.8 ， cuDNN版本 8.9.2

**Comment by Sunny2884** [comment]
我的显卡也是4060，也用不了paddlex，安装卸载好多遍都不行，你的解决了吗

**Comment by Sunny2884** [comment]
> 不过我安装的paddlex是1.0.2版本的，老师让学1.0版本的，哭咧，cuda是11.2，cudnn8.5.0

**Comment by Grubby-Wang** [comment]
有解决办法了吗？

**Comment by Sunny2884** [comment]
没有，应该不支持40开头的硬件吧
&nbsp;








卢艳军



河南理工大学/研究生/2023/计算机学院





河南焦作世纪路2001号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Grubby_wang"; 
Date: 2025年2月27日(星期四) 下午3:07
To: "PaddlePaddle/PaddleX"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [PaddlePaddle/PaddleX] 换了4060显卡了，paddlex赶紧更新一下吧，全线用不了都 (Issue #1715)

&nbsp;
   
有解决办法了吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  Grubby-Wang left a comment (PaddlePaddle/PaddleX#1715)
 
有解决办法了吗？
