### ISSUE TITLE
paddlex无法使用gpu训练，4060的显卡

### ISSUE THREAD

**Issue by Sunny2884** [PaddlePaddle/PaddleX#1726]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
This log file path is D:\software\paddlex\projects\P0001\T0037\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 118, in train
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 888, in __init__
    model_name=model_name, num_classes=num_classes, **params)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 70, in __init__
    self.net = self.build_net(**params)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 75, in build_net
    **params)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 352, in PPLCNet_x1_0
    model = PPLCNet(scale=1.0, **kwargs)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 183, in __init__
    stride=2)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 93, in __init__
    bias_attr=False)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 719, in __call__
    stop_gradient=True)
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "D:\files\chrome\PaddleX_GUI_2.1.0_win10\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at ..\paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]

2. 请提供您使用的GUI版本号                                 2.1.0

4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS                                    windows 11

5. 请问您使用的CUDA/cuDNN的版本号是？             cuda11.2        cudnn8.5.0

**Comment by dyning** [comment]
欢迎尝试使用PaddleX新版本试试，看看问题是否可以解决，https://aistudio.baidu.com/intro/paddlex
