### ISSUE TITLE
PaddleX可视化客户端使用问题

### ISSUE THREAD

**Issue by Zengfanxu1111** [PaddlePaddle/PaddleX#1727]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 描述问题
运行示例任务时训练报错，但是未直接中断
项目为目标检测的昆虫项目

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
2.报错信息如下
E:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "E:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\datasets\voc.py", line 324, in __getitem__
    sample = self.transforms(sample)
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 119, in __call__
    sample = self.decode_image(sample)
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 82, in __call__
    sample = self.apply(sample)
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 189, in apply
    sample['image'] = self.apply_im(sample['image'])
  File "E:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 164, in apply_im
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

3. 请提供您使用的GUI版本号
3.2.1
4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
windows10
5. 请问您使用的CUDA/cuDNN的版本号是？
cuda11.2   
CuDnn 8.1.0

**Comment by atat1010** [comment]
我也是这个问题，请问你解决了吗？
