### ISSUE TITLE
windows11 运行paddlex，执行图片分类任务的训练时，提示CUSOLVER_STATUS_INTERNAL_ERROR错误

### ISSUE THREAD

**Issue by jiaolongxue** [PaddlePaddle/PaddleX#1734]
## 描述问题
windows11 运行paddlex，执行图片分类任务的训练时，提示错误
![image](https://github.com/PaddlePaddle/PaddleX/assets/21324579/1ae86c11-8bbb-4281-b81a-fee380ee81ff)

单显卡 RTX4090

### 训练参数
![image](https://github.com/PaddlePaddle/PaddleX/assets/21324579/1c86770c-ca3d-4fd9-8a4c-669781691dc1)

### 错误日志

```
This log file path is E:\paddlex\projects\P0005\T0007\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:4:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 118, in train
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 888, in __init__
    model_name=model_name, num_classes=num_classes, **params)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 70, in __init__
    self.net = self.build_net(**params)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\classifier.py", line 75, in build_net
    **params)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 352, in PPLCNet_x1_0
    model = PPLCNet(scale=1.0, **kwargs)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 183, in __init__
    stride=2)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddlex\ppcls\arch\backbone\legendary_models\pp_lcnet.py", line 93, in __init__
    bias_attr=False)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 719, in __call__
    stop_gradient=True)
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "D:\soft-install\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at ..\paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]
```

**Comment by NeTChengGH** [comment]
up主，同问该问题，我也是一模一样的问题

**Comment by NeTChengGH** [comment]
40系列的显卡，CUDA11.2的版本，运行会有问题。我将window11的CUDA安装了11.7和cudnn安装了8.4.1后，到CUDA的安装目录下，将bin文件夹复制并替换到paddleX根目录下，然后运行exe后，训练就正常启动了。
![image](https://github.com/PaddlePaddle/PaddleX/assets/17527747/37091f3c-cfc8-4c5d-ad35-14faac88d147)

**Comment by green512** [comment]
> 40系列的显卡，CUDA11.2的版本，运行会有问题。我将window11的CUDA安装了11.7和cudnn安装了8.4.1后，到CUDA的安装目录下，将bin文件夹复制并替换到paddleX根目录下，然后运行exe后，训练就正常启动了。 ![image](https://private-user-images.githubusercontent.com/17527747/272929855-37091f3c-cfc8-4c5d-ad35-14faac88d147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjE4MTUsIm5iZiI6MTcwNjI2MTUxNSwicGF0aCI6Ii8xNzUyNzc0Ny8yNzI5Mjk4NTUtMzcwOTFmM2MtY2ZjOC00YzVkLWFkMzUtMTRmYWFjODhkMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5MzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZjQ1MDAxZTVhOTg4NTc0MWYwNTk2NGNlM2ZjNWU3ZmM2ZTEzN2QxNmFiOGViNWNlZTFmMWI0Y2Y2NWI1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WXoVvN6x3UKzu3v2KY0DZqaD17vcf9YnAPJ0u1lJzZA)

非常正确，我按照你的说明成功解决错误

**Comment by 77bw** [comment]
我是linux的ubuntu20.04，按照同样的方法也不行 怎么解决呢

**Comment by atat1010** [comment]
> 我是linux的ubuntu20.04，按照同样的方法也不行 怎么解决呢

请问解决了吗

**Comment by atat1010** [comment]
> 40系列的显卡，CUDA11.2的版本，运行会有问题。我将window11的CUDA安装了11.7和cudnn安装了8.4.1后，到CUDA的安装目录下，将bin文件夹复制并替换到paddleX根目录下，然后运行exe后，训练就正常启动了。 ![image](https://private-user-images.githubusercontent.com/17527747/272929855-37091f3c-cfc8-4c5d-ad35-14faac88d147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjgzMjUsIm5iZiI6MTcyODcyODAyNSwicGF0aCI6Ii8xNzUyNzc0Ny8yNzI5Mjk4NTUtMzcwOTFmM2MtY2ZjOC00YzVkLWFkMzUtMTRmYWFjODhkMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwMTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzRkMGQ5NDExNTZjOTU5OTM0NDg5MDk3MjNlZjNlN2QxNTE2MWMwMzU4ZGJlZTFhNDM3YTM0NWU4MTg3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5mJitnN0oRyn4xaNdki0_9PM2A44z2_ULxtm0IsXgGc)

你好，请问是直接将bin文件复制到paddle X的根目录下吗，我的paddlex里没有bin文件夹啊

**Comment by NeTChengGH** [comment]
> > 40系列的显卡，CUDA11.2的版本，运行会有问题。我将window11的CUDA安装了11.7和cudnn安装了8.4.1后，到CUDA的安装目录下，将bin文件夹复制并替换到paddleX根目录下，然后运行exe后，训练就正常启动了。 ![image](https://private-user-images.githubusercontent.com/17527747/272929855-37091f3c-cfc8-4c5d-ad35-14faac88d147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjgzMjUsIm5iZiI6MTcyODcyODAyNSwicGF0aCI6Ii8xNzUyNzc0Ny8yNzI5Mjk4NTUtMzcwOTFmM2MtY2ZjOC00YzVkLWFkMzUtMTRmYWFjODhkMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwMTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzRkMGQ5NDExNTZjOTU5OTM0NDg5MDk3MjNlZjNlN2QxNTE2MWMwMzU4ZGJlZTFhNDM3YTM0NWU4MTg3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5mJitnN0oRyn4xaNdki0_9PM2A44z2_ULxtm0IsXgGc)
> 
> 你好，请问是直接将bin文件复制到paddle X的根目录下吗，我的paddlex里没有bin文件夹啊

linux系统来使用paddleX进行训练，我也没试过。现在新版本的paddleX很多新模型都可以用的了，不一定要用旧版的paddleX的了。

**Comment by atat1010** [comment]
> > > 40系列的显卡，CUDA11.2的版本，运行会有问题。我将window11的CUDA安装了11.7和cudnn安装了8.4.1后，到CUDA的安装目录下，将bin文件夹复制并替换到paddleX根目录下，然后运行exe后，训练就正常启动了。 ![image](https://private-user-images.githubusercontent.com/17527747/272929855-37091f3c-cfc8-4c5d-ad35-14faac88d147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjgzMjUsIm5iZiI6MTcyODcyODAyNSwicGF0aCI6Ii8xNzUyNzc0Ny8yNzI5Mjk4NTUtMzcwOTFmM2MtY2ZjOC00YzVkLWFkMzUtMTRmYWFjODhkMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEwMTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzRkMGQ5NDExNTZjOTU5OTM0NDg5MDk3MjNlZjNlN2QxNTE2MWMwMzU4ZGJlZTFhNDM3YTM0NWU4MTg3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5mJitnN0oRyn4xaNdki0_9PM2A44z2_ULxtm0IsXgGc)
> > 
> > 
> > 你好，请问是直接将bin文件复制到paddle X的根目录下吗，我的paddlex里没有bin文件夹啊
> 
> linux系统来使用paddleX进行训练，我也没试过。现在新版本的paddleX很多新模型都可以用的了，不一定要用旧版的paddleX的了。

你好，我用的和提问者用的是一个版本，就是想在40系显卡上训练但是报错，按照你的方法我没有找到根目录下的bin文件，我直接复制Bin文件进去cuda版本并没有变
![image](https://github.com/user-attachments/assets/07c667f6-bbc3-4654-8aa5-d3bbd1d2470f)
