### ISSUE TITLE
点击启动训练后报错

### ISSUE THREAD

**Issue by jundada430** [PaddlePaddle/PaddleX#1740]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 复现

1. This log file path is D:\paddlex_workspace\projects\P0002\T0007\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 58, in _call_paddlex_train
  File "D:\PaddleX_GUI_2.1.0_win10\paddlex\__init__.py", line 17, in <module>
    from paddlex.utils.env import get_environ_info, init_parallel_env
  File "D:\PaddleX_GUI_2.1.0_win10\paddlex\utils\__init__.py", line 15, in <module>
    from . import logging
  File "D:\PaddleX_GUI_2.1.0_win10\paddlex\utils\logging.py", line 21, in <module>
    import paddle
  File "D:\PaddleX_GUI_2.1.0_win10\paddle\__init__.py", line 31, in <module>
    import paddle.dataset
  File "D:\PaddleX_GUI_2.1.0_win10\paddle\dataset\__init__.py", line 25, in <module>
    import paddle.dataset.sentiment
  File "D:\PaddleX_GUI_2.1.0_win10\paddle\dataset\sentiment.py", line 30, in <module>
    import nltk
ModuleNotFoundError: No module named 'nltk'

2. 2.1.0

3. win8

4. 无  用cpu训练

**Comment by dyning** [comment]
欢迎尝试使用PaddleX 新版本，https://aistudio.baidu.com/intro/paddlex
