### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by Kenneth-X** [PaddlePaddle/PaddleX#1749]
paddle.fluid has been  deleted ，so which paddlex version is correct ???

Traceback (most recent call last):
  File "/home/xietao/software/miniconda3/bin/paddlex", line 5, in <module>
    from paddlex.command import main
  File "/home/xietao/software/miniconda3/lib/python3.9/site-packages/paddlex/__init__.py", line 20, in <module>
    from . import cv
  File "/home/xietao/software/miniconda3/lib/python3.9/site-packages/paddlex/cv/__init__.py", line 15, in <module>
    from . import models
  File "/home/xietao/software/miniconda3/lib/python3.9/site-packages/paddlex/cv/models/__init__.py", line 15, in <module>
    from .segmenter import *
  File "/home/xietao/software/miniconda3/lib/python3.9/site-packages/paddlex/cv/models/segmenter.py", line 25, in <module>
    from paddlex.cv.transforms import arrange_transforms
  File "/home/xietao/software/miniconda3/lib/python3.9/site-packages/paddlex/cv/transforms/__init__.py", line 16, in <module>
    from .batch_operators import BatchRandomResize, BatchRandomResizeByShort, _BatchPadding
  File "/home/xietao/software/miniconda3/lib/python3.9/site-packages/paddlex/cv/transforms/batch_operators.py", line 22, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid'

**Comment by Sunting78** [comment]
欢迎尝试使用PaddleX 2.2 进行训练，https://aistudio.baidu.com/intro/paddlex
