### ISSUE TITLE
在paddlex在线工具箱里运行PP-YOLOE_plus_crn_s_80e_副本跑自己数据集出现api.base.utils.errors.CalledProcessError

### ISSUE THREAD

**Issue by szh1213** [PaddlePaddle/PaddleX#1756]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 描述问题
在aistudio里fork了PP-YOLOE_plus_crn_s_80e，用的自己的数据集验证通过后训练报错
## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）

欢迎使用PaddleX！^_^
您可以在这里查看运行日志和报错信息。环境重启后运行日志将重置。
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/tools/train.py", line 209, in
main()
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/tools/train.py", line 205, in main
run(FLAGS, cfg)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/tools/train.py", line 145, in run
trainer = Trainer(cfg, mode='train')
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/ppdet/engine/trainer.py", line 101, in __init__
self.loader = create('{}Reader'.format(capital_mode))(
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/ppdet/data/reader.py", line 168, in __call__
self.dataset.parse_dataset()
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/ppdet/data/source/coco.py", line 243, in parse_dataset
assert ct > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in /home/aistudio/data/ferry/annotations/instance_train.json
['/opt/conda/envs/python35-paddle120-env/bin/python', 'tools/train.py', '--eval', '--config', '/home/aistudio/.paddle_uapi/tmp8xg6_6te/detmodel_PP-YOLOE+_crn_s_80e.yml', '--use_vdl', 'True', '--vdl_log_dir', '/home/aistudio/output']
Log path: /home/aistudio/output/train.log
Traceback (most recent call last):
File "/home/aistudio/run_paddlex.py", line 52, in
runner.run()
File "/home/aistudio/base/base_run_paddlex.py", line 68, in run
self.run_train()
File "/home/aistudio/base/base_run_paddlex.py", line 267, in run_train
self.uapi_model.train(
File "uapi/pp_uapi/paddledet_uapi/det/model.py", line 84, in uapi.pp_uapi.paddledet_uapi.det.model.DetModel.train
File "uapi/pp_uapi/paddledet_uapi/det/model.py", line 86, in uapi.pp_uapi.paddledet_uapi.det.model.DetModel.train
File "uapi/pp_uapi/paddledet_uapi/det/model.py", line 97, in uapi.pp_uapi.paddledet_uapi.det.model.DetModel.train
File "uapi/pp_uapi/paddledet_uapi/det/runner.py", line 31, in uapi.pp_uapi.paddledet_uapi.det.runner.DetRunner.train
File "uapi/base/runner.py", line 348, in uapi.base.runner.BaseRunner.run_cmd
uapi.base.utils.errors.CalledProcessError: Command ['/opt/conda/envs/python35-paddle120-env/bin/python', 'tools/train.py', '--eval', '--config', '/home/aistudio/.paddle_uapi/tmp8xg6_6te/detmodel_PP-YOLOE+_crn_s_80e.yml', '--use_vdl', 'True', '--vdl_log_dir', '/home/aistudio/output'] returned non-zero exit status 1.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
数据集校验成功
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/tools/train.py", line 209, in
main()
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/tools/train.py", line 205, in main
run(FLAGS, cfg)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/tools/train.py", line 145, in run
trainer = Trainer(cfg, mode='train')
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/ppdet/engine/trainer.py", line 101, in __init__
self.loader = create('{}Reader'.format(capital_mode))(
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/ppdet/data/reader.py", line 168, in __call__
self.dataset.parse_dataset()
File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/uapi/pp_repos/PaddleDetection/ppdet/data/source/coco.py", line 243, in parse_dataset
assert ct > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in /home/aistudio/data/ferry/annotations/instance_train.json
['/opt/conda/envs/python35-paddle120-env/bin/python', 'tools/train.py', '--eval', '--config', '/home/aistudio/.paddle_uapi/tmpl1q_a_uh/detmodel_PP-YOLOE+_crn_s_80e.yml', '--use_vdl', 'True', '--vdl_log_dir', '/home/aistudio/output']
Log path: /home/aistudio/output/train.log
Traceback (most recent call last):
File "/home/aistudio/run_paddlex.py", line 52, in
runner.run()
File "/home/aistudio/base/base_run_paddlex.py", line 68, in run
self.run_train()
File "/home/aistudio/base/base_run_paddlex.py", line 267, in run_train
self.uapi_model.train(
File "uapi/pp_uapi/paddledet_uapi/det/model.py", line 84, in uapi.pp_uapi.paddledet_uapi.det.model.DetModel.train
File "uapi/pp_uapi/paddledet_uapi/det/model.py", line 86, in uapi.pp_uapi.paddledet_uapi.det.model.DetModel.train
File "uapi/pp_uapi/paddledet_uapi/det/model.py", line 97, in uapi.pp_uapi.paddledet_uapi.det.model.DetModel.train
File "uapi/pp_uapi/paddledet_uapi/det/runner.py", line 31, in uapi.pp_uapi.paddledet_uapi.det.runner.DetRunner.train
File "uapi/base/runner.py", line 348, in uapi.base.runner.BaseRunner.run_cmd
uapi.base.utils.errors.CalledProcessError: Command ['/opt/conda/envs/python35-paddle120-env/bin/python', 'tools/train.py', '--eval', '--config', '/home/aistudio/.paddle_uapi/tmpl1q_a_uh/detmodel_PP-YOLOE+_crn_s_80e.yml', '--use_vdl', 'True', '--vdl_log_dir', '/home/aistudio/output'] returned non-zero exit status 1.
2. 请提供您使用的GUI版本号
paddle2.5   python3.10
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

4. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by cuicheng01** [comment]
您好，请问您使用的是什么数据集呢？这个问题是必现的吗？

**Comment by szh1213** [comment]
使用的是自定义数据集，数据集校验通过了，但是每次必现这个问题
&nbsp;


风在动
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月26日(星期五) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleX] 在paddlex在线工具箱里运行PP-YOLOE_plus_crn_s_80e_副本跑自己数据集出现api.base.utils.errors.CalledProcessError (Issue #1756)














 
您好，请问您使用的是什么数据集呢？这个问题是必现的吗？

**Comment by cuicheng01** [comment]
您是否方便准备一个demo数据集呢？我们复现一下
