### ISSUE TITLE
paddlex.utils.errors.others.UnsupportedParamError: 'Mask-RT-DETR-H' is not a registered model name.

### ISSUE THREAD

**Issue by commonherat** [PaddlePaddle/PaddleX#1795]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
(paddlex) PS D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta> python main.py -c paddlex/configs/instance_segmentation/Mask-RT-DETR-H.yaml -o Global.mode=train -o Global.dataset_dir= 
小熊数据集
Traceback (most recent call last):
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\repo_apis\base\config.py", line 31, in _create_config
    model_info = get_registered_model_info(model_name)
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\repo_apis\base\register.py", line 81, in query
    return self._table[prim_key]
KeyError: 'Mask-RT-DETR-H'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\utils\result_saver.py", line 30, in wrap
    result = func(self, *args, **kwargs)
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\engine.py", line 41, in run
    trainer = build_trainer(self.config)
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\modules\base\trainer\trainer.py", line 35, in build_trainer
    return BaseTrainer.get(model_name)(config)
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\modules\base\trainer\trainer.py", line 53, in __init__
    self.pdx_config, self.pdx_model = build_model(self.global_config.model)
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\modules\base\build_model.py", line 34, in build_model
    config = Config(model_name, config_path)
  File "D:\实习学习\百度飞桨学习\PaddleX-release-3.0-beta\paddlex\repo_apis\base\config.py", line 33, in _create_config
    raise UnsupportedParamError(
paddlex.utils.errors.others.UnsupportedParamError: 'Mask-RT-DETR-H' is not a registered model name.
## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by TingquanGao** [comment]
请问是否执行如下安装命令：

```bash
pip install -e .
paddlex --install
```

**Comment by Light-Towers** [comment]
python 版本 3.10 执行

```bash
pip install -e .
paddlex --install
```

官方文档没有标注适配的版本，全靠自己摸索
