### ISSUE TITLE
Pillow支持的版本太低AttributeError: 'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleX#1819]
## Checklist:

在检测数据集时报错AttributeError: 'ImageDraw' object has no attribute 'textsize'

## 描述问题
```bash
/home/aistudio/PaddleX
Traceback (most recent call last):
  File "/home/aistudio/PaddleX/paddlex/utils/result_saver.py", line 30, in wrap
    result = func(self, *args, **kwargs)
  File "/home/aistudio/PaddleX/paddlex/engine.py", line 39, in run
    return dataset_checker.check()
  File "/home/aistudio/PaddleX/paddlex/modules/base/dataset_checker/dataset_checker.py", line 75, in check
    attrs = self.check_dataset(dataset_dir)
  File "/home/aistudio/PaddleX/paddlex/modules/image_classification/dataset_checker/__init__.py", line 77, in check_dataset
    return check(dataset_dir, self.output)
  File "/home/aistudio/PaddleX/paddlex/modules/image_classification/dataset_checker/dataset_src/check_dataset.py", line 105, in check
    vis_im = draw_label(img, label, label_map_dict)
  File "/home/aistudio/PaddleX/paddlex/modules/image_classification/dataset_checker/dataset_src/utils/visualizer.py", line 65, in draw_label
    text_width_tmp, text_height_tmp = draw.textsize(
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

## 复现

运行
```
python main.py -c paddlex/configs/image_classification/PP-LCNet_x1_0.yaml \
    -o Global.mode=check_dataset \
    -o Global.dataset_dir=./dataset/cls_flowers_examples
```

## 环境

Pillow版本10.0以上
aistudio paddlepaddle 3.0

**Comment by cuicheng01** [comment]
收到，感谢反馈，这个是不同pillow版本引起的，我们最近会升级适配各个pillow版本。您暂时可以通过安装9.5版本解决
