### ISSUE TITLE
uapi.base.model.AuthenticationFailedError

### ISSUE THREAD

**Issue by robertoding** [PaddlePaddle/PaddleX#1964]
windows 11客户端PaddleX-2.2.1.506.exe内开启训练正常.
![image](https://github.com/user-attachments/assets/abbaf12d-793e-4abb-8f94-65b0febbddf5)

如果按log显示，直接在windows终端中执行命令H:\PaddleX\resources\codelab\python.exe "H:\workspace\1779\1\run_paddlex.py" --exec_train，则出现下面的错误：
H:\workspace\1779\1>H:\PaddleX\resources\codelab\python.exe "H:\workspace\1779\1\run_paddlex.py" --exec_train
Traceback (most recent call last):
  File "H:\workspace\1779\1\run_paddlex.py", line 51, in <module>
    runner = RunPaddleXDet()
  File "H:\workspace\1779\1\run_paddlex.py", line 22, in __init__
    super().__init__()
  File "H:\workspace\1779\1\base\base_run_paddlex.py", line 61, in __init__
    self.uapi_model = PaddleModel(config=self.uapi_config)
  File "uapi\base\model.py", line 56, in uapi.base.model._create_model
  File "uapi\base\register.py", line 94, in uapi.base.register.build_model_from_model_info
  File "uapi\base\model.py", line 85, in uapi.base.model.BaseModel.__init__
  File "uapi\base\model.py", line 672, in uapi.base.model._authenticate_paddlex
uapi.base.model.AuthenticationFailedError

**Comment by TingquanGao** [comment]
终端命令行使用的话，建议用最新的paddlex release/3.0-beta

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
