### ISSUE TITLE
[PaddleX在昇腾910b 机器安装时报错  No matching distribution found for tool_helpers ]

### ISSUE THREAD

**Issue by mqy9787** [PaddlePaddle/PaddleX#1998]
## 描述问题
机器华为昇腾910b机器，安装paddleX，在执行paddlex --install 报错 
报错信息：
Collecting safetensors (from -r /tmp/tmpgr5ue_nk/requirements.txt (line 23))
  Using cached safetensors-0.4.5-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (3.8 kB)
ERROR: Could not find a version that satisfies the requirement tool_helpers (from versions: none)
ERROR: No matching distribution found for tool_helpers
Traceback (most recent call last):
  File "/usr/bin/paddlex", line 33, in <module>
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())
  File "/work/paddle_ocr/PaddleX/paddlex/paddlex_cli.py", line 109, in main
    install(args)
  File "/work/paddle_ocr/PaddleX/paddlex/paddlex_cli.py", line 85, in install
    setup(
  File "/work/paddle_ocr/PaddleX/paddlex/repo_manager/core.py", line 194, in setup
    installer.install(
  File "/work/paddle_ocr/PaddleX/paddlex/repo_manager/repo.py", line 259, in install
    self.install_deps(constraints=constraints)
  File "/work/paddle_ocr/PaddleX/paddlex/repo_manager/repo.py", line 302, in install_deps
    install_packages_using_pip(
  File "/work/paddle_ocr/PaddleX/paddlex/repo_manager/utils.py", line 68, in install_packages_using_pip
    return _check_call(args)
  File "/work/paddle_ocr/PaddleX/paddlex/repo_manager/utils.py", line 25, in _check_call
    return subprocess.check_call(*args, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '-m', 'pip', 'install', '-r', '/tmp/tmpgr5ue_nk/requirements.txt']' returned non-zero exit status 1.

## 复现 
[参考](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/INSTALL_OTHER_DEVICES.md)拉取910b推荐镜像，并执行该链接下pip命令安装paddlepaddle及 paddle_custom_npu
git clone https://github.com/PaddlePaddle/PaddleX.git 拉取最新paddleX代码
cd PaddleX
pip install -e .
paddlex --install
执行到此步骤时报了上述错误信息

## 环境
昇腾910b3机器，linux aarch64系统，拉取镜像https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/INSTALL_OTHER_DEVICES.md

**Comment by a31413510** [comment]
参考下这个文档

**Comment by a31413510** [comment]
可以参考下这个文档

**Comment by a31413510** [comment]
可以参考下这个文档
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/base/devices_use_guidance.md
先手动安装tool_helpers再安装PaddleX
pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlenlp-device/tool_helpers-0.1.1-cp39-cp39-linux_aarch64.whl

**Comment by zhang-prog** [comment]
可以参考上述方法

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
