### ISSUE TITLE
在aistudio中安装使用paddlex时报错KeyError: 'Mask-RT-DETR-H'

### ISSUE THREAD

**Issue by gyx210** [PaddlePaddle/PaddleX#2042]
Traceback (most recent call last):
  File "/home/aistudio/PaddleX/paddlex/repo_apis/base/config.py", line 31, in _create_config
    model_info = get_registered_model_info(model_name)
  File "/home/aistudio/PaddleX/paddlex/repo_apis/base/register.py", line 81, in query
    return self._table[prim_key]
KeyError: 'Mask-RT-DETR-H'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aistudio/PaddleX/paddlex/utils/result_saver.py", line 30, in wrap
    result = func(self, *args, **kwargs)
  File "/home/aistudio/PaddleX/paddlex/engine.py", line 41, in run
    trainer = build_trainer(self.config)
  File "/home/aistudio/PaddleX/paddlex/modules/base/trainer/trainer.py", line 35, in build_trainer
    return BaseTrainer.get(model_name)(config)
  File "/home/aistudio/PaddleX/paddlex/modules/base/trainer/trainer.py", line 53, in __init__
    self.pdx_config, self.pdx_model = build_model(self.global_config.model)
  File "/home/aistudio/PaddleX/paddlex/modules/base/build_model.py", line 34, in build_model
    config = Config(model_name, config_path)
  File "/home/aistudio/PaddleX/paddlex/repo_apis/base/config.py", line 33, in _create_config
    raise UnsupportedParamError(
paddlex.utils.errors.others.UnsupportedParamError: 'Mask-RT-DETR-H' is not a registered model name.

**Comment by Bobholamovic** [comment]
请确认已经按照文档正确安装PaddleX～

**Comment by liming1010** [comment]
相同的问题

**Comment by Bobholamovic** [comment]
请问是否按照文档执行了插件安装步骤哦？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by Light-Towers** [comment]
python 版本 3.10 执行

```bash
pip install -e .
paddlex --install
```

官方文档没有标注适配的版本，全靠自己摸索
