### ISSUE TITLE
高性能插件无法使用。我想用cpu的openvino

### ISSUE THREAD

**Issue by Pointvar** [PaddlePaddle/PaddleX#2184]
安装命令
paddlex --serve --pipeline OCR --device cpu --host 0.0.0.0 --port 5000 --use_hpip --serial_number XXXXX --update_license

安装环境
python3.9

提示错误
RuntimeError: FastDeploy initalized failed! Error: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by Bobholamovic** [comment]
抱歉，这是一个bug，我们将在近期修复。目前请在本地执行 `pip uninstall fastdeploy-gpu-python && pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/pkgs/240927/fastdeploy_python-0.0.0.0.0.0-cp39-cp39-linux_x86_64.whl` 以临时解决这一问题。

**Comment by Pointvar** [comment]
> 抱歉，这是一个bug，我们将在近期修复。目前请在本地执行 `pip uninstall fastdeploy-gpu-python && pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/pkgs/240927/fastdeploy_python-0.0.0.0.0.0-cp39-cp39-linux_x86_64.whl` 以临时解决这一问题。

发现这个问题了，这个脚本内url写错了。但是我还是提示一样的问题。RuntimeError: FastDeploy initalized failed! Error: libcudart.so.11.0
https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py

**Comment by Pointvar** [comment]
运行环境 ubuntu 22      pyhton3.10.12
1. pip install paddlepaddle==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
2. pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl
3.curl -s https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py | python3 - --arch x86_64 --os linux --device cpu --py 310


弄好后 运行
/home/ubuntu/.local/bin/paddlex --pipeline image_classification     --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg     --device cpu --use_hpip    --serial_number A25A-xxxxx-9DC2



报告错误：
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/paddlex_cli.py", line 182, in main
    return pipeline_predict(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/paddlex_cli.py", line 140, in pipeline_predict
    pipeline = create_pipeline(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/pipelines/__init__.py", line 109, in create_pipeline
    return create_pipeline_from_config(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/pipelines/__init__.py", line 84, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/pipelines/single_model_pipeline.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/pipelines/single_model_pipeline.py", line 22, in __init__
    self._build_predictor(model)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/pipelines/single_model_pipeline.py", line 26, in _build_predictor
    self.model = self._create_model(model)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/pipelines/base.py", line 41, in _create_model
    return create_predictor(*args, **kwargs, **self._predictor_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/models/__init__.py", line 77, in create_predictor
    return _create_hp_predictor(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/paddlex/inference/models/__init__.py", line 43, in _create_hp_predictor
    from paddlex_hpi.models import HPPredictor
  File "__init__.py", line 14, in init paddlex_hpi.models.__init__
  File "base.py", line 7, in init paddlex_hpi.models.base
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastdeploy/__init__.py", line 127, in <module>
    from .c_lib_wrap import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by Pointvar** [comment]
按照道理来说 这个是cpu部署 不应该需要libcudart.so.11.0的。我再研究研究～

**Comment by Bobholamovic** [comment]
看起来这是一个bug，目前即使是纯CPU的包，可能也只能在装有cuda toolkit的机器上使用……我们已经定位到初步原因，将尽快解决，感谢反馈～

**Comment by Pointvar** [comment]
> cuda toolkit

好的，我看看怎么装一个。

**Comment by Pointvar** [comment]
对了 支持下python3.11呗～。这个是稳定版，出来好久了。

**Comment by Bobholamovic** [comment]
> 对了 支持下python3.11呗～。这个是稳定版，出来好久了。

目前高性能推理插件支持的Python版本与paddlex支持的Python版本匹配。如果有paddlex支持python 3.11的需求，建议可以另开一个issue～

**Comment by Bobholamovic** [comment]
你好，这两个bug应该都已经修复了，可以尝试按照文档重新安装高性能推理插件～

**Comment by Pointvar** [comment]
看文档的部署脚本 并没修正

https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py

这里的3.9 还是fastdeploy_gpu_python

**Comment by Bobholamovic** [comment]
实在抱歉，现在应该可以了

**Comment by Pointvar** [comment]
好的，谢谢。等会 我测试一下～

**Comment by jiangshanwe** [comment]
> 实在抱歉，现在应该可以了

我这里为啥不行呢，基础镜像：registry.baidubce.com/paddlepaddle/paddle:3.0.0b1。
paddlepaddle              3.0.0b1
paddlex                   3.0.0b1
paddlex-hpi               0.0.0.dev0

服务启动命令：paddlex --serve --pipeline OCR --device cpu --use_hpip --serial_number 79FB-XXXX-XXXX-A317 --update_license

报错如下：
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.10/dist-packages/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/usr/local/lib/python3.10/dist-packages/paddlex/paddlex_cli.py", line 174, in main
    serve(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/paddlex_cli.py", line 155, in serve
    pipeline = create_pipeline_from_config(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/__init__.py", line 85, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/base.py", line 39, in _patched___init__
    ret = ctx.run(init_func, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/ocr.py", line 36, in __init__
    self._build_predictor(text_det_model, text_rec_model)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/ocr.py", line 43, in _build_predictor
    self.text_det_model = self._create(model=text_det_model)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/base.py", line 71, in _create
    return create_predictor(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/__init__.py", line 77, in create_predictor
    return _create_hp_predictor(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/__init__.py", line 43, in _create_hp_predictor
    from paddlex_hpi.models import HPPredictor
  File "__init__.py", line 2, in init paddlex_hpi.models.__init__
  File "anomaly_detection.py", line 4, in init paddlex_hpi.models.anomaly_detection
  File "/usr/local/lib/python3.10/dist-packages/fastdeploy/__init__.py", line 127, in <module>
    from .c_lib_wrap import (
  File "/usr/local/lib/python3.10/dist-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: libcudart.so.11.0: cannot open shared object file: No such file or directory
