### ISSUE TITLE
根据文档训练出现这个错

### ISSUE THREAD

**Issue by liming1010** [PaddlePaddle/PaddleX#2190]
```
(D:\conda\env\paddlex) D:\pyproject\PaddleX>python main.py -c paddlex/configs/object_detection/PicoDet-S.yaml -o Global.mode=train -o Global.dataset_dir=./dataset
ERROR:root:failed to import ujson, using json instead
Traceback (most recent call last):
  File "D:\pyproject\PaddleX\paddlex\repo_apis\base\config.py", line 30, in _create_config
    model_info = get_registered_model_info(model_name)
  File "D:\pyproject\PaddleX\paddlex\repo_apis\base\register.py", line 78, in query
    return self._table[prim_key]
KeyError: 'PicoDet-S'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pyproject\PaddleX\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "D:\pyproject\PaddleX\paddlex\engine.py", line 40, in run
    self._model.train()
  File "D:\pyproject\PaddleX\paddlex\model.py", line 93, in train
    trainer = build_trainer(self._config)
  File "D:\pyproject\PaddleX\paddlex\modules\base\trainer.py", line 34, in build_trainer
    return BaseTrainer.get(model_name)(config)
  File "D:\pyproject\PaddleX\paddlex\modules\base\trainer.py", line 54, in __init__
    self.pdx_config, self.pdx_model = build_model(self.global_config.model)
  File "D:\pyproject\PaddleX\paddlex\modules\base\build_model.py", line 32, in build_model
    config = Config(model_name, config_path)
  File "D:\pyproject\PaddleX\paddlex\repo_apis\base\config.py", line 32, in _create_config
    raise UnsupportedParamError(
paddlex.utils.errors.others.UnsupportedParamError: 'PicoDet-S' is not a registered model name.

版本3.0
数据集没有问题，训练出错
```

**Comment by changdazhou** [comment]
没有执行完整安装，执行paddlex --install

**Comment by zaza523** [comment]
执行paddlex --install   还是这个错  又是怎么回事呢
