### ISSUE TITLE
/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by boreassun** [PaddlePaddle/PaddleX#2193]
## 描述问题
运行：paddlex --pipeline OCR --input /work/test.png --device npu:0
报错内容：
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.9/dist-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/paddlex", line 33, in <module>
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())
  File "/root/PaddleX/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/root/PaddleX/paddlex/paddlex_cli.py", line 182, in main
    return pipeline_predict(
  File "/root/PaddleX/paddlex/paddlex_cli.py", line 144, in pipeline_predict
    for res in result:
  File "/root/PaddleX/paddlex/inference/pipelines/base.py", line 38, in __call__
    yield from self.predict(*args, **kwargs)
  File "/root/PaddleX/paddlex/inference/pipelines/ocr.py", line 60, in predict
    for det_res in self.text_det_model(
  File "/root/PaddleX/paddlex/inference/models/base/base_predictor.py", line 48, in __call__
    for res in super().__call__(input):
  File "/root/PaddleX/paddlex/inference/components/base.py", line 57, in __call__
    for each_output in output:
  File "/root/PaddleX/paddlex/inference/models/base/basic_predictor.py", line 51, in apply
    yield from self._generate_res(self.engine(x))
  File "/root/PaddleX/paddlex/inference/utils/process_hook.py", line 46, in _wrapper
    for ele in input_:
  File "/root/PaddleX/paddlex/inference/components/base.py", line 273, in __call__
    yield from self.__call__(data, i + 1)
  File "/root/PaddleX/paddlex/inference/components/base.py", line 273, in __call__
    yield from self.__call__(data, i + 1)
  File "/root/PaddleX/paddlex/inference/components/base.py", line 273, in __call__
    yield from self.__call__(data, i + 1)
  [Previous line repeated 1 more time]
  File "/root/PaddleX/paddlex/inference/components/base.py", line 272, in __call__
    for data in data_gen:
  File "/root/PaddleX/paddlex/inference/components/base.py", line 43, in __call__
    output = self.apply(**args)
  File "/root/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 167, in apply
    self._reset()
  File "/root/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 49, in _reset
    ) = self._create()
  File "/root/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 55, in _create
    from lazy_paddle.inference import Config, create_predictor
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load_unlocked
  File "/root/PaddleX/paddlex/utils/lazy_loader.py", line 45, in __getattr__
    self._load()
  File "/root/PaddleX/paddlex/utils/lazy_loader.py", line 35, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/paddle/__init__.py", line 37, in <module>
    from .base import core  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/backward.py", line 28, in <module>
    from . import core, framework, log_helper, unique_name
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/core.py", line 375, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

## 环境
昇腾910b  aarch64
python3.9   
cann: 8.0.RC1
paddlepaddle-3.0.0.dev20241010
paddleX3.0b1

**Comment by a31413510** [comment]
使用的这个文档里提供的环境吗

**Comment by a31413510** [comment]
请问使用的是这个文档里提供的环境吗

**Comment by a31413510** [comment]
请问使用的是这个文档里提供的环境吗
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/other_devices_support/paddlepaddle_install_NPU.md

**Comment by boreassun** [comment]
这个问题解决了，通过增加环境变量：LD_PRELOAD=/usr/local/lib/python3.9/dist-packages/scikit_learn.libs/libgomp-d22c30c5.so.1.0.0:/lib/aarch64-linux-gnu/libGLdispatch.so.0:/usr/lib/aarch64-linux-gnu/libgomp.so.1
但是运行报其他错误：RuntimeError: (NotFound) Cannot open file /root/.paddlex/official_models/PP-OCRv4_mobile_det/inference.json, please confirm whether the file is normal.
我不是按上述文档的，用的官方文档的，我看容器镜像是有差别，我也用您提供的试试，感谢！

**Comment by changdazhou** [comment]
好的，那我们这边关闭issue了哈
