### ISSUE TITLE
PaddleX可视化客户端训练报错

### ISSUE THREAD

**Issue by atat1010** [PaddlePaddle/PaddleX#2213]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 描述问题
win10系统，在图像分类训练时，报错
## 复现
![image](https://github.com/user-attachments/assets/b433e04d-8f12-4294-8e60-0824151b4e2b)

## 错误日志
This log file path is /home/rao/Code/SunPeiDiQinMao/paddleX/projects/P0001/T0001/err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/loss.py:1281: DeprecationWarning: invalid escape sequence \s
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/functional/pooling.py:740: DeprecationWarning: invalid escape sequence \_
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/layer/pooling.py:1187: DeprecationWarning: invalid escape sequence \_
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/incubate/nn/functional/fused_transformer.py:111: DeprecationWarning: invalid escape sequence \_
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/incubate/nn/functional/fused_transformer.py:339: DeprecationWarning: invalid escape sequence \_
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/vision/ops.py:952: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (len(x.shape) == 4,
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/signal.py:307: DeprecationWarning: invalid escape sequence \o
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/signal.py:472: DeprecationWarning: invalid escape sequence \s
  """
/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:3:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "pms/model_tasks/tasks.py", line 73, in _call_paddlex_train
  File "pms/model_tasks/train/classification.py", line 118, in train
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/classifier.py", line 703, in __init__
    model_name=model_name, num_classes=num_classes, **params)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/classifier.py", line 70, in __init__
    self.net = self.build_net(**params)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/cv/models/classifier.py", line 75, in build_net
    **params)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppcls/arch/backbone/legendary_models/mobilenet_v3.py", line 438, in MobileNetV3_small_x1_0
    **kwargs)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppcls/arch/backbone/legendary_models/mobilenet_v3.py", line 164, in __init__
    act="hardswish")
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddlex/ppcls/arch/backbone/legendary_models/mobilenet_v3.py", line 240, in __init__
    bias_attr=False)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/layer/conv.py", line 656, in __init__
    data_format=data_format)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/initializer.py", line 366, in __call__
    stop_gradient=True)
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/rao/Downloads/PaddleX_GUI_2.1.0_ubuntu_amd64/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at /paddle/paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]

**Comment by cuicheng01** [comment]
您好，建议您使用PaddleX3.0，命令行使用，更好自定义，功能特更强大，问题我们也更好地可以跟进～

**Comment by atat1010** [comment]
> 您好，建议您使用PaddleX3.0，命令行使用，更好自定义，功能特更强大，问题我们也更好地可以跟进～

你好，PaddleX3.0可以像这个客户端一样发布模型吗

**Comment by Sunting78** [comment]
您好，PaddleX3.0支持本地推理部署 以及 服务化部署。 客户端版本暂时维护人力不足。如果希望有图形界面，也可以使用PaddleX3.0的云端界面版本。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
