### ISSUE TITLE
高性能服务化部署，模型文件内inference。yml 文件Golbal.model_name ,填自己训练的模型时报错，

### ISSUE THREAD

**Issue by alanOO7** [PaddlePaddle/PaddleX#2221]
(pdx) root@mcn-server:/home/mcn/PaddleX/pipconfig# paddlex --serve --pipeline /home/mcn/PaddleX/pipconfig/CME.yaml --use_hpip --serial_number 8D19-D9B9-4F38-8F1B
2024-10-14 13:46:04,562 ERROR [PADDLEX] 128170357692224 Invalid license(2): /root/.baidu/paddlex/licenses/paddlex.auth.log
2024-10-14 13:46:04,562 DEBUG [PADDLEX] 128170357692224 3 licenses loaded
2024-10-14 13:46:04,562 DEBUG [PADDLEX] 128170357692224 /root/.baidu/paddlex/licenses/license.5E13.4190.02.data
2024-10-14 13:46:04,562 DEBUG [PADDLEX] 128170357692224 /root/.baidu/paddlex/licenses/license.8D19.5042.02.data
2024-10-14 13:46:04,562 DEBUG [PADDLEX] 128170357692224 /root/.baidu/paddlex/licenses/license.F2AE.8467.02.data
2024-10-14 13:46:04,562 DEBUG [PADDLEX] 128170357692224 License [8D19-D9B9-...] is permanently valid, skip check local time 
2024-10-14 13:46:04,567 DEBUG [PADDLEX] 128170357692224 License [8D19-D9B9-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(185)::PaddleXAuth  Basic authentication succeeded.
2024-10-14 13:46:04,571 DEBUG [PADDLEX] 128170357692224 License [8D19-D9B9-...] is permanently valid, skip check local time 
2024-10-14 13:46:04,574 DEBUG [PADDLEX] 128170357692224 License [8D19-D9B9-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(263)::PaddleXAuth  Task authentication succeeded.
[INFO] fastdeploy/runtime/runtime.cc(327)::Init The unencrypted model will be used for inference.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(28)::BuildOption    Will inference_precision float32
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1014 13:46:04.831781 3357992 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.4, Runtime API Version: 11.8
W1014 13:46:04.832280 3357992 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
[INFO] fastdeploy/runtime/runtime.cc(474)::CreatePaddleBackend  Runtime initialized with Backend::PDINFER in Device::GPU.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pdx/bin/paddlex", line 33, in <module>
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())
  File "/home/mcn/PaddleX/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/home/mcn/PaddleX/paddlex/paddlex_cli.py", line 169, in main
    serve(
  File "/home/mcn/PaddleX/paddlex/paddlex_cli.py", line 155, in serve
    pipeline = create_pipeline_from_config(
  File "/home/mcn/PaddleX/paddlex/inference/pipelines/__init__.py", line 84, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/home/mcn/PaddleX/paddlex/inference/pipelines/ocr.py", line 35, in __init__
    self._build_predictor(text_det_model, text_rec_model)
  File "/home/mcn/PaddleX/paddlex/inference/pipelines/ocr.py", line 40, in _build_predictor
    self.text_rec_model = self._create_model(text_rec_model)
  File "/home/mcn/PaddleX/paddlex/inference/pipelines/base.py", line 41, in _create_model
    return create_predictor(*args, **kwargs, **self._predictor_kwargs)
  File "/home/mcn/PaddleX/paddlex/inference/models/__init__.py", line 77, in create_predictor
    return _create_hp_predictor(
  File "/home/mcn/PaddleX/paddlex/inference/models/__init__.py", line 58, in _create_hp_predictor
    raise ValueError(
ValueError: text_recognition_module is not supported by the PaddleX HPI plugin.

**Comment by alanOO7** [comment]
![image](https://github.com/user-attachments/assets/3a301345-b976-4b40-b7d4-af6d5081ff1f)

**Comment by zhang-prog** [comment]
你好，目前不是所有模型都支持使用高性能推理插件的，可以参考[支持使用高性能推理插件的产线与模型](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/pipeline_deploy/high_performance_deploy.md) 。如果你自己训练的模型在列表里，可以把模型改成对应名称再试一下～

**Comment by alanOO7** [comment]
模型名称和必须是官方那几个。。
