### ISSUE TITLE
使用高性能推理插件过程中报错

### ISSUE THREAD

**Issue by a19970519** [PaddlePaddle/PaddleX#2252]
## 环境

ubuntu 22.04
Python 3.10.8
cuda 11.8
cuDNN 8.6
gpu 4090
驱动版本 550.107.02

paddlepaddle-gpu 3.0.0b1
paddlex 3.0.0b1
paddlex-hpi 0.0.0.dev0
fastdeploy-gpu-python 0.0.0.0.0.0
fastdeploy-tools 0.0.5

## 运行命令
paddlex --serve --pipeline OCR --device gpu:0 --host 0.0.0.0 --port 6006 --use_hpip --serial_number FXXX-2XXX-4XXX-9XXX --update_license

## 错误提示
File "/root/miniconda3/lib/python3.10/site-packages/fastdeploy/vision/ocr/ppocr/__init__.py", line 474, in __init__
    assert self.initialized, "DBDetector initialize failed."

## 完整内容
2024-10-16 11:02:32,143 ERROR [PADDLEX] 140086948185920 Device fingerprint mismatch(7)
[ERROR] fastdeploy/runtime/runtime.cc(172)::PaddleXAuth	License update failed.
Please ensure that you have purchased the product and set the correct serial number.
[ERROR] fastdeploy/runtime/runtime.cc(281)::Init	Authentication failed. Please check the serial number.
[ERROR] fastdeploy/vision/ocr/ppocr/dbdetector.cc(52)::Initialize	Failed to initialize fastdeploy backend.
Traceback (most recent call last):
  File "/root/miniconda3/bin/paddlex", line 33, in <module>
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())
  File "/root/autodl-tmp/PaddleX/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/root/autodl-tmp/PaddleX/paddlex/paddlex_cli.py", line 169, in main
    serve(
  File "/root/autodl-tmp/PaddleX/paddlex/paddlex_cli.py", line 155, in serve
    pipeline = create_pipeline_from_config(
  File "/root/autodl-tmp/PaddleX/paddlex/inference/pipelines/__init__.py", line 84, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/root/autodl-tmp/PaddleX/paddlex/inference/pipelines/ocr.py", line 35, in __init__
    self._build_predictor(text_det_model, text_rec_model)
  File "/root/autodl-tmp/PaddleX/paddlex/inference/pipelines/ocr.py", line 39, in _build_predictor
    self.text_det_model = self._create_model(text_det_model)
  File "/root/autodl-tmp/PaddleX/paddlex/inference/pipelines/base.py", line 41, in _create_model
    return create_predictor(*args, **kwargs, **self._predictor_kwargs)
  File "/root/autodl-tmp/PaddleX/paddlex/inference/models/__init__.py", line 77, in create_predictor
    return _create_hp_predictor(
  File "/root/autodl-tmp/PaddleX/paddlex/inference/models/__init__.py", line 49, in _create_hp_predictor
    predictor = HPPredictor.get(model_name)(
  File "text_detection.py", line 24, in paddlex_hpi.models.text_detection.TextDetPredictor.__init__
  File "base.py", line 152, in paddlex_hpi.models.base.CVPredictor.__init__
  File "base.py", line 48, in paddlex_hpi.models.base.HPPredictor.__init__
  File "base.py", line 89, in paddlex_hpi.models.base.HPPredictor.build_fd_model
  File "text_detection.py", line 46, in paddlex_hpi.models.text_detection.TextDetPredictor._build_fd_model
  File "/root/miniconda3/lib/python3.10/site-packages/fastdeploy/vision/ocr/ppocr/__init__.py", line 474, in __init__
    assert self.initialized, "DBDetector initialize failed."
AssertionError: DBDetector initialize failed.

**Comment by Bobholamovic** [comment]
请检查使用的序列号是否是OCR产线的~

**Comment by a19970519** [comment]
> 请检查使用的序列号是否是OCR产线的~

是ocr产线的

**Comment by a19970519** [comment]
执行离线获取设备指纹没有返回结果

**Comment by Bobholamovic** [comment]
请检查`/dev/disk/by-uuid`目录是否存在以及是否为空

**Comment by a19970519** [comment]
> /dev/disk/by-uuid

这个目录不存在，没有disk文件夹

**Comment by Bobholamovic** [comment]
请问执行的机器是物理机还是虚拟化的环境呀？

**Comment by a19970519** [comment]
> 请问执行的机器是物理机还是虚拟化的环境呀？

是租用的GPU计算服务器，是完整的GPU，可能是虚拟环境

**Comment by Bobholamovic** [comment]
看起来很可能是一个虚拟环境。由于目前paddlex的鉴权机制依赖于磁盘信息（`/dev/disk/by-uuid`目录中的文件），而这个环境里并没有相关的信息，因此，很抱歉，在这个环境里可能暂时不支持使用高性能推理插件。

**Comment by a19970519** [comment]
> 看起来很可能是一个虚拟环境。由于目前paddlex的鉴权机制依赖于磁盘信息（`/dev/disk/by-uuid`目录中的文件），而这个环境里并没有相关的信息，因此，很抱歉，在这个环境里可能暂时不支持使用高性能推理插件。

好吧，感谢，他这个应该是挂载的虚拟磁盘

**Comment by Bobholamovic** [comment]
那我就先关闭这个issue啦 有其他问题欢迎继续提问
