### ISSUE TITLE
执行 paddlex --install serving 反馈没有权限

### ISSUE THREAD

**Issue by fws407296762** [PaddlePaddle/PaddleX#2289]
我 window 11 下安装了 Anaconda，在里面新建了 paddlex 虚拟环境，用 cmd 的超级管理员权限下面，执行 `paddlex --install serving` 报没有权限

ERROR: Could not open requirements file: [Errno 13] Permission denied: 'C:\\Users\\xx\\AppData\\Local\\Temp\\tmpe9kwvbq0.txt'
Traceback (most recent call last):
  File "E:\anaconda3\envs\paddlex\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\paddlex\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\envs\paddlex\Scripts\paddlex.exe\__main__.py", line 7, in <module>
    sys.exit(console_entry())
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\__main__.py", line 28, in console_entry
    code = main()
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\paddlex_cli.py", line 171, in main
    install(args)
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\paddlex_cli.py", line 113, in install
    _install_serving_deps()
  File "E:\anaconda3\envs\paddlex\lib\site-packages\paddlex\paddlex_cli.py", line 42, in _install_serving_deps
    return subprocess.check_call(
  File "E:\anaconda3\envs\paddlex\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\anaconda3\\envs\\paddlex\\python.exe', '-m', 'pip', 'install', '-r', 'C:\\Users\\xx\\AppData\\Local\\Temp\\tmpe9kwvbq0.txt']' returned non-zero exit status 1.

**Comment by fws407296762** [comment]
我自己找了一下原因，是因为 `tempfile.NamedTemporaryFile`，如果要在 `windows` 打开该临时文件，需要将文件关闭，然后再打开，操作完文件后，再调用 `os.remove` 删除临时文件。

我临时改了一下代码文件：`/lib/site-packages/paddlex/paddlex_cli.py`，因为对 `python` 不熟悉，只能临时改成这样了

找到 `_install_serving_deps` 函数后修改成下面的代码

```
def _install_serving_deps():
    SERVING_DEPS = [
        "aiohttp>=3.9",
        "bce-python-sdk>=0.8",
        "fastapi>=0.110",
        "pydantic>=2",
        "starlette>=0.36",
        "typing_extensions>=4.11",
        "uvicorn>=0.16",
        "yarl>=1.9",
    ]
    f = tempfile.NamedTemporaryFile("w", suffix=".txt", encoding="utf-8",delete=False)
    temp = f.name
    for dep in SERVING_DEPS:
        f.write(dep + "\n")
    f.flush()
    return subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-r", temp]
    )
```

**Comment by Bobholamovic** [comment]
请尝试使用管理员权限打开终端后执行该指令～ 或者，请尝试直接执行：

```bash
python -m pip install aiohttp>=3.9 bce-python-sdk>=0.8 fastapi>=0.110 pydantic>=2 starlette>=0.36 typing_extensions>=4.11 uvicorn>=0.16 yarl>=1.9
```

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
