### ISSUE TITLE
训练模型时报错，数据校验已通过

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#2306]
(PaddleX) C:\Paddle\PaddleX-release-3.0-beta1>python main.py -c paddlex/configs/object_detection/PP-YOLOE_plus-L.yaml -o Global.mode=check_dataset -o Global.dataset_dir=F:/Bai/HB_Workspace_Det/CCD2/dataset/COCO2
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Check dataset passed !

(PaddleX) C:\Paddle\PaddleX-release-3.0-beta1>python main.py -c paddlex/configs/object_detection/PP-YOLOE_plus-L.yaml -o Global.mode=train -o Global.dataset_dir=F:/Bai/HB_Workspace_Det/CCD2/dataset/COCO2
['C:\\ProgramData\\anaconda3\\envs\\PaddleX\\python.exe', '-m', 'paddle.distributed.launch', '--devices', '0,1,2,3', '--log_dir', 'C:\\Paddle\\PaddleX-release-3.0-beta1\\output\\distributed_train_logs', 'tools/train.py', '--eval', '--config', 'C:\\Users\\LK\\.paddlex\\tmp1_dx1jfv\\detmodel_PP-YOLOE_plus-L.yml', '--use_vdl', 'True', '--vdl_log_dir', 'C:\\Paddle\\PaddleX-release-3.0-beta1\\output']

Log path: C:\Paddle\PaddleX-release-3.0-beta1\output\train.log

LAUNCH ERROR 2024-10-23 18:26:56,091 Device not found 1 from 0,1,2,3 for setting ['0']
LAUNCH ERROR 2024-10-23 18:26:56,091 Device not found 2 from 0,1,2,3 for setting ['0']
LAUNCH ERROR 2024-10-23 18:26:56,091 Device not found 3 from 0,1,2,3 for setting ['0']
LAUNCH INFO 2024-10-23 18:26:56,106 -----------  Configuration  ----------------------
LAUNCH INFO 2024-10-23 18:26:56,106 auto_parallel_config: None
LAUNCH INFO 2024-10-23 18:26:56,106 auto_tuner_json: None
LAUNCH INFO 2024-10-23 18:26:56,106 devices: 0,1,2,3
LAUNCH INFO 2024-10-23 18:26:56,106 elastic_level: -1
LAUNCH INFO 2024-10-23 18:26:56,106 elastic_timeout: 30
LAUNCH INFO 2024-10-23 18:26:56,106 enable_gpu_log: True
LAUNCH INFO 2024-10-23 18:26:56,106 gloo_port: 6767
LAUNCH INFO 2024-10-23 18:26:56,106 host: None
LAUNCH INFO 2024-10-23 18:26:56,106 ips: None
LAUNCH INFO 2024-10-23 18:26:56,106 job_id: default
LAUNCH INFO 2024-10-23 18:26:56,106 legacy: False
LAUNCH INFO 2024-10-23 18:26:56,106 log_dir: C:\Paddle\PaddleX-release-3.0-beta1\output\distributed_train_logs
LAUNCH INFO 2024-10-23 18:26:56,106 log_level: INFO
LAUNCH INFO 2024-10-23 18:26:56,106 log_overwrite: False
LAUNCH INFO 2024-10-23 18:26:56,107 master: None
LAUNCH INFO 2024-10-23 18:26:56,107 max_restart: 3
LAUNCH INFO 2024-10-23 18:26:56,107 nnodes: 1
LAUNCH INFO 2024-10-23 18:26:56,107 nproc_per_node: None
LAUNCH INFO 2024-10-23 18:26:56,107 rank: -1
LAUNCH INFO 2024-10-23 18:26:56,107 run_mode: collective
LAUNCH INFO 2024-10-23 18:26:56,107 server_num: None
LAUNCH INFO 2024-10-23 18:26:56,107 servers:
LAUNCH INFO 2024-10-23 18:26:56,107 sort_ip: False
LAUNCH INFO 2024-10-23 18:26:56,107 start_port: 6070
LAUNCH INFO 2024-10-23 18:26:56,107 trainer_num: None
LAUNCH INFO 2024-10-23 18:26:56,107 trainers:
LAUNCH INFO 2024-10-23 18:26:56,107 training_script: tools/train.py
LAUNCH INFO 2024-10-23 18:26:56,107 training_script_args: ['--eval', '--config', 'C:\\Users\\LK\\.paddlex\\tmp1_dx1jfv\\detmodel_PP-YOLOE_plus-L.yml', '--use_vdl', 'True', '--vdl_log_dir', 'C:\\Paddle\\PaddleX-release-3.0-beta1\\output']
LAUNCH INFO 2024-10-23 18:26:56,107 with_gloo: 1
LAUNCH INFO 2024-10-23 18:26:56,107 --------------------------------------------------
LAUNCH INFO 2024-10-23 18:26:56,108 Job: default, mode collective, replicas 1[1:1], elastic False
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\__main__.py", line 17, in <module>
    launch()
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\main.py", line 1362, in launch
    c.run()
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\controllers\controller.py", line 81, in run
    self.build_pod()
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\controllers\collective.py", line 51, in build_pod
    return self._build_pod_with_master(skip_run)
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\controllers\collective.py", line 216, in _build_pod_with_master
    selected_dev_list = self.ctx.node.device.get_selected_devices(
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\context\device.py", line 85, in get_selected_devices
    return [str(self._labels.index(d)) for d in devs]
  File "C:\ProgramData\anaconda3\envs\PaddleX\lib\site-packages\paddle\distributed\launch\context\device.py", line 85, in <listcomp>
    return [str(self._labels.index(d)) for d in devs]
ValueError: '1' is not in list
Traceback (most recent call last):
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\engine.py", line 40, in run
    self._model.train()
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\model.py", line 94, in train
    trainer.train()
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\base\trainer.py", line 71, in train
    train_result = self.pdx_model.train(**train_args)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\PaddleDetection_api\object_det\model.py", line 145, in train
    return self.runner.train(
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\PaddleDetection_api\object_det\runner.py", line 55, in train
    return self.run_cmd(
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\base\runner.py", line 355, in run_cmd
    raise CalledProcessError(
paddlex.utils.errors.others.CalledProcessError: Command ['C:\\ProgramData\\anaconda3\\envs\\PaddleX\\python.exe', '-m', 'paddle.distributed.launch', '--devices', '0,1,2,3', '--log_dir', 'C:\\Paddle\\PaddleX-release-3.0-beta1\\output\\distributed_train_logs', 'tools/train.py', '--eval', '--config', 'C:\\Users\\LK\\.paddlex\\tmp1_dx1jfv\\detmodel_PP-YOLOE_plus-L.yml', '--use_vdl', 'True', '--vdl_log_dir', 'C:\\Paddle\\PaddleX-release-3.0-beta1\\output'] returned non-zero exit status 1.

**Comment by Bobholamovic** [comment]
看起来现在的配置是4卡训练，请问你本地机器有几块显卡呀？

**Comment by CashBai** [comment]
解决了，确实把多余显卡序号删除就好了



---- 回复的原邮件 ----
| 发件人 | Lin ***@***.***> |
| 日期 | 2024年10月23日 20:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleX] 训练模型时报错，数据校验已通过 (Issue #2306) |

看起来现在的配置是4卡训练，请问你本地机器有几块显卡呀？

**Comment by Bobholamovic** [comment]
好的，我将关闭这个issue，如果有其他问题欢迎继续提issue～
