### ISSUE TITLE
数据集进行数据集验证并切分时报错

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#2359]
当数据集中不含有切分信息是就会报错
```
(paddlex) C:\Paddle\PaddleX-release-3.0-beta1>python main.py -c paddlex/configs/semantic_segmentation/OCRNet_HRNet-W48.yaml -o Global.mode=check_dataset -o Global.dataset_dir=F:\Bai\seg_optic_examples -o CheckDataset.split.enable=True -o CheckDataset.split.train_percent=80 -o CheckDataset.split.val_percent=20
The mapping file (F:\Bai\seg_optic_examples\train.txt) doesn't exist, ignored.
The mapping file (F:\Bai\seg_optic_examples\val.txt) doesn't exist, ignored.
Split dataset successfully !
Traceback (most recent call last):
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\engine.py", line 38, in run
    return self._model.check_dataset()
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\model.py", line 90, in check_dataset
    return dataset_checker.check()
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\base\dataset_checker\dataset_checker.py", line 75, in check
    attrs = self.check_dataset(dataset_dir)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\semantic_segmentation\dataset_checker\__init__.py", line 68, in check_dataset
    return check_dataset(dataset_dir, self.output, sample_num)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\semantic_segmentation\dataset_checker\dataset_src\check_dataset.py", line 76, in check_dataset
    attrs[f"{tag}_samples"] = i + 1
UnboundLocalError: local variable 'i' referenced before assignment
```
若本身含有切分数据，重新切分，就不会报错
```
(paddlex) C:\Paddle\PaddleX-release-3.0-beta1>python main.py -c paddlex/configs/semantic_segmentation/OCRNet_HRNet-W48.yaml -o Global.mode=check_dataset -o Global.dataset_dir=F:\Bai\seg_optic_examples -o CheckDataset.split.enable=True -o CheckDataset.split.train_percent=80 -o CheckDataset.split.val_percent=20
The original mapping file (F:\Bai\seg_optic_examples\train.txt) has been backed up to (F:\Bai\seg_optic_examples\train.txt.bak)
The original mapping file (F:\Bai\seg_optic_examples\val.txt) has been backed up to (F:\Bai\seg_optic_examples\val.txt.bak)
Split dataset successfully !
Check dataset passed !
```

**Comment by changdazhou** [comment]
感谢您的反馈，我们这边定位一下问题

**Comment by CashBai** [comment]
@changdazhou 修复bug麻烦回复我一下，谢谢

**Comment by changdazhou** [comment]
好的

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
