### ISSUE TITLE
模型评估时报错

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#2398]
```
(paddlex_det) C:\Paddle\PaddleX-release-3.0-beta1>python main.py -c paddlex/configs/semantic_segmentation/Deeplabv3_Plus-R50.yaml -o Global.mode=evaluate -o Global.dataset_dir=F:\Bai\V2\Datasets\CCD2\Det -o Evaluate.weight_path=F:\Bai\V2\Det_Model\CCD2\best_model\best_model.pdparams
Traceback (most recent call last):
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\engine.py", line 44, in run
    return self._model.evaluate()
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\model.py", line 97, in evaluate
    evaluator = build_evaluater(self._config)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\base\evaluator.py", line 36, in build_evaluater
    return BaseEvaluator.get(model_name)(config)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\base\evaluator.py", line 56, in __init__
    self.pdx_config, self.pdx_model = build_model(
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\modules\base\build_model.py", line 32, in build_model
    config = Config(model_name, config_path)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\base\config.py", line 39, in _create_config
    config_obj = config_cls(model_name=model_name, config_path=config_path)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\base\config.py", line 131, in __init__
    self.load(config_path)
  File "C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\PaddleSeg_api\base_seg_config.py", line 37, in load
    dict_ = parse_from_yaml(config_path)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\paddleseg\cvlibs\config.py", line 162, in parse_from_yaml
    dic = yaml.load(file, Loader=yaml.FullLoader)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\ProgramData\anaconda3\envs\paddlex_det\lib\site-packages\yaml\constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!ImageFolder'
  in "F:\Bai\V2\Det_Model\CCD2\config.yaml", line 97, column 14
```

```
CSPResNet:
  channels:
  - 64
  - 128
  - 256
  - 512
  - 1024
  layers:
  - 3
  - 6
  - 6
  - 3
  return_idx:
  - 1
  - 2
  - 3
  use_alpha: true
  use_large_stem: true
CustomCSPPAN:
  act: swish
  block_num: 3
  out_channels:
  - 768
  - 384
  - 192
  spp: true
  stage_num: 1
EvalDataset:
  allow_empty: true
  anno_path: annotations/instance_val.json
  dataset_dir: F:\Bai\V2\Datasets\CCD2\Det
  image_dir: images
  name: COCODetDataset
EvalReader:
  batch_size: 2
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 256
      - 800
  - NormalizeImage:
      mean:
      - 0.0
      - 0.0
      - 0.0
      norm_type: none
      std:
      - 1.0
      - 1.0
      - 1.0
  - Permute: {}
LearningRate:
  base_lr: 5.0e-05
  schedulers:
  - max_epochs: 96
    name: CosineDecay
  - name: LinearWarmup
    start_factor: 0.0
    steps: 100
OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
PPYOLOEHead:
  assigner:
    alpha: 1.0
    beta: 6.0
    name: TaskAlignedAssigner
    topk: 13
  fpn_strides:
  - 32
  - 16
  - 8
  grid_cell_offset: 0.5
  grid_cell_scale: 5.0
  loss_weight:
    class: 1.0
    dfl: 0.5
    iou: 2.5
  nms:
    keep_top_k: 300
    name: MultiClassNMS
    nms_threshold: 0.7
    nms_top_k: 1000
    score_threshold: 0.01
  static_assigner:
    name: ATSSAssigner
    topk: 9
  static_assigner_epoch: 30
  use_varifocal_loss: true
TestDataset: !ImageFolder
  anno_path: annotations/instance_val.json
  dataset_dir: F:\Bai\V2\Datasets\CCD2\Det
  image_dir: ''
  sample_num: -1
  use_default_label: null
TestReader:
  batch_size: 1
  inputs_def:
    image_shape:
    - 3
    - 256
    - 800
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 256
      - 800
  - NormalizeImage:
      mean:
      - 0.0
      - 0.0
      - 0.0
      norm_type: none
      std:
      - 1.0
      - 1.0
      - 1.0
  - Permute: {}
TrainDataset:
  anno_path: annotations/instance_train.json
  data_fields:
  - image
  - gt_bbox
  - gt_class
  - is_crowd
  dataset_dir: F:\Bai\V2\Datasets\CCD2\Det
  image_dir: images
  name: COCODetDataset
TrainReader:
  batch_size: 4
  batch_transforms:
  - NormalizeImage:
      mean:
      - 0.0
      - 0.0
      - 0.0
      norm_type: none
      std:
      - 1.0
      - 1.0
      - 1.0
  - Permute: {}
  - PadGT: {}
  collate_batch: true
  drop_last: true
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 256
      - 800
  shuffle: true
  use_shared_memory: true
YOLOv3:
  backbone: CSPResNet
  neck: CustomCSPPAN
  post_process: null
  yolo_head: PPYOLOEHead
amp: false
architecture: YOLOv3
custom_black_list:
- reduce_mean
depth_mult: 1.0
ema_black_list:
- proj_conv.weight
ema_decay: 0.9998
enable_ce: false
epoch: 10
eval: true
eval_height: 256
eval_size:
- 256
- 800
eval_width: 800
export:
  benchmark: false
  fuse_conv_bn: false
  nms: true
  post_process: true
filename: detmodel_PP-YOLOE_plus-L
find_unused_parameters: false
fleet: false
hpi_config_path: C:/Paddle/PaddleX-release-3.0-beta1/paddlex/utils/hpi_configs/PP-YOLOE_plus-L.yaml
log_iter: 10
metric: COCO
norm_type: sync_bn
num_classes: 3
pdx_model_name: PP-YOLOE_plus-L
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_l_obj365_pretrained.pdparams
print_flops: false
print_params: false
profiler_options: null
proposals_path: sniper/proposals.json
resume: null
save_dir: F:\Bai\V2\Det_Model\CCD2
save_prediction_only: false
save_proposals: false
snapshot_epoch: 1
to_static: false
uniform_output_enabled: true
use_ema: true
use_gpu: true
use_mlu: false
use_npu: false
use_vdl: true
use_wandb: false
use_xpu: false
vdl_log_dir: F:\Bai\V2\Det_Model\CCD2
width_mult: 1.0
worker_num: 4

```

**Comment by Sunting78** [comment]
您好 TestDataset: !ImageFolder 把  !ImageFolder部分删除后试一下。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
