### ISSUE TITLE
KeyError: 'SLANet_plus'，UnsupportedParamError: 'SLANet_plus' is not a registered model name.

### ISSUE THREAD

**Issue by yyhlichao** [PaddlePaddle/PaddleX#2401]
python：3.10
paddlex：3.0-beta1

根据文档执行安装，开始训练，报错如下（SLANet、SLANet_plus都是这种错）：

D:\git_workspace\github_project\PaddleX>python main.py -c paddlex/configs/table_recognition/SLANet_plus.yaml -o Global.mode=train -o Global.dataset_dir=./dataset/table_rec_dataset_examples
Traceback (most recent call last):
  File "D:\git_workspace\github_project\PaddleX\paddlex\repo_apis\base\config.py", line 30, in _create_config
    model_info = get_registered_model_info(model_name)
  File "D:\git_workspace\github_project\PaddleX\paddlex\repo_apis\base\register.py", line 78, in query
    return self._table[prim_key]
KeyError: 'SLANet_plus'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\git_workspace\github_project\PaddleX\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "D:\git_workspace\github_project\PaddleX\paddlex\engine.py", line 41, in run
    self._model.train()
  File "D:\git_workspace\github_project\PaddleX\paddlex\model.py", line 93, in train
    trainer = build_trainer(self._config)
  File "D:\git_workspace\github_project\PaddleX\paddlex\modules\base\trainer.py", line 34, in build_trainer
    return BaseTrainer.get(model_name)(config)
  File "D:\git_workspace\github_project\PaddleX\paddlex\modules\base\trainer.py", line 54, in __init__
    self.pdx_config, self.pdx_model = build_model(self.global_config.model)
  File "D:\git_workspace\github_project\PaddleX\paddlex\modules\base\build_model.py", line 32, in build_model
    config = Config(model_name, config_path)
  File "D:\git_workspace\github_project\PaddleX\paddlex\repo_apis\base\config.py", line 32, in _create_config
    raise UnsupportedParamError(
paddlex.utils.errors.others.UnsupportedParamError: 'SLANet_plus' is not a registered model name.

**Comment by hoobnn** [comment]
# 安装 PaddleX 全部插件
paddlex --install

你需要安装对应的插件，上述命令可以安装全部插件

**Comment by xiaoxiaoo8** [comment]
@yyhlichao 你解决了吗?我也遇到了这个问题

**Comment by hoobnn** [comment]
> @yyhlichao 你解决了吗?我也遇到了这个问题

我楼上的回复呀

**Comment by xiaoxiaoo8** [comment]
哦哦好的，谢谢我再试试

**Comment by savi8sant8s** [comment]
I had the same problem and ended up creating an [issue](https://github.com/PaddlePaddle/PaddleX/issues/2891). Has anyone managed to fix it and could you share the solution?
