### ISSUE TITLE
数据集创建引导问题

### ISSUE THREAD

**Issue by foreverseer** [PaddlePaddle/PaddleX#244]
PaddleX GUI: https://www.paddlepaddle.org.cn/paddle/paddleX
GUI的新建数据集界面右侧说明文档的“数据集导入规则说明“中的”语义分割任务“
下面的路径文件夹-（可选）label.txt，不能导入，存在lable.txt时，类别仍然为012...
经检查后发现应该命名为labels.txt，右测说明文档有问题

**Comment by mamingjie-China** [comment]
> PaddleX GUI: https://www.paddlepaddle.org.cn/paddle/paddleX
> GUI的新建数据集界面右侧说明文档的“数据集导入规则说明“中的”语义分割任务“
> 下面的路径文件夹-（可选）label.txt，不能导入，存在lable.txt时，类别仍然为012...
> 经检查后发现应该命名为labels.txt，右测说明文档有问题

感谢使用和反馈，这里的文档的确存在问题，已进行修改，预计会随着下一个GUI版本的发布更新，可以先使用labels.txt进行上传。

**Comment by WeiDaoLiang** [comment]
我导入了一个官方的家具数据集http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/231787/train-image.zip
共有12144张图片，选用的语义分割任务。报了以下错误：
Traceback (most recent call last):
  File "paddlexui\pms\dataset\seg_dataset.py", line 89, in check_dataset
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paddlexui\pms\dataset\operate.py", line 39, in _check_and_copy
  File "paddlexui\pms\dataset\seg_dataset.py", line 92, in check_dataset
ValueError: 标注信息与实际类别不一致
我检查了数据，并没有问题，上面报的错误中说超出范围，我猜想，在使用paddlex可视化软件，导入数据集时，是否存在数据集大小的限制问题，如果是，那么这个限制是多 少呢？

**Comment by lailuboy** [comment]
没有限制，从这个错误来看是标注信息存在问题，请检查一下对应的数据集。

**Comment by WeiDaoLiang** [comment]
我用paddlex可视化软件，运行了一个epoch一个后，报错，ValueError: column index exceeds matrix dimensions，数据集是30000万的，进行语义分割

**Comment by bolaado** [comment]
训练模型的时候刚开始就报错IndexError: list index out of range
![Uploading X6H8C73ZFYWVI(WCYAKSBL0.png…]()

**Comment by bolaado** [comment]
This log file path is E:\paddlex_workspace\projects\P0005\T0012\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
Process Process-1:4:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 67, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 171, in train
  File "paddlexui\pms\model_tasks\train\detection.py", line 104, in build_voc_datasets
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\datasets\voc.py", line 124, in __init__
IndexError: list index out of range

**Comment by jiangjiajun** [comment]
确认下你的数据集的xml标注文件中，有没有size这个字段
