### ISSUE TITLE
通过Paddlex训练paddleocr，报错：'gbk' codec can't encode character '\xcb' in position 0

### ISSUE THREAD

**Issue by willingtolove** [PaddlePaddle/PaddleX#2464]
## 描述问题
通过Paddlex训练paddleocr:
`python main.py -c paddlex\configs\text_recognition\PP-OCRv4_mobile_rec.yaml -o Global.mode=train -o  Global.dataset_dir=dataset\train_data\rec`

其中的报错部分为：
`File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 1139, in write_plain self.stream.write(data) UnicodeEncodeError: 'gbk' codec can't encode character '\xcb' in position 0: illegal multibyte sequence`

完整的报错：
`Traceback (most recent call last):
  File "C:\ai\PaddleX\paddlex\repo_manager\repos\PaddleOCR\tools\train.py", line 269, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "C:\ai\PaddleX\paddlex\repo_manager\repos\PaddleOCR\tools\train.py", line 222, in main
    program.train(
  File "C:\ai\PaddleX\paddlex\repo_manager\repos\PaddleOCR\tools\program.py", line 546, in train
    export(config, model, os.path.join(save_model_dir, prefix, "inference"))
  File "C:\ai\PaddleX\paddlex\repo_manager\repos\PaddleOCR\ppocr\utils\export_model.py", line 382, in export
    dump_infer_config(config, yaml_path, logger)
  File "C:\ai\PaddleX\paddlex\repo_manager\repos\PaddleOCR\ppocr\utils\export_model.py", line 100, in dump_infer_config
    yaml.dump(
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\representer.py", line 28, in represent
    self.serialize(node)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\serializer.py", line 98, in serialize_node
    self.serialize_node(item, node, index)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\serializer.py", line 89, in serialize_node
    self.emit(ScalarEvent(alias, node.tag, implicit, node.value,
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 115, in emit
    self.state()
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 384, in expect_block_sequence_item
    self.expect_node(sequence=True)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "C:\Users\zyl\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\emitter.py", line 1139, in write_plain
    self.stream.write(data)
UnicodeEncodeError: 'gbk' codec can't encode character '\xcb' in position 0: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\ai\PaddleX\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "C:\ai\PaddleX\paddlex\engine.py", line 41, in run
    self._model.train()
  File "C:\ai\PaddleX\paddlex\model.py", line 94, in train
    trainer.train()
  File "C:\ai\PaddleX\paddlex\modules\base\trainer.py", line 71, in train
    train_result = self.pdx_model.train(**train_args)
  File "C:\ai\PaddleX\paddlex\repo_apis\PaddleOCR_api\text_rec\model.py", line 148, in train
    return self.runner.train(
  File "C:\ai\PaddleX\paddlex\repo_apis\PaddleOCR_api\text_rec\runner.py", line 56, in train
    return self.run_cmd(
  File "C:\ai\PaddleX\paddlex\repo_apis\base\runner.py", line 355, in run_cmd
    raise CalledProcessError(
paddlex.utils.errors.others.CalledProcessError: Command ['C:\\Users\\zyl\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', 'tools/train.py', '-c', 'C:\\Users\\zyl\\.paddlex\\tmp7yv_dqys\\textrecmodel_PP-OCRv4_mobile_rec.yml'] returned non-zero exit status 1.`

## 环境

windows 10
python3.9
paddlex 3.0.0b1
cpu

---
**感谢各位大侠帮助！**

**Comment by zhang-prog** [comment]
看样子是编码的问题，把你当前环境改为utf-8编码试试。

ps：windows的问题比较多，如果可以尽量使用linux，这可以减少很多因为环境问题而浪费的时间。

**Comment by Barry-1212** [comment]
配置文件的编码修改成gbk就行

**Comment by zhang-prog** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.
