### ISSUE TITLE
AttributeError: 'paddle.base.libpaddle.AnalysisConfig' object has no attribute 'set_optimization_level'. Did you mean: 'tensorrt_optimization_level'?

### ISSUE THREAD

**Issue by Yt-nn** [PaddlePaddle/PaddleX#2546]
您好！我使用版面区域检测模块时，遇到下面的问题

## 教程
https://paddlepaddle.github.io/PaddleX/latest/module_usage/tutorials/ocr_modules/layout_detection.html#_3

## 描述问题
运行：
from paddlex import create_model

model_name = "PicoDet-L_layout_3cls"

model = create_model(model_name)
output = model.predict("layout.jpg", batch_size=1)

for res in output:
    res.print(json_format=False)
    res.save_to_img("./output/")
    res.save_to_json("./output/res.json")

报错：
Traceback (most recent call last):
  File "D:\pycharm\pythonProject\partOne\paddleX_prog\main.py", line 5, in <module>
    model = create_model(model_name)
  File "d:\gitclone\paddlex\paddlex\model.py", line 29, in create_model
    return _ModelBasedInference(model, *args, **kwargs)
  File "d:\gitclone\paddlex\paddlex\model.py", line 57, in __init__
    self._predictor = create_predictor(*args, **kwargs)
  File "d:\gitclone\paddlex\paddlex\inference\models\__init__.py", line 88, in create_predictor
    return BasicPredictor.get(model_name)(
  File "d:\gitclone\paddlex\paddlex\inference\models\base\basic_predictor.py", line 47, in __init__
    self._build_components()
  File "d:\gitclone\paddlex\paddlex\inference\models\object_detection.py", line 41, in _build_components
    predictor = ImageDetPredictor(
  File "d:\gitclone\paddlex\paddlex\inference\components\paddle_predictor\predictor.py", line 73, in __init__
    self._update_option(option)
  File "d:\gitclone\paddlex\paddlex\inference\components\paddle_predictor\predictor.py", line 80, in _update_option
    self._reset()
  File "d:\gitclone\paddlex\paddlex\inference\components\paddle_predictor\predictor.py", line 98, in _reset
    ) = self._create()
  File "d:\gitclone\paddlex\paddlex\inference\components\paddle_predictor\predictor.py", line 187, in _create
    config.set_optimization_level(3)
AttributeError: 'paddle.base.libpaddle.AnalysisConfig' object has no attribute 'set_optimization_level'. Did you mean: 'tensorrt_optimization_level'?

## 复现
1. 已经按照提供的教程安装依赖库
2. 未修改代码

## 环境

1. paddlepaddle-2.6.2；paddlex-3.0.0b2
2. 操作系统为Windows
3. Python版本为3.10.15
4. cpu运行

**Comment by zhangyubo0722** [comment]
将paddlepaddle版本升级为3.0 beta2尝试下呢

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by 110506-gyz** [comment]
@zhangyubo0722 大佬，想问问Gpu版的也是这样操作吗

**Comment by jianlins** [comment]
3.30 同样error

**Comment by t00350320** [comment]
L4, CUDA Version: 12.2 
same error
"  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 401, in _create
    config.set_optimization_level(3)
AttributeError: 'paddle.base.libpaddle.AnalysisConfig' object has no attribute 'set_optimization_level'. Did you mean: 'tensorrt_optimization_level'?
"

**Comment by KasuganoSoraw** [comment]
3.3.0遇到了同样的问题
\Lib\site-packages\paddlex\inference\models\common\static_infer.py", line 467, in _create
    config.set_optimization_level(3)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'paddle.base.libpaddle.AnalysisConfig' object has no attribute 'set_optimization_level'. Did you mean: 'tensorrt_optimization_level'?
@zhangyubo0722麻烦看看
