### ISSUE TITLE
PP-YOLOE-plus系列模型在cpu上预测时报错RuntimeError: (NotFound) The kernel `sync_batch_norm` is not registered.

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleX#2553]
我在gpu上使用自己的数据训练PP-YOLOE-plus-L和M模型， 在gpu上训练，评估和预测都没问题，但是把预测模型下载到本地使用cpu进行预测时就会报错：
![image](https://github.com/user-attachments/assets/1ae619d5-ac87-41a4-9514-f9445e361264)

预测和训练环境都是paddle-3.0beta2

**Comment by zhangyubo0722** [comment]
这个问题是由于多卡训练中导出时所用的模型bn层被替换成了sync_bn,而sync_bn在cpu上是不支持的，问题会尽快修复

**Comment by xujiang1** [comment]
如果从gpu 训练后搬到npu 也会有问题 是否可以解决
Traceback (most recent call last):
  File "/workspace/PaddleX/paddlex/utils/result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "/workspace/PaddleX/paddlex/engine.py", line 49, in run
    for res in self._model.predict():
  File "/workspace/PaddleX/paddlex/model.py", line 105, in predict
    predict_kwargs, predictor = self._build_predictor()
  File "/workspace/PaddleX/paddlex/model.py", line 84, in _build_predictor
    predictor = create_predictor(model, pp_option=pp_option)
  File "/workspace/PaddleX/paddlex/inference/models/__init__.py", line 88, in create_predictor
    return BasicPredictor.get(model_name)(
  File "/workspace/PaddleX/paddlex/inference/models/base/basic_predictor.py", line 47, in __init__
    self._build_components()
  File "/workspace/PaddleX/paddlex/inference/models/object_detection.py", line 41, in _build_components
    predictor = ImageDetPredictor(
  File "/workspace/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 73, in __init__
    self._update_option(option)
  File "/workspace/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 80, in _update_option
    self._reset()
  File "/workspace/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 98, in _reset
    ) = self._create()
  File "/workspace/PaddleX/paddlex/inference/components/paddle_predictor/predictor.py", line 198, in _create
    predictor = create_predictor(config)
RuntimeError: (NotFound) Operator (sync_batch_norm) is not registered.
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:152)

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/9249

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/9249
这个问题已经提交pr解决，稍后合入

**Comment by xujiang1** [comment]
@zhangyubo0722 https://github.com/PaddlePaddle/PaddleDetection/pull/9249 这个我看现在都还没有合入 能合入一下吗

**Comment by zhangyubo0722** [comment]
已经合入

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
