### ISSUE TITLE
AttributeError: 'paddle.base.libpaddle.AnalysisConfig' object has no attribute 'set_optimization_level'

### ISSUE THREAD

**Issue by Yanxingang** [PaddlePaddle/PaddleX#2578]
使用命令：paddlex --pipeline OCR 3.png --device gpu:5       
出现报错：                                                                      
Using official model (PP-OCRv4_mobile_det), the model files will be be automatically downloaded and saved in /root/.paddlex/official_models.
Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.8/dist-packages/paddlex/__main__.py", line 26, in console_entry
    code = main()
  File "/usr/local/lib/python3.8/dist-packages/paddlex/paddlex_cli.py", line 189, in main
    return pipeline_predict(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/paddlex_cli.py", line 142, in pipeline_predict
    pipeline = create_pipeline(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/pipelines/__init__.py", line 119, in create_pipeline
    return create_pipeline_from_config(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/pipelines/__init__.py", line 94, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/pipelines/base.py", line 39, in _patched___init__
    ret = ctx.run(init_func, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/pipelines/ocr.py", line 36, in __init__
    self._build_predictor(text_det_model, text_rec_model)
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/pipelines/ocr.py", line 43, in _build_predictor
    self.text_det_model = self._create(model=text_det_model)
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/pipelines/base.py", line 71, in _create
    return create_predictor(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/models/__init__.py", line 88, in create_predictor
    return BasicPredictor.get(model_name)(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/models/base/basic_predictor.py", line 47, in __init__
    self._build_components()
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/models/text_detection.py", line 40, in _build_components
    predictor = ImagePredictor(
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 73, in __init__
    self._update_option(option)
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 80, in _update_option
    self._reset()
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 98, in _reset
    ) = self._create()
  File "/usr/local/lib/python3.8/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 187, in _create
    config.set_optimization_level(3)
AttributeError: 'paddle.base.libpaddle.AnalysisConfig' object has no attribute 'set_optimization_level'

**Comment by changdazhou** [comment]
使用的哪个版本PaddlePaddle呢

**Comment by cuicheng01** [comment]
这个应该是paddle版本的问题，我们在文档中有明确paddlex和paddle的对应关系，如果使用的是paddlex 3.0beta2的代码，请使用paddle框架3.0b2哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by wang-kangkang** [comment]
上这里找最新的paddlex：https://pypi.org/project/paddlex/3.0.0b2/#files
上这里找最新的paddle：https://www.paddlepaddle.org.cn/

**Comment by hawkli-1994** [comment]
> 这个应该是paddle版本的问题，我们在文档中有明确paddlex和paddle的对应关系，如果使用的是paddlex 3.0beta2的代码，请使用paddle框架3.0b2哈

请问下能不能贴个文档链接， 找不到paddlex和paddle的对应关系 @cuicheng01

**Comment by fangfap** [comment]
update paddlepaddle to 3.0.0

**Comment by 1005cyxin** [comment]
gpu呢，paddlepaddle-gpu2.4.2也是报这个错

**Comment by JohnFiv** [comment]
> 这个应该是paddle版本的问题，我们在文档中有明确paddlex和paddle的对应关系，如果使用的是paddlex 3.0beta2的代码，请使用paddle框架3.0b2哈

找不到明确的点在哪。。。很混乱，直接贴在github首页多好

**Comment by Deng-Jiang-Lin** [comment]
参考一下Torch的官方文档来编写吧。看看人家写得多明确，你们这个文档敷衍了事。
