### ISSUE TITLE
python脚本方式集成本地体验ocr的时候无法编码保存json

### ISSUE THREAD

**Issue by fxy1108** [PaddlePaddle/PaddleX#2604]
使用：
from paddlex import create_pipeline
pipeline = create_pipeline(pipeline="OCR",device="cpu") 
output = pipeline.predict(".\dataset\images_ori\win_sys_1_ori.jpg")
for res in output:
    res.print()
    res.save_to_img("./dataset/images_ocr/")
    res.save_to_json("./dataset/jsons_ocr/")
报错：
Traceback (most recent call last):
  File "c:\fxy\to xy\2 PaddleOCR\ocr.py", line 8, in <module>
    res.save_to_json("./dataset/jsons_ocr/")
  File "C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\results\utils\mixin.py", line 101, in save_to_json
    _save_list_data(
  File "C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\results\utils\mixin.py", line 48, in _save_list_data
    save_func(save_path.as_posix(), data, *args, **kwargs)
  File "C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\utils\io\writers.py", line 144, in write
    return self._backend.write_obj(str(out_path), obj, **bk_args)
  File "C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\utils\io\writers.py", line 305, in write_obj
    return self._write_obj(out_path, obj, **bk_args)
  File "C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\utils\io\writers.py", line 314, in _write_obj
    json.dump(obj, f, **bk_args)
  File "C:\software\anaconda\envs\test\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\software\anaconda\envs\test\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-13: character maps to <undefined>

**Comment by zhangyubo0722** [comment]
这是由于保存的json文件中有特殊字符，可以尝试在C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\utils\io\writers.py，第313行改为 with open(out_path, "w") as f: -> with open(out_path, "w", encoding="utf-8") as f:

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by tlishi** [comment]
> 这是由于保存的json文件中有特殊字符，可以尝试在C:\software\anaconda\envs\test\lib\site-packages\paddlex\inference\utils\io\writers.py，第313行改为 with open(out_path, "w") as f: -> with open(out_path, "w", encoding="utf-8") as f:

请问如果不这样修改，保存的json是什么格式的编码，方便以后直接使用不需要修改。
因为我中文乱码，修改utf-8后重新识别出来的就对了
