### ISSUE TITLE
910b使用最新镜像，name 'libpaddle' is not defined

### ISSUE THREAD

**Issue by zhaonx** [PaddlePaddle/PaddleX#2620]
## Checklist:

- [x] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [x] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [x] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [x] 确认bug是否在新版本里还未修复

## 描述问题
按照最新的910b的安装教程，拉取了cann80t13的镜像
![image](https://github.com/user-attachments/assets/d32ed1b0-a91a-4896-929e-cbad703e735c)
执行下述命令
python3.9 -m pip install paddlepaddle==3.0.0.dev20240520 -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/
python3.9 -m pip install paddle_custom_npu==3.0.0.dev20240719 -i https://www.paddlepaddle.org.cn/packages/nightly/npu/
python -c "import paddle; paddle.utils.run_check()"
![image](https://github.com/user-attachments/assets/c444a415-7d2b-4e0c-b8e3-b3faff54cd6b)
使用
pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl 安装

执行 paddlex --pipeline OCR --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_002.png --device npu:1

报错 NameError: name 'libpaddle' is not defined
`Error: Can not import paddle core while this file exists: /usr/local/lib/python3.9/dist-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.9/dist-packages/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/usr/local/lib/python3.9/dist-packages/paddlex/paddlex_cli.py", line 189, in main
    return pipeline_predict(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/paddlex_cli.py", line 142, in pipeline_predict
    pipeline = create_pipeline(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/__init__.py", line 110, in create_pipeline
    return create_pipeline_from_config(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/__init__.py", line 85, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/base.py", line 39, in _patched___init__
    ret = ctx.run(init_func, self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/ocr.py", line 36, in __init__
    self._build_predictor(text_det_model, text_rec_model)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/ocr.py", line 43, in _build_predictor
    self.text_det_model = self._create(model=text_det_model)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/base.py", line 71, in _create
    return create_predictor(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/models/__init__.py", line 87, in create_predictor
    return BasicPredictor.get(model_name)(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/models/base/basic_predictor.py", line 42, in __init__
    self._build_components()
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/models/text_detection.py", line 40, in _build_components
    predictor = ImagePredictor(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 37, in __init__
    self._update_option(option)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 45, in _update_option
    self.reset()
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 64, in reset
    ) = self._create()
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 69, in _create
    from lazy_paddle.inference import Config, create_predictor
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/paddlex/utils/lazy_loader.py", line 60, in __getattr__
    self._load()
  File "/usr/local/lib/python3.9/dist-packages/paddlex/utils/lazy_loader.py", line 47, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/paddle/__init__.py", line 30, in <module>
    from .base import core  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/usr/local/lib/python3.9/dist-packages/paddle/base/core.py", line 379, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined`

## 复现

1. 您是否已经正常运行我们提供的[教程](https://paddlepaddle.github.io/PaddleX/main/index.html)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？
8.0.0.alpha001 cann arrch64

**Comment by nepeplwu** [comment]
@zhaonx 这个问题是libgomp在arm上的一个bug，试试在添加以下环境变量：
```shell
export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD
```
