### ISSUE TITLE
PaddleClas训练报错：ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by 188080501** [PaddlePaddle/PaddleX#2633]
我的环境是：
PaddleX 3.0-beta2
paddlepaddle-gpu 3.0.0b2
Windows10 ltsc 2019
Python 3.10
CUDA 11.8

我的训练命令是：
python main.py -c paddlex/configs/image_classification/ResNet50_vd.yaml -o Global.mode=train -o Global.dataset_dir=./dataset/mydata -o Global.device=gpu:0

yaml参数：
Train:
  num_classes: 3
  epochs_iters: 4000
  batch_size: 80
  learning_rate: 0.4
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/ResNet50_vd_pretrained.pdparams
  warmup_steps: 5
  resume_path: null
  log_interval: 10
  eval_interval: 50
  save_interval: 50

epochs_iters修改过，改到了4000，此数据集训练的时间预估是12小时，在训练的第8小时左右报错退出。
同样的数据集，epochs_iters改为200时都是正常训练，结果也是正常的

报错时的相关log：
[2024/12/12 07:03:30] ppcls INFO: Already save model info in E:\PaddleX3b2\output\latest
[2024/12/12 07:03:30] ppcls INFO: [Train][Epoch 2761/4000][Iter: 0/45]lr(LinearWarmup): 0.08778214, CELoss: 0.31856, loss: 0.31856, batch_cost: 0.22956s, reader_cost: 0.14004, ips: 348.48641 samples/s, eta: 3:33:29
[2024/12/12 07:03:33] ppcls INFO: [Train][Epoch 2761/4000][Iter: 10/45]lr(LinearWarmup): 0.08775321, CELoss: 0.39941, loss: 0.39941, batch_cost: 0.24930s, reader_cost: 0.14880, ips: 320.90138 samples/s, eta: 3:51:48
[2024/12/12 07:03:35] ppcls INFO: [Train][Epoch 2761/4000][Iter: 20/45]lr(LinearWarmup): 0.08772429, CELoss: 0.38701, loss: 0.38701, batch_cost: 0.25314s, reader_cost: 0.15202, ips: 316.03331 samples/s, eta: 3:55:20
[2024/12/12 07:03:38] ppcls INFO: [Train][Epoch 2761/4000][Iter: 30/45]lr(LinearWarmup): 0.08769536, CELoss: 0.40372, loss: 0.40372, batch_cost: 0.25188s, reader_cost: 0.15076, ips: 317.60801 samples/s, eta: 3:54:07
[2024/12/12 07:03:40] ppcls INFO: [Train][Epoch 2761/4000][Iter: 40/45]lr(LinearWarmup): 0.08766645, CELoss: 0.41095, loss: 0.41095, batch_cost: 0.25068s, reader_cost: 0.14975, ips: 319.13227 samples/s, eta: 3:52:57
[2024/12/12 07:03:42] ppcls INFO: [Train][Epoch 2761/4000][Avg]CELoss: 0.40320, loss: 0.40320
[2024/12/12 07:03:42] ppcls INFO: Skipping export to 'latest' path: E:\PaddleX3b2\output\latest\inference
[2024/12/12 07:03:42] ppcls INFO: Already save model info in E:\PaddleX3b2\output\latest
[2024/12/12 07:03:42] ppcls INFO: [Train][Epoch 2762/4000][Iter: 0/45]lr(LinearWarmup): 0.08765199, CELoss: 0.30561, loss: 0.30561, batch_cost: 0.21146s, reader_cost: 0.12242, ips: 132.41429 samples/s, eta: 3:16:29
[2024/12/12 07:03:45] ppcls INFO: [Train][Epoch 2762/4000][Iter: 10/45]lr(LinearWarmup): 0.08762307, CELoss: 0.43213, loss: 0.43213, batch_cost: 0.27751s, reader_cost: 0.17535, ips: 288.28309 samples/s, eta: 4:17:49
[2024/12/12 07:03:45] ppcls INFO: [Train][Epoch 2762/4000][Iter: 20/45]lr(LinearWarmup): 0.08759416, CELoss: 0.42841, loss: 0.42841, batch_cost: 0.09273s, reader_cost: 0.06206, ips: 862.75723 samples/s, eta: 1:26:08
Traceback (most recent call last):
  File "E:\PaddleX3b2\paddlex\repo_manager\repos\PaddleClas\tools\train.py", line 53, in <module>
    engine.train()
  File "E:\PaddleX3b2\paddlex\repo_manager\repos\PaddleClas\ppcls\engine\engine.py", line 339, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "E:\PaddleX3b2\paddlex\repo_manager\repos\PaddleClas\ppcls\engine\train\train.py", line 86, in train_epoch
    log_info(engine, batch_size, epoch_id, iter_id)
  File "E:\PaddleX3b2\paddlex\repo_manager\repos\PaddleClas\ppcls\engine\train\utils.py", line 56, in log_info
    batch_size / trainer.time_info["batch_cost"].avg)
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "E:\PaddleX3b2\paddlex\utils\result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "E:\PaddleX3b2\paddlex\engine.py", line 41, in run
    self._model.train()
  File "E:\PaddleX3b2\paddlex\model.py", line 94, in train
    trainer.train()
  File "E:\PaddleX3b2\paddlex\modules\base\trainer.py", line 71, in train
    train_result = self.pdx_model.train(**train_args)
  File "E:\PaddleX3b2\paddlex\repo_apis\PaddleClas_api\cls\model.py", line 123, in train
    return self.runner.train(
  File "E:\PaddleX3b2\paddlex\repo_apis\PaddleClas_api\cls\runner.py", line 50, in train
    return self.run_cmd(
  File "E:\PaddleX3b2\paddlex\repo_apis\base\runner.py", line 355, in run_cmd
    raise CalledProcessError(
paddlex.utils.errors.others.CalledProcessError: Command ['C:\\Users\\Jason\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'tools/train.py', '-c', 'C:\\Users\\Jason\\.paddlex\\tmp161ph07f\\clsmodel_ResNet50_vd.yml', '-o', 'Global.eval_during_train=True'] returned non-zero exit status 1.

utils.py中具体报错的代码：
    ips_msg = "ips: {:.5f} samples/s".format(
        batch_size / trainer.time_info["batch_cost"].avg)

是否这里需要一个除以0的保护?

**Comment by TingquanGao** [comment]
提PR修了，可以先参考改一下：https://github.com/PaddlePaddle/PaddleClas/pull/3324

**Comment by 188080501** [comment]
感谢修复
