### ISSUE TITLE
在本地检测数据集格式成功，但模型配置时检测不通过。

### ISSUE THREAD

**Issue by tianmingxing** [PaddlePaddle/PaddleX#2692]
## Checklist:

- [ v] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ v] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [v ] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [v ] 确认bug是否在新版本里还未修复

## 描述问题

在本地检测数据集格式成功，也反复与示例数据集对比看了。

```bash
python ./PaddleX/main.py -c ./PaddleX/paddlex/configs/text_detection/PP-OCRv4_server_det.yaml \
    -o Global.mode=check_dataset \
    -o Global.dataset_dir=./ocr_det_dataset_demo1
Check dataset passed !
```

但在配置文本检测模型，走到数据集格式检测时出现错误。

```log
2024-12-18 20:55:16,067 - pp-pipeline-exec - INFO - u-15204360-pp-p-7137d10d3eae-tt-7193af0a1cec
2024-12-18 20:55:16,067 - pp-pipeline-exec - INFO - 执行命令：python /home/aistudio/template_pipelines/general_ocr_pipeline/text_detection_module/main.py --mode check_dataset --dataset_dir /home/aistudio/data --output_dir /home/aistudio/output --dst_dataset_name 我的数据集 --model_name PP-OCRv4_server_det
2024-12-18 20:55:17,187 - pp-pipeline-exec - INFO - ERROR:root:failed to import ujson, using json instead
Traceback (most recent call last):
  File "/home/aistudio/template_pipelines/general_ocr_pipeline/text_detection_module/base/engine.py", line 31, in wrap
    func(self, *args, **kwargs)
  File "/home/aistudio/template_pipelines/general_ocr_pipeline/text_detection_module/base/engine.py", line 66, in run
    self.run_dataset_check()
  File "/home/aistudio/template_pipelines/general_ocr_pipeline/text_detection_module/base/engine.py", line 108, in run_dataset_check
    self.dataset_checker()
  File "/home/aistudio/template_pipelines/general_ocr_pipeline/text_detection_module/base/dataset_checker/dataset_checker.py", line 29, in __call__
    dataset_dir = self.get_dataset_root(self.args.dataset_dir)
  File "/home/aistudio/template_pipelines/general_ocr_pipeline/text_detection_module/base/dataset_checker/dataset_checker.py", line 67, in get_dataset_root
    assert len(dataset_dir) == 1
AssertionError

```

## 复现

1. 您使用的命令是？

2. 您使用的数据集是？

```
/dataset_dir/ tree -L 1
.
├── images
├── train.txt
└── val.txt

```

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号

[release/3.0-beta2](https://github.com/PaddlePaddle/PaddleX/tree/release/3.0-beta2)

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

MacOS

4. 请问您使用的Python版本是

3.9

**Comment by liuhongen1234567** [comment]
您好，可以到这个[位置](https://github.com/PaddlePaddle/PaddleX/blob/cbfd7c16e2c084349384f2ea788db0fa8c5d2040/paddlex/modules/base/dataset_checker/dataset_checker.py#L97)打印一下 dataset_dir 看看呢？或者可以试一下绝对路径

**Comment by tianmingxing** [comment]
感谢回复。
在不断尝试之后似乎找到了解决方法，我在MacOS上整理好数据集之后，便在访达里面直接右键压缩，这导致产生了的很多隐藏的多余文件。
后来我在终端中使用命令压缩并过滤掉这些隐藏文件，再上传数据集便解决了问题。
因时间关系我并没有深究和复现确认。
