### ISSUE TITLE
图像异常检测使用官方数据集训练，执行脚本缺失/PaddleX/paddlex/repo_manager/repos/PaddleSeg/tools/train.py

### ISSUE THREAD

**Issue by SolMing** [PaddlePaddle/PaddleX#2709]
## 描述问题
运行代码，进行图片异常检测的训练，使用文档提供的案例
1、
` python main.py -c paddlex/configs/anomaly_detection/STFPM.yaml     -o Global.mode=train  -o Global.device=gpu:0    -o Global.dataset_dir=../dataset/mvtec_examples 
`
2、最初提示没有 STFPM 这个模块，通过：https://github.com/PaddlePaddle/PaddleX/issues/2455
提供解决的，paddlex --install PaddleSeg 安装插件，不再提示该问题。

3、安装PaddleSeg 插件后，重新执行该训练动作命令，出现新的问题，提示：

/home/ai/anaconda3/envs/paddleocr/bin/python: can't open file '/home/ai/labelme/PaddleX/paddlex/repo_manager/repos/PaddleSeg/tools/train.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/ai/labelme/PaddleX/paddlex/utils/result_saver.py", line 29, in wrap
    result = func(self, *args, **kwargs)
  File "/home/ai/labelme/PaddleX/paddlex/engine.py", line 41, in run
    self._model.train()
  File "/home/ai/labelme/PaddleX/paddlex/model.py", line 94, in train
    trainer.train()
  File "/home/ai/labelme/PaddleX/paddlex/modules/base/trainer.py", line 71, in train
    train_result = self.pdx_model.train(**train_args)
  File "/home/ai/labelme/PaddleX/paddlex/repo_apis/PaddleSeg_api/seg/model.py", line 178, in train
    return self.runner.train(
  File "/home/ai/labelme/PaddleX/paddlex/repo_apis/PaddleSeg_api/seg/runner.py", line 55, in train
    return self.run_cmd(
  File "/home/ai/labelme/PaddleX/paddlex/repo_apis/base/runner.py", line 355, in run_cmd
    raise CalledProcessError(
paddlex.utils.errors.others.CalledProcessError: Command ['/home/ai/anaconda3/envs/paddleocr/bin/python', 'tools/train.py', '--do_eval', '--config', '/home/ai/.paddlex/tmpdnrb5ygj/segmodel_STFPM.yml', '--batch_size', '1', '--learning_rate', '0.4', '--iters', '50', '--device', 'gpu', '--use_vdl', '--save_dir', '/home/ai/labelme/PaddleX/output', '--save_interval', '100', '--log_iters', '10'] returned non-zero exit status 2.

4、通过github的代码路径，也没有找到此文件目录，所以前来咨询此问题

5、另外图像异常检测的标注数据，形成训练数据集的文档不全，通过推荐按照推荐图片语义切割的，形成的的训练数据集的内容和此提供的参考训练数据集不一样，不清楚是我的操作漏了什么导致，请教下

## 环境

1. 请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号
2. 
python 3.9 
paddlepaddle-gpu==3.0.0b2
paddlex==3.0.0b2

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
unbuntu22.04

5. 请问您使用的CUDA/cuDNN的版本号是？

cuda11.8

**Comment by SolMing** [comment]
抱歉，要用 插件安装模式 安装 paddlex 才会有，否则需要单独去下载 paddleseg 的代码

**Comment by skyler9901** [comment]
请问什么叫 用插件安装模式安装paddlex呢？
