### ISSUE TITLE
inference转hub出错

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/PaddleX#282]
你好，我使用paddlex训练了一个模型，并已经生成了paddlex inference model，按照说明文档使用hub（paddlehub版本为1.8.1） convert将inference转hub时，出现如下报错：
```javascript
hub convert --model_dir D:/paddlex_workspace/modules/P0005-T0031_export_model/inference_model --module_name bba_classify
2020-08-21 11:41:31,338-INFO: Instantiated empty configuration.
HDFS initialization failed, please check if .hdfscli，cfg exists.
Traceback (most recent call last):
  File "d:\program files (x86)\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Python\Python37\Scripts\hub.exe\__main__.py", line 7, in <module>
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\commands\hub.py", line 64, in main
    command.execute(argv[1:])
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\commands\hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\commands\convert.py", line 149, in execute
    self.create_serving_demo_py()
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\commands\convert.py", line 102, in create_serving_demo_py
    tmpl = Template(template_file.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 493: illegal multibyte sequence
```

**Comment by ShenYuhan** [comment]
您好，这个问题我们已经修复，您可以使用下面这个文件替换`d:\program files (x86)\python\python37\lib\site-packages\paddlehub\commands\convert.py`，稍后我们会发布新版的paddlehub，届时就可以解决此问题


[convert.py.txt](https://github.com/PaddlePaddle/PaddleX/files/5106865/convert.py.txt)

**Comment by ClassmateXiaoyu** [comment]
> 您好，这个问题我们已经修复，您可以使用下面这个文件替换`d:\program files (x86)\python\python37\lib\site-packages\paddlehub\commands\convert.py`，稍后我们会发布新版的paddlehub，届时就可以解决此问题
> 
> [convert.py.txt](https://github.com/PaddlePaddle/PaddleX/files/5106865/convert.py.txt)

多谢，问题已解决，模型转换成功。
