### ISSUE TITLE
hub convert转换模型报错

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/PaddleX#288]
你好，使用paddlex训练模型并已经生成了paddlex inference model，按照说明文档使用hub（paddlehub版本为1.8.2） convert将inference转hub时，出现如下报错：
```javascript
C:\Users\Administrator>hub convert --model_dir inference_model --module_name bba_classify
Traceback (most recent call last):
  File "d:\program files (x86)\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\python\python37\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\__init__.py", line 27, in <module>
    from . import module
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "d:\program files (x86)\python\python37\lib\site-packages\paddlehub\module\module.py", line 28, in <module>
    import paddle
  File "d:\program files (x86)\python\python37\lib\site-packages\paddle\__init__.py", line 39, in <module>
    from . import incubate
  File "d:\program files (x86)\python\python37\lib\site-packages\paddle\incubate\__init__.py", line 15, in <module>
    from . import hapi
  File "d:\program files (x86)\python\python37\lib\site-packages\paddle\incubate\hapi\__init__.py", line 16, in <module>
    from . import vision
  File "d:\program files (x86)\python\python37\lib\site-packages\paddle\incubate\hapi\vision\__init__.py", line 15, in <module>
    from . import transforms
  File "d:\program files (x86)\python\python37\lib\site-packages\paddle\incubate\hapi\vision\transforms\__init__.py", line 15, in <module>
    from . import transforms
  File "d:\program files (x86)\python\python37\lib\site-packages\paddle\incubate\hapi\vision\transforms\transforms.py", line 18, in <module>
    import cv2
  File "d:\program files (x86)\python\python37\lib\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by ClassmateXiaoyu** [comment]
server2008 R2的服务问题，已解决。
