### ISSUE TITLE
模型训练多轮后出错

### ISSUE THREAD

**Issue by pughua** [PaddlePaddle/PaddleX#430]
问题类型：模型训练  
**问题描述**d  
模型训练6轮后出错

====================  
使用的paddlex gui
D:\AI\paddlex\PaddleX\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
Process Process-1:6:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 67, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 216, in train
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\models\faster_rcnn.py", line 271, in train
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\models\base.py", line 494, in train_loop
  File "site-packages\paddle\fluid\executor.py", line 1071, in run
  File "site-packages\six.py", line 703, in reraise
  File "site-packages\paddle\fluid\executor.py", line 1066, in run
  File "site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
  File "site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "site-packages\paddle\fluid\framework.py", line 2610, in append_op
  File "site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
  File "site-packages\paddle\fluid\layers\nn.py", line 8239, in roi_align
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\nets\detection\roi_extractor.py", line 105, in __call__
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\nets\detection\faster_rcnn.py", line 212, in build_net
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\models\faster_rcnn.py", line 127, in build_net
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\models\base.py", line 105, in build_program
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\models\faster_rcnn.py", line 247, in train
  File "paddlexui\pms\model_tasks\train\detection.py", line 216, in train
  File "paddlexui\pms\model_tasks\tasks.py", line 67, in _call_paddlex_train
  File "multiprocessing\process.py", line 99, in run
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\spawn.py", line 118, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 43, in _freeze_support
  File "paddlexui\PaddleXCore.py", line 39, in main
  File "paddlexui\PaddleX.py", line 18, in <module>

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The rois_batch_size and imgs batch_size must be the same. But received rois_batch_size = 1, batch_size = 2
  [Hint: Expected rois_batch_size == batch_size, but received rois_batch_size:1 != batch_size:2.] at (D:\1.8.4\paddle\paddle/fluid/operators/roi_align_op.h:198)
  [operator < roi_align > error]

**Comment by jiangjiajun** [comment]
这个问题重新训也会出现吗

**Comment by lr310440764** [comment]
这个问题是怎么解决的，我也出现了

**Comment by jiangjiajun** [comment]
> 这个问题是怎么解决的，我也出现了

你的这个问题也是重新训练会重复出这个错误吗，如果是会重复出现这个问题，麻烦贴一下你的训练环境信息

1. 是否使用PaddleX可视化客户端或是使用Python代码进行训练
2. 若为可视化客户端，则客户端设置页面截图上传一下；若为Python代码，则说明一下paddlepaddle版本和paddlex版本
3. 方便的话上传你的训练数据和参数配置，方便工程师进行debug分析

**Comment by lr310440764** [comment]
> > 这个问题是怎么解决的，我也出现了
> 
> 你的这个问题也是重新训练会重复出这个错误吗，如果是会重复出现这个问题，麻烦贴一下你的训练环境信息
> 
> 1. 是否使用PaddleX可视化客户端或是使用Python代码进行训练
> 2. 若为可视化客户端，则客户端设置页面截图上传一下；若为Python代码，则说明一下paddlepaddle版本和paddlex版本
> 3. 方便的话上传你的训练数据和参数配置，方便工程师进行debug分析


这个问题是重新训练会重复出这个错误，，第一次中断不是这个错误信息，会存储模型文件，，，接下来一直都是这个错误信息，并且不会存储模型文件，
使用Python代码进行训练的，paddlex版本__version__ = '1.3.3'，paddlepaddle->full_version    = '1.8.5'
model = pdx.det.FasterRCNN(
    num_classes=num_classes,
    backbone='ResNet50_vd_ssld',
    with_dcn=True,
    fpn_num_channels=64,
    with_fpn=True,
    test_pre_nms_top_n=500,
    test_post_nms_top_n=300)

model.train(
    num_epochs=8,
    train_dataset=train_dataset,
    train_batch_size=2,
    eval_dataset=eval_dataset,
    learning_rate=0.0025,
    lr_decay_epochs=[60, 70],
    warmup_steps=5000,
    save_dir='/Users/modelfasterrcnn/faster_rcnn_r50_vd_dcn',
    use_vdl=True)

报错信息：

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The rois_batch_size and imgs batch_size must be the same. But received rois_batch_size = 1, batch_size = 2
  [Hint: Expected rois_batch_size == batch_size, but received rois_batch_size:1 != batch_size:2.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/roi_align_op.h:198)
  [operator < roi_align > error]

2021-02-01 08:55:46 [INFO]	[TRAIN] Epoch=1/8, Step=2/2425, loss=2.146592, loss_cls=0.051102, loss_bbox=4.9e-05, loss_rpn_cls=0.702458, loss_rpn_bbox=1.392983, lr=0.000834, time_each_step=279.69s, eta=1674:15:54
2021-02-01 09:04:14 [INFO]	[TRAIN] Epoch=1/8, Step=4/2425, loss=1.314551, loss_cls=0.038078, loss_bbox=4.3e-05, loss_rpn_cls=0.668129, loss_rpn_bbox=0.608301, lr=0.000834, time_each_step=265.12s, eta=1586:54:34
2021-02-01 09:12:15 [INFO]	[TRAIN] Epoch=1/8, Step=6/2425, loss=1.436415, loss_cls=0.06391, loss_bbox=2.4e-05, loss_rpn_cls=0.636229, loss_rpn_bbox=0.736252, lr=0.000835, time_each_step=258.17s, eta=1545:7:52
2021-02-01 09:21:48 [INFO]	[TRAIN] Epoch=1/8, Step=8/2425, loss=1.179358, loss_cls=0.141976, loss_bbox=0.000116, loss_rpn_cls=0.581307, loss_rpn_bbox=0.455957, lr=0.000836, time_each_step=265.03s, eta=1586:5:0
之后报错。

**Comment by jiangjiajun** [comment]
可以上传下你的数据集和训练代码吗？我们这边来定位下原因
