### ISSUE TITLE
实力分割数据转换错误

### ISSUE THREAD

**Issue by Gaoang112** [PaddlePaddle/PaddleX#480]
教程中 创建保存目录D:\dataset_seg  而给的代码为 --save_dir D:\dataset_coco 且在执行中报错PermissionError: [Errno 13] Permission denied: '../data_coco' 
应该怎样进行转换呢

**Comment by Gaoang112** [comment]
paddlex --data_conversion --source labelme --to MSCOCO --pics ../MyDataset/PEGImages/ --annotations ../MyDataset/Annotations/ --save_dir ../data_coco 
Traceback (most recent call last):
  File "/home/ga/anaconda3/envs/paddlex/bin/paddlex", line 8, in <module>
    sys.exit(main())
  File "/home/ga/anaconda3/envs/paddlex/lib/python3.7/site-packages/paddlex/command.py", line 220, in main
    os.makedirs(args.save_dir)
  File "/home/ga/anaconda3/envs/paddlex/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '../data_coco'

**Comment by jiangjiajun** [comment]
这个是权限问题，因为在导出数据时，需要创建--save_dir指定的目录，如若没有权限，则会出现上面的错误，请确认你的帐户权限

**Comment by Gaoang112** [comment]
谢谢您的帮助
