### ISSUE TITLE
deploy predictor Trt动态shape推理出问题

### ISSUE THREAD

**Issue by jedibobo** [PaddlePaddle/PaddleX#512]
问题类型：模型部署
**问题描述**  
在deploy.py中加入这几行后
![image](https://user-images.githubusercontent.com/44748473/104318441-61028d80-551a-11eb-9777-577d0cbfab43.png)
推理时就会出问题：

Traceback (most recent call last):
  File "infer.py", line 24, in <module>
    result = model.predict(img_name,eval_transforms)
  File "/home/liuyibo/envs/paddle/lib/python3.7/site-packages/paddlex/deploy.py", line 287, in predict
    im_info=im_info)
  File "/home/liuyibo/envs/paddle/lib/python3.7/site-packages/paddlex/deploy.py", line 220, in postprocess
    true_topk = min(self.num_classes, topk)
TypeError: '<' not supported between instances of 'Compose' and 'int'

但是我修改paddle inference demo的推理脚本用动态shape有正确的结果。
个人推测时paddlex的问题。
麻烦了。
推理代码：

import paddlex as pdx
from paddlex.cls import transforms
import os
import time
test_jpg = '1.jpg'
eval_transforms = transforms.Compose([
    transforms.Normalize()
])

#model = pdx.load_model('inference_model/RM-resnet18-nofixed/')
model=pdx.deploy.Predictor('inference_model/RM-resnet18/',use_gpu=True,use_trt=True,use_glog=False,memory_optimize=True)
test_num=3
path="./"+str(test_num)

num=0
count=0
for root,dirs,files in os.walk(path):
    for file in files:
        num+=1
        img_name = root + '/' + file
        start=time.time()
        result = model.predict(img_name,eval_transforms)
        end=time.time()
        print("fps: ",1/(end-start))

        
        #print("Predict Result: ", result)
        #print(result[0]['category'],type(result[0]['category']))
        if int(result[0]['category'])==test_num:
            count+=1
print("precision:",count/num)

需求：因为输出确实不固定，是由目标检测结果传过来的。但是resize的结果我测试发现精度下降明显。。
========================  
环境：
GPU:3090
CUDA:11
TRT:7
PaddlePaddle:2.0.0-rc0 自己全流程编译的有trt支持
paddlex：1.2.8

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by jedibobo** [comment]
报错的deploy.py里面的true_topk强行改成1（符合我的需求下）勉强可用，但是中间会有这个错误。

E0112 13:26:17.973011  2512 helper.h:78] Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]

**Comment by jiangjiajun** [comment]
```
需求：因为输出确实不固定，是由目标检测结果传过来的。但是resize的结果我测试发现精度下降明显。。
```
@jedibobo 你好，你这里提到的精度明显下降，麻烦说明下具体是指什么场景下下降。
例如，当前使用的是FasterRCNN-ResNet18模型，在普通导出和部署的流程中，精度为80%。当使用fix_input_shape固定输入shape后，使用TensorRT预测，精度下降至XX%

关于固定shape导出后精度变化的几点说明

1. 如果你使用的是pip安装的paddlex，麻烦请安装一下github最新的代码，再重新使用fix_input_shape导出，因为此前我们发现当fix_input_shape时，导出的模型存在预测偏差问题（新版本我们会在本周发布）
2. 如果是分类模型，是否指定fix_input_shape，导出模型的精度不会有变化

**Comment by jedibobo** [comment]
> ```
> 需求：因为输出确实不固定，是由目标检测结果传过来的。但是resize的结果我测试发现精度下降明显。。
> ```
> 
> @jedibobo 你好，你这里提到的精度明显下降，麻烦说明下具体是指什么场景下下降。
> 例如，当前使用的是FasterRCNN-ResNet18模型，在普通导出和部署的流程中，精度为80%。当使用fix_input_shape固定输入shape后，使用TensorRT预测，精度下降至60%
> 
> 关于固定shape导出后精度变化的几点说明
> 
> 1. 如果你使用的是pip安装的paddlex，麻烦请安装一下github最新的代码，再重新使用fix_input_shape导出，因为此前我们发现当fix_input_shape时，导出的模型存在预测偏差问题（新版本我们会在本周发布）
> 2. 如果是分类模型，是否指定fix_input_shape，导出模型的精度不会有变化

确实是分类模型出的问题，我发现精度下降是我预处理的锅（用paddlex对比了一下）。想提的issue是直接在deploy.py加入那几行动态shape配置的代码推理分类模型会有问题（用上面的脚本），我被迫把topk赋成1可以用。
