### ISSUE TITLE
为何出现list out of range

### ISSUE THREAD

**Issue by leo123-cell** [PaddlePaddle/PaddleX#515]
在设置完模型参数后，刚开始训练模型即出现该错误，请问各位大佬这是什么问题呢？
Process Process-1:8:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 62, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 171, in train
  File "paddlexui\pms\model_tasks\train\detection.py", line 104, in build_voc_datasets
  File "site-packages\paddlex-1.1.5-py3.7.egg\paddlex\cv\datasets\voc.py", line 146, in __init__
IndexError: list index out of range

**Comment by jiangjiajun** [comment]
应该是某个数据的标注文件xml中的目标框里，少了name这个字段导致， 建议检查一下数据 https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/datasets/voc.py#L146

**Comment by leo123-cell** [comment]
> 应该是某个数据的标注文件xml中的目标框里，少了name这个字段导致， 建议检查一下数据 https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/datasets/voc.py#L146

非常感谢您的回复，我检查了一下name字段没有缺失，请问还存在什么可能吗？我看了一下voc.py也没找到原因...

**Comment by jiangjiajun** [comment]
方便的话，使用如下代码检查下你的标注文件，请将下面代码保存为`check_ann.py`，然后在数据集目录下执行此Python代码，如在目录`D:\workspace\datasets\D0002`下执行，看代码在检查过程中，是在哪个标注文件下出的错误，如有检查出问题，也麻烦反馈一下给我们这边
```
import copy
import os
import os.path as osp
import random
import re
import numpy as np
from collections import OrderedDict
import xml.etree.ElementTree as ET

def read_xml(xml_file):
    tree = ET.parse(xml_file)
    pattern = re.compile('<object>', re.IGNORECASE)
    obj_match = pattern.findall(
        str(ET.tostringlist(tree.getroot())))
    if len(obj_match) == 0:
        return None
    obj_tag = obj_match[0][1:-1]
    objs = tree.findall(obj_tag)
    pattern = re.compile('<size>', re.IGNORECASE)
    size_tag = pattern.findall(
        str(ET.tostringlist(tree.getroot())))[0][1:-1]
    size_element = tree.find(size_tag)
    pattern = re.compile('<width>', re.IGNORECASE)
    width_tag = pattern.findall(
        str(ET.tostringlist(size_element)))[0][1:-1]
    im_w = float(size_element.find(width_tag).text)
    pattern = re.compile('<height>', re.IGNORECASE)
    height_tag = pattern.findall(
        str(ET.tostringlist(size_element)))[0][1:-1]
    im_h = float(size_element.find(height_tag).text)
    gt_bbox = np.zeros((len(objs), 4), dtype=np.float32)
    gt_class = np.zeros((len(objs), 1), dtype=np.int32)
    gt_score = np.ones((len(objs), 1), dtype=np.float32)
    is_crowd = np.zeros((len(objs), 1), dtype=np.int32)
    difficult = np.zeros((len(objs), 1), dtype=np.int32)
    for i, obj in enumerate(objs):
        pattern = re.compile('<name>', re.IGNORECASE)
        name_tag = pattern.findall(str(ET.tostringlist(obj)))[0][1:-1]
        cname = obj.find(name_tag).text.strip()
        pattern = re.compile('<difficult>', re.IGNORECASE)
        diff_tag = pattern.findall(str(ET.tostringlist(obj)))
        if len(diff_tag) == 0:
            _difficult = 0
        else:
            diff_tag = diff_tag[0][1:-1]
            try:
                _difficult = int(obj.find(diff_tag).text)
            except Exception:
                _difficult = 0
        pattern = re.compile('<bndbox>', re.IGNORECASE)
        box_tag = pattern.findall(str(ET.tostringlist(obj)))
        if len(box_tag) == 0:
            print(
                "There's no field '<bndbox>' in one of object, so this object will be ignored. xml file: {}".
                format(xml_file))
            continue
        box_tag = box_tag[0][1:-1]
        box_element = obj.find(box_tag)
        pattern = re.compile('<xmin>', re.IGNORECASE)
        xmin_tag = pattern.findall(
            str(ET.tostringlist(box_element)))[0][1:-1]
        x1 = float(box_element.find(xmin_tag).text)
        pattern = re.compile('<ymin>', re.IGNORECASE)
        ymin_tag = pattern.findall(
            str(ET.tostringlist(box_element)))[0][1:-1]
        y1 = float(box_element.find(ymin_tag).text)
        pattern = re.compile('<xmax>', re.IGNORECASE)
        xmax_tag = pattern.findall(
            str(ET.tostringlist(box_element)))[0][1:-1]
        x2 = float(box_element.find(xmax_tag).text)
        pattern = re.compile('<ymax>', re.IGNORECASE)
        ymax_tag = pattern.findall(
            str(ET.tostringlist(box_element)))[0][1:-1]
        y2 = float(box_element.find(ymax_tag).text)
        x1 = max(0, x1)
        y1 = max(0, y1)
        if im_w > 0.5 and im_h > 0.5:
            x2 = min(im_w - 1, x2)
            y2 = min(im_h - 1, y2)


train_list = 'train_list.txt'
val_list = 'val_list.txt'

with open(train_list) as f:
    for line in f:
        items = line.strip().split()
        assert len(items) == 2, "lenght of items must be 2"
        xml_file = items[1]
        print("check xml file: {}......".format(xml_file))
        read_xml(xml_file)

with open(val_list) as f:
    for line in f:
        items = line.strip().split()
        assert len(items) == 2, "lenght of items must be 2"
        xml_file = items[1]
        print("check xml file: {}".format(xml_file))
        read_xml(xml_file)
```
