### ISSUE TITLE
检测任务 transforms.ComposedYOLOv3Transforms 推理异常

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleX#528]
第一次用paddlex不是很熟悉，ppyolo检测模型，使用transforms.ComposedYOLOv3Transforms增强，训练和验证没有问题，但是推理数据增强这一步报错。

训练代码
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from paddlex.det import transforms
import paddlex as pdx

train_transforms = transforms.Compose([transforms.ComposedYOLOv3Transforms("train")])
eval_transforms = transforms.Compose([transforms.ComposedYOLOv3Transforms("eval")])

train_dataset = pdx.datasets.CocoDetection(
    data_dir='/home/aistudio/data/data67498/DatasetId_152881_1610856374/Images',
    ann_file='/home/aistudio/data/data67498/DatasetId_152881_1610856374/train.json',
    transforms=train_transforms,
    num_workers=4,
    buffer_size=64,
    parallel_method='process',
    shuffle=True)
eval_dataset = pdx.datasets.CocoDetection(
    data_dir='/home/aistudio/data/data67498/DatasetId_152881_1610856374/Images',
    ann_file='/home/aistudio/data/data67498/DatasetId_152881_1610856374/val.json',
    transforms=eval_transforms)

num_classes = len(train_dataset.labels)

model = pdx.det.PPYOLO(num_classes=num_classes)

model.train(
    num_epochs=200,
    save_interval_epochs=10,
    train_dataset=train_dataset,
    train_batch_size=16,
    eval_dataset=eval_dataset,
    learning_rate=0.000125,
    lr_decay_epochs=[25],
    save_dir='output/ppyolo',
    use_vdl=True)

```

推理代码
```python
import paddlex as pdx
from paddlex.det import transforms

model = pdx.load_model('output/ppyolo/epoch_13')
image_name = '/home/aistudio/data/data67498/DatasetId_152881_1610856374/Images/1.png'

transforms = transforms.Compose([transforms.ComposedYOLOv3Transforms()])

result = model.predict(image_name, transforms=transforms)
print(result)
pdx.det.visualize(image_name, result, threshold=0.001, save_dir='./output/plane_lg')
```

训练生成的 model.yml
```shell
Model: PPYOLO
Transforms:
- ComposedYOLOv3Transforms:
    batch_transforms: null
    transforms:
    - !!python/object:paddlex.cv.transforms.det_transforms.Resize
      interp: CUBIC
      target_size: 608
    - !!python/object:paddlex.cv.transforms.det_transforms.Normalize
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
    use_mixup: false
_Attributes:
  eval_metrics:
    bbox_mmap: 6.528627542125153e-08
  fixed_input_shape: null
  labels:
  - "\u524D\u8D77\u843D\u67B6"
  model_type: detector
  num_classes: 1
_init_params:
  anchor_masks: null
  anchors: null
  backbone: ResNet50_vd_ssld
  ignore_threshold: 0.7
  input_channel: 3
  label_smooth: false
  nms_iou_threshold: 0.45
  nms_keep_topk: 100
  nms_score_threshold: 0.01
  nms_topk: 1000
  num_classes: 1
  scale_x_y: 1.05
  train_random_shapes:
  - 320
  - 352
  - 384
  - 416
  - 448
  - 480
  - 512
  - 544
  - 576
  - 608
  use_coord_conv: true
  use_drop_block: true
  use_iou_aware: true
  use_iou_loss: true
  use_matrix_nms: true
  use_spp: true
  with_dcn_v2: true
completed_epochs: 2
status: Normal
version: 1.3.3
```

推理报错
```shell
python infer.py 
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/iou_aware.py:64
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/iou_aware.py:40
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
W0118 12:09:08.139017   529 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0118 12:09:08.143851   529 device_context.cc:330] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py:2216: UserWarning: This list is not set, Because of Paramerter not found in program. There are: create_parameter_0.w_0 create_parameter_1.w_0 create_parameter_2.w_0 create_parameter_3.w_0 create_parameter_4.w_0 create_parameter_5.w_0 create_parameter_6.w_0 create_parameter_7.w_0 create_parameter_8.w_0 create_parameter_9.w_0 create_parameter_10.w_0 create_parameter_11.w_0 create_parameter_12.w_0 create_parameter_13.w_0 create_parameter_14.w_0 create_parameter_15.w_0 create_parameter_16.w_0 create_parameter_17.w_0 create_parameter_18.w_0 create_parameter_19.w_0 create_parameter_20.w_0 create_parameter_21.w_0 create_parameter_22.w_0 create_parameter_23.w_0 create_parameter_24.w_0 create_parameter_25.w_0 create_parameter_26.w_0 create_parameter_27.w_0 create_parameter_28.w_0 create_parameter_29.w_0 create_parameter_30.w_0 create_parameter_31.w_0 create_parameter_32.w_0 create_parameter_33.w_0 create_parameter_34.w_0 create_parameter_35.w_0 create_parameter_36.w_0 create_parameter_37.w_0 create_parameter_38.w_0 create_parameter_39.w_0 create_parameter_40.w_0 create_parameter_41.w_0 create_parameter_42.w_0 create_parameter_43.w_0 create_parameter_44.w_0 create_parameter_45.w_0 create_parameter_46.w_0 create_parameter_47.w_0
  format(" ".join(unused_para_list)))
Traceback (most recent call last):
  File "infer.py", line 4, in <module>
    model = pdx.load_model('output/ppyolo/epoch_13')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 110, in load_model
    model.model_type, info['Transforms'], to_rgb)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/__init__.py", line 38, in build_transforms
    getattr(T, op_name)(**op_attr)
TypeError: __init__() got an unexpected keyword argument 'batch_transforms'
```

看起来是infer的时候读取那个model.yml有点问题，yml是生成的没做过修改。训练和验证没有问题，就推理报错

**Comment by FlyingQianMM** [comment]
请先不要使用ComposedYOLOv3Transforms，目前ComposedYOLOv3Transforms没有在维护了。按照tutorial给出的方式组合使用transforms https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/object_detection/ppyolo.py#L15
![image](https://user-images.githubusercontent.com/22235422/104883923-73f4e200-59a0-11eb-88ee-f41e87dc6818.png)

**Comment by linhandev** [comment]
那建议在代码注释里写一下，或者报个 废弃warning 之类的。看代码这个用起来最简单就使了
