### ISSUE TITLE
训练icdar2015 失败---Fail to allocate CPU memory: size

### ISSUE THREAD

**Issue by mybrew** [PaddlePaddle/PaddleX#537]
问题类型：模型训练  
**问题描述**  

WIN7 64位，8G内存。对应的train_data\icdar2015\text_localization 都有了。
执行训练失败。另外请问CPU_NUM怎么设置为4？多谢。

E:\PaddleOCR\PaddleOCR>python tools/train.py -c configs/det/det_mv3_db.yml -o Gl
obal.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained/
2021-01-21 13:28:32,848-INFO: {'Global': {'debug': False, 'algorithm': 'DB', 'us
e_gpu': False, 'epoch_num': 1200, 'log_smooth_window': 20, 'print_batch_step': 2
, 'save_model_dir': './output/det_db/', 'save_epoch_step': 200, 'eval_batch_step
': [4000, 5000], 'train_batch_size_per_card': 16, 'test_batch_size_per_card': 16
, 'image_shape': [3, 640, 640], 'reader_yml': './configs/det/det_db_icdar15_read
er.yml', 'pretrain_weights': './pretrain_models/MobileNetV3_large_x0_5_pretraine
d/', 'checkpoints': None, 'save_res_path': './output/det_db/predicts_db.txt', 's
ave_inference_dir': None, 'infer_img': None}, 'Architecture': {'function': 'ppoc
r.modeling.architectures.det_model,DetModel'}, 'Backbone': {'function': 'ppocr.m
odeling.backbones.det_mobilenet_v3,MobileNetV3', 'scale': 0.5, 'model_name': 'la
rge'}, 'Head': {'function': 'ppocr.modeling.heads.det_db_head,DBHead', 'model_na
me': 'large', 'k': 50, 'inner_channels': 96, 'out_channels': 2}, 'Loss': {'funct
ion': 'ppocr.modeling.losses.det_db_loss,DBLoss', 'balance_loss': True, 'main_lo
ss_type': 'DiceLoss', 'alpha': 5, 'beta': 10, 'ohem_ratio': 3}, 'Optimizer': {'f
unction': 'ppocr.optimizer,AdamDecay', 'base_lr': 0.001, 'beta1': 0.9, 'beta2':
0.999}, 'PostProcess': {'function': 'ppocr.postprocess.db_postprocess,DBPostProc
ess', 'thresh': 0.3, 'box_thresh': 0.6, 'max_candidates': 1000, 'unclip_ratio':
1.5}, 'TrainReader': {'reader_function': 'ppocr.data.det.dataset_traversal,Train
Reader', 'process_function': 'ppocr.data.det.db_process,DBProcessTrain', 'num_wo
rkers': 8, 'img_set_dir': './train_data/icdar2015/text_localization/', 'label_fi
le_path': './train_data/icdar2015/text_localization/train_icdar2015_label.txt'},
 'EvalReader': {'reader_function': 'ppocr.data.det.dataset_traversal,EvalTestRea
der', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', 'img_set_di
r': './train_data/icdar2015/text_localization/', 'label_file_path': './train_dat
a/icdar2015/text_localization/test_icdar2015_label.txt', 'test_image_shape': [73
6, 1280]}, 'TestReader': {'reader_function': 'ppocr.data.det.dataset_traversal,E
valTestReader', 'process_function': 'ppocr.data.det.db_process,DBProcessTest', '
img_set_dir': './train_data/icdar2015/text_localization/', 'label_file_path': '.
/train_data/icdar2015/text_localization/test_icdar2015_label.txt', 'do_eval': Tr
ue}}
3 640 640
2021-01-21 13:28:33,646-INFO: If regularizer of a Parameter has been set by 'flu
id.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay
, regularization_coeff=0.000000] in Optimizer will not take effect, and it will
only be applied to other Parameters!
3 640 640
./train_data/icdar2015/text_localization/train_icdar2015_label.txt
2021-01-21 13:28:36,040-INFO: places would be ommited when DataLoader is not ite
rable
2021-01-21 13:28:36,243-INFO: Loading parameters from ./pretrain_models/MobileNe
tV3_large_x0_5_pretrained/...
2021-01-21 13:28:36,244-WARNING: ./pretrain_models/MobileNetV3_large_x0_5_pretra
ined/.pdparams not found, try to load model file saved with [ save_params, save_
persistables, save_vars ]
2021-01-21 13:28:36,458-INFO: Finish initing model from ./pretrain_models/Mobile
NetV3_large_x0_5_pretrained/
2021-01-21 13:28:36,458-INFO: During the training process, after the 4000th iter
ation, an evaluation is run every 5000 iterations
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment vari
able list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) th
e program may be faster.

export CPU_NUM=4 # for example, set CPU_NUM as number of physical CPU core which
 is 4.

!!! The default number of CPU_NUM=1.
W0121 13:28:36.502846  9384 build_strategy.cc:170] fusion_group is not enabled f
or Windows/MacOS now, and only effective when running with CUDA GPU.
multiprocess is not fully compatible with Windows.num_workers will be 1.
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 104, in main
    program.train_eval_det_run(config, exe, train_info_dict, eval_info_dict)
  File "E:\PaddleOCR\PaddleOCR\tools\program.py", line 302, in train_eval_det_ru
n
    return_numpy=False)
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 107
1, in run
    six.reraise(*sys.exc_info())
  File "E:\Python\Python37\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 106
6, in run
    return_merged=return_merged)
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 116
7, in _run_impl
    return_merged=return_merged)
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 879
, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 26
10, in append_op
    attrs=kwargs.get("attrs", None))
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\layer_helper.py", line
 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "E:\Python\Python37\lib\site-packages\paddle\fluid\layers\nn.py", line 29
38, in conv2d
    "data_format": data_format,
  File "E:\PaddleOCR\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3.py", li
ne 155, in conv_bn_layer
    bias_attr=False)
  File "E:\PaddleOCR\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3.py", li
ne 249, in residual_unit
    res_last_bn_init=True)
  File "E:\PaddleOCR\PaddleOCR\ppocr\modeling\backbones\det_mobilenet_v3.py", li
ne 116, in __call__
    name='conv' + str(i + 2))
  File "E:\PaddleOCR\PaddleOCR\ppocr\modeling\architectures\det_model.py", line
139, in __call__
    conv_feas = self.backbone(image)
  File "E:\PaddleOCR\PaddleOCR\tools\program.py", line 175, in build
    dataloader, outputs = model(mode=mode)
  File "tools/train.py", line 52, in main
    config, train_program, startup_program, mode='train')
  File "tools/train.py", line 135, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Fail to allocate CPU memory: size = 259389824 .
  [Hint: p should not be null.] at (D:\1.8.4\paddle\paddle\fluid\memory\detail\s
ystem_allocator.cc:61)
  [operator < conv2d > error]

**Comment by jiangjiajun** [comment]
看日志是在训练OCR模型过程中报错，可在此提交issue反馈 https://github.com/PaddlePaddle/PaddleOCR
