### ISSUE TITLE
运行下载示例模型时出错

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/PaddleX#544]
问题类型：模型训练  
**问题描述**  
报错信息显示预训练权重与实际不匹配，但不知道咋改。。。。
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
![image](https://user-images.githubusercontent.com/65533171/105824126-df990980-5fb5-11eb-90cf-37d6fffd764d.png)
![image](https://user-images.githubusercontent.com/65533171/105824254-02c3b900-5fb6-11eb-9aa8-5f01f8a991c6.png)

错误日志
2021-01-26 16:50:16,718-WARNING: D:\迅雷下载\passlex_project\pretrain\MobileNetV3_large_x1_0_ssld_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
D:\PaddleX\PaddleX\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
Process Process-1:8:
Traceback (most recent call last):
  File "site-packages\paddle\fluid\io.py", line 1891, in load_program_state
  File "site-packages\paddle\fluid\io.py", line 805, in load_vars
  File "site-packages\paddle\fluid\executor.py", line 1071, in run
  File "site-packages\six.py", line 703, in reraise
  File "site-packages\paddle\fluid\executor.py", line 1066, in run
  File "site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
  File "site-packages\paddle\fluid\executor.py", line 1229, in _run_program
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "site-packages\paddle\fluid\framework.py", line 2610, in append_op
  File "site-packages\paddle\fluid\io.py", line 785, in load_vars
  File "site-packages\paddle\fluid\io.py", line 1891, in load_program_state
  File "site-packages\paddlex\utils\utils.py", line 292, in load_pretrain_weights
  File "site-packages\paddlex\cv\models\base.py", line 262, in net_initialize
  File "site-packages\paddlex\cv\models\classifier.py", line 195, in train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "multiprocessing\process.py", line 99, in run
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\spawn.py", line 118, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 43, in _freeze_support
  File "paddlexui\PaddleXCore.py", line 39, in main
  File "paddlexui\PaddleX.py", line 18, in <module>

----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file D:\迅雷下载\passlex_project\pretrain\MobileNetV3_large_x1_0_ssld_pretrained\conv1_weights, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (D:\1.8.4\paddle\paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "site-packages\paddlex\cv\models\classifier.py", line 195, in train
  File "site-packages\paddlex\cv\models\base.py", line 262, in net_initialize
  File "site-packages\paddlex\utils\utils.py", line 292, in load_pretrain_weights
  File "site-packages\paddle\fluid\io.py", line 1894, in load_program_state
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars

**Comment by jiangjiajun** [comment]
你好，问题已通过邮件回复。

1. 预训练模型参数中，部分参数不匹配是正常的现象，由于实际训练时的类别数和预训练模型的类别数不同，所以会有部分参数不匹配会被舍弃掉。
2. 当前从err.log中看，出错的原因是由于workspace被设置在了中文路径下的原因（当前为D:\迅雷下载\passlex_project\)，因此将workspace设置在纯英文路径下（不包含空格）即可解决。
