### ISSUE TITLE
macOS 无法启动MAC Remote GUI

### ISSUE THREAD

**Issue by snowind** [PaddlePaddle/PaddleX#546]
macOS: big Sur 11.1 

根据下面这个指导，
https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/gui/restful/introduction.md

下载了Mac版本的Remote GUI应用 PaddleX.app ， 启动时无法出现界面即退出。

**Comment by lailuboy** [comment]
MAC下主要是权限导致，首先在安全->通用中设置信任下载的包，然后参考下载包中的readme.txt说明执行sudo xattr -r -d com.apple.quarantine PaddleX.app语句后再运行。

**Comment by snowind** [comment]
将macOS remote GUI 包解压到当前用户目录下， ~/macos_paddlex_remote_gui/
有2个文件：
PaddleX.app 
使用教程.txt  

执行： 
cd  ~/macos_paddlex_remote_gui/
sudo xattr -r -d com.apple.quarantine PaddleX.app
sudo xattr -r ~/macos_paddlex_remote_gui/ 

再次运行 PaddleX.app 仍然不能启动。

~/.paddlex 目录已经删除。

**Comment by lailuboy** [comment]
有什么错误提示？
在命令行中open PaddleX.app 看看提示是什么

**Comment by naah69** [comment]
> 有什么错误提示？
> 在命令行中open PaddleX.app 看看提示是什么

macOS 10.14.6也出现打开闪退的问题，安装上面的方案，依旧无法解决

PaddleX Remote GUI是针对PaddleX RESTful开发的可视化客服端 
![image](https://user-images.githubusercontent.com/25682169/106084516-77832880-6159-11eb-9766-5119fae6114f.png)
![image](https://user-images.githubusercontent.com/25682169/106084545-823dbd80-6159-11eb-8e84-ec25db0f1074.png)

**Comment by lailuboy** [comment]
在/Users/xxx/.paddlex_gui/目录下的log看打印什么。
还有下载非remote 的macOS GUI 包看能不能运行。

**Comment by naah69** [comment]
paddlex.log
```
2021-01-28 11:55:23,120 applogger.py[line:66] INFO:Log init! with PID: 82421
2021-01-28 11:55:23,726 frame.py[line:2909] INFO:PaddleXApp OnInit
2021-01-28 11:55:23,726 resource.py[line:77] INFO:ResourceManager::create managers
2021-01-28 11:55:23,781 PaddleXCore.py[line:47] INFO:send create resource msg
2021-01-28 11:55:23,781 PaddleXCore.py[line:49] INFO:PaddleX start...
2021-01-28 11:55:23,781 utils.py[line:170] INFO:init_app_resource init_server
2021-01-28 11:55:23,781 utils.py[line:172] INFO:读取项目配置文件
/Users/naah/Downloads/PaddleX_Remote_GUI 1/PaddleX.app/Contents/MacOS/common/resource.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "paddlexui/PaddleX.py", line 19, in <module>
  File "paddlexui/PaddleXCore.py", line 52, in main
  File "paddlexui/main/utils.py", line 183, in init_app_resource
  File "configparser.py", line 1198, in set
  File "configparser.py", line 900, in set
configparser.NoSectionError: No section: 'USERCFG'

```

**Comment by syyxsxx** [comment]
@naah69 
你好，该问题已经修复，重新下载GUI即可

**Comment by naah69** [comment]
好的，可以使用了
