### ISSUE TITLE
使用Paddle X训练果蔬识别出现错误

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleX#547]
错误日志为：
This log file path is D:\test\数据集\projects\P0003\T0008\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=16 # for example, set CPU_NUM as number of physical CPU core which is 16.

!!! The default number of CPU_NUM=1.
2021-01-26 23:12:43,095-WARNING: D:\test\数据集\pretrain\MobileNetV2_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
D:\PaddleX\PaddleX\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
Process Process-1:2:
Traceback (most recent call last):
  File "site-packages\paddle\fluid\io.py", line 1891, in load_program_state
  File "site-packages\paddle\fluid\io.py", line 805, in load_vars
  File "site-packages\paddle\fluid\executor.py", line 1071, in run
  File "site-packages\six.py", line 703, in reraise
  File "site-packages\paddle\fluid\executor.py", line 1066, in run
  File "site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
  File "site-packages\paddle\fluid\executor.py", line 1229, in _run_program
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "site-packages\paddle\fluid\framework.py", line 2610, in append_op
  File "site-packages\paddle\fluid\io.py", line 785, in load_vars
  File "site-packages\paddle\fluid\io.py", line 1891, in load_program_state
  File "site-packages\paddlex\utils\utils.py", line 292, in load_pretrain_weights
  File "site-packages\paddlex\cv\models\base.py", line 262, in net_initialize
  File "site-packages\paddlex\cv\models\classifier.py", line 195, in train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "multiprocessing\process.py", line 99, in run
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\spawn.py", line 118, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 43, in _freeze_support
  File "paddlexui\PaddleXCore.py", line 39, in main
  File "paddlexui\PaddleX.py", line 18, in <module>

----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file D:\test\数据集\pretrain\MobileNetV2_pretrained\conv1_1_weights, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (D:\1.8.4\paddle\paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "site-packages\paddlex\cv\models\classifier.py", line 195, in train
  File "site-packages\paddlex\cv\models\base.py", line 262, in net_initialize
  File "site-packages\paddlex\utils\utils.py", line 292, in load_pretrain_weights
  File "site-packages\paddle\fluid\io.py", line 1894, in load_program_state
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars

**Comment by lailuboy** [comment]
工作区和程序目录需要放到英文目录

**Comment by gaorui999** [comment]
> 工作区和程序目录需要放到英文目录

think you~

**Comment by gaorui999** [comment]
thanks
