### ISSUE TITLE
PaddleX启动报错，训练报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleX#550]
启动提示错误
Traceback (most recent call last):
  File "paddlexui\pms\core.py", line 1755, in execute
  File "paddlexui\pms\core.py", line 710, in get_task_params
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\test\\数据集\\projects\\P0001\\T0004\\params.pkl'
During handling of the above exception, another exception occurred:
训练提示错误日志
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file D:\test\数据集\datasets\D0001\rose\1666341535_99c6f7509f_n.jpg!
Exception in thread Thread-20:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file D:\test\数据集\datasets\D0001\daisy\34266042310_9c1abd8e11_n.jpg!
Exception in thread Thread-22:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file D:\test\数据集\datasets\D0001\tulip\5635347336_bc1400e939_n.jpg!

Exception in thread Thread-24:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file D:\test\数据集\datasets\D0001\daisy\5058708968_8bdcd29e63_n.jpg!

Exception in thread Thread-19:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file D:\test\data\datasets\D0001\sunflower\5970300143_36b42437de_n.jpg!

**Comment by jiangjiajun** [comment]
根据这里的提示，这张图片`D:\test\data\datasets\D0001\sunflower\5970300143_36b42437de_n.jpg`无法使用opencv进行加载读取

建议检查下图片文件是否可以使用opencv读取

**Comment by hy-shadow** [comment]
路径不要包含中文
