### ISSUE TITLE
paddleX示例项目模型训练时训练失败

### ISSUE THREAD

**Issue by Liubaiwen-seu** [PaddlePaddle/PaddleX#552]
问题类型：模型训练  
**问题描述**  
在paddleX客户端对示例项目进行模型训练时出错，

UnavailableError: Load operator fail to open file D:\车道线检测\pretrain\MobileNetV2_pretrained\conv1_1_weights, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (D:\1.8.4\paddle\paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "site-packages\paddlex\cv\models\classifier.py", line 195, in train
  File "site-packages\paddlex\cv\models\base.py", line 262, in net_initialize
  File "site-packages\paddlex\utils\utils.py", line 292, in load_pretrain_weights
  File "site-packages\paddle\fluid\io.py", line 1894, in load_program_state
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars
![image](https://user-images.githubusercontent.com/68486034/106081239-8070fb80-6153-11eb-964e-4d7c0d68e613.png)

请问这个的错误是什么问题呢？
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by jiangjiajun** [comment]
Hi，你好，PaddleX在训练过程中，所有路径（包括workspace)都不能出现中文或空格，当前你这里出错的原因是由于出现了中文路径
