### ISSUE TITLE
训练失败，无法使用GPU训练，RuntimeError: parallel_for failed: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by sangyuxiaowu** [PaddlePaddle/PaddleX#569]
问题类型：PaddleX可视化客户端  
**问题描述** 

客户端 1.1.7

无法使用GPU开始训练，后面换成CPU可以训练了

### 电脑概览

电脑型号  THUNDEROBOT Z490 Phantom Gaming 4
操作系统  Microsoft Windows 10 专业版 (64位)
CPU  (英特尔)Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz(3601 MHz)
主板  THUNDEROBOT Z490 Phantom Gaming 4
内存  32.00 GB (   2400 MHz)
主硬盘  1020 GB (  未知型号 已使用时间: 未知)
显卡  NVIDIA GeForce RTX 3070 (4095 MB)
显示器  DELL DELL P2417H 32位真彩色 32Hz
声卡  Realtek High Definition Audio
网卡  Intel(R) Wi-Fi 6 AX201 160MHz

```
Fri Feb 05 21:28:19 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 457.51       Driver Version: 457.51       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070   WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   39C    P8    11W / 220W |    296MiB /  8192MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1376    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      1384    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      1436    C+G   ...bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A      7172    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      8652    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9660    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     10312    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A     10384    C+G   ...nputApp\TextInputHost.exe    N/A      |
+-----------------------------------------------------------------------------+
```

### nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

### python

Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32

### 错误日志 err.log

```
D:\PaddleX\PaddleX\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
Process Process-1:3:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 216, in train
  File "site-packages\paddlex\cv\models\ppyolo.py", line 350, in train
  File "site-packages\paddlex\cv\models\base.py", line 244, in net_initialize
  File "site-packages\paddle\fluid\executor.py", line 1071, in run
  File "site-packages\six.py", line 703, in reraise
  File "site-packages\paddle\fluid\executor.py", line 1066, in run
  File "site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
  File "site-packages\paddle\fluid\executor.py", line 1229, in _run_program
RuntimeError: parallel_for failed: no kernel image is available for execution on the device
```

===================================  

请在这里描述您在使用GUI过程中的问题

**Comment by FlyingQianMM** [comment]
抱歉，目前框架暂时不支持30系列的显卡，预计4月份发版2.1版本就能支持30显卡了。

**Comment by sangyuxiaowu** [comment]
> 抱歉，目前框架暂时不支持30系列的显卡，预计4月份发版2.1版本就能支持30显卡了。

好的，谢谢，明白了

**Comment by zhaojiafu** [comment]
> 抱歉，目前框架暂时不支持30系列的显卡，预计4月份发版2.1版本就能支持30显卡了。

你好 现在支持了吗？

**Comment by zkailinzhang** [comment]
现在安装的 paddlepaddle-gpu      2.1.0.post101  ，也不支持呢，GTX3090  ubuntu18，还是报这样的错误
gaussian_random raises an exception thrust::system::system_error, parallel_for failed: no kernel image is available for execution on the device
