### ISSUE TITLE
paddlx进行分类训练时出错，预训练模型无法下载？

### ISSUE THREAD

**Issue by yangkerrr** [PaddlePaddle/PaddleX#570]
问题类型：模型训练  
**问题描述**  

====================  
运行环境：
paddlehub           2.0.0
paddlenlp           2.0.0rc1
paddlepaddle-gpu    2.0.0.post100
paddleseg           2.0.0rc0
paddleslim          1.1.1
paddlex             1.3.4

出错信息：
2021-02-06 13:38:12 [INFO]      Starting to read file list from dataset...
2021-02-06 13:38:13 [INFO]      17939 samples in file imgs/train_list.txt
2021-02-06 13:38:13 [INFO]      Starting to read file list from dataset...
2021-02-06 13:38:13 [INFO]      2243 samples in file imgs/val_list.txt
2021-02-06 13:38:25 [INFO]      Connecting PaddleHub server to get pretrain weights...
2021-02-06 13:38:25 [ERROR]     Couldn't download pretrain weight, you can download it manualy from https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar (decompress the file if it is a compressed file), and set pretrain weights by your self
Traceback (most recent call last):
    hub.download(backbone, save_path=new_save_dir)
  File "H:\Anaconda\envs\paddle\lib\site-packages\paddlehub\utils\paddlex.py", line 43, in download
    resources = module_server.search_resouce(name=name, version=version, type='Model')
AttributeError: 'HubServer' object has no attribute 'search_resouce'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:/imgs/run.py", line 47, in <module>
    use_vdl=True)
  File "H:\Anaconda\envs\paddle\lib\site-packages\paddlex\cv\models\classifier.py", line 195, in train
    resume_checkpoint=resume_checkpoint)
  File "H:\Anaconda\envs\paddle\lib\site-packages\paddlex\cv\models\base.py", line 243, in net_initialize
    pretrain_weights, class_name, backbone, pretrain_dir)
  File "H:\Anaconda\envs\paddle\lib\site-packages\paddlex\cv\models\utils\pretrain_weights.py", line 239, in get_pretrain_weights
    "Unexpected error, please make sure paddlehub >= 1.6.2")
Exception: Unexpected error, please make sure paddlehub >= 1.6.2

**Comment by FlyingQianMM** [comment]
先暂时手动下载预训练模型 https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar ，解压后将所在路径设置给model.train()的参数pretrain_weights

**Comment by yangkerrr** [comment]
是paddlehub2.0的问题，将paddlehub降级为1.8.2以上即可

**Comment by jiangjiajun** [comment]
升级PaddleX 1.3.5后即可

> 原因在于PaddleHub于2月5号新发布了2.0版本，对PaddlePaddle的要求是2.0，而当前你是在1.8.4的Paddle下
