### ISSUE TITLE
转换为openvino报错

### ISSUE THREAD

**Issue by zhuqiang00099** [PaddlePaddle/PaddleX#571]
问题类型：模型部署
**问题描述**  

========================  

转换为openvino模型的时候报错了，我看着好像paddle2onnx的时候就报错了。模型是paddlex自带的mobilenetv2训练的结果。下面是错误提示，大佬帮我看看是啥原因？难道是openvino环境没装好吗。
python converter.py --model_dir /home/zhuqiang/paddle_ifmodel/ifmodel --save_dir /home/zhuqiang/paddle_ifmodel/IRmodel --fixed_input_shape [224,224]
2021-02-05 20:08:52 [INFO]	Model already has fixed_input_shape with [224, 224]
W0205 20:08:52.817740 17823 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0205 20:08:52.821902 17823 device_context.cc:372] device: 0, cuDNN Version: 7.6.
2021-02-05 20:08:55 [INFO]	Model[MobileNetV2] loaded.
Traceback (most recent call last):
  File "converter.py", line 127, in <module>
    main()
  File "converter.py", line 123, in main
    export_openvino_model(model, args)
  File "converter.py", line 59, in export_openvino_model
    pdx.converter.export_onnx_model(model, onnx_save_file, 11)
  File "/home/zhuqiang/miniconda3/envs/base_py36/lib/python3.6/site-packages/paddlex/converter.py", line 283, in export_onnx_model
    opset_version=opset_version)
  File "/home/zhuqiang/miniconda3/envs/base_py36/lib/python3.6/site-packages/paddle2onnx/convert.py", line 73, in program2onnx
    target_vars, scope)
  File "/home/zhuqiang/miniconda3/envs/base_py36/lib/python3.6/site-packages/paddle2onnx/graph/paddle_graph.py", line 215, in build_from_program
    fetch_vars)
  File "/home/zhuqiang/miniconda3/envs/base_py36/lib/python3.6/site-packages/paddle2onnx/graph/paddle_graph.py", line 107, in __init__
    self.build_graph(program, parameters, feed_var_names, fetch_vars)
  File "/home/zhuqiang/miniconda3/envs/base_py36/lib/python3.6/site-packages/paddle2onnx/graph/paddle_graph.py", line 179, in build_graph
    self.add_input_node(feed_var_names, program.global_block())
  File "/home/zhuqiang/miniconda3/envs/base_py36/lib/python3.6/site-packages/paddle2onnx/graph/paddle_graph.py", line 133, in add_input_node
    for ipt in inputs:
TypeError: 'NoneType' object is not iterable

**Comment by syyxsxx** [comment]
@zhuqiang00099  您好，请确定paddle2onnx是否为0.4版本，paddlex是否为最新代码

**Comment by zhuqiang00099** [comment]
@syyxsxx 大佬牛逼，我刚看了是0.5的，换成0.4的立马好了，这是为啥啊？

**Comment by syyxsxx** [comment]
@zhuqiang00099 当前还没适配0.5版本，后续会尽快适配0.5版本

**Comment by zhuqiang00099** [comment]
@syyxsxx 可以可以，加油！
