### ISSUE TITLE
PaddleX训练时报错

### ISSUE THREAD

**Issue by hadano-269** [PaddlePaddle/PaddleX#572]
问题类型：模型训练  
报错信息
This log file path is E:\PaddleX\projects\P0014\T0027\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
Process Process-1:4:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 107, in train
  File "paddlexui\pms\model_tasks\train\classification.py", line 60, in build_datasets
  File "site-packages\paddlex\cv\datasets\imagenet.py", line 73, in __init__
Exception: A space is defined as the separator, but it exists in image or label name negative\ATT1408_Murder hornet.jpg 0
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by jiangjiajun** [comment]
你好，参与此issue回复 https://github.com/PaddlePaddle/PaddleX/issues/552#issuecomment-768758183

原因在于图片文件路径中出现了空格
