### ISSUE TITLE
模型裁剪 ai studio使用的高级版GPU环境但是还是使用CPU进行prune_train

### ISSUE THREAD

**Issue by axdo** [PaddlePaddle/PaddleX#608]
问题类型：模型部署
**问题描述**  

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。
模型裁剪 ai studio使用的高级版GPU环境但是还是使用CPU进行prune_train
![{2Z3ZD%XSQX{L(OX)%HIW`2](https://user-images.githubusercontent.com/46195295/109106117-25d6b980-776a-11eb-867e-1e9a0a750983.png) 
训练提示如下：
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.
export CPU_NUM=24 # for example, set CPU_NUM as number of physical CPU core which is 24.
!!! The default number of CPU_NUM=1.
代码如下：
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from paddlex.det import transforms
import paddlex as pdx

train_transforms = transforms.Compose([
    transforms.MixupImage(mixup_epoch=250),
    transforms.RandomDistort(),
    transforms.RandomExpand(),
    transforms.RandomCrop(),
    transforms.Resize(target_size=608, interp='RANDOM'),
    transforms.RandomHorizontalFlip(),
    transforms.Normalize(),
])

eval_transforms = transforms.Compose([
    transforms.Resize(
        target_size=608, interp='CUBIC'),
    transforms.Normalize(),
])

train_dataset = pdx.datasets.VOCDetection(
    data_dir='/home/aistudio/data/data71225/D0023',
    file_list='/home/aistudio/data/data71225/D0023/train_list.txt',
    label_list='/home/aistudio/data/data71225/D0023/labels.txt',
    transforms=train_transforms,
    shuffle=True)
eval_dataset = pdx.datasets.VOCDetection(
    data_dir='/home/aistudio/data/data71225/D0023',
    file_list='/home/aistudio/data/data71225/D0023al_list.txt',
    label_list='/home/aistudio/data/data71225/D0023/labels.txt',
    transforms=eval_transforms)

num_classes = len(train_dataset.labels)

model = pdx.det.YOLOv3(num_classes=num_classes, backbone='MobileNetV3_large')

model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    learning_rate=0.000125,
    lr_decay_epochs=[210, 240],
    pretrain_weights='output/yolov3_mobilenetv3_2x/best_model',
    save_dir='output/yolov3_mobilenetv3_2x_prune',
    sensitivities_file='./output/yolov3_mobilenetv3_2x.sensi.data',
    eval_metric_loss=0.05,
    use_vdl=True)
重新进入还是同样的问题!

**Comment by FlyingQianMM** [comment]
在AISTUDIO上使用1.8.4环境测试了下yolov3的剪裁，是可以正常使用GPU的。
![image](https://user-images.githubusercontent.com/22235422/109249870-8118b280-7823-11eb-94ae-888e329341d5.png)
试下在终端上运行过export CUDA_VISIBLE_DEVICES=0后再执行python yolov3_prune_train.py

**Comment by axdo** [comment]
> 在AISTUDIO上使用1.8.4环境测试了下yolov3的剪裁，是可以正常使用GPU的。
> ![image](https://user-images.githubusercontent.com/22235422/109249870-8118b280-7823-11eb-94ae-888e329341d5.png)
> 试下在终端上运行过export CUDA_VISIBLE_DEVICES=0后再执行python yolov3_prune_train.py

![image](https://user-images.githubusercontent.com/46195295/109274843-eafa8180-784e-11eb-8c34-d91245a59837.png)
我按照你的说法操作了 然后提示我需要paddle>1.8.5 <2.0 我pip install paddlepaddle==1.8.5之后又是那样了 请问咋回事

**Comment by FlyingQianMM** [comment]
可以把/opt/.../parl/utils/utils.py的74行assert注释掉，不影响使用。或者安装paddlepaddle_gpu 2.0.0试下。

**Comment by binglebai** [comment]
`aistudio@jupyter-661724-1563628:~$ python params_analysis.py
2021-03-02 15:30:06 [INFO]      Model[YOLOv3] loaded.
2021-03-02 15:30:06 [INFO]      Starting to read file list from dataset...
Traceback (most recent call last):
  File "params_analysis.py", line 11, in <module>
    transforms=model.eval_transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/datasets/imagenet.py", line 81, in __init__
    self.file_list.append([full_path, int(items[1])])
ValueError: invalid literal for int() with base 10: 'Annotations/0170.xml'`
在 ai studio 上尝试裁剪 出现这样的错误 请问要怎么处理呢？
