### ISSUE TITLE
 import paddlex报错

### ISSUE THREAD

**Issue by 1150xi** [PaddlePaddle/PaddleX#640]
``` python
# 设置使用0号GPU卡（如无GPU，执行此代码后仍然会使用CPU训练模型）
import matplotlib
matplotlib.use('Agg') 
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import paddlex as pdx
```
#### 报错日志
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-66560d19a88d> in <module>
      4 import os
      5 os.environ['CUDA_VISIBLE_DEVICES'] = '0'
----> 6 import paddlex as pdx

/opt/conda/lib/python3.6/site-packages/paddlex/__init__.py in <module>
     42 
     43 from .utils.utils import get_environ_info
---> 44 from . import cv
     45 from . import det
     46 from . import seg

/opt/conda/lib/python3.6/site-packages/paddlex/cv/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from . import models
     16 from . import nets
     17 from . import transforms

/opt/conda/lib/python3.6/site-packages/paddlex/cv/models/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from .classifier import BaseClassifier
     16 from .classifier import ResNet18
     17 from .classifier import ResNet34

/opt/conda/lib/python3.6/site-packages/paddlex/cv/models/classifier.py in <module>
     20 from multiprocessing.pool import ThreadPool
     21 import paddle.fluid as fluid
---> 22 import paddlex.utils.logging as logging
     23 from paddlex.utils import seconds_to_hms
     24 import paddlex

AttributeError: module 'paddlex' has no attribute 'utils'
```

**Comment by jiangjiajun** [comment]
你的paddlex是pip安装的吗，版本号是多少呢

**Comment by 1150xi** [comment]
> 你的paddlex是pip安装的吗，版本号是多少呢

paddlex是pip安装的

版本号是：1.3.7

**Comment by jiangjiajun** [comment]
我这里运行没问题，请问你是否有将你的python代码命名为`paddlex.py`或者在代码运行目录下有名为paddlex的文件或目录

**Comment by 1150xi** [comment]
> 我这里运行没问题，请问你是否有将你的python代码命名为`paddlex.py`或者在代码运行目录下有名为paddlex的文件或目录

没有的。

我是在另一个jupyter环境下写的 按照这篇文档https://aistudio.baidu.com/aistudio/projectdetail/1643214?channelType=0&channel=0

执行到导入paddlex就报错了

**Comment by jiangjiajun** [comment]
那麻烦先卸载paddlex，然后再重新安装一下试试

**Comment by 1150xi** [comment]
> 那麻烦先卸载paddlex，然后再重新安装一下试试

也还是不行 还是这个报错

**Comment by jiangjiajun** [comment]
如果不用jupyter,而是直接在终端命令行里，通过python里面执行`import paddlex as pdx`呢

**Comment by 1150xi** [comment]
也还是报错

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/paddlex/__init__.py", line 29, in <module>
    import paddle
  File "/opt/conda/lib/python3.6/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/framework.py", line 28, in <module>
    import numpy as np
  File "/opt/conda/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "/opt/conda/bin/python"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory
```

**Comment by 1150xi** [comment]
> 如果不用jupyter,而是直接在终端命令行里，通过python里面执行`import paddlex as pdx`呢

也还是报错

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/paddlex/__init__.py", line 29, in <module>
    import paddle
  File "/opt/conda/lib/python3.6/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/framework.py", line 28, in <module>
    import numpy as np
  File "/opt/conda/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "/opt/conda/bin/python"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory
```

**Comment by jiangjiajun** [comment]
这个错看起来像是paddle没有安装好，确认下你的环境里有没有安装openblas，如果没安装，试试安装openblas

**Comment by 1150xi** [comment]
> 这个错看起来像是paddle没有安装好，确认下你的环境里有没有安装openblas，如果没安装，试试安装openblas

您好，安装好了、环境也配置好了 之后需要怎么操作

**Comment by 60999** [comment]
可以参考https://aistudio.baidu.com/aistudio/projectdetail/580517

**Comment by JiangLang688** [comment]
请问题主现在安装好了吗，我也碰到了你这样子的问题

**Comment by JiangLang688** [comment]
请问题主现在安装好了吗，我也碰到了你这样子的问题
