### ISSUE TITLE
图片分类训练中止报错

### ISSUE THREAD

**Issue by A97139012** [PaddlePaddle/PaddleX#645]
问题类型：模型训练  
**问题描述**  
本人在进行图片分类的过程中，分开db和非db两个数据集，训练的时候报错图片的问题，不知道是图片文件大小的问题还是其他的什么问题，望解答。
[1616721654_P0014_T0017_out.log](https://github.com/PaddlePaddle/PaddleX/files/6208763/1616721654_P0014_T0017_out.log)
[1616721664_P0014_T0017_err.log](https://github.com/PaddlePaddle/PaddleX/files/6208765/1616721664_P0014_T0017_err.log)

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

图片分类训练中止报错：
This log file path is E:\paddleworkspace\projects\P0014\T0017\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
2021-03-26 09:03:57,432-WARNING: E:\paddleworkspace\pretrain\MobileNetV2_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Exception in thread Thread-17:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\db\169.jpg!
Exception in thread Thread-18:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\非db\113.jpg!

Exception in thread Thread-19:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\db\50.jpg!
Exception in thread Thread-20:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\db\49.jpg!

Exception in thread Thread-21:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\非db\90.jpg!
Exception in thread Thread-22:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\非db\41.jpg!

Exception in thread Thread-23:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\db\152.jpg!
Exception in thread Thread-24:
Traceback (most recent call last):
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 76, in __call__
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
  File "site-packages\paddlex\cv\transforms\cls_transforms.py", line 79, in __call__
TypeError: Can't read The image file E:\paddleworkspace\datasets\D0018\db\93.jpg!

**Comment by jiangjiajun** [comment]
在上面有提示多张图片无法读入，建议自行检查下这些图片文件，使用python cv2.imread加载测试下

另外图片文件路径中不能出现空格或中文

**Comment by A97139012** [comment]
好的，谢谢
