### ISSUE TITLE
paddlex语义分割，裁剪后，带上sensi.data继续训练，报了异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#659]
环境aistudio，前面通过
model = pdx.seg.HRNet(
    num_classes=N_CLASSES,
    width=WIDTH,
    class_weight=weights, 
    input_channel=4
)
model.train(
        num_epochs=EPOCHS,
        train_dataset=train_dataset,
        train_batch_size=BATCH_SIZE, 
        eval_dataset=eval_dataset,
        learning_rate=LR,
        log_interval_steps=20,
        save_interval_epochs=SAVE_INTERVAL,
        save_dir=SAVE_DIR,
        pretrain_weights='/home/aistudio/HRNet_W64_C_pretrained',
        use_vdl=True)
训练完30个epoch，加载最优模型进行裁剪
model = pdx.load_model('/home/aistudio/Models/HRNet64/epoch_29')
BATCH_SIZE = 12
pdx.slim.prune.analysis(
    model,
    dataset=eval_dataset,
    batch_size=BATCH_SIZE,
    save_file='/home/aistudio/hrnet.sensi.data')
得到了sensi.data，然后带上这文件继续训练
model.train(
        num_epochs=EPOCHS,
        train_dataset=train_dataset,
        train_batch_size=BATCH_SIZE, #12占用约25G
        eval_dataset=eval_dataset,
        learning_rate=LR,
        log_interval_steps=20,
        save_interval_epochs=SAVE_INTERVAL,
        save_dir=SAVE_DIR,
        pretrain_weights='/home/aistudio/Models/HRNet64/epoch_29',
        sensitivities_file='/home/aistudio/hrnet.sensi.data',
        eval_metric_loss=0.05,
        use_vdl=True)
报异常
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-5-38ac4eee59f1> in <module>
     40         # pretrain_weights='/home/aistudio/HRNet_W64_C_pretrained',
     41         # resume_checkpoint='/home/aistudio/Models/HRNet64/epoch_200', #需要从断点继续训练时可以将该参数设置为模型保存的路径
---> 42         use_vdl=True)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/hrnet.py in train(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, pretrain_weights, optimizer, learning_rate, lr_decay_power, use_vdl, sensitivities_file, eval_metric_loss, early_stop, early_stop_patience, resume_checkpoint)
    176             pretrain_weights, optimizer, learning_rate, lr_decay_power,
    177             use_vdl, sensitivities_file, eval_metric_loss, early_stop,
--> 178             early_stop_patience, resume_checkpoint)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/deeplabv3p.py in train(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, pretrain_weights, optimizer, learning_rate, lr_decay_power, use_vdl, sensitivities_file, eval_metric_loss, early_stop, early_stop_patience, resume_checkpoint)
    356             use_vdl=use_vdl,
    357             early_stop=early_stop,
--> 358             early_stop_patience=early_stop_patience)
    359 
    360     def evaluate(self,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py in train_loop(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, use_vdl, early_stop, early_stop_patience)
    499                     self.parallel_train_prog,
    500                     feed=data,
--> 501                     fetch_list=list(self.train_outputs.values()))
    502                 outputs_avg = np.mean(np.array(outputs), axis=1)
    503                 records.append(outputs_avg)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1108                 return_merged=return_merged)
   1109         except Exception as e:
-> 1110             six.reraise(*sys.exc_info())
   1111 
   1112     def _run_impl(self, program, feed, fetch_list, feed_var_name,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1106                 use_program_cache=use_program_cache,
   1107                 use_prune=use_prune,
-> 1108                 return_merged=return_merged)
   1109         except Exception as e:
   1110             six.reraise(*sys.exc_info())
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1249                 fetch_var_name=fetch_var_name,
   1250                 return_numpy=return_numpy,
-> 1251                 return_merged=return_merged)
   1252 
   1253     def _run_program(self, program, feed, fetch_list, feed_var_name,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_parallel(self, program, scope, feed, fetch_list, fetch_var_name, return_numpy, return_merged)
    911 
    912         fetch_var_names = list(map(_to_name_str, fetch_list))
--> 913         tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
    914         return as_numpy(tensors) if return_numpy else tensors
    915 
ValueError: In user code:

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
      app.start()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
      self.io_loop.start()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
      self._run_once()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
      handle._run()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
      self.run()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
      user_expressions, allow_stdin,
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
      return runner(coro)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
      coro.send(None)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
      if (yield from self.run_code(code, result)):
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-5-38ac4eee59f1>", line 42, in <module>
      use_vdl=True)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/hrnet.py", line 178, in train
      early_stop_patience, resume_checkpoint)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/deeplabv3p.py", line 338, in train
      self.build_program()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py", line 105, in build_program
      self.train_inputs, self.train_outputs = self.build_net(mode='train')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/hrnet.py", line 98, in build_net
      model_out = model.build_net(inputs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/segmentation/hrnet.py", line 96, in build_net
      name='conv-2')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/segmentation/hrnet.py", line 197, in _conv_bn_layer
      bias_attr=False)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1622, in conv2d
      "data_format": data_format,
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3023, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 798, the input's shape is [12, 798, 96, 96]; the filter's channels is 815, the filter's shape is [284, 815, 1, 1]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:798 != filter_dims[1] * groups:815.] (at /paddle/paddle/fluid/operators/conv_op.cc:96)
      [operator < conv2d > error]

**Comment by FlyingQianMM** [comment]
这个问题跟issue #644 相似，麻烦看下该issue的回复，更新相应版本

**Comment by bbbxixixixi** [comment]
> 这个问题跟issue #644 相似，麻烦看下该issue的回复，更新相应版本

更新slim120，paddle2也能行

**Comment by lleesg** [comment]
paddlex2.0训练已经没有sensitivities_file这个参数了呢，请问该怎么加载sensi.data
