### ISSUE TITLE
在使用yolov3_darknet53.py中的代码训练时报错

### ISSUE THREAD

**Issue by song1992413** [PaddlePaddle/PaddleX#679]
问题类型：模型训练  
**问题描述**  
在使用yolov3_darknet53.py中的代码训练时报错
环境是win10

报错信息
Exception in thread Thread-18:
Exception in thread Exception in thread Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-21:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 932, in _bootstrap_inner
Thread-20    self.run()Thread-19:
:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 932, in _bootstrap_inner

  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 870, in run
    self.run()
    self.run()  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 870, in run

  File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\envs\tf_env\lib\site-packages\paddlex\cv\datasets\dataset.py", line 85, in handle_worker
    r = mapper(sample[0], sample[1], sample[2])
TypeError: __call__() takes from 2 to 3 positional arguments but 4 were given
        self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\envs\tf_env\lib\site-packages\paddlex\cv\datasets\dataset.py", line 85, in handle_worker
    r = mapper(sample[0], sample[1], sample[2])
TypeError    self.run()
:   File "D:\Anaconda3\envs\tf_env\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)__call__() takes from 2 to 3 positional arguments but 4 were given
  File "D:\Anaconda3\envs\tf_env\lib\site-packages\paddlex\cv\datasets\dataset.py", line 85, in handle_worker

    r = mapper(sample[0], sample[1], sample[2])
TypeError: __call__() takes from 2 to 3 positional arguments but 4 were given
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\envs\tf_env\lib\site-packages\paddlex\cv\datasets\dataset.py", line 85, in handle_worker
    r = mapper(sample[0], sample[1], sample[2])
TypeError: __call__() takes from 2 to 3 positional arguments but 4 were given
====================  
代码
import paddlex as pdx
from paddlex.cls import transforms

train_transforms = transforms.Compose([
    transforms.RandomDistort(),
    transforms.RandomRotate(),
    transforms.RandomCrop(),
    transforms.ResizeByShort(short_size =[500, 600, 700, 800],),
    transforms.RandomHorizontalFlip(),
    transforms.Normalize()
])

eval_transforms = transforms.Compose([
    transforms.ResizeByShort(short_size =[500, 600, 700, 800],),
    transforms.Normalize()
])

train_dataset = pdx.datasets.VOCDetection(
    data_dir= r'D:\data\insect_det',
    file_list=r'D:\data\insect_det\train_list.txt',
    label_list=r'D:\data\insect_det\labels.txt',
    transforms=train_transforms,
    shuffle=True)
eval_dataset = pdx.datasets.VOCDetection(
    data_dir= r'D:\data\insect_det',
    file_list=r'D:\data\insect_det\val_list.txt',
    label_list=r'D:\data\insect_det\labels.txt',
    transforms=eval_transforms)

num_classes = len(train_dataset.labels)
model = pdx.det.YOLOv3(num_classes=num_classes, backbone='DarkNet53')

model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    learning_rate=0.000125,
    lr_decay_epochs=[210, 240],
    save_dir='output/yolov3_darknet53',
    use_vdl=True)

**Comment by FlyingQianMM** [comment]
请问PaddleX的版本号是多少？

**Comment by FlyingQianMM** [comment]
import paddlex as pdx
from paddlex.cls import transforms

train_transforms = transforms.Compose([
transforms.RandomDistort(),
transforms.RandomRotate(),
transforms.RandomCrop(),
transforms.ResizeByShort(short_size =[500, 600, 700, 800],),
transforms.RandomHorizontalFlip(),
transforms.Normalize()
])
eval_transforms = transforms.Compose([
transforms.ResizeByShort(short_size =[500, 600, 700, 800],),
transforms.Normalize()
])

---------------
你好，检测任务只能调用检测的transform，这里不能使用paddlex.cls.transforms。
具体看下tutorials里面的示例 https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/object_detection/yolov3_darknet53.py#L6-L25
