### ISSUE TITLE
在模型训练过程中评估报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleX#685]
问题类型：模型训练  
**在模型训练过程中评估报错**

报错如下：
2021-04-25 12:24:15 [INFO]	Start to evaluating(total_samples=3284, total_steps=411)...

  0%|          | 0/411 [00:00<?, ?it/s]
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-2-0e7264b3e08b> in <module>
     58     lr_decay_epochs=[210, 240],
     59     save_dir='output/ppyolo',
---> 60     use_vdl=True)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py in train(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, pretrain_weights, optimizer, learning_rate, warmup_steps, warmup_start_lr, lr_decay_epochs, lr_decay_gamma, metric, use_vdl, sensitivities_file, eval_metric_loss, early_stop, early_stop_patience, resume_checkpoint, use_ema, ema_decay)
    364             use_vdl=use_vdl,
    365             early_stop=early_stop,
--> 366             early_stop_patience=early_stop_patience)
    367 
    368     def evaluate(self,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py in train_loop(self, num_epochs, train_dataset, train_batch_size, eval_dataset, save_interval_epochs, log_interval_steps, save_dir, use_vdl, early_stop, early_stop_patience)
    569                         batch_size=eval_batch_size,
    570                         epoch_id=i + 1,
--> 571                         return_details=True)
    572                     logging.info('[EVAL] Finished, Epoch={}, {} .'.format(
    573                         i + 1, dict2str(self.eval_metrics)))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py in evaluate(self, eval_dataset, batch_size, epoch_id, metric, return_details)
    429                     feed=[feed_data],
    430                     fetch_list=list(self.test_outputs.values()),
--> 431                     return_numpy=False)
    432             res = {
    433                 'bbox': (np.array(outputs[0]),
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1108                 return_merged=return_merged)
   1109         except Exception as e:
-> 1110             six.reraise(*sys.exc_info())
   1111 
   1112     def _run_impl(self, program, feed, fetch_list, feed_var_name,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1106                 use_program_cache=use_program_cache,
   1107                 use_prune=use_prune,
-> 1108                 return_merged=return_merged)
   1109         except Exception as e:
   1110             six.reraise(*sys.exc_info())
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1236                 scope=scope,
   1237                 return_numpy=return_numpy,
-> 1238                 use_program_cache=use_program_cache)
   1239 
   1240         program._compile(scope, self.place)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
   1326         if not use_program_cache:
   1327             self._default_executor.run(program.desc, scope, 0, True, True,
-> 1328                                        [fetch_var_name])
   1329         else:
   1330             self._default_executor.run_prepared_ctx(ctx, scope, False, False,
ValueError: In user code:

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
      app.start()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
      self.io_loop.start()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
      self._run_once()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
      handle._run()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
      self.run()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
      user_expressions, allow_stdin,
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
      return runner(coro)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
      coro.send(None)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3189, in run_ast_nodes
      if (yield from self.run_code(code, result)):
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-0e7264b3e08b>", line 60, in <module>
      use_vdl=True)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py", line 346, in train
      self.build_program()
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/base.py", line 114, in build_program
      mode='test')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py", line 175, in build_net
      model_out = model.build_net(inputs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 512, in build_net
      head_outputs = self._head(feats, self.mode == 'train')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 148, in _head
      name=self.prefix_name + "yolo_block.{}".format(i))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 335, in _detection_block
      conv = self._add_coord(conv, is_test=is_test)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 253, in _add_coord
      return fluid.layers.concat([input, x_range, y_range], axis=1)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 355, in concat
      type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3027, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 2-th dimension of input[0] and input[2] is expected to be equal.But received input[0]'s shape = [8, 2048, 42, 34], input[2]'s shape = [8, 1, 34, 42].
      [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:42 != inputs_dims[i][j]:34.] (at /paddle/paddle/fluid/operators/concat_op.h:63)
      [operator < concat > error]

**Comment by jiangjiajun** [comment]
贴一下你的训练代码

**Comment by thomas-yanxin** [comment]
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from paddlex.det import transforms
import paddlex as pdx


train_transforms = transforms.Compose([
    transforms.RandomHorizontalFlip(), transforms.Normalize(),
    transforms.ResizeByShort(
        short_size=800, max_size=1333), transforms.Padding(coarsest_stride=32)
])

eval_transforms = transforms.Compose([
    transforms.Normalize(), transforms.ResizeByShort(
        short_size=800, max_size=1333), transforms.Padding(coarsest_stride=32)
])

train_dataset = pdx.datasets.CocoDetection(
    data_dir='/home/aistudio/VOC2007/JPEGImages',
    ann_file='/home/aistudio/VOC2007/train.json',
    transforms=train_transforms,
    shuffle=True)
eval_dataset = pdx.datasets.CocoDetection(
    data_dir='/home/aistudio/VOC2007/JPEGImages',
    ann_file='/home/aistudio/VOC2007/val.json',
    transforms=eval_transforms)

num_classes = len(train_dataset.labels) + 1

model = pdx.det.MaskRCNN(num_classes=num_classes, backbone='ResNet50')

model.train(
    num_epochs=12,
    train_dataset=train_dataset,
    train_batch_size=1,
    metric = "COCO",
    eval_dataset=eval_dataset,
    learning_rate=0.00125,
    warmup_steps=10,
    lr_decay_epochs=[8, 11],
    save_dir='output/mask_rcnn_r50_fpn',
    use_vdl=True)

**Comment by jiangjiajun** [comment]
从你上面的日志来看，并不是这个训练代码，因为上面的错误提示显示你是在训练ppyolo模型

**Comment by thomas-yanxin** [comment]
import paddlex as pdx
from paddlex.det import transforms


# 定义训练和验证时的transforms
# API说明 https://paddlex.readthedocs.io/zh_CN/develop/apis/transforms/det_transforms.html
train_transforms = transforms.Compose([
    transforms.MixupImage(mixup_epoch=250), transforms.RandomDistort(),
    transforms.RandomExpand(), transforms.RandomCrop(), transforms.Resize(
        target_size=608, interp='RANDOM'), transforms.RandomHorizontalFlip(),
    transforms.Normalize()
])

eval_transforms = transforms.Compose([
    transforms.Resize(
        target_size=608, interp='CUBIC'), transforms.Normalize()
])

train_transforms = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.Normalize(),
    transforms.ResizeByShort(short_size=800, max_size=1333),
    transforms.Padding(coarsest_stride=32)
])

eval_transforms = transforms.Compose([
    transforms.Normalize(),
    transforms.ResizeByShort(short_size=800, max_size=1333),
    transforms.Padding(coarsest_stride=32),
])

train_dataset = pdx.datasets.VOCDetection(
                        data_dir='/home/aistudio/PaddleDetection/dataset/voc/VOC2007',
                        file_list='/home/aistudio/PaddleDetection/dataset/voc/VOC2007/val_list.txt',
                        label_list='/home/aistudio/PaddleDetection/dataset/voc/VOC2007/label_list.txt',
                        transforms=train_transforms)
eval_dataset = pdx.datasets.VOCDetection(
                        data_dir='/home/aistudio/PaddleDetection/dataset/voc/VOC2007',
                        file_list='/home/aistudio/PaddleDetection/dataset/voc/VOC2007/train_list.txt',
                        label_list='/home/aistudio/PaddleDetection/dataset/voc/VOC2007/label_list.txt',
                        transforms=eval_transforms)

num_classes = len(train_dataset.labels)

# API说明: https://paddlex.readthedocs.io/zh_CN/develop/apis/models/detection.html#paddlex-det-ppyolo
model = pdx.det.PPYOLO(num_classes=num_classes)

# API说明: https://paddlex.readthedocs.io/zh_CN/develop/apis/models/detection.html#train
# 各参数介绍与调整说明：https://paddlex.readthedocs.io/zh_CN/develop/appendix/parameters.html
model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    learning_rate=0.00025,
    save_interval_epochs = 1 ,
    metric="VOC",
    lr_decay_epochs=[210, 240],
    save_dir='output/ppyolo',
    use_vdl=True)

**Comment by thomas-yanxin** [comment]
不好意思贴错了，应该是上面这个……还请您看一下，emmm基本上是paddlex提供的ppyolo的demo代码，改掉了数据集地址，在train中加了metric="VOC"，其他应该没变

**Comment by FlyingQianMM** [comment]
train_transforms = transforms.Compose([
transforms.RandomHorizontalFlip(),
transforms.Normalize(),
transforms.ResizeByShort(short_size=800, max_size=1333),
transforms.Padding(coarsest_stride=32)
])

eval_transforms = transforms.Compose([
transforms.Normalize(),
transforms.ResizeByShort(short_size=800, max_size=1333),
transforms.Padding(coarsest_stride=32),
])

上面这段代码是rcnn的transform，删除掉即可
