### ISSUE TITLE
UnboundLocalError: local variable 'im' referenced before assignment

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#703]
import paddlex as pdx
import cv2

print("Loading model...")
model = pdx.deploy.Predictor('/home/hello/P0013-T0038_fbm_model/inference_model', use_gpu=True)
print("Model loaded.")

im = cv2.imread('/home/xxxx/P0013-T0038_model/Image_20210429164117226.JPG')
im = im.astype('float32')

result = model.predict(im)

if model.model_type == "classifier":
    print(result)

if model.model_type == "detector":
    pdx.det.visualize(im, result, threshold=0.5, save_dir='./')

if model.model_type == "segmenter":
    pdx.seg.visualize(im, result, weight=0.0, save_dir='./')

========================
python predict.py

Loading model...
W0505 20:59:52.036068  7796 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
Model loaded.

Traceback (most recent call last):
  File "predict.py", line 20, in <module>
    result = model.predict(im)
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.6/site-packages/paddlex/deploy.py", line 277, in predict
    preprocessed_input = self.preprocess([image])
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.6/site-packages/paddlex/deploy.py", line 161, in preprocess
    thread_pool=thread_pool)
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.6/site-packages/paddlex/cv/models/classifier.py", line 309, in _preprocess
    batch_data.append(transforms(image))
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.6/site-packages/paddlex/cv/transforms/cls_transforms.py", line 89, in __call__
    self.data_type = im.dtype
UnboundLocalError: local variable 'im' referenced before assignment

------------------------------
result = model.predict(im)
改为 
result = model.predict('/home/xxxx/P0013-T0038_model/Image_20210429164117226.JPG')
才不会报错

**Comment by FlyingQianMM** [comment]
分类transform里面漏掉了当输入im_file是np.array时对im的赋值，感谢您的指正，该问题已修复，见pr https://github.com/PaddlePaddle/PaddleX/pull/705
