### ISSUE TITLE
目标检测划分数据集报错，提示不是一个良构的xml文件

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleX#709]
!paddlex --split_dataset --format VOC --dataset_dir 'work/' --val_value 0.2 --test_value 0.1
目标检测
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/tools/dataset_split/voc_split.py", line 41, in split_voc_dataset
    osp.join(dataset_dir, "Annotations", anno_name))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 228, in main
    test_value, save_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/tools/split.py", line 30, in dataset_split
    dataset_dir, val_value, test_value, save_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/tools/dataset_split/voc_split.py", line 44, in split_voc_dataset
    osp.join(dataset_dir, "Annotations", anno_name)))
Exception: 文件work/Annotations/220605908000000190_002288430200000046087926_20171117130148.xml不是一个良构的xml文件，请检查标注文件

xml文件内容
<annotation>
	<folder>22落地增高架</folder>
<filename>220605908000000190_002288430200000046087926_20171117130148.jpg</filename>
	<path>F:\管理服务推广交付\toweroom\12.14\22落地增高架\220605908000000190_002288430200000046087926_20171117130148.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>1224</width>
		<height>1632</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>jianyita</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>323</xmin>
			<ymin>84</ymin>
			<xmax>939</xmax>
			<ymax>1589</ymax>
		</bndbox>
	</object>
</annotation>

**Comment by FlyingQianMM** [comment]
文件夹路径不要有中文
