### ISSUE TITLE
Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#733]
python mobilenetv2_quant.py

/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
W0517 14:53:02.829377 21942 init.cc:136] Compiled with WITH_GPU, but no GPU found in runtime.
/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/framework.py:299: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
2021-05-17 14:53:02 [INFO]      Decompressing ./mobilenetv2_vegetables.tar.gz...
2021-05-17 14:53:03 [INFO]      Decompressing ./vegetables_cls.tar.gz...
Traceback (most recent call last):
  File "mobilenetv2_quant.py", line 14, in <module>
    model = pdx.load_model('mobilenetv2_vegetables')
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/models/load_model.py", line 84, in load_model
    model.exe.run(startup_prog)
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/six-1.16.0-py3.7.egg/six.py", line 719, in reraise
    raise value
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1238, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1328, in _run_program
    [fetch_var_name])
OSError: In user code:

    File "mobilenetv2_quant.py", line 14, in <module>
      model = pdx.load_model('mobilenetv2_vegetables')
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/models/load_model.py", line 82, in load_model
      mode='test')
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/models/classifier.py", line 76, in build_net
      net_out = model(image, num_classes=self.num_classes)
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/nets/__init__.py", line 91, in mobilenetv2
      return model(input)
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/nets/mobilenet_v2.py", line 110, in __call__
      bias_attr=ParamAttr(name='fc10_offset'))
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 367, in fc
      pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 128, in append_bias_op
      attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 378, in create_parameter
      **attr._to_kwargs(with_initializer=True))
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2988, in create_parameter
      initializer(param, self)
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 165, in __call__
      stop_gradient=True)
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3113, in _prepend_op
      attrs=kwargs.get("attrs", None))
    File "/home/hello/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
      [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:78)
      [operator < fill_constant > error]
-------------
模型训练没问题  可以正常训练

MobileNetV2模型的量化示例 报错
mobilenetv2_quant.py
/tutorials/slim/quant/image_classification

显卡驱动 也是正常的

NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by FlyingQianMM** [comment]
参考 https://github.com/PaddlePaddle/PaddleX/issues/659 看下更改paddleslim的版本能否解决现在这个问题
