### ISSUE TITLE
Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#740]
faster_rcnn_r18_fpn.py

目标检测
只改了数据集  其他没动
然后报错

(默认的都能正常训练，换了自己的数据集就不行了，标签都有重新生成)
------------

python faster_rcnn_r18_fpn.py

/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
2021-05-18 20:50:00 [INFO]    Starting to read file list from dataset...
2021-05-18 20:50:08 [INFO]    8747 samples in file /database1/ImageData/X/train_list.txt
creating index...
index created!
2021-05-18 20:50:08 [INFO]    Starting to read file list from dataset...
2021-05-18 20:50:10 [INFO]    2495 samples in file /database1/ImageData/X/val_list.txt
creating index...
index created!
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/framework.py:687: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/nets/detection/fpn.py:172
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-05-18 20:50:10,710 - INFO - If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/nets/detection/bbox_head.py:278
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle2onnx-0.5.1-py3.7.egg/paddle2onnx/onnx_helper/mapping.py:42: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle2onnx-0.5.1-py3.7.egg/paddle2onnx/constant/dtypes.py:43: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle2onnx-0.5.1-py3.7.egg/paddle2onnx/constant/dtypes.py:44: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle2onnx-0.5.1-py3.7.egg/paddle2onnx/constant/dtypes.py:49: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
2021-05-18 20:50:11 [INFO]    Connecting PaddleHub server to get pretrain weights...
Download https://paddle-imagenet-models-name.bj.bcebos.com/ResNet18_pretrained.tar
[##################################################] 100.00%
Decompress /home/intsoft/.paddlehub/tmp/tmpuy739att/ResNet18_pretrained.tar
[##################################################] 100.00%
W0518 20:50:16.872452  7438 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0518 20:50:16.873911  7438 device_context.cc:372] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "faster_rcnn_r18_fpn.py", line 60, in <module>
    use_vdl=True)
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/models/faster_rcnn.py", line 362, in train
    eval_metric_loss=eval_metric_loss)
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddlex-1.3.10-py3.7.egg/paddlex/cv/models/base.py", line 247, in net_initialize
    self.exe.run(startup_prog)
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1238, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/intsoft/anaconda3/envs/PaddleX/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1328, in _run_program
    [fetch_var_name])
OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /paddle/paddle/fluid/platform/device_context.h:264)

**Comment by FlyingQianMM** [comment]
此错误可能是gpu显存不足造成的，减小batch size和resize后的大小试试
