### ISSUE TITLE
模型裁剪invalid literal for int() with base 10: 'annotations/06000496.xml

### ISSUE THREAD

**Issue by SUPERSCHOLARYUN** [PaddlePaddle/PaddleX#774]
问题类型：模型部署
**问题描述**  

========================  

Traceback (most recent call last):
  File "params_analysis.py", line 11, in <module>
    transforms=model.eval_transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/datasets/imagenet.py", line 81, in __init__
    self.file_list.append([full_path, int(items[1])])
ValueError: invalid literal for int() with base 10: 'annotations/06000496.xml'

**Comment by FlyingQianMM** [comment]
imagenet是分类任务的数据集读取对象， 但是你加载的是检测数据集
