### ISSUE TITLE
利用PaddleX对实例分割数据集进行数据划分报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleX#780]
数据类型：实例分割数据集划分报错
项目链接：https://aistudio.baidu.com/aistudio/projectdetail/1995514

代码：
!paddlex --split_dataset --format COCO --dataset_dir 'work/' --val_value 0.2 --test_value 0.1
报错：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
loading annotations into memory...
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 228, in main
    test_value, save_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/tools/split.py", line 27, in dataset_split
    dataset_dir, val_value, test_value, save_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/tools/dataset_split/coco_split.py", line 35, in split_coco_dataset
    coco = COCO(annotation_file)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/coco.py", line 85, in __init__
    dataset = json.load(f)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 58)

**Comment by FlyingQianMM** [comment]
看日志是读取annotations.json文件报错了
```
!paddlex --split_dataset --format COCO --dataset_dir work/ --val_value 0.2 --test_value 0.1
```
work下面都有什么文件？

看下这里吧 https://paddlex.readthedocs.io/zh_CN/develop/data/format/instance_segmentation.html
