### ISSUE TITLE
PaddleX restful的目标检测任务：模型评估报错

### ISSUE THREAD

**Issue by LiKangyuLKY** [PaddlePaddle/PaddleX#787]
问题类型：其它  
**PaddleX restful的目标检测任务：模型评估报错**  

>版本详情：
paddlepaddle-gpu==1.8.5.post107
ubuntu 18.04
paddlex 1.3.10
cuda 10.1
cudnn 7.6.5

========================

在使用PaddleX restful版本进行目标检测任务时，模型评估报错。
网页显示：
> 评估失败，详细信息：
> {'evaluate_status":12,'message":"\u8bc4\u4f30\u5931\u8d25\uff0c\u8bf7\u91cd\u65b0\u8bc4\u4f30!","result":null,"status":-1}

ps：训练过程正常，使用测试集图片进行测试正常

**err.log显示如下**

> Process Process-72:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
>     self.run()  
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/operate.py", line 122, in _call_paddlex_evaluate_model
>     report = evaluator.generate_report()
>   File "/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py", line 604, in generate_report
>     report['Confusion_Matrix'] = copy.deepcopy(self.cal_confusion_matrix())
>   File "/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py", line 544, in cal_confusion_matrix
>     confusion_matrix.update(bbox, gt_box, gt_label, difficult)
>   File "/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py", line 264, in update
>     if float(score) < self.score_threshold:
> TypeError: '<' not supported between instances of 'float' and 'NoneType'

看起来像是置信度score没有值，无法进行比较。

**Comment by FlyingQianMM** [comment]
麻烦您在安装paddlex的机器上先debug下，在/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py 264行打印下score和self.score_threshold看下是哪个为Nonetype，如果是score为None，麻烦打印下262行的bbox

**Comment by LiKangyuLKY** [comment]
> 麻烦您在安装paddlex的机器上先debug下，在/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py 264行打印下score和self.score_threshold看下是哪个为Nonetype，如果是score为None，麻烦打印下262行的bbox

print之后发现，self.score_thredshold的值为None，代码中应该是赋了0.3初值的吧，怎么会出现这种情况

**Comment by LiKangyuLKY** [comment]
> 麻烦您在安装paddlex的机器上先debug下，在/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py 264行打印下score和self.score_threshold看下是哪个为Nonetype，如果是score为None，麻烦打印下262行的bbox

测试发现，self.overlap_thresh也为None

**Comment by LiKangyuLKY** [comment]
> 麻烦您在安装paddlex的机器上先debug下，在/usr/local/lib/python3.8/dist-packages/paddlex_restful/restful/project/evaluate/detection.py 264行打印下score和self.score_threshold看下是哪个为Nonetype，如果是score为None，麻烦打印下262行的bbox

把self.overlap_thresh和self.score_threshold改为固定值后，模型评估正常了。

**Comment by FlyingQianMM** [comment]
是不是有在html界面上调整了score_threshold和overlap_thresh的设置值后才出现这种情况的？

**Comment by LiKangyuLKY** [comment]
@FlyingQianMM 未调整，设置为固定值后正常。更新至paddlepaddle-gpu 2.1.0.post110后也正常了

**Comment by FlyingQianMM** [comment]
> 把self.overlap_thresh和self.score_threshold改为固定值后，模型评估正常了。

这个改成固定值是在代码里面修改的还是html界面上设置的？

**Comment by LiKangyuLKY** [comment]
@

> > 把self.overlap_thresh和self.score_threshold改为固定值后，模型评估正常了。
> 
> 这个改成固定值是在代码里面修改的还是html界面上设置的？

detection.py 代码中修改的，更新到paddlepaddle-gpu 2.1.0.post110不需更改就work了
