### ISSUE TITLE
模型训练中的数据增强出错

### ISSUE THREAD

**Issue by Siriuscy** [PaddlePaddle/PaddleX#789]
问题类型：模型训练  
**问题描述**  

====================  
我用的是python生成的图片，但是有的能读取，有的读取不了。不知道为什么，检查过了，所有图片都能用Image读取显示。

2021-05-27 22:11:23,853-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-05-27 22:11:24 [INFO]	Decompressing output/faster_rcnn_r50_fpn/pretrain/ResNet50_cos_pretrained.tar...
2021-05-27 22:11:27 [INFO]	Load pretrain weights from output/faster_rcnn_r50_fpn/pretrain/ResNet50_cos_pretrained.
2021-05-27 22:11:27,131-WARNING: output/faster_rcnn_r50_fpn/pretrain/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2021-05-27 22:11:27 [INFO]	There are 265 varaibles in output/faster_rcnn_r50_fpn/pretrain/ResNet50_cos_pretrained are loaded.
2021-05-27 22:11:29 [INFO]	[TRAIN] Epoch=1/10, Step=2/120, loss=1.619201, loss_cls=0.876635, loss_bbox=2e-06, loss_rpn_cls=0.698067, loss_rpn_bbox=0.044497, lr=0.000837, time_each_step=0.66s, eta=0:16:34
2021-05-27 22:11:29 [INFO]	[TRAIN] Epoch=1/10, Step=4/120, loss=1.018859, loss_cls=0.264852, loss_bbox=4e-06, loss_rpn_cls=0.695395, loss_rpn_bbox=0.058608, lr=0.000843, time_each_step=0.49s, eta=0:12:6
2021-05-27 22:11:30 [INFO]	[TRAIN] Epoch=1/10, Step=6/120, loss=0.919157, loss_cls=0.036404, loss_bbox=0.002886, loss_rpn_cls=0.689783, loss_rpn_bbox=0.190083, lr=0.00085, time_each_step=0.41s, eta=0:10:6
2021-05-27 22:11:30 [INFO]	[TRAIN] Epoch=1/10, Step=8/120, loss=1.055311, loss_cls=0.061291, loss_bbox=0.020401, loss_rpn_cls=0.690866, loss_rpn_bbox=0.282754, lr=0.000857, time_each_step=0.37s, eta=0:9:5
2021-05-27 22:11:31 [INFO]	[TRAIN] Epoch=1/10, Step=10/120, loss=0.747305, loss_cls=0.031498, loss_bbox=0.002285, loss_rpn_cls=0.677515, loss_rpn_bbox=0.036007, lr=0.000863, time_each_step=0.36s, eta=0:8:49
2021-05-27 22:11:31 [INFO]	[TRAIN] Epoch=1/10, Step=12/120, loss=3.773873, loss_cls=0.051113, loss_bbox=0.009292, loss_rpn_cls=0.662133, loss_rpn_bbox=3.051336, lr=0.00087, time_each_step=0.35s, eta=0:8:33
2021-05-27 22:11:32 [INFO]	[TRAIN] Epoch=1/10, Step=14/120, loss=1.389426, loss_cls=0.214923, loss_bbox=0.041175, loss_rpn_cls=0.653619, loss_rpn_bbox=0.479709, lr=0.000877, time_each_step=0.33s, eta=0:8:3
2021-05-27 22:11:33 [INFO]	[TRAIN] Epoch=1/10, Step=16/120, loss=1.208307, loss_cls=0.122072, loss_bbox=0.03224, loss_rpn_cls=0.622, loss_rpn_bbox=0.431996, lr=0.000883, time_each_step=0.32s, eta=0:7:58
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/datasets/dataset.py", line 85, in handle_worker
    r = mapper(sample[0], sample[1], sample[2])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/det_transforms.py", line 149, in __call__
    outputs = decode_image(im, im_info, label_info, input_channel)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/det_transforms.py", line 124, in decode_image
    self.data_type = im.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by jiangjiajun** [comment]
其中某张图片读取后为None，建议检查下所有图片是否能使用cv2.imread读取，并且读取后不为None

**Comment by Siriuscy** [comment]
谢谢！我检查了一下，图片的起始为1，而json里的为0，所以读取失败，谢谢！！
