### ISSUE TITLE
使用Mac Pro的cpu版进行训练的报错

### ISSUE THREAD

**Issue by MichaelZhero** [PaddlePaddle/PaddleX#807]
问题类型：模型训练  
**问题描述**  
 使用Mac Pro的cpu版进行训练的报错
====================  
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=12 # for example, set CPU_NUM as number of physical CPU core which is 12.

!!! The default number of CPU_NUM=1.
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:294: UserWarning: /Users/apple/PaddleX/paddlex/cv/nets/xception.py:316
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py:689: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:294: UserWarning: /Users/apple/PaddleX/paddlex/cv/nets/segmentation/model_utils/loss.py:74
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle2onnx/onnx_helper/mapping.py:42: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:43: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:44: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:49: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
2021-06-04 23:00:43 [INFO]	Connecting PaddleHub server to get pretrain weights...
2021-06-04 23:00:44 [INFO]	Load pretrain weights from output/meter_seg/pretrain/DeepLabv3p_Xception65_COCO.
2021-06-04 23:00:44 [WARNING]	[SKIP] Shape of pretrained weight output/meter_seg/pretrain/DeepLabv3p_Xception65_COCO/logit/weights doesn't match.(Pretrained: (21, 256, 1, 1), Actual: (3, 256, 1, 1))
2021-06-04 23:00:44 [WARNING]	[SKIP] Shape of pretrained weight output/meter_seg/pretrain/DeepLabv3p_Xception65_COCO/logit/biases doesn't match.(Pretrained: (21,), Actual: (3,))
2021-06-04 23:00:45 [INFO]	There are 730 varaibles in output/meter_seg/pretrain/DeepLabv3p_Xception65_COCO are loaded.
Traceback (most recent call last):
  File "/Users/apple/PaddleX/examples/meter_reader/train_segmentation.py", line 46, in <module>
    model.train(
  File "/Users/apple/PaddleX/paddlex/cv/models/deeplabv3p.py", line 348, in train
    self.train_loop(
  File "/Users/apple/PaddleX/paddlex/cv/models/base.py", line 507, in train_loop
/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/reader.py:1294: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
WARNING:root:Your reader has raised an exception!
[WARNING 2021-06-04 23:00:56,435 reader.py:1294] Your reader has raised an exception!
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    for step, data in enumerate(self.train_data_loader()):
  File "/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1251, in __next__
    return self._reader.read_next()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /home/Paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

    self.run()
  File "/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apple/opt/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1295, in __thread_main__
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by FlyingQianMM** [comment]
tutorials里面的https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train/semantic_segmentation 可以正常运行么？

运行的`examples/meter_reader/train_segmentation.py`这个文件有做什么修改么？

**Comment by MichaelZhero** [comment]
> tutorials里面的https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train/semantic_segmentation 可以正常运行么？
> 


只要一运行都是报同样的问题

**Comment by FlyingQianMM** [comment]
从您贴的报错信息来看，是reader部分报错：
![image](https://user-images.githubusercontent.com/22235422/121113825-4e7c4e00-c845-11eb-8a63-ff3a7ea1dddf.png)
这个可能是数据集有问题，也有可能是数据预处理有问题。

所以前面让您运行下tutorials里面的https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train/semantic_segmentation ，是为了确认使用示例数据集是否可以正常运行，但您说报一样的错误。

我这边使用mac cpu，安装paddlepaddle 2.1.0，paddlex 1.3.11运行了deeplabv3_xception65，运行代码是示例代码 https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/semantic_segmentation/deeplabv3p_xception65.py ，因机器带不动，所以bs设置为1（https://github.com/PaddlePaddle/PaddleX/blob/b15bf757868bd6acf525f85364c59235f7cf8f2a/tutorials/train/semantic_segmentation/deeplabv3p_xception65.py#L57 ），是可以正常运行的，没有复现出您的问题。

![image](https://user-images.githubusercontent.com/22235422/121114141-c5194b80-c845-11eb-9862-918a86d614e8.png)

**Comment by MichaelZhero** [comment]
1、系统是macOS Big sur 11.4（系统版本过高？）；
2、paddle版本是2.1.0，paddlex在虚拟环境下是1.3.10，而git到本地的是1.3.9的源码，注释掉os.environ['CUDA_VISIBLE_DEVICES'] = '0'，以及将train_batch_size=4改为, train_batch_size=1，依然报同样的错。
3、下载了paddles.gui.是1.1.7，可以顺利运行及训练，在使用paddlex.gui使需要心运行一下prepare.sh，是否有相关性？

**Comment by MichaelZhero** [comment]
prepare.sh 内容如下，主要是获取权限。
因此，在怀疑出问题是因为数据读取失败有可能是没有获得权限

# /bin/sh !
dirname=$(dirname "$0")

echo "脚本将会需要sudo权限，可能会提示您输入系统登录密码。"
echo "sudo permission is needed for this shell execution, you may need to type your password below.\n"

sudo xattr -r -d com.apple.quarantine $dirname/${dirname}

echo "\n正在打开PaddleX可视化客户端，第一次下载后打开客户端，可能会比较慢（1分钟内），请耐心等待\n"
echo "\n如出现安全性/隐私提示，请在『系统偏好设置->安全性与隐私->通用』中，选择『仍要打开』\n"
echo "\n之后可通过点击目录 $dirname 下的PaddleX图标打开客户端"

open ${dirname}/Contents/MacOS/PaddleX
