### ISSUE TITLE
模型裁剪报“TypeError: reduce() of empty sequence with no initial value”

### ISSUE THREAD

**Issue by SUPERSCHOLARYUN** [PaddlePaddle/PaddleX#808]
报错信息如下：
Traceback (most recent call last):
  File "slim_visualize.py", line 3, in <module>
    pdx.slim.visualize(model, 'yolov3.sensi.data', save_dir='./')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/slim/visualize.py", line 48, in visualize
    scope=model.scope)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/slim/prune.py", line 386, in cal_model_size
    origin_size += reduce(lambda x, y: x * y, shape)
TypeError: reduce() of empty sequence with no initial value

Python文件代码：
import paddlex as pdx
model = pdx.load_model('work/FasterRCNN_02/best_model')
pdx.slim.visualize(model, 'yolov3.sensi.data', save_dir='./')

**Comment by FlyingQianMM** [comment]
加载的是faster rcnn模型，但是visualize的是yolo的敏感度分析文件，故无法正常运行

**Comment by smallwhi** [comment]
> 加载的是faster rcnn模型，但是visualize的是yolo的敏感度分析文件，故无法正常运行

您好，我也遇到了类似的问题，但我加载的是faster_rcnn_r50_fpn.sensi的模型,visualize也是faster_rcnn_r50_fpn的分析文件也报了这个错误，报错信息如下：
![image](https://user-images.githubusercontent.com/66171021/126052947-92b120c2-eb15-40fe-924d-cc9ae3115b77.png)
代码如下：
![image](https://user-images.githubusercontent.com/66171021/126053101-91186d5f-ca65-4a1d-ae27-24197250d6cc.png)
