### ISSUE TITLE
PaddleX2.0.0rc0示例代码ppyolov2.py无法启动训练

### ISSUE THREAD

**Issue by thinkall** [PaddlePaddle/PaddleX#811]
在 [ppyolov2.py](https://github.com/PaddlePaddle/PaddleX/blob/v2.0.0rc0/tutorials/train/object_detection/ppyolov2.py) 开头加入了，
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
```

运行日志如下：
```

(paddle2.1) ly@ai-Super-Server:~/jli/paddlexs$ python ppyolov2.py 
/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/distributed/parallel.py:118: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
2.1.0
2021-06-07 18:51:13 [INFO]      Starting to read file list from dataset...
2021-06-07 18:51:14 [INFO]      169 samples in file insect_det/train_list.txt
creating index...
index created!
2021-06-07 18:51:14 [INFO]      Starting to read file list from dataset...
2021-06-07 18:51:14 [INFO]      24 samples in file insect_det/val_list.txt
creating index...
index created!
W0607 18:51:14.163457 30266 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0607 18:51:14.163714 30266 dynamic_loader.cc:267] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "ppyolov2.py", line 53, in <module>
    model = pdx.models.PPYOLOv2(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 1162, in __init__
    backbone = self._get_backbone(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 75, in _get_backbone
    backbone = backbones.__dict__[backbone_name](**params)
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/nets/ppdet/modeling/backbones/resnet.py", line 518, in __init__
    ConvNormLayer(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/nets/ppdet/modeling/backbones/resnet.py", line 61, in __init__
    self.conv = nn.Conv2D(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3193, in create_parameter
    initializer(param, self)
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 353, in __call__
    op = block.append_op(
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3219, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/ly/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)
  [operator < gaussian_random > error]
```

各版本库如下：
```
(paddle2.1) ly@ai-Super-Server:~/jli/paddlexs$ python -m pip list | grep paddle
paddle2onnx      0.6
paddlehub        2.1.0
paddlenlp        2.0.2
paddlepaddle-gpu 2.1.0.post101
paddleslim       2.0.0
paddlex          2.0.0rc0
```

显卡驱动如下，总共4块卡：
```
(paddle2.1) liuyu@ai-Super-Server:~/jli/paddlexs$ nvidia-smi 
Mon Jun  7 18:58:11 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.197.02   Driver Version: 418.197.02   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
```

**Comment by thinkall** [comment]
重新装了一遍CUDA, cudnn, nccl2, 手动设置各种环境变量后OK了。
