### ISSUE TITLE
多卡训练每次evaluate以后就退出

### ISSUE THREAD

**Issue by thinkall** [PaddlePaddle/PaddleX#812]
首先，单卡是正常的：

```
python faster_rcnn_r34_fpn.py 

......
2021-06-08 09:30:58 [INFO]      [EVAL] Finished, Epoch=11, mAP(0.50, 11point)=83.420776 .
2021-06-08 09:30:58 [INFO]      Current evaluated best model in eval_dataset is epoch_10, mAP(0.50, 11point)=84.75437391202493
2021-06-08 09:31:01 [INFO]      Model saved in output/faster_rcnn_r50_fpn/epoch_11.
2021-06-08 09:31:02 [INFO]      [TRAIN] Epoch=12/12, Step=6/84, loss_rpn_cls=0.003508, loss_rpn_reg=0.017556, loss_bbox_cls=0.156611, loss_bbox_reg=0.259780, loss=0.437455, lr=0.002500, time_each_step=0.2s, eta=0:0:15
2021-06-08 09:31:04 [INFO]      [TRAIN] Epoch=12/12, Step=16/84, loss_rpn_cls=0.005416, loss_rpn_reg=0.020782, loss_bbox_cls=0.255538, loss_bbox_reg=0.296849, loss=0.578584, lr=0.002500, time_each_step=0.2s, eta=0:0:13
2021-06-08 09:31:06 [INFO]      [TRAIN] Epoch=12/12, Step=26/84, loss_rpn_cls=0.002409, loss_rpn_reg=0.016013, loss_bbox_cls=0.196038, loss_bbox_reg=0.266008, loss=0.480468, lr=0.002500, time_each_step=0.2s, eta=0:0:11
2021-06-08 09:31:08 [INFO]      [TRAIN] Epoch=12/12, Step=36/84, loss_rpn_cls=0.002575, loss_rpn_reg=0.029529, loss_bbox_cls=0.175272, loss_bbox_reg=0.359199, loss=0.566575, lr=0.002500, time_each_step=0.21s, eta=0:0:9
2021-06-08 09:31:11 [INFO]      [TRAIN] Epoch=12/12, Step=46/84, loss_rpn_cls=0.005410, loss_rpn_reg=0.021958, loss_bbox_cls=0.204535, loss_bbox_reg=0.322195, loss=0.554098, lr=0.002500, time_each_step=0.22s, eta=0:0:8
2021-06-08 09:31:13 [INFO]      [TRAIN] Epoch=12/12, Step=56/84, loss_rpn_cls=0.005159, loss_rpn_reg=0.023370, loss_bbox_cls=0.188118, loss_bbox_reg=0.293606, loss=0.510253, lr=0.002500, time_each_step=0.2s, eta=0:0:5
2021-06-08 09:31:15 [INFO]      [TRAIN] Epoch=12/12, Step=66/84, loss_rpn_cls=0.004621, loss_rpn_reg=0.022950, loss_bbox_cls=0.192790, loss_bbox_reg=0.247517, loss=0.467878, lr=0.002500, time_each_step=0.2s, eta=0:0:3
2021-06-08 09:31:17 [INFO]      [TRAIN] Epoch=12/12, Step=76/84, loss_rpn_cls=0.008105, loss_rpn_reg=0.042379, loss_bbox_cls=0.195194, loss_bbox_reg=0.336070, loss=0.581748, lr=0.002500, time_each_step=0.21s, eta=0:0:1
2021-06-08 09:31:18 [INFO]      [TRAIN] Epoch 12 finished, loss_rpn_cls=0.0058819074, loss_rpn_reg=0.024468873, loss_bbox_cls=0.19964509, loss_bbox_reg=0.29602566, loss=0.5260215 .
2021-06-08 09:31:18 [WARNING]   Detector only supports single card evaluation with batch_size=1 during evaluation, so batch_size is forcibly set to 1.
2021-06-08 09:31:18 [INFO]      Start to evaluate(total_samples=24, total_steps=24)...
2021-06-08 09:31:20 [INFO]      Accumulating evaluatation results...
2021-06-08 09:31:20 [INFO]      [EVAL] Finished, Epoch=12, mAP(0.50, 11point)=83.401929 .
2021-06-08 09:31:20 [INFO]      Current evaluated best model in eval_dataset is epoch_10, mAP(0.50, 11point)=84.75437391202493
2021-06-08 09:31:23 [INFO]      Model saved in output/faster_rcnn_r50_fpn/epoch_12.
```

**但是多卡第一次evaluate后就退出了**

启动命令：
```
python -m paddle.distributed.launch --gpus='2,3' faster_rcnn_r34_fpn.py 
```

**endpoints.log**
```
PADDLE_TRAINER_ENDPOINTS:
127.0.0.1:36689
127.0.0.1:59821
```

**worklog.0**
```
I0608 09:23:22.844642 34522 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 2 ring id: 0
W0608 09:23:23.274696 34522 device_context.cc:404] Please NOTE: device: 2, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0608 09:23:23.276417 34522 device_context.cc:422] device: 2, cuDNN Version: 8.0.
/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
2021-06-08 09:23:26 [INFO]      Starting to read file list from dataset...
2021-06-08 09:23:26 [INFO]      169 samples in file insect_det/train_list.txt
creating index...
index created!
2021-06-08 09:23:26 [INFO]      Starting to read file list from dataset...
2021-06-08 09:23:26 [INFO]      24 samples in file insect_det/val_list.txt
creating index...
index created!
2021-06-08 09:23:26 [INFO]      Loading pretrained model from output/faster_rcnn_r50_fpn/pretrain/ResNet34_pretrained.pdparams
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res2_sum_lateral.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res2_sum_lateral.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res2_sum.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res2_sum.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res3_sum_lateral.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res3_sum_lateral.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res3_sum.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res3_sum.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res4_sum_lateral.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res4_sum_lateral.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res4_sum.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res4_sum.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res5_sum.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_inner_res5_sum.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res5_sum.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   neck.fpn_res5_sum.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   rpn_head.rpn_feat.rpn_conv.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   rpn_head.rpn_feat.rpn_conv.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   rpn_head.rpn_rois_score.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   rpn_head.rpn_rois_score.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   rpn_head.rpn_rois_delta.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   rpn_head.rpn_rois_delta.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.head.fc6.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.head.fc6.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.head.fc7.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.head.fc7.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.bbox_score.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.bbox_score.bias is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.bbox_delta.weight is not in pretrained model
2021-06-08 09:23:27 [WARNING]   bbox_head.bbox_delta.bias is not in pretrained model
2021-06-08 09:23:27 [INFO]      There are 185/215 variables loaded into FasterRCNN.
2021-06-08 09:23:29 [INFO]      [TRAIN] Epoch=1/12, Step=10/84, loss_rpn_cls=0.676389, loss_rpn_reg=0.064361, loss_bbox_cls=0.356633, loss_bbox_reg=0.046335, loss=1.143717, lr=0.000291, time_each_step=0.24s, eta=0:4:1
2021-06-08 09:23:31 [INFO]      [TRAIN] Epoch=1/12, Step=20/84, loss_rpn_cls=0.603916, loss_rpn_reg=0.031719, loss_bbox_cls=0.358314, loss_bbox_reg=0.043863, loss=1.037812, lr=0.000336, time_each_step=0.17s, eta=0:2:48
2021-06-08 09:23:33 [INFO]      [TRAIN] Epoch=1/12, Step=30/84, loss_rpn_cls=0.562639, loss_rpn_reg=0.127511, loss_bbox_cls=0.224877, loss_bbox_reg=0.026501, loss=0.941528, lr=0.000380, time_each_step=0.18s, eta=0:2:53
2021-06-08 09:23:35 [INFO]      [TRAIN] Epoch=1/12, Step=40/84, loss_rpn_cls=0.434309, loss_rpn_reg=0.075577, loss_bbox_cls=0.253639, loss_bbox_reg=0.126334, loss=0.889859, lr=0.000425, time_each_step=0.17s, eta=0:2:49
2021-06-08 09:23:36 [INFO]      [TRAIN] Epoch=1/12, Step=50/84, loss_rpn_cls=0.225688, loss_rpn_reg=0.046049, loss_bbox_cls=0.191036, loss_bbox_reg=0.127301, loss=0.590075, lr=0.000470, time_each_step=0.17s, eta=0:2:49
2021-06-08 09:23:38 [INFO]      [TRAIN] Epoch=1/12, Step=60/84, loss_rpn_cls=0.124876, loss_rpn_reg=0.029492, loss_bbox_cls=0.344767, loss_bbox_reg=0.257693, loss=0.756827, lr=0.000516, time_each_step=0.18s, eta=0:2:52
2021-06-08 09:23:40 [INFO]      [TRAIN] Epoch=1/12, Step=70/84, loss_rpn_cls=0.106548, loss_rpn_reg=0.014399, loss_bbox_cls=0.292814, loss_bbox_reg=0.329417, loss=0.743177, lr=0.000561, time_each_step=0.17s, eta=0:2:42
2021-06-08 09:23:42 [INFO]      [TRAIN] Epoch=1/12, Step=80/84, loss_rpn_cls=0.144694, loss_rpn_reg=0.043969, loss_bbox_cls=0.280239, loss_bbox_reg=0.216250, loss=0.685152, lr=0.000606, time_each_step=0.17s, eta=0:2:39
2021-06-08 09:23:43 [INFO]      [TRAIN] Epoch 1 finished, loss_rpn_cls=0.37998733, loss_rpn_reg=0.04838558, loss_bbox_cls=0.33314955, loss_bbox_reg=0.13094977, loss=0.8924722 .
2021-06-08 09:23:43 [WARNING]   Detector only supports single card evaluation with batch_size=1 during evaluation, so batch_size is forcibly set to 1.
2021-06-08 09:23:43 [INFO]      Start to evaluate(total_samples=24, total_steps=24)...
2021-06-08 09:23:44 [INFO]      Accumulating evaluatation results...
2021-06-08 09:23:44 [INFO]      [EVAL] Finished, Epoch=1, mAP(0.50, 11point)=3.199185 .


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1623115425 (unix time) try "date -d @1623115425" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ec00008651) received by PID 34522 (TID 0x7fd1e845b740) from PID 34385 ***]
```

**worklog.1**
```
I0608 09:23:22.823462 34527 gen_comm_id_helper.cc:181] Server listening on: 127.0.0.1:59821 successful.
I0608 09:23:22.844743 34527 nccl_context.cc:74] init nccl context nranks: 2 local rank: 1 gpu id: 3 ring id: 0
W0608 09:23:23.274931 34527 device_context.cc:404] Please NOTE: device: 3, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0608 09:23:23.276734 34527 device_context.cc:422] device: 3, cuDNN Version: 8.0.
/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
creating index...
index created!
creating index...
index created!
Traceback (most recent call last):
  File "faster_rcnn_r34_fpn.py", line 48, in <module>
    model.train(
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 264, in train
    self.train_loop(
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 327, in train_loop
    i + 1, dict2str(self.eval_metrics)))
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/utils/utils.py", line 56, in dict2str
    for k, v in dict_input.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Paddle版本信息**
```
paddlepaddle-gpu 2.1.0.post101
paddlex          2.0.0rc0
```

**Comment by FlyingQianMM** [comment]
这个之前是有问题，参考 https://github.com/PaddlePaddle/PaddleX/issues/775

最快能够正常运行的方式是，参考 https://github.com/PaddlePaddle/PaddleX/pull/778/files 直接修改 /home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/base.py

**Comment by thinkall** [comment]
搞定了，谢谢！
