### ISSUE TITLE
训练过程中因为  Too many open files  退出

### ISSUE THREAD

**Issue by thinkall** [PaddlePaddle/PaddleX#815]
**启动命令**
```
python -m paddle.distributed.launch --gpus='0,1,2,3' ppyolov2.py
```

**在193 epoch时退出了**
```
2021-06-08 17:38:46 [INFO]      [TRAIN] Epoch 193 finished, loss_xy=1.8856273, loss_wh=2.8467307, loss_iou=11.691441, loss_iou_aware=3.2113776, loss_obj=6.5854096, loss_cls=9.795078, loss=36.015663 .
INFO 2021-06-08 17:38:51,489 launch_utils.py:327] terminate all the procs
ERROR 2021-06-08 17:38:51,490 launch_utils.py:582] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
INFO 2021-06-08 17:38:54,492 launch_utils.py:327] terminate all the procs
```

**worklog.0**
```
2021-06-08 17:38:46 [INFO]      [TRAIN] Epoch 193 finished, loss_xy=1.8856273, loss_wh=2.8467307, loss_iou=11.691441, loss_iou_aware=3.2113776, loss_obj=6.5854096, loss_cls=9.795078, loss=36.015663 .


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GPUUniformRandomKernel<float>, paddle::operators::GPUUniformRandomKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::operators::GPUUniformRandomKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1623145128 (unix time) try "date -d @1623145128" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ec00000b73) received by PID 3066 (TID 0x7fbcafd53740) from PID 2931 ***]
```

**worklog.1**
```
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/utils/det_dataloader.py", line 45, in __next__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/six.py", line 719, in reraise
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppyolov2.py", line 58, in <module>
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 264, in train
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 266, in train_loop
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/utils/det_dataloader.py", line 47, in __next__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _init_workers
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/context.py", line 103, in Queue
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/context.py", line 68, in Lock
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
OSError: [Errno 24] Too many open files


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1623145126 (unix time) try "date -d @1623145126" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ec00000c03) received by PID 13739 (TID 0x7f69605e3740) from PID 3075 ***]

Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f690ad55af0>
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

**worklog.2**
```
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/utils/det_dataloader.py", line 45, in __next__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/six.py", line 719, in reraise
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppyolov2.py", line 58, in <module>
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 264, in train
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 266, in train_loop
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/utils/det_dataloader.py", line 47, in __next__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _init_workers
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/context.py", line 103, in Queue
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/context.py", line 68, in Lock
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
OSError: [Errno 24] Too many open files


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1623145126 (unix time) try "date -d @1623145126" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ec00000c09) received by PID 13738 (TID 0x7f7f26608740) from PID 3081 ***]

Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f7ed4dabaf0>
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

**worklog.3**
```
/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py:237: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.float32, the right dtype will convert to paddle.int64
  warnings.warn(
/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py:237: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  warnings.warn(
/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/utils/det_dataloader.py", line 45, in __next__
    return next(self.loader)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
    six.reraise(*sys.exc_info())
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppyolov2.py", line 58, in <module>
    model.train(
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/detector.py", line 264, in train
    self.train_loop(
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 266, in train_loop
    for step, data in enumerate(self.train_data_loader()):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddlex/cv/models/utils/det_dataloader.py", line 47, in __next__
    self.loader = iter(self.dataloader)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 327, in _init_workers
    worker.start()
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7fbf12aa3af0>
Traceback (most recent call last):
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/liuyu/anaconda3/envs/paddle2.1/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

**Comment by lailuboy** [comment]
用ulimit -a看操作系统open files最大值是多少，可以尝试用ulimit -n 命令改大该值（如10240）后看问题是否解决。
