### ISSUE TITLE
训练弹窗中止

### ISSUE THREAD

**Issue by freedomcandy** [PaddlePaddle/PaddleX#869]
问题类型：模型训练  
**问题描述**  
export CPU_NUM=4 # for example, set CPU_NUM as number of physical CPU core which is 4.

!!! The default number of CPU_NUM=1.
2021-06-25 17:40:48,234-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-06-25 17:40:55,698-WARNING: /Users/RoyGuo/desktop/paddlex_workspace/projects/P0009/T0009/output/epoch_30.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
/Users/RoyGuo/Downloads/paddlex_gui_mac_v1.1.7/Contents/MacOS/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "paddlexui/pms/model_tasks/tasks.py", line 68, in _call_paddlex_train
  File "paddlexui/pms/model_tasks/train/detection.py", line 216, in train
  File "site-packages/paddlex/cv/models/ppyolo.py", line 350, in train
  File "site-packages/paddlex/cv/models/base.py", line 250, in net_initialize
  File "site-packages/paddlex/utils/utils.py", line 313, in load_pretrain_weights
Exception: Optimizer parameter /Users/RoyGuo/desktop/paddlex_workspace/projects/P0009/T0009/output/epoch_30/@LR_DECAY_COUNTER@ doesn't exist, the training process can not be resumed due to optimizer set now and last time is different. Recommend to use `pretrain_weights` instead of `resume_checkpoint`

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by FlyingQianMM** [comment]
> /Users/RoyGuo/desktop/paddlex_workspace/projects/P0009/T0009/output/epoch_30/@LR_DECAY_COUNTER@ doesn't exist, the training process can not be resumed due to optimizer set now and last time is different. Recommend to use pretrain_weights instead of resume_checkpoint

因为这次训练的优化器设置跟上次不一样，所以无法恢复训练
