### ISSUE TITLE
PaddleX模型剪裁报错：parallel_for failed: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by mzxhzhp** [PaddlePaddle/PaddleX#910]
问题类型：模型训练  
**问题描述**  
PaddleX 1.3.11 版本，模型训练没有问题，但是在模型剪裁的时候报错了。报错内容如下：

creating index...
index created!
Paddle Version: 1.8.5
PaddleX Version: 1.3.11
num_classes = 1
W0702 08:14:17.499222   211 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.2, Runtime API Version: 10.0
W0702 08:14:17.501857   211 device_context.cc:260] device: 0, cuDNN Version: 8.1.
W0702 08:14:22.019361   211 operator.cc:187] gaussian_random raises an exception thrust::system::system_error, parallel_for failed: no kernel image is available for execution on the device
/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "model_prune_paddlex1.3.11.py", line 59, in <module>
    use_vdl=True)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/yolo_v3.py", line 174, in train
    early_stop_patience, resume_checkpoint, False)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/ppyolo.py", line 354, in train
    resume_checkpoint=resume_checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/base.py", line 247, in net_initialize
    self.exe.run(startup_prog)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
**RuntimeError: parallel_for failed: no kernel image is available for execution on the device**

各个工具的版本号如下：
paddle2onnx         0.6            
paddlehub           2.1.0          
paddlenlp           2.0.5          
paddlepaddle-gpu    1.8.5.post107  
paddleslim          1.1.1          
paddlex             1.3.11

电脑显卡：RTX3090，系统：Ubuntu18.04

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by mzxhzhp** [comment]
奇怪的是，在AIStudio上面，则没有这个报错。我对比了下软件版本，都是一样的，不知道是啥原因。

**Comment by FlyingQianMM** [comment]
paddlepaddle-gpu 1.8.5.post107训RTX3090会有点问题，试下最新的paddle

**Comment by mzxhzhp** [comment]
首先，PaddleX 1.3.11 只支持1.8.5的 PaddlePaddle。要用最新的Paddle，只能使用2.0.0 的PaddleX。
其次，我试了2.0.0版本的PaddleX，发现问题更多了，例如：
1.模型训练非常慢，之前1.3.11的PaddleX只需要二十几个小时，2.0.0的PaddleX需要一百多个小时；
2.模型剪裁的时候，模型大小不减反增，由剪裁之前的471M变成475M；

**Comment by mzxhzhp** [comment]
> paddlepaddle-gpu 1.8.5.post107训RTX3090会有点问题，试下最新的paddle

不过，有点奇怪的是，在RTX3090的机器上，训练没问题，剪裁才报的错。

**Comment by FlyingQianMM** [comment]
> 模型训练非常慢，之前1.3.11的PaddleX只需要二十几个小时，2.0.0的PaddleX需要一百多个小时

这个具体是跑的什么模型呢？参数设置前后都是一样的吗？

> 模型剪裁的时候，模型大小不减反增，由剪裁之前的471M变成475M；

这个具体是怎么设置剪裁时的参数呢？

**Comment by mzxhzhp** [comment]
>> 这个具体是跑的什么模型呢？参数设置前后都是一样的吗？
>
> 模型都是YOLOv3_Darknet53，数据集也一样。
> 
# PaddleX v1.3.11 的训练代码如下：
`train_transforms = transforms.Compose([
    transforms.MixupImage(mixup_epoch=250),
    transforms.RandomDistort(),
    transforms.RandomExpand(),
    transforms.RandomCrop(),
    transforms.Resize(target_size=608, interp='RANDOM'),
    transforms.RandomHorizontalFlip(),
    transforms.Normalize(),
])

num_classes = len(train_dataset.labels)

print("num_classes = %d"%num_classes)

model = pdx.det.YOLOv3(num_classes=num_classes, backbone='DarkNet53')

model.train(
    num_epochs=300,
    train_dataset=train_dataset,
    train_batch_size=4,
    eval_dataset=eval_dataset,
    learning_rate=0.000125,
    lr_decay_epochs=[210, 240],
    # pretrain_weights='output/yolov3_darknet53_new/best_model',
    save_interval_epochs=10,
    save_dir='output/yolov3_darknet53',
    use_vdl=True)`

# PaddleX v2.0.0 的训练代码如下：
`train_transforms = T.Compose([
    T.MixupImage(mixup_epoch=250), 
    T.RandomDistort(),
    T.RandomExpand(im_padding_value=[123.675, 116.28, 103.53]), 
    T.RandomCrop(),
    T.RandomHorizontalFlip(),
    T.BatchRandomResize(target_sizes=[320, 352, 384, 416, 448, 480, 512, 544, 576, 608], interp='RANDOM'), 
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transforms = T.Compose([
    T.Resize(608, interp='CUBIC'), 
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
num_classes = len(train_dataset.labels)
print("num_classes = %d"%num_classes)
model = pdx.cv.models.YOLOv3(num_classes=num_classes, backbone='DarkNet53')

model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    learning_rate=0.001 / 8,
    warmup_steps=1000,
    warmup_start_lr=0.0,
    save_interval_epochs=5,
    #lr_decay_epochs=[216, 243],
    lr_decay_epochs=[116, 143],
    save_dir='output_paddlex200/yolov3_darknet53',
    use_vdl=True)`


>> > 模型剪裁的时候，模型大小不减反增，由剪裁之前的471M变成475M；
> 
>> 这个具体是怎么设置剪裁时的参数呢？
# PaddleX v1.3.11 `的剪裁代码如下:
from paddlex.det import transforms
train_transforms = transforms.Compose([
    transforms.MixupImage(mixup_epoch=250),
    transforms.RandomDistort(),
    transforms.RandomExpand(),
    transforms.RandomCrop(),
    transforms.Resize(target_size=608, interp='RANDOM'),
    transforms.RandomHorizontalFlip(),
    transforms.Normalize(),
])

eval_transforms = transforms.Compose([
    transforms.Resize(target_size=608, interp='CUBIC'),
    transforms.Normalize(),
])
    
import paddle as pp
print('Paddle Version: {}'.format(pp.__version__))
print('PaddleX Version: {}'.format(pdx.__version__))

num_classes = len(train_dataset.labels)
print("num_classes = %d"%num_classes)
model = pdx.det.YOLOv3(num_classes=num_classes, backbone='DarkNet53')

model.train(
    num_epochs=300,
    train_dataset=train_dataset,
    train_batch_size=4,
    eval_dataset=eval_dataset,
    learning_rate=0.000125,
    lr_decay_epochs=[110, 140],
    pretrain_weights='output/yolov3_darknet53/epoch_110',
    save_dir='output/yolov3_darknet53_prune',
    sensitivities_file='./yolov3.sensi.data',
    save_interval_epochs=5,
    eval_metric_loss=0.05,
    use_vdl=True)
`
> 
# PaddleX v2.0.0 的剪裁代码如下：
train_transforms = T.Compose([
    T.MixupImage(mixup_epoch=250), 
    T.RandomDistort(),
    T.RandomExpand(im_padding_value=[123.675, 116.28, 103.53]), 
    T.RandomCrop(),
    T.RandomHorizontalFlip(),
    T.BatchRandomResize(target_sizes=[320, 352, 384, 416, 448, 480, 512, 544, 576, 608], interp='RANDOM'), 
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transforms = T.Compose([
    T.Resize(608, interp='CUBIC'), 
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

model = pdx.load_model('output_paddlex200/yolov3_darknet53/epoch_10')

model.analyze_sensitivity(
    dataset=eval_dataset,
    batch_size=1,
    save_dir='output_paddlex200/yolov3_darknet53/prune')

model.prune(pruned_flops=.2)

model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=4,
    eval_dataset=eval_dataset,
    learning_rate=0.001 / 8,
    warmup_steps=1000,
    warmup_start_lr=0.0,
    save_interval_epochs=5,
    lr_decay_epochs=[116, 143],
    save_dir='output_paddlex200/yolov3_darknet53/prune')`

**Comment by will-jl944** [comment]
> 1.模型训练非常慢，之前1.3.11的PaddleX只需要二十几个小时，2.0.0的PaddleX需要一百多个小时；

请问训练使用的是单卡还是多卡？如果是多卡的话，PaddleX2.0.0的训练脚本是否是用`python -m paddle.distributed.launch your_training_script.py`的方式运行的？


> 2.模型剪裁的时候，模型大小不减反增，由剪裁之前的471M变成475M；

模型剪裁之后得到的model.pdparams参数文件可能会出现体积不变或者变大的情况，因为该参数文件中不仅包含模型推理时所需的参数，但是此时模型的flops已经减少了。如果需要进一步得到推理时所需的参数文件，需要将模型导出，具体可以参考我们的[模型导出文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/docs/apis/export_model.md)。

**Comment by mzxhzhp** [comment]
> > 请问训练使用的是单卡还是多卡？如果是多卡的话，PaddleX2.0.0的训练脚本是否是用`python -m paddle.distributed.launch your_training_script.py`的方式运行的？
> 我用的是单卡训练。
> 
> >  模型剪裁之后得到的model.pdparams参数文件可能会出现体积不变或者变大的情况，因为该参数文件中不仅包含模型推理时所需的参数，但是此时模型的flops已经减少了。如果需要进一步得到推理时所需的参数文件，需要将模型导出，具体可以参考我们的[模型导出文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/docs/apis/export_model.md)。
> 
> 我只是好奇，为啥paddlex 1.3.11 剪裁的时候，是可以减少体积的，而2.0.0的PaddleX反而不行。

**Comment by will-jl944** [comment]
> > > 请问训练使用的是单卡还是多卡？如果是多卡的话，PaddleX2.0.0的训练脚本是否是用`python -m paddle.distributed.launch your_training_script.py`的方式运行的？
> > > 我用的是单卡训练。
> > 
> > 
> > > 模型剪裁之后得到的model.pdparams参数文件可能会出现体积不变或者变大的情况，因为该参数文件中不仅包含模型推理时所需的参数，但是此时模型的flops已经减少了。如果需要进一步得到推理时所需的参数文件，需要将模型导出，具体可以参考我们的[模型导出文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/docs/apis/export_model.md)。
> > 
> > 
> > 我只是好奇，为啥paddlex 1.3.11 剪裁的时候，是可以减少体积的，而2.0.0的PaddleX反而不行。

针对问题一：
两个训练脚本设置的`save_interval_epochs`不同，检测模型仅支持单卡batch size为1进行模型评估，会比较耗时。可否把`save_interval_epochs`设置为相同值，再对比一下？

针对问题二：
PaddleX1.3.11使用的是静态图，PaddleX2.0.0使用的是动态图，只会在导出模型时进行动态图转静态图的操作。

**Comment by mzxhzhp** [comment]
耗时长的问题，有可能就是 batch size 比较小的缘故。
我用PaddleX1.3.11试了下，batch size 为 1 的时候确实耗时会变长。
