### ISSUE TITLE
利用yolov3_mobilenetv3_large_pruned模型推理报错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleX#925]
问题类型：模型部署
**问题描述**  

========================  

利用官方提供的`yolov3_mobilenetv3_large_pruned`模型进行推理报错
```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "predict.py", line 37, in <module>
    model = pdx.load_model(model_dir)
  File "/usr/local/lib/python3.6/dist-packages/paddlex/cv/models/load_model.py", line 47, in load_model
    model = getattr(paddlex.cv.models, info['Model'])(**info['_init_params'])
TypeError: __init__() got an unexpected keyword argument 'scale_x_y'
```

**Comment by FlyingQianMM** [comment]
> 利用官方提供的yolov3_mobilenetv3_large_pruned模型进行推理报错

这里提供模型具体是在哪里获取的？另外当前使用的paddlex的版本号是多少呢？

**Comment by Huihuihh** [comment]
> > 利用官方提供的yolov3_mobilenetv3_large_pruned模型进行推理报错
> 
> 这里提供模型具体是在哪里获取的？另外当前使用的paddlex的版本号是多少呢？

模型是通过官网上面提供的地址下载的
`wget https://bj.bcebos.com/paddlex/examples/industrial_quality_inspection/models/yolov3_mobilenetv3_large_pruned.tar.gz`
paddlex版本1.3.3

**Comment by FlyingQianMM** [comment]
更新下paddlex试试:
```
pip install paddlex==1.3.11 -U
```

**Comment by Huihuihh** [comment]
还是一样的效果
```
paddle-serving-app      0.3.0
paddle-serving-client   0.5.0
paddle-serving-server   0.5.0
paddle2onnx             0.6
paddlehub               2.1.0
paddlelite              2.6.1
paddlenlp               2.0.5
paddlepaddle            2.0.0
paddleslim              1.1.1
paddlex                 1.3.11
x2paddle                1.0.0rc1
```
推理结果
```
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "predict.py", line 37, in <module>
    model = pdx.load_model(model_dir)
  File "/usr/local/lib/python3.6/dist-packages/paddlex/cv/models/load_model.py", line 47, in load_model
    model = getattr(paddlex.cv.models, info['Model'])(**info['_init_params'])
TypeError: __init__() got an unexpected keyword argument 'scale_x_y'
```

**Comment by FlyingQianMM** [comment]
之前静态图的代码有点问题。目前最快的解决方法是，先手动删除model.yml里面'scale_x_y'，如果还有其他的argument报错，也相应地删除掉。
