### ISSUE TITLE
预测程序出现使用问题

### ISSUE THREAD

**Issue by TerryPanda3032** [PaddlePaddle/PaddleX#944]
W0712 18:20:46.185123  7380 analysis_predictor.cc:1183] Deprecated. Please use CreatePredictor instead.
Traceback (most recent call last):
  File "g:/AI/my_face/predict.py", line 13, in <module>
    model = pdx.deploy.Predictor('G:\AI\my_face\inference_model', use_gpu=False)
  File "C:\Users\Terry\AppData\Roaming\Python\Python37\site-packages\paddlex\deploy.py", line 85, in __init__
    memory_optimize, max_trt_batch_size)
  File "C:\Users\Terry\AppData\Roaming\Python\Python37\site-packages\paddlex\deploy.py", line 144, in create_predictor
    predictor = fluid.core.create_paddle_predictor(config)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 2513288639 found).
  [Hint: Expected version == 0U, but received version:2513288639 != 0U:0.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\lod_tensor.cc:329)
  [operator < load_combine > error]

**Comment by TerryPanda3032** [comment]
W0712 18:20:46.185123  7380 analysis_predictor.cc:1183] Deprecated. Please use CreatePredictor instead.
Traceback (most recent call last):
  File "g:/AI/my_face/predict.py", line 13, in <module>
    model = pdx.deploy.Predictor('G:\AI\my_face\inference_model', use_gpu=False)
  File "C:\Users\Terry\AppData\Roaming\Python\Python37\site-packages\paddlex\deploy.py", line 85, in __init__
    memory_optimize, max_trt_batch_size)
  File "C:\Users\Terry\AppData\Roaming\Python\Python37\site-packages\paddlex\deploy.py", line 144, in create_predictor
    predictor = fluid.core.create_paddle_predictor(config)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 2513288639 found).
  [Hint: Expected version == 0U, but received version:2513288639 != 0U:0.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\lod_tensor.cc:329)
  [operator < load_combine > error]

**Comment by FlyingQianMM** [comment]
> ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 2513288639 found).

G:\AI\my_face\inference_mode下面都有哪些文件呢？
