### ISSUE TITLE
Cuda error(3), initialization error.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#952]
问题类型：PaddleX可视化客户端  
![微信截图_20210714193236](https://user-images.githubusercontent.com/6490927/125615344-66338ea1-419a-4812-8b73-71367fa9b9a8.png)

NVIDIA-SMI 441.22       Driver Version: 441.22       CUDA Version: 10.2

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

===================================  
This log file path is E:\paddlex_workspace_AI\projects\P0008\T0009\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
F:\PaddleX\paddle\fluid\framework.py:301: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
F:\PaddleX\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
F:\PaddleX\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Process Process-1:4:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 58, in _call_paddlex_train
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\cv\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\cv\models\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\cv\models\detector.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\data\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\data\transform\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\data\transform\operators.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\modeling\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dltp-sz-windows\anaconda3\envs\paddlex30x0\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\rpn_head.py", line 58, in <module>
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\rpn_head.py", line 74, in RPNHead
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 57, in __init__
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 83, in _calculate_anchors
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 83, in <listcomp>
  File "site-packages\paddlex\ppdet\modeling\proposal_generator\anchor_generator.py", line 76, in generate_cell_anchors
  File "<decorator-gen-128>", line 2, in to_tensor
  File "site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
  File "site-packages\paddle\fluid\framework.py", line 227, in __impl__
  File "site-packages\paddle\tensor\creation.py", line 160, in to_tensor
OSError: (External)  Cuda error(3), initialization error.
  [Advise: Please search for the error code(3) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release2\paddle\fluid\platform\gpu_info.cc:99)

**Comment by FlyingQianMM** [comment]
安装的是cuda 11.2，cudnn 8.0？

**Comment by monkeycc** [comment]
是2060显卡

安装的是 cuda 10.2   cuDNN 7

**Comment by FlyingQianMM** [comment]
升级到cuda 11.2，cudnn 8.0即可
