### ISSUE TITLE
训练图像分类数据集出错

### ISSUE THREAD

**Issue by Ghost1989** [PaddlePaddle/PaddleX#991]
[使用图像分类时，使用自己数据集出错：]([https://aistudio.baidu.com/aistudio/datasetdetail/101954])
output1/mobilenetv3_small_ssld\pretrain\MobileNetV3_small_x1_0_ssld_pretrained are loaded.
2021-07-26 20:18:59 [INFO]	[TRAIN] Epoch=1/12, Step=2/50, loss=3.443056, acc1=0.0, acc5=0.09375, lr=0.00625, time_each_step=1.61s, eta=0:20:36
2021-07-26 20:18:59 [INFO]	[TRAIN] Epoch=1/12, Step=4/50, loss=3.313844, acc1=0.03125, acc5=0.21875, lr=0.00625, time_each_step=0.86s, eta=0:10:53
2021-07-26 20:19:00 [INFO]	[TRAIN] Epoch=1/12, Step=6/50, loss=3.340708, acc1=0.03125, acc5=0.1875, lr=0.00625, time_each_step=0.6s, eta=0:7:37
2021-07-26 20:19:00 [INFO]	[TRAIN] Epoch=1/12, Step=8/50, loss=3.085745, acc1=0.0625, acc5=0.28125, lr=0.00625, time_each_step=0.47s, eta=0:5:59
2021-07-26 20:19:00 [INFO]	[TRAIN] Epoch=1/12, Step=10/50, loss=3.051461, acc1=0.1875, acc5=0.34375, lr=0.00625, time_each_step=0.41s, eta=0:5:13
2021-07-26 20:19:01 [INFO]	[TRAIN] Epoch=1/12, Step=12/50, loss=3.016625, acc1=0.09375, acc5=0.40625, lr=0.00625, time_each_step=0.4s, eta=0:5:4
2021-07-26 20:19:02 [INFO]	[TRAIN] Epoch=1/12, Step=14/50, loss=2.542789, acc1=0.21875, acc5=0.6875, lr=0.00625, time_each_step=0.4s, eta=0:5:5
2021-07-26 20:19:02 [INFO]	[TRAIN] Epoch=1/12, Step=16/50, loss=2.453616, acc1=0.34375, acc5=0.71875, lr=0.00625, time_each_step=0.39s, eta=0:4:54
2021-07-26 20:19:03 [INFO]	[TRAIN] Epoch=1/12, Step=18/50, loss=2.232209, acc1=0.4375, acc5=0.5625, lr=0.00625, time_each_step=0.39s, eta=0:4:52
2021-07-26 20:19:04 [INFO]	[TRAIN] Epoch=1/12, Step=20/50, loss=2.288795, acc1=0.34375, acc5=0.78125, lr=0.00625, time_each_step=0.39s, eta=0:4:52
2021-07-26 20:19:04 [INFO]	[TRAIN] Epoch=1/12, Step=22/50, loss=2.068473, acc1=0.4375, acc5=0.78125, lr=0.00625, time_each_step=0.26s, eta=0:3:12
2021-07-26 20:19:05 [INFO]	[TRAIN] Epoch=1/12, Step=24/50, loss=2.244123, acc1=0.34375, acc5=0.71875, lr=0.00625, time_each_step=0.28s, eta=0:3:30
2021-07-26 20:19:06 [INFO]	[TRAIN] Epoch=1/12, Step=26/50, loss=1.738214, acc1=0.4375, acc5=0.875, lr=0.00625, time_each_step=0.3s, eta=0:3:45
2021-07-26 20:19:06 [INFO]	[TRAIN] Epoch=1/12, Step=28/50, loss=2.034224, acc1=0.46875, acc5=0.78125, lr=0.00625, time_each_step=0.32s, eta=0:3:59
Exception in thread Thread-19:
Traceback (most recent call last):
  File "C:\Users\sdxyz\miniconda3\envs\baiduPaddle\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\sdxyz\miniconda3\envs\baiduPaddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sdxyz\miniconda3\envs\baiduPaddle\lib\site-packages\paddlex\cv\datasets\dataset.py", line 83, in handle_worker
    r = mapper(sample[0], sample[1])
  File "C:\Users\sdxyz\miniconda3\envs\baiduPaddle\lib\site-packages\paddlex\cv\transforms\cls_transforms.py", line 90, in __call__
    self.data_type = im.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'
2021-07-26 20:19:07 [INFO]	[TRAIN] Epoch=1/12, Step=30/50, loss=1.700515, acc1=0.5625, acc5=0.78125, lr=0.00625, time_each_step=0.36s, eta=0:4:24
2021-07-26 20:19:08 [INFO]	[TRAIN] Epoch=1/12, Step=32/50, loss=1.439511, acc1=0.59375, acc5=0.9375, lr=0.00625, time_each_step=0.36s, eta=0:4:25
2021-07-26 20:19:09 [INFO]	[TRAIN] Epoch=1/12, Step=34/50, loss=1.767021, acc1=0.53125, acc5=0.8125, lr=0.00625, time_each_step=0.35s, eta=0:4:17
2021-07-26 20:19:10 [INFO]	[TRAIN] Epoch=1/12, Step=36/50, loss=1.317116, acc1=0.71875, acc5=0.90625, lr=0.00625, time_each_step=0.37s, eta=0:4:28
2021-07-26 20:19:10 [INFO]	[TRAIN] Epoch=1/12, Step=38/50, loss=1.493024, acc1=0.65625, acc5=0.90625, lr=0.00625, time_each_step=0.36s, eta=0:4:24
2021-07-26 20:19:11 [INFO]	[TRAIN] Epoch=1/12, Step=40/50, loss=1.144336, acc1=0.78125, acc5=0.90625, lr=0.00625, time_each_step=0.36s, eta=0:4:20
2021-07-26 20:19:12 [INFO]	[TRAIN] Epoch=1/12, Step=42/50, loss=1.114662, acc1=0.71875, acc5=0.90625, lr=0.00625, time_each_step=0.36s, eta=0:4:22
2021-07-26 20:19:12 [INFO]	[TRAIN] Epoch=1/12, Step=44/50, loss=1.675847, acc1=0.5625, acc5=0.84375, lr=0.00625, time_each_step=0.36s, eta=0:4:20
2021-07-26 20:19:13 [INFO]	[TRAIN] Epoch=1/12, Step=46/50, loss=1.146729, acc1=0.6875, acc5=0.96875, lr=0.00625, time_each_step=0.38s, eta=0:4:35
2021-07-26 20:19:14 [INFO]	[TRAIN] Epoch=1/12, Step=48/50, loss=1.767216, acc1=0.625, acc5=0.84375, lr=0.00625, time_each_step=0.39s, eta=0:4:38
2021-07-26 20:19:15 [INFO]	[TRAIN] Epoch=1/12, Step=50/50, loss=1.424577, acc1=0.6875, acc5=0.90625, lr=0.00625, time_each_step=0.38s, eta=0:4:30

**Comment by Ghost1989** [comment]
数据集：https://aistudio.baidu.com/aistudio/datasetdetail/101954

**Comment by will-jl944** [comment]
有图片读取失败了，返回了None，检查一下图片是否都正常，以及train_list.txt中的图片路径是否都是存在的。
